/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit', './DvtAxis'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.bJ=(0,D.s)();(0,D.ca)("DvtGauge",D.bJ);D.y.q(D.bJ,D.Fk,"DvtGauge");D.bJ.prototype.Init=function(a,b,c,d){D.bJ.u.Init.call(this,a,b,c);this.D3=d;this.D3||(this.xa=this.CH(),this.xa.Ne(this),(0,D.Ze)()||(0,D.Yl)(this.xa,this.Uv(this.xa)),this.setId("gauge1000"+window.Math.floor(1E9*window.Math.random())),this.TI=new D.D(a,0,0),(0,D.Aj)(this.TI),this.k(this.TI));this.mE=D.p;this.DF=D.o};
D.bJ.prototype.Od=function(a){this.G=a;(0,D.$l)()||(this.G.animationOnDisplay="none",this.G.animationOnDataChange="none")};
D.bJ.prototype.U=function(a,b,c){a?this.Od(a):this.G||this.Od(D.o);this.G.thresholds&&(this.G.thresholds=this.G.thresholds.sort(D.lJ));!(0,window.isNaN)(b)&&!(0,window.isNaN)(c)&&(this.fb=b,this.tb=c);c=this.hy;this.hy=[];b=new D.C(this.j());this.Ua(b,0);this.sj(b,this.fb,this.tb);var d=a!=D.o,e=this.fb,f=this.tb;this.kb&&this.kb.stop();a=D.p;var g=this.mE?"none":this.A().animationOnDataChange,h=this.mE?"none":this.A().animationOnDisplay,j=(0,D.jq)(this.A().animationDuration)/1E3;if(h||g){e=new D.B(0,
0,e,f);f=this.j();if(!this.da&&"none"!==h&&this.hy[0]!=D.o)this.kb=D.em.DC(f,h,b,e,j),this.kb||(this.kb=this.m0(this.hy,h,j));else if(this.da&&"none"!=g&&d&&this.hy[0]!=D.o)if(this.kb=D.em.AC(f,g,this.da,b,e,j))a=D.k;else{d=this.hy;g=[];for(h=0;h<c.length;h++){var e=d[h],l=c[h].oe(),f=e.oe();e.Md(l);l=new D.yo(this.j(),e,j);(0,D.S)(l.P,"typeNumberArray",e,e.oe,e.Md,f);g.push(l)}this.kb=new D.wo(this.j(),g)}a||this.removeChild(this.da);this.kb&&(this.kb.play(),this.kb.je(this.Xw,this));a&&(this.aj=
this.da);this.da=b}this.TI&&this.G.readOnly===D.p&&(this.TI.sa(this.fb),this.TI.Ia(this.tb));!this.D3&&!this.G.readOnly&&(b.xd("slider"),b.Wb("valuemin",this.G.min),b.Wb("valuemax",this.G.max),c=D.kJ.gn(this.G.value,this),b.Wb("valuenow",c),a=D.kJ.LG(this),(0,D.Ze)()&&(this.da.Wb("live","assertive"),c!=a&&(a=c+(0,D.M)("DvtUtilBundle","ARIA_LABEL_DESC_DELIMITER")+a)),c!=a&&b.Wb("label",a),this.a8=this.a8!=D.o?this.a8+1:0,c=this.getId()+"_"+this.a8,b.setId(c),(0,D.yh)(this.j(),b),(b=this.Aa())&&b.Ba(this.TI,
this.za(),D.k));this.G._selectingCursor&&this.setCursor("pointer");this.wo()};D.bJ.prototype.render=D.bJ.prototype.U;D.x=D.bJ.prototype;D.x.za=function(){var a=D.kJ.LG(this),b=D.dJ.Ib(this);return new D.Ok(D.o,a,b)};D.x.sj=(0,D.s)();D.x.m0=(0,D.ba)(D.o);D.x.FA=(0,D.ba)(D.o);D.x.fsa=function(){this.U();(0,D.fJ)(this,this.da)};D.fJ=function(a,b,c){c=D.kJ.gn(c?c:a.G.value,a);b.Wb("valuenow",c);(0,D.Ze)()&&b.Wb("label",c)};D.x=D.bJ.prototype;
D.x.Xw=function(){this.aj&&(this.removeChild(this.aj),this.aj=D.o);this.kb=D.o};D.x.Aa=(0,D.w)("xa");D.x.kU=function(a,b){this.mE=D.k;this.DF=this.G.value;this.hI(a,b)};D.x.hI=function(a,b){this.DF!=D.o&&(this.G.value=D.kJ.FY(this.G,this.FA(a,b)),this.fsa(),this.Wa(new D.QC(this.DF,this.G.value,D.p)))};
D.x.O2=function(a,b){this.hI(a,b);if((0,D.Ze)()){var c=D.kJ.gn(this.G.value,this),d=D.kJ.LG(this);c!=d&&(d=c+(0,D.M)("DvtUtilBundle","ARIA_LABEL_DESC_DELIMITER")+d,this.da.Wb("label",d))}this.Wa(new D.QC(this.DF,this.G.value,D.k));this.mE=D.p;this.DF=D.o};D.x.CH=function(){return new D.mJ(this)};D.lJ=function(a,b){return a.max!=D.o&&b.max!=D.o?a.max-b.max:a.max?-window.Infinity:window.Infinity};D.bJ.prototype.Zf=function(){return new D.nJ(this)};D.bJ.prototype.getAutomation=D.bJ.prototype.Zf;
D.bJ.prototype.Uv=function(a){return new D.oJ(a,this)};D.bJ.prototype.Lj=function(){return(0,D.Zl)(this.A(),"componentName","DvtUtilBundle","GAUGE")};
D.bJ.prototype.wo=function(){if(!this.D3){var a=D.kJ.LG(this);(0,D.XD)(this)?this.G.readOnly?(this.j().xd("img"),(0,D.YD)(this.j(),(0,D.M)("DvtUtilBundle","COLON_SEP_LIST",[(0,D.M)("DvtUtilBundle","DATA_VISUALIZATION"),(0,D.ql)(D.Yg.nA(this.Lj()),a?[a]:D.o)]))):(this.j().xd("application"),(0,D.YD)(this.j(),(0,D.M)("DvtUtilBundle","COLON_SEP_LIST",[(0,D.M)("DvtUtilBundle","DATA_VISUALIZATION"),D.Yg.nA(this.Lj())]))):this.G.readOnly&&(this.xd("img"),this.Wb("label",(0,D.ql)(D.Yg.nA(this.Lj()),a?[a]:
D.o)))}};
D.nJ=(0,D.v)("Mf");(0,D.ca)("DvtGaugeAutomation",D.nJ);D.y.q(D.nJ,D.Nk,"DvtGaugeAutomation");D.nJ.prototype.getValue=function(){return this.Mf.A().value};D.nJ.prototype.getValue=D.nJ.prototype.getValue;D.nJ.prototype.OHa=function(){return D.kJ.gn(this.getValue(),this.Mf)};D.nJ.prototype.getMetricLabel=D.nJ.prototype.OHa;
(0,D.Bh)("DvtGaugeBundle",{});
D.hJ=(0,D.s)();D.y.q(D.hJ,D.Vk,"DvtGaugeDefaults");D.pJ={skin:"alta",color:"#393737",metricLabel:{style:new D.I("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},_thresholdColors:["#ed6647","#fad55c","#68c182"]};
D.qJ={skin:"skyros",min:0,max:100,color:"#313842",borderColor:D.o,visualEffects:"auto",emptyText:D.o,animationOnDataChange:"none",animationOnDisplay:"none",animationDuration:500,readOnly:"true",metricLabel:{rendered:"off",scaling:"auto",style:new D.I("font-family: tahoma, sans-serif;"),textType:"number"},_thresholdColors:["#D62800","#FFCF21","#84AE31"],__layout:{outerGap:1,labelGap:5}};
D.hJ.prototype.Init=function(a){a={skyros:D.vm.Dd(a.skyros,D.qJ),alta:D.vm.Dd(a.alta,D.pJ)};D.hJ.u.Init.call(this,a)};D.rJ=function(a){return"skyros"==a.A().skin};
D.jJ={};D.y.q(D.jJ,D.y,"DvtGaugeDataUtils");D.jJ.vx=function(a){a=a.A();return!a||(0,window.isNaN)(a.value)||a.value===D.o?D.p:D.k};D.jJ.OG=function(a,b){var c=a.A(),d=b!=D.o?b:c.value,c=c.thresholds;if(!c)return-1;for(var e=0;e<c.length;e++)if(d<=c[e].max)return e;return c.length-1};D.jJ.AL=function(a,b){var c=a.A().thresholds;return c&&0<=b&&b<c.length?c[b]:D.o};D.jJ.hPa=function(a,b){var c=a.A().referenceLines;return c&&0<=b&&b<c.length?c[b]:D.o};
D.mJ=function(a){this.Init(a.j(),a.Wa,a);this.Mf=a;this.qn=D.p};D.y.q(D.mJ,D.Xk,"DvtGaugeEventManager");D.x=D.mJ.prototype;D.x.Ll=function(a){this.Mf.A().readOnly===D.p?(this.qn=D.k,this.Vc(),a=(0,D.sJ)(this,a.pageX,a.pageY),this.Mf.kU(a.x,a.y)):D.mJ.u.Ll.call(this,a)};D.x.yn=function(a){this.qn?(this.qn=D.p,a=(0,D.sJ)(this,a.pageX,a.pageY),this.Mf.O2(a.x,a.y)):D.mJ.u.yn.call(this,a)};
D.x.ks=function(a){if(this.qn){var b=(0,D.sJ)(this,a.pageX,a.pageY);this.Mf.hI(b.x,b.y)}(this.q1()||!this.qn)&&D.mJ.u.ks.call(this,a)};D.x.q1=(0,D.ba)(D.p);
D.x.aN=function(a){if(D.Ye.eg===a.type&&this.Mf.A().readOnly===D.p){this.qn=D.k;var b=(0,D.sJ)(this,a.touches[0].pageX,a.touches[0].pageY);this.Mf.kU(b.x,b.y);a.preventDefault()}else D.Ye.rk===a.type&&this.qn?(b=(0,D.sJ)(this,a.touches[0].pageX,a.touches[0].pageY),this.Mf.hI(b.x,b.y),a.preventDefault()):D.Ye.Pi===a.type&&this.qn&&(this.qn=D.p,b=(0,D.sJ)(this,a.changedTouches[0].pageX,a.changedTouches[0].pageY),this.Mf.O2(b.x,b.y),a.preventDefault());(!this.qn||this.q1())&&D.mJ.u.aN.call(this,a)};
D.sJ=function(a,b,c){b=(0,D.qv)(a.j(),b,c);return a.Mf.oc(b)};D.mJ.prototype.fw=(0,D.s)();
D.oJ=function(a,b){this.Init(a,b)};D.y.q(D.oJ,D.On,"DvtGaugeKeyboardHandler");D.oJ.prototype.Init=function(a,b){D.oJ.u.Init.call(this,a);this.Mf=b};
D.oJ.prototype.Gj=function(a){var b=a.keyCode,c=(0,D.F)(this.Mf.j());if(38==b||b==(c?37:39))b=this.Mf,b.G.readOnly||(c=b.G.value,b.G.value=b.G.step!=D.o?D.kJ.FY(b.G,b.G.value+b.G.step):window.Math.min(window.Math.max(b.G.value+(b.G.max-b.G.min)/100,b.G.min),b.G.max),b.U(),b.Wa(new D.QC(c,b.G.value,D.k))),(0,D.ji)(a);else if(40==b||b==(c?39:37))b=this.Mf,b.G.readOnly||(c=b.G.value,b.G.value=b.G.step!=D.o?D.kJ.FY(b.G,b.G.value-b.G.step):window.Math.min(window.Math.max(b.G.value-(b.G.max-b.G.min)/100,
b.G.min),b.G.max),b.U(),b.Wa(new D.QC(c,b.G.value,D.k))),(0,D.ji)(a)};
D.dJ={};D.y.q(D.dJ,D.y,"DvtGaugeStyleUtils");D.dJ.hNa=["#ed6647","#fad55c","#68c182"];D.dJ.Ywa=["#D62800","#FFCF21","#84AE31"];D.dJ.Ywa=["#D62800","#FFCF21","#84AE31"];D.dJ.Cva={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:80,y:86,width:40,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};
D.dJ.Dva={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:83,y:86,width:34,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};D.dJ.Fva={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:83,y:86,width:34,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};
D.dJ.Gva={startAngle:220.5,angleExtent:261.1,anchorX:100,anchorY:100,metricLabelBounds:{x:82,y:133,width:36,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:61,majorTickCount:6};D.dJ.Hva={startAngle:195.5,angleExtent:210.8,anchorX:100,anchorY:100,metricLabelBounds:{x:84,y:135,width:32,height:35},indicatorLength:0.98,tickLabelHeight:20,tickLabelWidth:30,radius:63,majorTickCount:6};
D.dJ.Jva={startAngle:207.6,angleExtent:235,anchorX:100,anchorY:95.8,metricLabelBounds:{x:83,y:125,width:34,height:40},indicatorLength:1.05,tickLabelHeight:20,tickLabelWidth:30,radius:64,majorTickCount:6};D.dJ.kwa={startAngle:220.5,angleExtent:261.1,anchorX:100,anchorY:100,metricLabelBounds:{x:80,y:82,width:40,height:40},indicatorLength:0.82,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};
D.dJ.lwa={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:89,metricLabelBounds:{x:80,y:70,width:41,height:39},indicatorLength:1.23,tickLabelHeight:20,tickLabelWidth:30,radius:56,majorTickCount:6};D.dJ.nwa={startAngle:211,angleExtent:242,anchorX:100,anchorY:91.445,metricLabelBounds:{x:78,y:75,width:44,height:38},indicatorLength:1.1,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};
D.dJ.Rva={startAngle:220.5,angleExtent:261.5,metricLabelBounds:{x:80,y:82,width:40,height:40},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};D.dJ.Sva={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:89,metricLabelBounds:{x:80,y:73,width:40,height:36},indicatorLength:1.23,tickLabelHeight:20,tickLabelWidth:30,radius:56,majorTickCount:6};
D.dJ.Uva={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:99.5,metricLabelBounds:{x:80,y:83,width:41,height:36},indicatorLength:1.1,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};D.dJ.Iva={anchorX:42,anchorY:510};D.dJ.Eva={anchorX:187,anchorY:388};D.dJ.mwa={anchorX:227,anchorY:425};D.dJ.Tva={anchorX:227,anchorY:425};
D.dJ.Ib=function(a){var b=a.A(),c=D.jJ.OG(a),d=D.jJ.AL(a,c);return d&&(!(a instanceof D.tJ)||a instanceof D.tJ&&"onIndicator"==b.thresholdDisplay)?D.dJ.tR(a,d,c):b.color};D.dJ.tl=function(a){var b=a.A(),c=D.jJ.OG(a);return(c=D.jJ.AL(a,c))&&c.borderColor&&(!(a instanceof D.tJ)||a instanceof D.tJ&&"onIndicator"==b.thresholdDisplay)?c.borderColor:b.borderColor};
D.dJ.vqa=function(a){var b=a.A(),c=D.jJ.OG(a),d=D.jJ.AL(a,c);return d&&(!(a instanceof D.tJ)||a instanceof D.tJ&&"onIndicator"!=b.thresholdDisplay)?D.dJ.tR(a,d,c):b.plotArea.color};D.dJ.tR=function(a,b,c){if(b.color)return b.color;a=a.A();return a._thresholdColors[c%a._thresholdColors.length]};
D.dJ.eHa=function(a){return"rectangleAlta"===a?D.dJ.Fva:"domeAlta"===a?D.dJ.Dva:"circleAntique"===a?D.dJ.Gva:"rectangleAntique"===a?D.dJ.Jva:"domeAntique"===a?D.dJ.Hva:"circleLight"===a?D.dJ.kwa:"rectangleLight"===a?D.dJ.nwa:"domeLight"===a?D.dJ.lwa:"circleDark"===a?D.dJ.Rva:"rectangleDark"===a?D.dJ.Uva:"domeDark"===a?D.dJ.Sva:D.dJ.Cva};D.dJ.fHa=function(a){return"needleAntique"===a?D.dJ.Iva:"needleLight"===a?D.dJ.mwa:"needleDark"===a?D.dJ.Tva:D.dJ.Eva};
D.kJ={};D.y.q(D.kJ,D.y,"DvtGaugeRenderer");D.kJ.sn=function(a,b,c){var d=a.A(),e=d.emptyText;e||(e=(0,D.Zl)(d,"labelNoData","DvtUtilBundle","NO_DATA",D.o));d.metricLabel.style.D("font-size")||d.metricLabel.style.ca("font-size","13px");D.yf.sn(b,e,new D.B(c.x,c.y,c.e,c.g),a.Aa(),d.metricLabel.style)};
D.kJ.gn=function(a,b){var c=b.A(),d=D.o,e="percent"==c.metricLabel.textType;"on"==c.metricLabel.rendered&&c.metricLabel.converter&&(d=c.metricLabel.converter);var f=D.o;"on"==c.metricLabel.rendered&&c.metricLabel.scaling&&(f=c.metricLabel.scaling);return D.kJ.Tia(a,b,d,f,c.metricLabel.autoPrecision?c.metricLabel.autoPrecision:"on",e)};
D.kJ.j$=function(a,b){var c=b.A(),d=D.o,e="percent"==c.tickLabel.textType;"on"==c.tickLabel.rendered&&c.tickLabel.converter&&(d=c.tickLabel.converter);var f=D.o;"on"==c.tickLabel.rendered&&c.tickLabel.scaling&&(f=c.tickLabel.scaling);return D.kJ.Tia(a,b,d,f,c.tickLabel.autoPrecision?c.tickLabel.autoPrecision:"on",e)};
D.kJ.Tia=function(a,b,c,d,e,f){var g=b.A(),h=D.o,j=g.min,l=g.max,m=l-j,n=D.o;(0,window.isNaN)(m)||(n=m/(1E3>m?100:1E3));f&&(a=D.kJ.bR(g,g.min,a),h=(0,D.Dl)(b.j(),{style:"percent",maximumFractionDigits:0}));b=new D.tl(b.j(),j,l,n,d,e);a=c&&c.getAsString?b.oq(a,c):c&&c.format?b.oq(a,c):h?b.oq(a,h):f?b.oq(100*a):b.oq(a);return f&&(!h||c)?(0,window.String)(a)+"%":a};D.kJ.bR=function(a,b,c){a=(c-b)/(a.max-a.min);return a=window.Math.min(window.Math.max(0,a),1)};
D.kJ.LG=function(a){var b=a.A(),c=D.jJ.OG(a);return(c=D.jJ.AL(a,c))&&c.shortDesc!=D.o?c.shortDesc:b.shortDesc!=D.o?b.shortDesc:D.kJ.gn(b.value,a)};
D.kJ.Eba=function(a,b,c,d){var e=a.A();if("on"==e.metricLabel.rendered){var f=D.kJ.gn(e.value,a),g=D.kJ.gn(e.min,a),h=D.kJ.gn(e.max,a),j=c.e,l=c.g;a=new D.lg(a.j(),f,c.x+c.e/2,c.y+c.g/2);a.Na(e.metricLabel.style);e=(e=e.metricLabel.style.D("font-size"))?(0,window.parseInt)(e):D.o;e||(e=D.kJ.KY([f,g,h],a,c),a.Te(f),a.qf(e));a.Xf();a.Ff();d!=D.o&&a.ra(d);D.yf.wc(a,j,l,b)&&a.ua(D.p)}};D.kJ.KY=function(a,b,c){for(var d=0,e=D.o,f=0,g=0;g<a.length;g++)b.Te(a[g]),f=b.Lb().e,f>d&&(e=a[g],d=f);b.Te(e);return b.KC(c)};
D.kJ.FY=function(a,b){var c=(0,window.Number)(a.step);if(c&&0<c){var d=(b-a.min)/c;return 0.5<d?window.Math.max(window.Math.min(a.max,window.Math.round(d)*c+a.min),a.min):a.min}return b};
D.uJ=(0,D.s)();(0,D.ca)("DvtLedGauge",D.uJ);D.y.q(D.uJ,D.bJ,"DvtLedGauge");D.vJ=function(a,b,c,d){var e=new D.uJ;e.Init(a,b,c,d);return e};D.uJ.newInstance=D.vJ;D.uJ.prototype.Init=function(a,b,c,d){D.uJ.u.Init.call(this,a,b,c,d);this.If=new D.wJ};D.uJ.prototype.Od=function(a){D.uJ.u.Od.call(this,this.If.ej(a));"auto"==this.G.animationOnDisplay&&(this.G.animationOnDisplay="zoom");"auto"==this.G.animationOnDataChange&&(this.G.animationOnDataChange="alphaFade");this.G.readOnly=D.k};
D.uJ.prototype.sj=function(a,b,c){D.xJ.U(this,a,b,c)};
D.wJ=function(){this.Init({skyros:D.yJ,alta:{}})};D.y.q(D.wJ,D.hJ,"DvtLedGaugeDefaults");D.yJ={type:"circle"};
D.xJ={};D.y.q(D.xJ,D.y,"DvtLedGaugeRenderer");D.xJ.iNa=1/6;D.xJ.Wwa="M-42,36.6Q-50,36.6,-46.54,28.6L-4,-43.07Q0,-50,4,-43.07L46.54,28.6Q50,36.6,42,36.6Z";D.xJ.Rwa=[-50,36.6,0,-50,50,36.6];D.xJ.Xwa=[-50,36.6,0,-50,50,36.6];D.xJ.qga=[-13.05,-12.94,-50,-11.13,-21.06,11.9,-30.74,47.6,0.1,27.18,31.06,47.44,21.17,11.79,50,-11.39,13.05,-13.01,-0.06,-47.59];D.xJ.Qwa=[-50,-11.22,-16.69,-17.94,0,-47.55,16.69,-17.94,50,-11.22,26.69,13.8,30.9,47.56,0,33.42,-30.9,47.56,-26.69,13.8];D.xJ.Uwa="M0,45L21,45Q24.414,44.414,25,41L25,10L42,10Q48.5,9.1,45,4L2,-38Q0,-39,-2,-38L-45,4Q-48.5,9.1,-42,10L-25,10L-25,41Q-24.414,44.414,-21,45Z";
D.xJ.Owa=[25,48,25,8,47.5,8,0,-39,-47.5,8,-25,8,-25,48];D.xJ.Vwa=[25,48,25,8,47.5,8,0,-39,-47.5,8,-25,8,-25,48];D.xJ.Pwa="M -0.06059525142297417 -50.86842065108466 C -11.4496388584463 -50.86842065108466 -20.708163169810554 -39.024253028220556 -20.708163169810554 -24.413724255650386 C -20.708163169810554 -9.803195483080515 -11.4496388584463 2.040972139783591 -0.06059525142297417 2.040972139783591 C 11.328499974520241 2.040972139783591 20.586972666964613 -9.803195483080515 20.586972666964613 -24.413724255650386 C 20.586972666964613 -39.024253028220556 11.328499974520241 -50.86842065108466 -0.06059525142297417 -50.86842065108466 z M -23.93434565705865 -2.959610715450779 C -30.908061721494278 3.3998402034127153 -42.00096758564793 18.817121073473572 -38.77478509839983 33.65756051481475 C -20.651382358034887 47.30044101688934 14.372054723529814 49.13162219665128 39.298831093003386 32.85101489300273 C 40.26410489318826 16.477493533721187 32.34060070450674 4.7883891459240715 23.167918656763206 -2.959610715450779 C 11.553661702670112 21.074158341552575 -11.029615708066558 16.237465556670102 -23.93434565705865 -2.959610715450779 z ";
D.xJ.U=function(a,b,c,d){if(D.jJ.vx(a)){var e=a.A(),f=e.__layout.outerGap,g=e&&(0<=e.size||1>e.size)?window.Math.sqrt(e.size):1;c=new D.B(f+(c-2*f)*(1-g)/2,f+(d-2*f)*(1-g)/2,(c-2*f)*g,(d-2*f)*g);D.xJ.UP(a,b,c);D.xJ.j8(a,b,c);"on"==e.metricLabel.rendered&&(D.Sp!==D.k&&e.metricLabel.style.D("color")!=D.o?D.kJ.Eba(a,b,D.xJ.kja(a,c),D.o):(d=D.J.gk(D.dJ.Ib(a)),e.metricLabel.style.ca("color",d),D.kJ.Eba(a,b,D.xJ.kja(a,c),d)))}else D.kJ.sn(a,b,new D.B(0,0,c,d))};
D.xJ.UP=function(a,b,c){var d=a.j(),e=a.A(),f=e.type,g=D.dJ.Ib(a),h=D.dJ.tl(a),j=c.x+c.e/2,l=c.y+c.g/2,m=window.Math.min(c.e,c.g)/2,n=(0,D.rJ)(a),q,r=window.Math.min(c.e/100,c.g/100);"rectangle"==f?d=new D.D(d,c.x,c.y,c.e,c.g):"diamond"==f?d=new D.cp(d,[j-m,l,j,l-m,j+m,l,j,l+m]):"star"==f||"triangle"==f||"arrow"==f||"human"==f?("star"==f?q=n?D.xJ.qga:D.xJ.Qwa:"triangle"==f?q=n?D.xJ.Wwa:D.xJ.Rwa:"arrow"==f?q=n?D.xJ.Uwa:D.xJ.Owa:"human"==f&&(q=D.xJ.Pwa),n&&"triangle"==f||n&&"arrow"==f||"human"==f?(q=
D.K.MS(q,c.x+c.e/2,c.y+c.g/2,r,r),d=new D.Ei(d,q)):(q=D.bp.scale(q,r,r),q=D.bp.translate(q,c.x+c.e/2,c.y+c.g/2),d=new D.cp(d,q))):d=new D.dp(d,j,l,m);n||"none"==e.visualEffects?d.ra(g):(j=[D.J.Mh(g,-0.09,0.04),D.J.Mh(g,-0.04,-0.05)],l=e&&0==e.rotation%90?e.rotation:0,d.O(new D.Ug("arrow"==f||"star"==f||"triangle"==f?l-90:270,j,[1,1],[0,1])));h&&d.Ya(h);h=a.Aa();(j=D.kJ.LG(a))&&h&&h.Ba(d,new D.Ok(D.o,j,g));l=n?e.rotation+90:e.rotation;if(0!=l&&("arrow"==f||"triangle"==f))d=D.xJ.q8(a,b,d,c);b.k(d)};
D.xJ.q8=function(a,b,c,d){var e=a.A();a=new D.C(a.j());b.k(a);a.k(c);b=e&&0==e.rotation%90?e.rotation:0;e=new D.vk;e.rotate(window.Math.PI*b/180);c.Ga(e);b=a.I();c=d.x+d.e/2-(b.x+b.e/2);d=d.y+d.g/2-(b.y+b.g/2);b=new D.vk;b.translate(c,d);a.Ga(b);return a};D.xJ.j8=function(a,b,c){var d=a.A(),e=d.type;"none"!=d.visualEffects&&(0,D.rJ)(a)&&("rectangle"==e?D.xJ.FDa(a,b,c):"diamond"==e?D.xJ.EDa(a,b,c):"triangle"==e?D.xJ.HDa(a,b,c):"star"==e?D.xJ.GDa(a,b):"arrow"==e?D.xJ.CDa(a,b,c):D.xJ.DDa(a,b,c))};
D.xJ.FDa=function(a,b,c){var d=0.05*c.e,e=0.05*c.g;c=new D.B(c.x+d,c.y+e,c.e-2*d,c.g-2*e);a=new D.D(a.j(),c.x,c.y,c.e,c.g);a.ua(D.p);b.k(a);b=new D.Ug(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);a.O(b)};
D.xJ.EDa=function(a,b,c){var d=0.05*c.e,e=0.05*c.g,e=new D.B(c.x+d,c.y+e,c.e-2*d,c.g-2*e);c=e.x+e.e/2;d=e.y+e.g/2;e=window.Math.min(e.e,e.g)/2;a=new D.cp(a.j(),[c-e,d,c,d-e,c+e,d,c,d+e]);a.ua(D.p);b.k(a);b=new D.Ug(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);a.O(b)};
D.xJ.HDa=function(a,b,c){var d=0.05*c.e,e=0.05*c.g,f=(0,D.rJ)(a),d=new D.B(c.x+d,c.y+e,c.e-2*d,c.g-2*e),e=D.xJ.Xwa,g=window.Math.min(d.e/100,d.g/100),e=D.bp.scale(e,g,g),e=D.bp.translate(e,c.x+c.e/2,c.y+c.g/2);c=new D.cp(a.j(),e);e=(e=a.A())&&0==e.rotation%90?e.rotation:0;f=new D.Ug(f?e-90:360-e,["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);c.O(f);c=D.xJ.q8(a,b,c,d);c.ua(D.p);b.k(c)};
D.xJ.CDa=function(a,b,c){var d=0.05*c.e,e=0.05*c.g,f=(0,D.rJ)(a),d=new D.B(c.x+d,c.y+e,c.e-2*d,c.g-2*e),e=D.xJ.Vwa,g=window.Math.min(d.e/100,d.g/100),e=D.bp.scale(e,g,g),e=D.bp.translate(e,c.x+c.e/2,c.y+c.g/2);c=new D.cp(a.j(),e);e=(e=a.A())&&0==e.rotation%90?e.rotation:0;f=new D.Ug(f?e-90:360-e,["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);c.O(f);c=D.xJ.q8(a,b,c,d);c.ua(D.p);b.k(c)};
D.xJ.GDa=function(a,b){var c=new D.Ei(a.j(),D.xJ.qga),d=a.A(),d=360-(d&&0==d.rotation%90?d.rotation:0),e=D.dJ.Ib(a),e=[D.J.en(e,0.9),e,D.J.vpa(e)],d=new D.Ug(d,e,[1,1,1],[0.1,0.4,0.8]);c.O(d);c.ua(D.p);b.k(c)};
D.xJ.DDa=function(a,b,c){var d=0.05*c.e,e=0.05*c.g;c=new D.B(c.x+d,c.y+e,c.e-2*d,c.g-2*e);var d=c.x+c.e/2,e=c.y+c.g/2,f=window.Math.min(c.e,c.g)/2,g=new D.dp(a.j(),d,e,f);g.ua(D.p);b.k(g);var h=new D.iq(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.25,0.5],[0.15,0.7,0.95],d,e-0.6*f,1.5*f,[c.x,c.y,c.e,c.g]);g.O(h);g=0.6*f;f*=0.4;e-=0.3*f;a=new D.XH(a.j(),d,e-f,g,f);a.ua(D.p);b.k(a);b=new D.iq(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.2,0.5],[0.6,0.8,1],d,e,g,[c.x,c.y,c.e,c.g]);a.O(b)};
D.xJ.kja=function(a,b){var c=a.A(),d=c.type,c=0==c.rotation%90?c.rotation:0,e=window.Math.min(b.e,b.g),f=b.x+b.e/2-e/2,g=b.y+b.g/2-e/2,h=e,j=e;if("triangle"==d)0==c?(f+=0.2*e,g+=0.25*e,h-=0.4*e,j-=0.3*e):90==c?(f+=0.05*e,g+=0.2*e,h-=0.3*e,j-=0.4*e):180==c?(f+=0.2*e,g+=0.05*e,h-=0.4*e,j-=0.3*e):270==c&&(f+=0.25*e,g+=0.2*e,h-=0.3*e,j-=0.4*e);else if("arrow"==d)0==c?(f+=0.2*e,g+=0.2*e,h-=0.4*e,j-=0.4*e):90==c?(f+=0.05*e,g+=0.2*e,h-=0.28*e,j-=0.4*e):180==c?(f+=0.2*e,g+=0.2*e,h-=0.4*e,j-=0.4*e):270==c&&
(f+=0.23*e,g+=0.2*e,h-=0.28*e,j-=0.4*e);else if("star"==d)f+=0.25*e,g+=0.25*e,h-=0.5*e,j-=0.4*e;else if("diamond"==d)f+=0.15*e,g+=0.15*e,h-=0.3*e,j-=0.3*e;else if("rectangle"==d)f+=0.1*e,g+=0.1*e,h-=0.2*e,j-=0.2*e;else if("circle"==d||"human"==d)f+=0.15*e,g+=0.15*e,h-=0.3*e,j-=0.3*e;return new D.B(f,g,h,j)};
D.tJ=(0,D.s)();(0,D.ca)("DvtStatusMeterGauge",D.tJ);D.y.q(D.tJ,D.bJ,"DvtStatusMeterGauge");D.tJ.newInstance=function(a,b,c){var d=new D.tJ;d.Init(a,b,c);return d};D.x=D.tJ.prototype;D.x.Init=function(a,b,c){D.tJ.u.Init.call(this,a,b,c);this.If=new D.HJ;this.N2=D.o};D.x.Od=function(a){D.tJ.u.Od.call(this,this.If.ej(a))};D.x.sj=function(a,b,c){D.IJ.U(this,a,b,c)};
D.x.m0=function(a,b,c){b=[];for(var d=0;d<a.length;d++){var e=a[d],f=e.oe();"horizontal"==this.G.orientation?e.Md([f[0],f[0],f[2],f[3]]):"vertical"==this.G.orientation?e.Md([f[0],f[1],f[3],f[3]]):"circular"==this.G.orientation&&e.Md([f[0],f[1],0,f[3],f[4]]);var g=new D.yo(this.j(),e,c);(0,D.S)(g.P,"typeNumberArray",e,e.oe,e.Md,f);g.P.Dl(function(a){return(0,D.xD)(a,0.7)});b.push(g)}return new D.wo(this.j(),b)};
D.x.FA=function(a,b){var c=this.G,d=(0,D.F)(this.j());if("horizontal"==c.orientation)return this.N2.aZ(a);if("vertical"==c.orientation)return this.N2.aZ(b);if("circular"==c.orientation){var e=c.angleExtent,f=window.Math.atan2(b-this.Wo,a-this.Vo),d=d?180-(D.eh.TL(f)-c.startAngle):D.eh.TL(f)-(360-c.startAngle),d=(d+720)%360,f=c.min,c=c.max,f=d/e*(c-f)+f;d>e&&(f=0.5<(d-e)/(360-e)?0:c);return f}};
D.HJ=function(){this.Init({skyros:D.LJ,alta:D.MJ})};D.y.q(D.HJ,D.hJ,"DvtStatusMeterGaugeDefaults");D.MJ={color:"#393737",metricLabel:{style:new D.I("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},plotArea:{color:"#f5f6f7",borderColor:"#D6DFE6"}};
D.LJ={angleExtent:360,color:"#313842",indicatorSize:1,innerRadius:0.7,metricLabel:{style:new D.I("font-family: tahoma, sans-serif; color: #333333;")},orientation:"horizontal",plotArea:{color:"#AAAAAA",borderColor:"#C6C6C6",rendered:"auto"},startAngle:90,thresholdDisplay:"onIndicator"};
D.IJ={};D.y.q(D.IJ,D.y,"DvtStatusMeterGaugeRenderer");D.IJ.U=function(a,b,c,d){if(D.jJ.vx(a)){var e=a.A(),f=e.__layout.outerGap;c=new D.B(f,f,c-2*f,d-2*f);"horizontal"==e.orientation||"vertical"==e.orientation?(D.IJ.dq(a,b,c),D.IJ.UP(a,b,c)):"circular"==e.orientation&&D.IJ.jDa(a,b,c)}else D.kJ.sn(a,b,new D.B(0,0,c,d))};
D.IJ.jDa=function(a,b,c){var d=a.A(),e=(0,D.F)(a.j()),f=0,g=D.o,h=d.value,j=d.innerRadius,l=d.thresholds,m=D.o,n=D.eh.eN-D.eh.Br(d.startAngle),q=D.eh.Br(d.angleExtent),r=(n+q)%(2*window.Math.PI);a.Vo=c.e/2;a.Wo=c.g/2;q!=2*window.Math.PI&&(g=D.IJ.Exa(a,j,n,q,r,c,e));var m=m?m:window.Math.min(c.e,c.g),e=0.5*m*j,r=0.5*m,t=d.indicatorSize;if(t&&1<t)var u=(1-1/t)/2*(r-e),e=e+u,r=r-u;g||(g=window.Math.min(c.e,c.g)*j,j?j*window.Math.min(c.e,c.g):window.Math.min(c.e,c.g),g=new D.B(c.x+c.e/2-g*(3/7),c.y+c.g/
2-g*(2.5/7),g*(6/7),g*(5/7)));D.kJ.Eba(a,b,g,D.o);g=n;f*=q;if(l&&"off"!=d.plotArea.rendered&&"all"==d.thresholdDisplay)for(u=0;u<l.length;u++){var A=D.dJ.tR(a,l[u],u),f=l[u].max<d.max?l[u].max:d.max,z=0==u?d.min:l[u-1].max,g=n+q*D.kJ.bR(d,d.min,z),f=D.kJ.bR(d,z,f),f=f*q;D.IJ.S4(a,b,c,g,f,e,r,A,D.k)}else"off"!=d.plotArea.rendered&&(!("auto"==d.plotArea.rendered&&"onIndicator"==d.thresholdDisplay)&&"all"!=d.thresholdDisplay)&&(A=D.dJ.vqa(a),D.IJ.S4(a,b,c,n,q,e,r,A,D.k));e=0.5*m*j;r=0.5*m;t&&1>t&&(j=
(1-t)/2*(r-e),e+=j,r-=j);f=D.kJ.bR(d,d.min,h);D.IJ.S4(a,b,c,n,f*q,e,r,D.dJ.Ib(a),D.p);if(j=d.referenceLines)for(l=0;l<j.length;l++)m=j[l].color?j[l].color:"black",e=j[l].lineWidth?j[l].lineWidth:2,r=j[l].lineStyle,h=j[l].value,h=n+D.kJ.bR(d,d.min,h)*q,D.IJ.Eza(a,b,c,h,m,e,r);c=new D.D(a.j(),c.x,c.y,c.e,c.g);(0,D.Aj)(c);b.k(c);((b=D.kJ.LG(a))||a.A().readOnly===D.p)&&a.Aa().Ba(c,new D.Ok(D.o,b,D.dJ.Ib(a)))};
D.IJ.UP=function(a,b,c){var d=a.A(),e=(0,D.F)(a.j()),f="vertical"==d.orientation,g={layout:{}};g.layout.gapRatio=0;g.timeAxisType="disabled";g.position=f?"left":"bottom";g.min=d.min;g.max=d.max;g.dataMin=d.min;g.dataMax=d.max;g.tickLabel={rendered:"off"};g=(0,D.hl)(a.j(),g,c);a.N2=g;var h=0;0>=d.max?h=d.max:0<=d.min&&(h=d.min);h=g.Qg(h);"off"!=d.plotArea.rendered&&!("auto"==d.plotArea.rendered&&"onIndicator"==d.thresholdDisplay)&&(h=g.of(d.min));var j=g.of(d.value),j=f?window.Math.max(c.y,window.Math.min(c.y+
c.g,j)):window.Math.max(c.x,window.Math.min(c.x+c.e,j)),l=d.indicatorSize,m,n,q,r,t,u,A=0,z=1>l?1:l;q=1<l?1:l;f?(l=c.x+(1-q)/2*c.e+0.5,m=c.x+c.e*(1+q)/2-0.5,q=h-0.5,n=j+0.5,r=c.x+(1-1/z)/2*c.e,t=c.x+c.e*(1+1/z)/2,u=c.y,A=c.y+c.g):(l=e?h-0.5:h+0.5,m=e?j+0.5:j-0.5,n=c.y+(1-q)/2*c.g+0.5,q=c.y+c.g*(1+q)/2-0.5,r=c.x,t=c.x+c.e,u=c.y+(1-1/z)/2*c.g,A=c.y+c.g*(1+1/z)/2);z=D.k;j==h&&(z=D.p);var E=D.dJ.tl(a),U=d.plotArea.borderColor,L=d.thresholds,j=f?0:270;if(L&&"off"!=d.plotArea.rendered&&"all"==d.thresholdDisplay)for(h=
L.length-1;0<=h;h--){var O=h,Z=D.IJ.Fy(a,a.j(),r,t,u,A),W=new D.ih("pacp"+a.getId());h==L.length-1?!f&&e?(0,D.kh)(W,g.of(d.max),0,c.e+2,c.g+2,0,0):(0,D.kh)(W,0,0,c.e+2,c.g+2,0,0):f?(0,D.kh)(W,0,g.of(d.max),c.e+2,1*(d.max-L[L.length-2-O].max)/window.Math.abs(d.min-d.max)*c.g,0,0):e?(0,D.kh)(W,0,0,1*(d.max-(L[L.length-2-O].max==D.o?100:L[L.length-2-O].max))/window.Math.abs(d.min-d.max)*c.e,c.g+2,0,0):(0,D.kh)(W,0,0,1*(L[O].max-d.min)/window.Math.abs(d.min-d.max)*c.e,c.g+2,0,0);(0,D.lh)(Z,W);if(e||f)O=
L.length-1-h;Z.ra(D.dJ.tR(a,L[O],O));Z.Ya(U);D.IJ.ena(a,b,Z,D.dJ.tR(a,L[O],O),j)}else"off"!=d.plotArea.rendered&&(!("auto"==d.plotArea.rendered&&"onIndicator"==d.thresholdDisplay)&&"all"!=d.thresholdDisplay)&&(Z=f?D.IJ.Fy(a,a.j(),r,t,g.of(d.max),g.of(d.min)):D.IJ.Fy(a,a.j(),g.of(d.min),g.of(d.max),u,A),h=D.dJ.vqa(a),Z.ra(h),Z.Ya(U),D.IJ.ena(a,b,Z,h,j));h=D.IJ.Fy(a,a.j(),l,m,n,q);a.hy.push(h);e=D.dJ.Ib(a);!(0,D.rJ)(a)&&"none"!=d.visualEffects?(r=[D.J.Mh(e,-0.09,0.04),D.J.Mh(e,-0.04,-0.05)],r=new D.Ug(j,
r,[1,1],[0,1]),h.O(r)):h.ra(e);E&&h.Ya(E);z&&b.k(h);h=D.IJ.Fy(a,a.j(),l,m,n,q);D.IJ.j8(a,b,h,z,j);if(m=d.referenceLines)for(h=0;h<m.length;h++)n=m[h].color?m[h].color:"white",j=m[h].value,l=d.indicatorSize,f?(z=((1-l)/2+l)*c.e,q=c.x+(1-l)/4*c.e,l=g.of(j),l=new D.Hj(a.j(),q,l,q+z,l)):(z=((1-l)/2+l)*c.g,q=g.of(j),l=c.y+(1-l)/4*c.g,l=new D.Hj(a.j(),q,l,q,l+z)),n=new D.Wg(n,1,m[h].lineWidth?m[h].lineWidth:2),m[h].lineStyle&&n.ca((0,D.Xg)(m[h].lineStyle)),l.ea(n),b.k(l),!(0,D.dk)()&&"none"!=d.visualEffects&&
(n=new D.Vp(D.J.Bv(0,0,0,0.8),0.75,3,3,50,1,2,D.p,D.p,D.p),(0,D.Yp)(l,n));c=new D.D(a.j(),c.x,c.y,c.e,c.g);(0,D.Aj)(c);b.k(c);((b=D.kJ.LG(a))||d.readOnly===D.p)&&a.Aa().Ba(c,new D.Ok(D.o,b,e))};D.IJ.Fy=function(a,b,c,d,e,f){return new D.NJ(a,b,c,d,e,f)};D.IJ.j8=function(a,b,c,d,e){"none"!=a.A().visualEffects&&(0,D.rJ)(a)&&(e=new D.Ug(e,["#FFFFFF","#FFFFFF","#FFFFFF"],[0.5,0.3125,0],[0,0.3,1]),c.O(e),a.hy.push(c),c.ua(D.p),d&&b.k(c))};
D.IJ.ena=function(a,b,c,d,e){var f=a.A();c.ua(D.p);b.k(c);"none"!=f.visualEffects&&((0,D.rJ)(a)?(a=[D.J.en(d,0.9),d,D.J.vpa(d)],e=new D.Ug(e,a,[1,1,1],[0,0.04,0.73])):(a=[D.J.Mh(d,-0.04,-0.05),D.J.Mh(d,-0.09,0.04)],e=new D.Ug(e,a,[1,1],[0,1])),c.O(e))};
D.IJ.dq=function(a,b,c){var d=a.A(),e=(0,D.F)(a.j()),f="vertical"==d.orientation,g=new D.lg(a.j(),""),h=D.kJ.gn(d.value,a),j=d.__layout.labelGap;g.Na(d.metricLabel.style);if(f&&"on"==d.metricLabel.rendered){var l=0<d.max?d.max:d.min,l=D.kJ.gn(l,a),m=new D.lg(a.j(),l);m.Na(d.metricLabel.style);e=new D.B(c.x,c.y+0.8*c.g,c.e,0.2*c.g);f=(f=d.metricLabel.style.D("font-size"))?(0,window.parseInt)(f):m.KC(e);m=m.Lb();c.g-=m.g;l=m.e;g.qf(f);g.Te(h);g.ja(c.x+c.e/2);g.Ea(c.y+c.g);c.g-=j;g.Ff();D.yf.wc(g,c.e,
c.g,b)}else if(!f&&"on"==d.metricLabel.rendered){var f=(f=d.metricLabel.style.D("font-size"))?(0,window.parseInt)(f):13,n=D.kJ.gn(d.min,a),m=D.kJ.gn(d.max,a);18>c.g&&(f=D.kJ.KY([h,n,m],g,c));g.qf(f);var q;if(0<d.max||"off"!=d.plotArea.rendered||!("auto"==d.plotArea.rendered&&"onIndicator"==d.thresholdDisplay))l=0<d.max?d.max:d.min,l=D.kJ.gn(l,a),m=new D.lg(a.j(),l),m.Na(d.metricLabel.style),m.qf(f),m=m.Lb(),q=e?c.x+m.e:c.x+c.e,l=m.e,e&&(c.x+=m.e+j),c.e-=m.e+j;if(0>d.min&&"on"!=d.plotArea.rendered&&
!("auto"==d.plotArea.rendered&&"onIndicator"==d.thresholdDisplay)){f=D.kJ.gn(d.min,a);n=new D.lg(a.j(),f);n.Na(d.metricLabel.style);a=n.Lb();if(0>d.value||0>=d.max)q=e?c.x+c.e:c.x+a.e,l=a.e;e||(c.x+=a.e+j);c.e-=a.e+j}g.Te(h);g.ja(q);g.Ea(c.y+c.g/2);g.Xf();g.Di();D.yf.wc(g,l,c.g,b)}};D.IJ.uw=function(a,b,c){return{x:window.Math.cos(c)*b+a.e/2+a.x,y:window.Math.sin(c)*b+a.g/2+a.y}};
D.IJ.S4=function(a,b,c,d,e,f,g,h,j){var l=a.j();(0,D.F)(a.j())&&(d=window.Math.PI-d-e,d=0<d?d:d+2*window.Math.PI);j?c=new D.Ei(l,D.IJ.Goa(c,d,e,f,g)):(c=new D.JJ(l,c,d,e,f,g),a.hy.push(c));c.ra(h);(a=D.dJ.tl(a))&&!j&&c.Ya(a);b.k(c)};D.IJ.Eza=function(a,b,c,d,e,f,g){var h=a.j(),j=window.Math.min(c.e,c.g),l=0.275*j,j=0.5*j;(0,D.F)(a.j())&&(d=window.Math.PI-d,d=0<d?d:d+2*window.Math.PI);a=D.IJ.uw(c,l,d);c=D.IJ.uw(c,j,d);h=new D.Hj(h,a.x,a.y,c.x,c.y);e=new D.Wg(e,1,f);g&&e.ca((0,D.Xg)(g));h.ea(e);b.k(h)};
D.IJ.Goa=function(a,b,c,d,e){var f,g,h;c<D.eh.eN?(f=D.IJ.uw(a,e,b),g=D.IJ.uw(a,e,b+c),h=D.IJ.uw(a,d,b+c),a=D.IJ.uw(a,d,b),e=D.K.moveTo(f.x,f.y)+D.K.arcTo(e,e,c,1,g.x,g.y)+D.K.lineTo(h.x,h.y)+D.K.arcTo(d,d,c,0,a.x,a.y)+D.K.closePath()):(f=D.IJ.uw(a,e,b),g=D.IJ.uw(a,e,b+c/2),h=D.IJ.uw(a,d,b),a=D.IJ.uw(a,d,b+c/2),e=D.K.moveTo(f.x,f.y)+D.K.arcTo(e,e,c/2,1,g.x,g.y)+D.K.arcTo(e,e,c/2,1,f.x,f.y),0<d&&(e+=D.K.moveTo(a.x,a.y)+D.K.arcTo(d,d,c/2,0,h.x,h.y)+D.K.arcTo(d,d,c/2,0,a.x,a.y)),e+=D.K.closePath());return e};
D.IJ.kpa=function(a,b){var c=1;if(b)a>=D.eh.HD&&a<window.Math.PI?c=2:a>=window.Math.PI&&a<1.5*window.Math.PI?c=3:a>=1.5*window.Math.PI&&a<D.eh.eN&&(c=4);else if(a>D.eh.HD&&a<=window.Math.PI)c=2;else if(a>window.Math.PI&&a<=1.5*window.Math.PI)c=3;else if(a>1.5*window.Math.PI&&a<D.eh.eN||0==a)c=4;return c};
D.IJ.Exa=function(a,b,c,d,e,f,g){var h=D.o,j=D.IJ.kpa(c,D.k),l=D.IJ.kpa(e,D.p),m=f.e,n=f.g,q=m/2,r=n/2;if(j==l&&d<=D.eh.HD)if(c=2*window.Math.min(f.e,f.g),f.e+=c/2,f.g+=c/2,b*=c,!g&&1==j||g&&2==j)f.x-=c/2,f.y-=c/2,q=m/2-c/4+1,r=n/2-c/4+1,h=new D.B(f.x+f.e/2-1,f.y+f.g/2-1,b*(3/7)-2,b*(2.5/7)-2);else if(!g&&2==j||g&&1==j)f.y-=c/2,q=m/2+c/4-1,r=n/2-c/4+1,h=new D.B(f.x+f.e/2-b*(3/7)+1,f.y+f.g/2-1,b*(3/7)-2,b*(2.5/7)-2);else if(!g&&3==j||g&&4==j)q=m/2+c/4-1,r=n/2+c/4-1,h=new D.B(f.x+f.e/2-b*(3/7)+1,f.y+
f.g/2-b*(2.5/7)+1,b*(3/7)-2,b*(2.5/7)-2);else{if(!g&&4==j||g&&3==j)f.x-=c/2,q=m/2-c/4+1,r=n/2+c/4-1,h=new D.B(f.x+f.e/2-1,f.y+f.g/2-b*(2.5/7)+1,b*(3/7)-2,b*(2.5/7)-2)}else j%4+1==l&&d<=window.Math.PI?1==j||3==j?(c=window.Math.min(f.e,2*f.g),b*=c,f.e>f.g&&(h=new D.B(f.x+f.e/2-b*(3/7),f.y+f.g-(f.g-c/2)/2-b*(2.75/7),b*(6/7),b*(2.5/7)),1==j?(h.y=f.y+(f.g-c/2)/2+b*(0.5/7),f.y-=c/2-(f.g-c/2)/2,r=n/2-c/4+1):(f.y+=(f.g-c/2)/2,r=n/2+c/4-1),f.g=c)):(c=window.Math.min(2*f.e,f.g),b*=c,f.e<f.g&&(h=new D.B(f.x+
f.e-(f.e-c/2)/2-b*(3.25/7),f.y+f.g/2-b*(2.5/7),b*(3/7),b*(5/7)),!g&&4==j||g&&2==j?(h.x=f.x+(f.e-c/2)/2+b*(0.25/7),f.x-=c/2-(f.e-c/2)/2,q=m/2-c/4+1):(f.x+=(f.e-c/2)/2,q=m/2+c/4-1),f.e=c)):l%4+1==j&&d>window.Math.PI&&(1==j&&f.g>f.e?(c=window.Math.min(2*(f.e/(window.Math.cos(c)+1)),2*(f.e/(window.Math.sin(e-1.5*window.Math.PI)+1)),f.g),b*=c,h=b*(3/7)*(2*f.e/c-1),g?(h=new D.B(f.x+f.e-c/2-h,f.y+f.g/2-b*(2.5/7),b*(3/7)+h,b*(5/7)),f.x-=c-f.e,q=-c/2+m):(h=new D.B(f.x+c/2-b*(3/7),f.y+f.g/2-b*(2.5/7),b*(3/
7)*(1+(2*f.e/c-1)),b*(5/7)),q=c/2),f.e=c):2==j&&f.g<f.e?(c=window.Math.min(2*(f.g/(window.Math.cos(c-D.eh.HD)+1)),2*(f.g/(window.Math.sin(e)+1)),f.e),b*=c,h=new D.B(f.x+f.e/2-b*(3/7),f.y+c/2-b*(2.5/7),b*(6/7),b*(2.5/7)*(1+(2*f.g/c-1))),f.g=c,r=c/2):3==j&&f.g>f.e?(c=window.Math.min(2*(f.e/(window.Math.cos(c-window.Math.PI)+1)),2*(f.e/(window.Math.sin(e-D.eh.HD)+1)),f.g),b*=c,h=b*(3/7)*(2*f.e/c-1),g?(h=new D.B(f.x+c/2-b*(3/7),f.y+f.g/2-b*(2.5/7),b*(3/7)*(1+(2*f.e/c-1)),b*(5/7)),q=c/2):(h=new D.B(f.x+
f.e-c/2-h,f.y+f.g/2-b*(2.5/7),b*(3/7)+h,b*(5/7)),f.x-=c-f.e,q=-c/2+m),f.e=c):4==j&&f.g<f.e&&(c=window.Math.min(2*(f.g/(window.Math.cos(c-1.5*window.Math.PI)+1)),2*(f.g/(window.Math.sin(D.eh.eN-e)+1)),f.e),b*=c,h=b*(2.5/7)*(2*f.g/c-1),h=new D.B(f.x+f.e/2-b*(3/7),f.y+f.g-c/2-h,b*(6/7),b*(2.5/7)+h),f.y-=c-f.g,f.g=c,r=-c/2+n));a.Vo=q;a.Wo=r;return h};
D.NJ=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};D.y.q(D.NJ,D.D,"DvtStatusMeterGaugeIndicator");D.NJ.prototype.Init=function(a,b,c,d,e,f){D.NJ.u.Init.call(this,b);this.Mf=a;this.sBa="vertical"==a.A().orientation;this.mD(c,d,e,f)};D.NJ.prototype.mD=function(a,b,c,d){this.Of=a;this.wf=b;this.Gz=c;this.Hz=d;var e=window.Math.min(a,b),f=window.Math.min(c,d);a=window.Math.abs(a-b);c=window.Math.abs(d-c);(0,D.ZH)(this,e,f,a,c);e=(this.sBa?a:c)*((0,D.rJ)(this.Mf)?0.25:0.15);2.5<=e&&(0,D.Fr)(this,e,e)};
D.NJ.prototype.oe=function(){return[this.Of,this.wf,this.Gz,this.Hz]};D.NJ.prototype.Md=function(a){a&&4==a.length&&this.mD(a[0],a[1],a[2],a[3])};
D.JJ=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};D.y.q(D.JJ,D.Ei,"DvtStatusMeterGaugeCircularIndicator");D.JJ.prototype.Init=function(a,b,c,d,e,f){D.JJ.u.Init.call(this,a);(0,D.KJ)(this,b,c,d,e,f)};D.KJ=function(a,b,c,d,e,f){b&&b instanceof D.B?a.Ka=b:b=a.Ka;a.Id=c;a.Xd=d;a.Xj=e;a.bj=f;a.Hj(D.IJ.Goa(b,c,d,e,f))};D.JJ.prototype.oe=function(){return[this.Ka,this.Id,this.Xd,this.Xj,this.bj]};D.JJ.prototype.Md=function(a){a&&5==a.length&&(0,D.KJ)(this,a[0],a[1],a[2],a[3],a[4])};
D.aJ=(0,D.s)();(0,D.ca)("DvtDialGauge",D.aJ);D.y.q(D.aJ,D.bJ,"DvtDialGauge");D.aJ.newInstance=function(a,b,c){var d=new D.aJ;d.Init(a,b,c);return d};D.x=D.aJ.prototype;D.x.Init=function(a,b,c){D.aJ.u.Init.call(this,a,b,c);this.If=new D.cJ;this.L2=D.o};D.x.Od=function(a){var b=a.background,c=a.indicator;"string"===typeof b&&(a.background=D.dJ.eHa(b),a.background.images=a._backgroundImages);"string"===typeof c&&(a.indicator=D.dJ.fHa(c),a.indicator.images=a._indicatorImages);D.aJ.u.Od.call(this,this.If.ej(a))};
D.x.sj=function(a,b,c){D.eJ.U(this,a,b,c)};D.x.fsa=function(){D.eJ.cMa(this,this.da,this.fb,this.tb);(0,D.fJ)(this,this.da)};D.x.m0=function(a,b,c){b=[];for(var d=0;d<a.length;d++){var e=a[d],f=e.oe(),g=D.eJ.oxa(this);e.mi(g);g=new D.yo(this.j(),e,c);(0,D.S)(g.P,"typeNumberArray",e,e.oe,e.Md,f);g.P.Dl(function(a){return(0,D.xD)(a,0.7)});b.push(g)}return new D.wo(this.j(),b)};
D.x.FA=function(a,b){var c=D.eh.TL(window.Math.atan2(b-this.L2.y,a-this.L2.x));0>=c&&(c+=360);var d=(0,D.F)(this.j()),e=this.A().background,f=d?180+e.startAngle:360-e.startAngle,e=e.angleExtent,g=f+e;if(d){g=f;for(f-=e;0>f;)f+=360,g+=360}c+360>=f&&c+360<=g?c+=360:c>=f&&c<=g||(c=c>g?f+360-c<c-g?f:g:f-c<c+360-g?f:g);c=(c-f)/e;d&&(c=1-c);d=this.G.min;return c*(this.G.max-d)+d};
D.cJ=function(){this.Init({skyros:D.gJ,alta:{}})};D.y.q(D.cJ,D.hJ,"DvtDialGaugeDefaults");D.gJ={background:{startAngle:180,angleExtent:180,indicatorLength:0.7},metricLabel:{style:new D.I("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},tickLabel:{scaling:"auto",style:new D.I("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};
D.eJ={};D.y.q(D.eJ,D.y,"DvtDialGaugeRenderer");D.eJ.U=function(a,b,c,d){D.jJ.vx(a)?(c=new D.B(0,0,c,d),D.eJ.UP(a,b,c),D.eJ.dq(a,b,c)):D.kJ.sn(a,b,new D.B(0,0,c,d))};D.eJ.cMa=function(a,b,c,d){a.pxa.mi(D.eJ.C5(a,a.A().value));b.removeChild(a.qxa);D.eJ.dq(a,b,new D.B(0,0,c,d))};
D.eJ.UP=function(a,b,c){var d=a.A(),e=D.eJ.bza(a,c);b.k(e);d.background.majorTickCount&&d.background.radius&&D.eJ.MDa(a,b,c);var f=D.eJ.fza(a,c),g=new D.C(a.j()),h=new D.iJ(a.j());b.k(g);g.k(h);h.k(f);var j=f.I(),l=D.eJ.C5(a,d.value),e=D.eJ.$ia(a,c),m=D.eJ.kAa(a,j);c=D.eJ.lAa(a,c,j);j=new D.vk;j.translate(-m.x,-m.y);j.scale(c,c);f.Ga(j);h.mi(l);j=new D.vk;j.translate(e.x,e.y);g.Ga(j);a.hy.push(h);a.pxa=h;((d=d.shortDesc)||a.A().readOnly===D.p)&&a.Aa().Ba(b,new D.Ok(D.o,d));a.L2=e};
D.eJ.bza=function(a,b){var c=a.A().background,d=(0,D.F)(a.j()),e=(0,D.Ze)(),f=e?2*b.e:b.e,g=e?2*b.g:b.g,h=c.images;if(h&&0<h.length){var j,l,m,e=[];for(j=0;j<h.length;j++){var n="rtl"==h[j].dir;d&&n?e.push(h[j]):!d&&!n&&e.push(h[j])}h=0<e.length?e:h;for(j=0;j<h.length;j++){var q=h[j],n=q.src,e=q.width,q=q.height,r=n&&-1<n.search(".svg");0==j&&(l=e,m=q);if(r||e>=f&&q>=g||j==h.length-1){var f=new D.sf(a.j(),n,0,0,e,q),t=new D.vk,g=window.Math.min(b.e/e,b.g/q),h=(b.e-g*e)/2;j=(b.g-g*q)/2;t.scale(g,g);
t.translate(h,j);f.Ga(t);r&&(0,D.wk)()&&(n=D.Oe.jo(a.j(),n,D.y.Yf(f,f.Q2)))&&f.Q2(n);b.x+=h;b.y+=j;b.e=g*e;b.g=g*q;!(0,window.isNaN)(c.anchorX)&&!(0,window.isNaN)(c.anchorY)&&(c._anchorX=d?b.x+b.e-b.e*c.anchorX/l:b.x+b.e*c.anchorX/l,c._anchorY=b.y+b.g*c.anchorY/m);c.metricLabelBounds&&(e={},e.width=b.e*c.metricLabelBounds.width/l,e.height=b.g*c.metricLabelBounds.height/m,e.y=b.y+b.g*c.metricLabelBounds.y/m,e.x=d?b.x+b.e-b.e*c.metricLabelBounds.x/l-e.width:b.x+b.e*c.metricLabelBounds.x/l,c._metricLabelBounds=
e);d=window.Math.min(b.e/l,b.g/m);c._radius=c.radius*d;c._tickLabelHeight=c.tickLabelHeight*b.g/m;c._tickLabelWidth=c.tickLabelWidth*b.e/l;return f}}}return D.o};
D.eJ.fza=function(a,b){var c=a.A().indicator,d=D.eJ.hja(a,b),e=(0,D.Ze)()?2*d:d,f,g,h=c.images;if(h&&0<h.length)for(var j=0;j<h.length;j++){var l=h[j],d=l.src,m=l.width,l=l.height,n=d&&-1<d.search(".svg");0==j&&(f=m,g=l);if(n||l>=e||j==h.length-1)return e=new D.sf(a.j(),d,0,0,m,l),n&&(0,D.wk)()&&D.Oe.jo(a.j(),d,D.y.Yf(e,e.Q2))&&(e.sa(m),e.Ia(l)),!(0,window.isNaN)(c.anchorX)&&!(0,window.isNaN)(c.anchorY)&&(c._anchorX=c.anchorX*m/f,c._anchorY=c.anchorY*l/g),e}return D.o};
D.eJ.oxa=function(a){var b=a.A().background;a=(0,D.F)(a.j())?180-b.startAngle:b.startAngle;return window.Math.PI*(90-a)/180};D.eJ.C5=function(a,b){var c=a.A(),d=c.background,e=c.min,c=c.max;b=window.Math.max(window.Math.min(b,c),e);e=(b-e)/(c-e);c=(0,D.F)(a.j());return window.Math.PI*(90-((c?180-d.startAngle:d.startAngle)-e*(c?-d.angleExtent:d.angleExtent)))/180};
D.eJ.$ia=function(a,b){var c=a.A().background,d=c._anchorX,c=c._anchorY;return!(0,window.isNaN)(d)&&!(0,window.isNaN)(c)?new D.H(d,c):new D.H(b.x+b.e/2,b.y+b.g/2)};D.eJ.hja=function(a,b){var c=window.Math.min(b.e,b.g)/2;return a.A().background.indicatorLength*c};D.eJ.kAa=function(a,b){var c=a.A().indicator,d=c._anchorX,c=c._anchorY;return!(0,window.isNaN)(d)&&!(0,window.isNaN)(c)?new D.H(d,c):new D.H(b.x+b.e/2,b.y+b.g)};D.eJ.lAa=function(a,b,c){return D.eJ.hja(a,b)/c.g};
D.eJ.dq=function(a,b,c){var d=a.A();if("on"==d.metricLabel.rendered){var e=D.kJ.gn(d.value,a),f=D.kJ.gn(d.min,a),g=D.kJ.gn(d.max,a),h=c.x+c.e/2,j=c.y+c.g/2,l=c.e,m=c.g,n=d.background._metricLabelBounds;n&&(h=n.x+n.width/2,j=n.y+n.height/2,c.e=n.width,c.g=n.height);h=new D.lg(a.j(),e,h,j);!d.metricLabel.style.D("color")&&d.background._isDark&&d.metricLabel.style.ca("color","#CCCCCC");h.Na(d.metricLabel.style);d=(d=(0,window.parseInt)(d.metricLabel.style.yG()))?(0,window.parseInt)(d):D.o;d||(d=D.kJ.KY([e,
f,g],h,c),h.Te(e),h.qf(d));h.Ff();h.Xf();D.yf.wc(h,l,m,b)&&(a.qxa=h,h.Pk()&&a.Aa().Ba(h,new D.Ok(e)))}};
D.eJ.MDa=function(a,b,c){var d=a.A(),e=(0,D.F)(a.j());if(d.background.radius&&d.background.majorTickCount){var f=d.background._radius,g=d.min,h=d.max,j=d.background.majorTickCount,l=12,m=new D.B(u,r,c.e,c.g),n=d.metricLabel.style.D("font-size");d.background._tickLabelHeight&&!n&&(m.g=d.background._tickLabelHeight);d.background._tickLabelWidth&&!n&&(m.e=d.background._tickLabelWidth);if(!n)var q=new D.lg(a.j(),"",u,r),l=D.kJ.KY([D.kJ.j$(d.max,a),D.kJ.j$(d.min,a)],q,m);for(n=0;n<j;n++){u=g+window.Math.abs(h-
g)*n/(j-1);e&&(u=g+window.Math.abs(h-g)*(j-1-n)/(j-1));var q=D.kJ.j$(u,a),r=D.eJ.C5(a,u),t=D.eJ.$ia(a,c),u=t.x+f*window.Math.cos(r-window.Math.PI/2),r=t.y+f*window.Math.sin(r-window.Math.PI/2),q=new D.lg(a.j(),q,u,r);!d.tickLabel.style.D("color")&&d.background._isDark&&d.tickLabel.style.ca("color","#CCCCCC");q.Na(d.tickLabel.style);d.tickLabel.style.D("font-size")||q.qf(l);q.Ff();q.Xf();D.yf.wc(q,m.e+0.5,m.g+0.5,b)&&q.Pk()&&a.Aa().Ba(q,new D.Ok(q.io()))}}};
D.iJ=function(a){this.Init(a)};D.y.q(D.iJ,D.C,"DvtDialGaugeIndicator");D.iJ.prototype.mi=function(a){var b=new D.vk;b.rotate(a);this.Ga(b);this.Oxa=a};D.iJ.prototype.oe=function(){return[this.Oxa]};D.iJ.prototype.Md=function(a){a&&1==a.length&&this.mi(a[0])};
D.zJ=(0,D.s)();(0,D.ca)("DvtRatingGauge",D.zJ);D.y.q(D.zJ,D.bJ,"DvtRatingGauge");D.zJ.newInstance=function(a,b,c){var d=new D.zJ;d.Init(a,b,c);return d};D.x=D.zJ.prototype;D.x.Init=function(a,b,c){D.zJ.u.Init.call(this,a,b,c);this.If=new D.AJ};D.x.Od=function(a){D.zJ.u.Od.call(this,this.If.ej(a))};
D.x.sj=function(a,b,c){var d=this.A().__layout.outerGap,e=this.G.max,f="vertical"==this.G.orientation;this.Wf=f?window.Math.min(b-2*d,(c-2*d)/e):window.Math.min(c-2*d,(b-2*d)/e);this.Ka=f?new D.B(d,(this.tb-this.Wf*e)/2,this.fb-2*d,this.Wf*e):new D.B((this.fb-this.Wf*e)/2,d,this.Wf*e,this.tb-2*d);D.BJ.U(this,a,b,c)};D.x.za=function(){return new D.CJ(this)};
D.x.FA=function(a,b){if(D.jJ.vx(this)){if("vertical"==this.G.orientation)b=window.Math.max(window.Math.min(b,this.Ka.y+this.Ka.g),this.Ka.y),c=window.Math.max((this.Ka.y+this.Ka.g-b)/this.Wf,this.G.min);else{a=window.Math.max(window.Math.min(a,this.Ka.x+this.Ka.e),this.Ka.x);var c=0,c=(0,D.F)(this.j())?window.Math.max((this.Ka.x+this.Ka.e-a)/this.Wf,this.G.min):window.Math.max((a-this.Ka.x)/this.Wf,this.G.min)}return D.kJ.FY(this.G,c)}return D.o};D.x.kU=function(a,b){this.hI(a,b)};
D.x.hI=function(a,b){var c=this.FA(a,b);(0,D.DJ)(this,c,"hover");this.Wa(new D.QC(this.G.value,c,D.p))};D.x.O2=function(a,b){var c=this.G.value;this.G.value=this.FA(a,b);this.G.changed=D.k;this.U();this.Wa(new D.QC(c,this.G.value,D.p));this.Wa(new D.QC(c,this.G.value,D.k))};
D.DJ=function(a,b,c,d){if(D.jJ.vx(a)){d||(d=a.da);var e=(0,D.F)(a.j()),f="vertical"==a.G.orientation;b=window.Math.max(window.Math.min(b,a.G.max),0);var g=0,h=b*a.Wf,j=b*a.Wf;"render"==c&&(g=b*a.Wf,h=0);f?(c=d.na(0),e=new D.ih("unsel"+a.getId()),(0,D.kh)(e,a.Ka.x,a.Ka.y,a.Ka.e,a.Ka.g-j),(0,D.lh)(c,e),c=d.na(1),e=new D.ih("sel"+a.getId()),(0,D.kh)(e,a.Ka.x,a.Ka.y+a.Ka.g-g,a.Ka.e,g),(0,D.lh)(c,e),g=d.na(2),c=new D.ih("hover"+a.getId()),(0,D.kh)(c,a.Ka.x,a.Ka.y+a.Ka.g-h,a.Ka.e,h)):e?(c=d.na(0),e=new D.ih("unsel"+
a.getId()),(0,D.kh)(e,a.Ka.x,a.Ka.y,a.Ka.e-j,a.Ka.g),(0,D.lh)(c,e),c=d.na(1),e=new D.ih("sel"+a.getId()),(0,D.kh)(e,a.Ka.x+a.Ka.e-j,a.Ka.y,g,a.Ka.g),(0,D.lh)(c,e),g=d.na(2),c=new D.ih("hover"+a.getId()),(0,D.kh)(c,a.Ka.x+a.Ka.e-j,a.Ka.y,h,a.Ka.g)):(c=d.na(0),e=new D.ih("unsel"+a.getId()),(0,D.kh)(e,a.Ka.x+j,a.Ka.y,a.Ka.e-j,a.Ka.g),(0,D.lh)(c,e),c=d.na(1),e=new D.ih("sel"+a.getId()),(0,D.kh)(e,a.Ka.x,a.Ka.y,g,a.Ka.g),(0,D.lh)(c,e),g=d.na(2),c=new D.ih("hover"+a.getId()),(0,D.kh)(c,a.Ka.x,a.Ka.y,h,
a.Ka.g));(0,D.lh)(g,c);(0,D.fJ)(a,d,b)}};D.zJ.prototype.CH=function(){return new D.EJ(this)};
D.AJ=function(){this.Init({skyros:D.FJ,alta:D.GJ})};D.y.q(D.AJ,D.hJ,"DvtRatingGaugeDefaults");D.GJ={unselectedState:{shape:"star",color:"#C4CED7",borderColor:D.o},selectedState:{shape:"star",color:"#F8C15A",borderColor:D.o},hoverState:{shape:"star",color:"#007CC8",borderColor:D.o},changedState:{shape:"star",color:"#ED2C02",borderColor:D.o}};
D.FJ={min:0,max:5,orientation:"horizontal",unselectedState:{shape:"star",color:"#F2F2F2",borderColor:"#B6B6B6"},selectedState:{shape:"star",color:"#F8C15A",borderColor:"#F5A700"},hoverState:{shape:"star",color:"#66A7DA",borderColor:"#4A86C5"},changedState:{shape:"star",color:"#F8C15A",borderColor:"#959595"},step:1};
D.CJ=function(a){this.Init();this.Mf=a};D.y.q(D.CJ,D.Ok,"DvtRatingGaugePeer");D.CJ.prototype.Pe=function(a,b,c){a=this.Mf.A();b=this.Mf.Aa().qn?D.jJ.OG(this.Mf,this.Mf.FA(b,c)):D.jJ.OG(this.Mf);return(b=D.jJ.AL(this.Mf,b))&&b.shortDesc?b.shortDesc:a.shortDesc};
D.BJ={};D.y.q(D.BJ,D.y,"DvtRatingGaugeRenderer");D.BJ.hU="circle diamond rectangle star triangle human".split(" ");
D.BJ.U=function(a,b,c,d){if(D.jJ.vx(a)){var e=a.A(),f=(0,D.F)(a.j()),g="vertical"==e.orientation,h=e.__layout.outerGap,j=e.max,l=g?window.Math.min(c-2*h,(d-2*h)/j):window.Math.min(d-2*h,(c-2*h)/j);c=g?new D.B(h,(d-l*j)/2,c-2*h,l*j):new D.B((c-l*j)/2,h,l*j,d-2*h);d=D.jJ.OG(a);d=D.jJ.AL(a,d);var m=e.selectedState.color,n=e.changedState.color,q=e.selectedState.borderColor,r=e.changedState.borderColor;d&&d.color&&(n=m=d.color);d&&d.borderColor&&(r=q=d.borderColor);h={value:0,type:e.unselectedState.shape,
color:e.unselectedState.color,borderColor:e.unselectedState.borderColor,visualEffects:e.visualEffects};m={value:0,type:e.selectedState.shape,color:m,borderColor:q,visualEffects:e.visualEffects};n={value:0,type:e.changedState.shape,color:n,borderColor:r,visualEffects:e.visualEffects};r={value:0,type:e.hoverState.shape,color:e.hoverState.color,borderColor:e.hoverState.borderColor,visualEffects:e.visualEffects};"dot"==e.unselectedState.shape&&(h.type="circle",h.visualEffects="none",h.size=0.05);q=new D.C(a.j());
b.k(q);var t=new D.C(a.j());b.k(t);var u=new D.C(a.j());b.k(u);(0,D.DJ)(a,e.value,"render",b);for(var A=0;A<j;A++){if("none"!=e.unselectedState.shape){var z=(0,D.vJ)(a.j(),D.o,D.o,D.k);q.k(z);g?(0,D.N)(z,c.x+c.e/2-l/2,c.y+c.g-(A+1)*l):f?(0,D.N)(z,c.x+c.e-(A+1)*l,c.y+c.g/2-l/2):(0,D.N)(z,c.x+A*l,c.y+c.g/2-l/2);-1==D.Ag.Ra(D.BJ.hU,h.type)&&(h.type="star");z.U(h,l,l)}e.changed?(z=(0,D.vJ)(a.j(),D.o,D.o,D.k),t.k(z),g?(0,D.N)(z,c.x+c.e/2-l/2,c.y+c.g-(A+1)*l):f?(0,D.N)(z,c.x+c.e-(A+1)*l,c.y+c.g/2-l/2):
(0,D.N)(z,c.x+A*l,c.y+c.g/2-l/2),-1==D.Ag.Ra(D.BJ.hU,n.type)&&(n.type="star"),z.U(n,l,l)):(z=(0,D.vJ)(a.j(),D.o,D.o,D.k),t.k(z),g?(0,D.N)(z,c.x+c.e/2-l/2,c.y+c.g-(A+1)*l):f?(0,D.N)(z,c.x+c.e-(A+1)*l,c.y+c.g/2-l/2):(0,D.N)(z,c.x+A*l,c.y+c.g/2-l/2),-1==D.Ag.Ra(D.BJ.hU,m.type)&&(m.type="star"),z.U(m,l,l));z=(0,D.vJ)(a.j(),D.o,D.o,D.k);u.k(z);g?(0,D.N)(z,c.x+c.e/2-l/2,c.y+c.g-(A+1)*l):f?(0,D.N)(z,c.x+c.e-(A+1)*l,c.y+c.g/2-l/2):(0,D.N)(z,c.x+A*l,c.y+c.g/2-l/2);-1==D.Ag.Ra(D.BJ.hU,r.type)&&(r.type="star");
z.U(r,l,l)}f=new D.D(a.j(),c.x,c.y,c.e,c.g);(0,D.Aj)(f);b.k(f);(d&&d.shortDesc?d.shortDesc:e.shortDesc)&&a.Aa().Ba(f,new D.CJ(a))}else D.kJ.sn(a,b,new D.B(0,0,c,d))};
D.EJ=function(a){this.Init(a.j(),a.Wa,a);this.Mf=a};D.y.q(D.EJ,D.mJ,"DvtRatingGaugeEventManager");D.x=D.EJ.prototype;D.x.Ut=function(a){if(this.Mf.A().readOnly===D.p){var b=(0,D.sJ)(this,a.pageX,a.pageY);this.Mf.kU(b.x,b.y);this.qn=D.k}D.EJ.u.Ut.call(this,a)};D.x.Xk=function(a){if(this.Mf.A().readOnly===D.p){(0,D.sJ)(this,a.pageX,a.pageY);var b=this.Mf;(0,D.DJ)(b,b.G.value,"render");b.Wa(new D.QC(b.G.value,b.G.value,D.p))}D.EJ.u.Xk.call(this,a)};
D.x.ks=function(a){var b=(0,D.sJ)(this,a.pageX,a.pageY);this.Mf.A().readOnly===D.p&&(!this.qn&&this.Mf.A().value!=this.Mf.FA(b.x,b.y))&&(this.qn=D.k);D.EJ.u.ks.call(this,a)};D.x.Ll=function(a){D.mJ.u.Ll.call(this,a)};D.x.q1=(0,D.ba)(D.k);
  return D;
});