/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.YN=(0,D.s)();(0,D.ca)("DvtLegend",D.YN);D.y.q(D.YN,D.Fk,"DvtLegend");D.Ko=function(a,b,c){var d=new D.YN;d.Init(a,b,c);return d};D.YN.newInstance=D.Ko;D.YN.getDefaults=function(a){return(0,D.Gk)(new D.ZN,a)};D.YN.prototype.Init=function(a,b,c){D.YN.u.Init.call(this,a,b,c);this.setId("legend1000"+window.Math.floor(1E9*window.Math.random()));this.If=new D.ZN;this.xa=new D.$N(this);this.xa.Ne(this);this.cq=[];this.sF=[];this.Ka=D.o;this.m9=[]};
D.YN.prototype.Od=function(a){a?(this.G=this.If.ej(a),(0,D.aO)(this,this.G.sections)):this.G||(this.G=(0,D.Kk)(this))};D.YN.prototype.uq=function(a,b,c){this.Od(a);this.A().isLayout=D.k;a=D.bO.U(this,new D.B(0,0,b,c));this.A().isLayout=D.p;return new D.Ah(a.e,a.g)};D.YN.prototype.getPreferredSize=D.YN.prototype.uq;
D.YN.prototype.U=function(a,b,c){this.Od(a);!(0,window.isNaN)(b)&&!(0,window.isNaN)(c)&&(this.fb=b,this.tb=c);this.A().isLayout=D.p;this.Sk();this.cq=[];this.sF=[];this.Ka=D.o;this.m9=[];(0,D.Ze)()||(0,D.Yl)(this.xa,new D.cO(this.xa,this));this.wo();this.m4=D.bO.U(this,new D.B(0,0,this.fb,this.tb));(a=this.A().highlightedCategories)&&0<a.length&&this.pf(a);return this.m4};D.YN.prototype.render=D.YN.prototype.U;
D.YN.prototype.pf=function(a){this.A().highlightedCategories=a&&0<a.length?a.slice():D.o;(0,D.wm)(a,this.cq,D.k)};D.YN.prototype.highlight=D.YN.prototype.pf;D.YN.prototype.ze=function(a,b){var c=a.$a();if(("categoryRollOver"==c||"categoryRollOut"==c)&&"dim"==this.A().hoverBehavior){var d=this.cq;this!=b&&this.pf(a.categories);for(var e=0;e<d.length;e++)if(d[e].getId()==a.al){this.yFa.scrollIntoView(d[e].Qd()[0]);break}}(this==b||"showPopup"==c||"hidePopup"==c)&&this.Wa(a)};D.YN.prototype.Aa=(0,D.w)("xa");
D.YN.prototype.aa=function(){this.xa&&(this.xa.qm(this),this.xa.aa(),this.xa=D.o);D.YN.u.aa.call(this)};D.YN.prototype.destroy=D.YN.prototype.aa;D.YN.prototype.P2=(0,D.v)("Ka");D.YN.prototype.Zf=function(){return new D.dO(this)};D.YN.prototype.getAutomation=D.YN.prototype.Zf;D.YN.prototype.gR=function(){return this.xa.Jd()};
D.um=function(a,b,c){for(var d=a.sF,e=0;e<d.length;e++)if(d[e].getId()==b.getId()){(0,D.sm)(a.xa,d[e]);c&&d[e].ke();break}if(b=a.gR())c=b.Qd()[0],c.Wb("label",b.mc()),(0,D.yh)(a.j(),c)};D.YN.prototype.I=function(a){var b=new D.B(0,0,this.fb,this.tb);return!a||a===this?b:(0,D.Fh)(this,b,a)};D.YN.prototype.jv=function(a){return!a||a===this?this.m4:(0,D.Fh)(this,this.m4,a)};D.YN.prototype.Lj=function(){return(0,D.M)("DvtUtilBundle","LEGEND")};
D.aO=function(a,b){if(b&&!(0>=b.length))for(var c=a.A().hiddenCategories,d=0;d<b.length;d++){var e=b[d];e.sections&&(c=(0,D.aO)(a,e.sections));if((e=e.items)&&!(0>=e.length))for(var f=0;f<e.length;f++){var g=e[f],h=D.bO.mZ(g);"hidden"==g.categoryVisibility&&0>D.Ag.Ra(c,h)&&c.push(h);g.categoryVisibility=D.o}}};
D.YN.prototype.wo=function(){if((0,D.XD)(this)){var a=this.A(),b=a.hideAndShowBehavior;if("off"!=b&&"none"!=b||"dim"==a.hoverBehavior)this.j().xd("application"),(0,D.YD)(this.j(),(0,D.M)("DvtUtilBundle","COLON_SEP_LIST",[(0,D.M)("DvtUtilBundle","DATA_VISUALIZATION"),D.Yg.nA(this.Lj())]))}};D.YN.prototype.TG=function(){return 0<this.sF.length};
D.Tm={};(0,D.ca)("DvtLegendConstants",D.Tm);D.y.q(D.Tm,D.y,"DvtLegendConstants");D.Tm.yH="background";D.Tm.BACKGROUND=D.Tm.yH;D.Tm.OH="legendItem";D.Tm.LEGEND_ITEM=D.Tm.OH;D.Tm.Vq="title";D.Tm.TITLE=D.Tm.Vq;
D.dO=function(a){this.Hb=a;this.Ae=this.Hb.A()};(0,D.ca)("DvtLegendAutomation",D.dO);D.y.q(D.dO,D.Nk,"DvtLegendAutomation");D.dO.prototype.Jl=function(a){if((a=this.Hb.Aa().za(a))&&a instanceof D.eO)if(a=a.getData(),a=(0,D.fO)(this,a,this.Ae))return"section"+a;return D.o};
D.fO=function(a,b,c){if(c.sections&&0<c.sections.length){for(var d=0;d<c.sections.length;d++){if(c.sections[d]==b)return"["+d+"]";var e=(0,D.fO)(a,b,c.sections[d]);if(e)return"["+d+"]"+e}return D.o}if(c.items&&0<c.items.length){for(a=0;a<c.items.length;a++)if(c.items[a]==b)return":item["+a+"]";return D.o}};
D.jn=function(a,b,c){if(c.sections&&0<c.sections.length){for(var d=0;d<c.sections.length;d++){var e=(0,D.jn)(a,b,c.sections[d]);if(e)return"["+d+"]"+e}return D.o}if(c.items&&0<c.items.length){for(a=0;a<c.items.length;a++)if(c.items[a].text==b.name)return":item["+a+"]";return D.o}};
D.dn=function(a,b,c){var d=c.indexOf("["),e=c.indexOf("]");if(0<=d&&0<=e){var d=c.substring(d+1,e),f=c.indexOf(":");c=c.substring(e+1);e=c.indexOf("]");return 0<=c.indexOf("[")&&0<=e?(0,D.dn)(a,b.sections[d],c):0==f?b.items[d]:b.sections[d]}};D.dO.prototype.Cg=function(a){a=(0,D.dn)(this,this.Ae,a);for(var b=this.Hb.cq,c=0;c<b.length;c++){var d=b[c].getData();if(a==d)return b[c].Qd()[0].Fa()}return D.o};D.dO.prototype.getDomElementForSubId=D.dO.prototype.Cg;D.dO.prototype.rv=function(){return this.Ae.title};
D.dO.prototype.getTitle=D.dO.prototype.rv;D.dO.prototype.getItem=function(a){for(var b,c=a.shift(),d=this.Ae;c!=D.i;)0<a.length?d=d.sections[c]:b=d.items[c],c=a.shift();return{text:b.text?b.text:D.o}};D.dO.prototype.getItem=D.dO.prototype.getItem;D.dO.prototype.oIa=function(a){for(var b,c=a.shift(),d=this.Ae;c!=D.i;)0<a.length?d=d.sections[c]:b=d.sections[c],c=a.shift();return{title:b.title?b.title:D.o,items:b.items?(0,D.gO)(b.items):D.o,sections:b.sections?(0,D.hO)(this,b.sections):D.o}};
D.dO.prototype.getSection=D.dO.prototype.oIa;D.gO=function(a){for(var b=[],c=0;c<a.length;c++)b.push({text:a[c].text});return b};D.hO=function(a,b){for(var c=[],d=0;d<b.length;d++)c.push({title:b[d].title?b[d].title:D.o,items:b[d].items?(0,D.gO)(b[d].items):D.o,sections:b[d].sections?(0,D.hO)(a,b[d].sections):D.o});return c};
D.ZN=function(){this.Init({skyros:D.iO,alta:D.jO,next:D.kO})};D.y.q(D.ZN,D.Vk,"DvtLegendDefaults");D.kO={skin:"next",titleStyle:new D.I("color: #737373;"),_sectionTitleStyle:new D.I("color: #737373;"),layout:{titleGapWidth:17,titleGapHeight:9,symbolGapWidth:7,symbolGapHeight:4,rowGap:4,columnGap:10,sectionGapHeight:16,sectionGapWidth:24}};
D.jO={skin:"alta",colors:D.pn,textStyle:new D.I("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"),titleStyle:new D.I("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333333;"),_sectionTitleStyle:new D.I("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333333;")};
D.iO={skin:"skyros",orientation:"vertical",position:D.o,backgroundColor:D.o,borderColor:D.o,textStyle:new D.I("font-family: tahoma, sans-serif; font-size: 11px; color: #333333;"),titleStyle:new D.I("font-family: tahoma, sans-serif; font-size: 12px; color: #003d5b;"),titleHalign:"start",hiddenCategories:[],hideAndShowBehavior:"off",hoverBehavior:"none",hoverBehaviorDelay:200,scrolling:"asNeeded",halign:"start",valign:"top",drilling:"off",colors:D.qn,markerShape:"square",lineWidth:3,layout:{outerGapWidth:3,
outerGapHeight:3,titleGapWidth:8,titleGapHeight:3,symbolGapWidth:5,symbolGapHeight:4,rowGap:0,columnGap:8,sectionGapHeight:6,sectionGapWidth:15},isLayout:D.p};D.lO=function(a,b){var c=window.Math.min(D.yf.zL(a.j(),a.A().textStyle)/14,1);return window.Math.ceil(b*c)};
D.$N=function(a){this.Init(a.j(),a.ze,a);this.Hb=a};D.y.q(D.$N,D.Xk,"DvtLegendEventManager");D.x=D.$N.prototype;D.x.Yv=function(a,b){var c=D.o;b instanceof D.Ok&&b.jn()!=D.o?c=b.jn():b instanceof D.eO&&(c=b.getId(),c={type:D.Tm.OH,id:c});this.gh(new D.al(a,c),this.Hb)};D.x.Wg=function(a){D.$N.u.Wg.call(this,a);var b=this.za(a.target);if(b){var c=(0,D.mO)(this,b),b=this.bn(b);(c||b)&&a.stopPropagation()}};D.x.Ut=function(a){D.$N.u.Ut.call(this,a);(a=this.za(a.target))&&this.fw(a)};
D.x.Xk=function(a){D.$N.u.Xk.call(this,a);this.za(a.target)};D.x.Rt=function(a){var b=this.za(a.target);if(b){a=a.cca;var c=(0,D.mO)(this,b),b=this.bn(b);(c||b)&&a&&a.preventDefault()}};
D.mO=function(a,b){var c=a.Hb.A().hideAndShowBehavior;if("none"==c||"off"==c)return D.p;var d=b.Xc?b.Xc():D.o;if(!d||0>=d.length)return D.p;for(var e=b.Xc()[0],c=a.Hb.A().hiddenCategories||[],c=c.slice(),f=b.Qd(),g=0;g<f.length;g++){var h=f[g];h instanceof D.po?h.mH(b.Ib()):h instanceof D.D&&(0,D.nO)(b)}d=d[0];D.bO.XZ(e,a.Hb)?(c.splice(c.indexOf(e),1),e=new D.Cm(D.Cm.YD,d)):(c.push(e),e=new D.Cm(D.Cm.SA,d));e.hiddenCategories=c;a.Hb.A().hiddenCategories=c;a.gh(e,a.Hb);return D.k};
D.$N.prototype.bn=function(a){return a&&a.Oe&&a.Oe()?(this.gh(new D.bl("action",a.Oe(),a.getId()),this.Hb),D.k):a instanceof D.eO&&a.jm()?(a=a.getData().text,this.gh(new D.dl(a,a,D.o),this.Hb),D.k):D.p};
D.$N.prototype.Gp=function(a,b,c){var d=this.Hb.A();"none"==d.hoverBehavior||b.Qd&&b.Qd()[0]instanceof D.ef||(b=b.Xc?b.Xc():[],d.highlightedCategories=c?b.slice():D.o,c=new D.Kn(c?"categoryRollOver":"categoryRollOut",d.highlightedCategories),d=(0,D.jq)(d.hoverBehaviorDelay),this.PA.ze(c,this.Hb.cq,d,D.k),a.stopPropagation())};
D.$N.prototype.fba=function(a,b){for(var c=b.getId(),d=this.Hb.A(),e=0;e<c.length;e++)d=d.sections[c[e]];d.expanded="off"==d.expanded?"on":"off";a.type==D.$e&&(c=this.za((0,D.Bn)(a)),(0,D.sm)(this,c.Td(a)));d=(c=this.Hb.gR())?c.Nc():D.p;this.Hb.U();c&&(0,D.um)(this.Hb,c,d);this.Vc();c=this.Hb.jv();this.gh(new D.oC(c.e,c.g,c.x,c.y),this.Hb)};
D.cO=function(a,b){this.Init(a,b)};D.y.q(D.cO,D.On,"DvtLegendKeyboardHandler");D.cO.prototype.Init=function(a,b){D.cO.u.Init.call(this,a);this.Hb=b};
D.cO.prototype.Gj=function(a){var b=a.keyCode,c=this.xa.Jd(),d=this.Hb.Aa(),e=c&&c.Qd()[0]instanceof D.ef;if(9==b){if(c)return(0,D.ji)(a),c;b=this.Hb.sF;if(0<b.length)return(0,D.ji)(a),this.gL(b)}else if(13==b||32==b)c&&(e?d.fba(a,c.Qd()[0]):(0,D.mO)(d,c),(0,D.ji)(a));else if(e&&(37==b||39==b))d.fba(a,c.Qd()[0]),(0,D.ji)(a);else return D.cO.u.Gj.call(this,a)};
D.eO=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};D.y.q(D.eO,D.y,"DvtLegendObjPeer");D.eO.prototype.Init=function(a,b,c,d,e,f){this.Hb=a;this.me=b;this.HW=c;this.jb=(this.al=D.bO.mZ(this.HW))?this.al:c.title;this.Fm=c.action;this.br=f;this.lEa=c._spb;this.Kh=d;this.H4=e;this.Ub=D.p;if(this.Fm||this.br)for(a=0;a<this.me.length;a++)this.me[a].setCursor("pointer")};
D.oO=function(a,b,c,d,e,f){if(!a||!c)return D.o;c=new D.eO(b,a,c,d,e,f);c.Qd()[0]instanceof D.ef?b.sF.push(c):(d=b.A().hideAndShowBehavior,(c.Pe()!=D.o||"none"!=d&&"off"!=d)&&b.sF.push(c),b.cq.push(c));for(d=0;d<a.length;d++)b.Aa().Ba(a[d],c);return c};D.x=D.eO.prototype;D.x.getData=(0,D.w)("HW");D.x.Ib=function(){return this.HW.color};D.x.getId=(0,D.w)("jb");D.x.Qd=(0,D.w)("me");D.x.Xc=function(){return this.al!=D.o?[this.al]:D.o};D.x.Oe=(0,D.w)("Fm");D.x.jm=(0,D.w)("br");D.x.we=(0,D.w)("lEa");
D.x.mc=function(){var a;a=this.Hb.A().hideAndShowBehavior;var b=D.bO.XZ(this.al,this.Hb);return this.me[0]instanceof D.ef?(a=[(0,D.M)("DvtUtilBundle","off"==this.getData().expanded?"STATE_COLLAPSED":"STATE_EXPANDED")],(0,D.ql)(this.getData().title,a)):this.getData().shortDesc!=D.o?(a=[(0,D.M)("DvtUtilBundle",b?"STATE_HIDDEN":"STATE_VISIBLE")],(0,D.ql)(this.getData().shortDesc,a)):"off"!=a&&"none"!=a?(a=[(0,D.M)("DvtUtilBundle",b?"STATE_HIDDEN":"STATE_VISIBLE")],(0,D.ql)(this.getData().text,a)):D.o};
D.nO=function(a){!(0,D.Cf)()&&a.me[0]&&a.me[0].Wb("label",a.mc())};D.x=D.eO.prototype;D.x.Td=function(a){return a.type==D.$e?this:(0,D.Wn)(this,a,this.Hb.sF,D.k)};D.x.Ze=function(a){return this.me[0]?this.me[0].I(a):new D.B(0,0,0,0)};D.x.Ej=function(){return this.me[0]?this.me[0].Fa():D.o};D.x.ke=function(){this.Ub=D.k;this.me[0]&&(this.me[0]instanceof D.ef?(0,D.yF)(this.me[0]):this.me[0].Ya((0,D.ME)()))};D.x.qc=function(){this.Ub=D.p;this.me[0]&&(this.me[0]instanceof D.ef?(0,D.wF)(this.me[0]):this.me[0].ea(D.o))};
D.x.Nc=(0,D.w)("Ub");D.x.ce=(0,D.w)("Kh");D.x.Pe=(0,D.w)("H4");D.x.kj=function(){return this.HW.color};
D.bO={};D.y.q(D.bO,D.y,"DvtLegendRenderer");D.bO.pwa=5;D.bO.qwa=2;D.bO.hga=0.6;D.bO.Sfa=10;D.bO.Ah=12;D.bO.iN=2;
D.bO.U=function(a,b){var c=a.A(),d=a.j(),e=(0,D.F)(d);c.isLayout||D.bO.TF(a,b);var f=new D.VA(d,b.e,b.g),g=new D.C(d);f.da.k(g);a.k(f);a.yFa=f;var h=(0,D.lO)(a,c.layout.outerGapWidth),j=(0,D.lO)(a,c.layout.outerGapHeight);b.x+=h;b.y+=j;b.e-=2*h;b.g-=2*j;a.P2(b);if(0>=b.e||0>=b.g)return new D.Ah(0,0);d=D.bO.Z7(a,g,new D.B(b.x,b.y,b.e,b.g));if(0==d.e||0==d.g)return new D.Ah(0,0);(0,D.WA)(f);d.g>b.g&&(d.g=b.g);var l=f=0,m=c.hAlign!=D.o?c.hAlign:c.halign;"center"==m?f=b.x-d.x+(b.e-d.e)/2:"end"==m&&(f=
e?b.x-d.x:b.x-d.x+b.e-d.e);e=c.vAlign!=D.o?c.vAlign:c.valign;"middle"==e?l=b.y-d.y+(b.g-d.g)/2:"bottom"==e&&(l=b.y-d.y+b.g-d.g);e=new D.B(d.x+f-h,d.y+l-j,d.e+2*h,d.g+2*j);if(c.isLayout)return e;(f||l)&&(0,D.N)(g,f,l);c=a.m9;for(g=0;g<c.length;g++)(0,D.Qo)(d,c[g].eJa,c[g].text,c[g].text.Lb().e);return e};
D.bO.Z7=function(a,b,c){var d=a.A();c=c.ia();var e=D.bO.VP(a,b,d.title,c,D.o,D.k);if(e){var f=e.Lb(),g=(0,D.lO)(a,d.layout.titleGapHeight);c.y+=f.g+g;c.g-=window.Math.floor(f.g+g)}a=D.bO.fna(a,b,d.sections,c,[]);return e?(0,D.Kp)(f,a):a};D.bO.TF=function(a,b){var c=a.A(),d=c.backgroundColor,c=c.borderColor;if(d||c){var e=new D.D(a.j(),b.x,b.y,b.e,b.g);d?e.ra(d):(0,D.Aj)(e);c&&(e.Ya(c),(0,D.Ij)(e));a.Aa().Ba(e,new D.Ok(D.o,D.o,D.o,{type:D.Tm.yH,id:D.i}));a.k(e)}};
D.bO.VP=function(a,b,c,d,e,f){var g=a.A(),h=b.j(),j=(0,D.F)(h);if(!c)return D.o;c=new D.lg(h,c,d.x,d.y);h=g.titleStyle;e&&e.titleStyle?h=new D.I(e.titleStyle):e&&g._sectionTitleStyle&&(h=g._sectionTitleStyle);c.Na(h);return D.yf.wc(c,d.e,window.Infinity,b)?(j&&c.ja(d.x+d.e-c.Lb().e),g.isLayout?b.removeChild(c):(a.Aa().Ba(c,new D.Ok(c.io(),D.o,D.o,{type:D.Tm.Vq,id:D.i})),f&&a.m9.push({text:c,eJa:e&&e.titleHalign?e.titleHalign:g.titleHalign})),c):D.o};
D.bO.fna=function(a,b,c,d,e){var f=a.A();f.symbolWidth==D.o&&f.symbolHeight==D.o?(f.symbolWidth=D.bO.Sfa,f.symbolHeight=D.bO.Sfa):f.symbolWidth==D.o?f.symbolWidth=f.symbolHeight:f.symbolHeight==D.o&&(f.symbolHeight=f.symbolWidth);for(var g=(0,D.lO)(a,f.layout.sectionGapHeight),h=(0,D.lO)(a,f.layout.titleGapHeight),j=(0,D.lO)(a,f.layout.sectionGapWidth),l=D.bO.CAa(a),f="vertical"!=f.orientation,m=D.o,n=d.ia(),q,r=0;r<c.length;r++){var t=e.concat([r]),u="off"==c[r].expanded||c[r].expanded==D.p?h:g;
f?(q=D.bO.ana(a,b,c[r],n,l),q.e>n.e?(n.e<d.e&&(d.y+=q.g+u,d.g-=q.g+u),q=q.e<=d.e?D.bO.ana(a,b,c[r],d,l):D.bO.hna(a,b,c[r],d,l,t,D.k),d.y+=q.g+u,d.g-=q.g+u,n=d.ia()):(n.e-=q.e+j,(0,D.F)(a.j())||(n.x+=q.e+j))):(q=D.bO.hna(a,b,c[r],d,l,t,D.p),d.y+=q.g+u,d.g-=q.g+u);m=m?(0,D.Kp)(m,q):q}return m};
D.bO.cza=function(a,b,c,d,e,f,g,h,j,l,m){var n=D.bO.s4(a,d,e+"Enabled",f,g),q=D.bO.s4(a,d,e+"Over",f,g);d=D.bO.s4(a,d,e+"Down",f,g);a=new D.ef(a,n,q,d,D.o,j,l,m);b=(0,D.oO)([a],b,c,h,D.o,D.p);a.xd("button");(0,D.nO)(b);return a};D.bO.s4=function(a,b,c,d,e){var f=(0,D.F)(a)?"RTL":"";a=new D.sf(a,b[c+f]?b[c+f]:b[c],d,e,D.bO.Ah,D.bO.Ah);(0,D.Aj)(a);return a};
D.bO.hna=function(a,b,c,d,e,f,g){if(c){var h=a.A(),j=(0,D.lO)(a,h.layout.symbolGapWidth),l=(0,D.lO)(a,h.layout.rowGap),m=(0,D.lO)(a,h.layout.columnGap),n=a.j(),q=(0,D.F)(n);d=d.ia();"off"!=h.scrolling&&(d.g=window.Infinity);var r,t="on"==c.collapsible||c.collapsible==D.k;if(t){r=q?d.x+d.e-D.bO.Ah:d.x;if(!h.isLayout){var u="off"==c.expanded||c.expanded==D.p,A=u?"closed":"open",u=(0,D.M)("DvtUtilBundle",u?"EXPAND":"COLLAPSE",D.o),z=a.Aa(),n=D.bO.cza(n,a,c,h._resources,A,r,d.y,u,f,z.fba,z);b.k(n)}r=
new D.B(r,d.y,D.bO.Ah,D.bO.Ah);n=(0,D.lO)(a,h.layout.symbolGapWidth);q||(d.x+=D.bO.Ah+n);d.e-=D.bO.Ah+n}t=(t=D.bO.VP(a,b,c.title,d,c,!t&&1>=f.length))?t.Lb():new D.B(q?d.x+d.e:d.x,d.y,0,0);t=r?(0,D.Kp)(t,r):t;if(!c.items&&!c.sections||"off"==c.expanded||c.expanded==D.p)return t;0<t.g&&(n=(0,D.lO)(a,h.layout.titleGapHeight),d.y+=t.g+n,d.g-=t.g+n);c.sections&&(f=D.bO.fna(a,b,c.sections,d,f),t=(0,D.Kp)(t,f));if(!c.items)return t;n=D.bO.Kya(a,d,e,c.items,g);g=n.numCols;f=n.numRows;n=n.width;r=d.y;if(0==
f||0==g)return t;A=f*(e+l)-l;u=window.Math.min(g*(n+m)-m,d.e);t=(0,D.Kp)(t,new D.B(q?d.x+d.e-u:d.x,d.y,u,A));if(h.isLayout)return t;h=n-h.symbolWidth-j;j=0;A=1;u=c.items.length;for(z=0;z<u;z++)D.bO.XN(a,b,c.items[z],d,h,e,z),d.y+=e+l,j++,j===f&&A!==g&&(d.y=r,d.e-=n+m,q||(d.x+=n+m),j=0,A++);return t}};
D.bO.ana=function(a,b,c,d,e){if(c){var f=a.A(),g=f.symbolWidth,h=(0,D.lO)(a,f.layout.symbolGapWidth),j=(0,D.lO)(a,f.layout.columnGap),l=(0,D.lO)(a,f.layout.titleGapWidth),m=c.items.length,n=(0,D.F)(a.j()),q=d.ia(),r=D.bO.VP(a,b,c.title,d,c,D.p),t=r?r.Lb():new D.B(n?d.x+d.e:d.x,d.y,0,0);if(c.items)0<t.e&&(q.e-=t.e+l,n||(q.x+=t.e+l));else return t;var l=[],u=d.e-q.e,A,z;for(z=0;z<m;z++)A=c.items[z],A=window.Math.ceil(D.yf.jaa(a.j(),A.text,f.textStyle)),u+=A+g+h+j,l.push(A);0<m&&(u-=j);t=new D.B(n?d.x+
d.e-u:d.x,d.y,u,window.Math.max(e,t.g));if(f.isLayout||u>d.e)return b.removeChild(r),t;for(z=0;z<m;z++)A=c.items[z],D.bO.XN(a,b,A,q,l[z],e,z),d=l[z]+g+h,q.e-=d+j,n||(q.x+=d+j);return t}};
D.bO.Kya=function(a,b,c,d,e){for(var f=a.A(),g=0,h=0;h<d.length;h++){var j=D.yf.jaa(a.j(),d[h].text,f.textStyle);j>g&&(g=j)}var h=f.symbolWidth,l=(0,D.lO)(a,f.layout.symbolGapWidth),j=(0,D.lO)(a,f.layout.rowGap);a=(0,D.lO)(a,f.layout.columnGap);g=window.Math.ceil(h+l+g);e?(e=window.Math.min(window.Math.floor((b.e+a)/(g+a)),d.length),c=window.Math.ceil(d.length/e)):window.Infinity==b.g?(e=1,c=d.length):(c=window.Math.min(window.Math.floor((b.g+j)/(c+j)),d.length),e=window.Math.ceil(d.length/c),c=window.Math.ceil(d.length/
e));b=window.Math.min(g,(b.e-a*(e-1))/e);return b<h?{width:0,numCols:0,numRows:0}:{width:b,numCols:e,numRows:c}};D.bO.CAa=function(a){var b=a.A(),c=new D.lg(a.j(),"Test");c.Na(b.textStyle);c.Xf();c=D.yf.pj(c).g;a=b.symbolHeight+(0,D.lO)(a,b.layout.symbolGapHeight);return window.Math.ceil(window.Math.max(c,a))};
D.bO.XN=function(a,b,c,d,e,f,g){var h=a.A(),j=a.j(),l=(0,D.F)(j),m=h.symbolWidth,n=(0,D.lO)(a,h.layout.symbolGapWidth),q=l?d.x+d.e-m:d.x,r=l?d.x+d.e-m-n:d.x+m+n;g=D.bO.gza(a,q,d.y,f,c,g);var t=c.text,u;if(t&&(u=D.bO.hza(b,e,t,h.textStyle)))u.ja(r),u.Ea(d.y+f/2),l&&u.Di();b.k(g);d=new D.D(j,l?r-e-D.bO.iN:q-D.bO.iN,d.y-D.bO.iN,m+n+e+2*D.bO.iN,f+2*D.bO.iN);(0,D.Aj)(d);h=h.hideAndShowBehavior;"none"!=h&&"off"!=h&&d.setCursor("pointer");b.k(d);b=[d,g];u!=D.o&&b.push(u);u=(0,D.oO)(b,a,c,u!=D.o?u.io():D.o,
c.shortDesc,D.bO.nBa(a,c));D.bO.XZ(D.bO.mZ(c),a)&&g.mH(u.Ib());if("none"!=h&&"off"!=h||c.shortDesc!=D.o)d.xd("img"),(0,D.nO)(u)};D.bO.nBa=function(a,b){return"on"==b.drilling?D.k:"off"==b.drilling?D.p:"on"==a.A().drilling};D.bO.hza=function(a,b,c,d){c=new D.lg(a.j(),c);c.Xf();c.Na(d);return c=D.yf.wc(c,b,window.Infinity,a)?c:D.o};
D.bO.gza=function(a,b,c,d,e,f){var g=a.A();e.markerShape||(e.markerShape=g.markerShape);if(!e.color){var h=g.colors;e.color=h[f%h.length]}e.lineWidth||(e.lineWidth=g.lineWidth);f=g.symbolWidth;var g=g.symbolHeight,h=c+d/2,j=b+f/2,l=e.type!=D.o?e.type:e.symbolType;"line"==l?(e.lineWidth=window.Math.min(e.lineWidth,D.bO.pwa),b=D.bO.Rha(a.j(),b,c,f,d,e)):"lineWithMarker"==l?(e.lineWidth=window.Math.min(e.lineWidth,D.bO.qwa),b=D.bO.Rha(a.j(),b,c,f,d,e),D.bO.XZ(D.bO.mZ(e),a)||b.k(D.bO.wV(a,j,h,f*D.bO.hga,
g*D.bO.hga,e))):b="image"==l?D.bO.u4(a,b,c,f,g,d,e):D.bO.wV(a,j,h,f,g,e);return b};D.bO.u4=function(a,b,c,d,e,f,g){return new D.sf(a.j(),g.source,b,c+(f-e)/2,d,e)};
D.bO.wV=function(a,b,c,d,e,f){var g=a.j(),h=a.A();a=f.markerShape;var j=f.markerColor?f.markerColor:f.color,l=f.pattern;l&&"none"!=l?(d=new D.po(g,a,h.skin,0,0,d,e),d.O(new D.ci(l,j,"#FFFFFF")),(0,D.N)(d,b,c)):(d=new D.po(g,a,h.skin,b,c,d,e),d.ra(j));f.borderColor&&d.Ya(f.borderColor,D.o,f._borderWidth?f._borderWidth:1);"square"==a&&(0,D.Ij)(d);return d};
D.bO.Rha=function(a,b,c,d,e,f){c+=e/2;a=new D.Hj(a,b,c,b+d,c);b=new D.Wg(f.color,1,f.lineWidth);f=f.lineStyle;"dashed"==f?b.Uk((0,D.Xg)(f),"4,2,4"):"dotted"==f&&b.Uk((0,D.Xg)(f),"2");a.ea(b);(0,D.Ij)(a);return a};D.bO.mZ=function(a){var b=D.o;return b=a.categories&&0<a.categories.length?a.categories[0]:a.id?a.id:a.text};D.bO.XZ=function(a,b){var c=b.A().hiddenCategories;return!c||0>=c.length?D.p:-1!==c.indexOf(a)};
  return D;
});