/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.hP={Hl:function(){return(0,D.Ze)()}};D.y.q(D.hP,D.y,"DvtTimeUtils");D.hP.be=function(a,b,c,d){c=(c-a)*d;a=b-a;return 0==c||0==a?0:c/a};D.hP.pg=function(a,b,c,d){b=c*(b-a);return 0==b||0==d?a:b/d+a};
D.Gp=function(a,b,c){this.Init(a,b,c)};(0,D.ca)("DvtOverview",D.Gp);D.y.q(D.Gp,D.C,"DvtOverview");
D.Gp.prototype.Init=function(a,b,c){D.Gp.u.Init.call(this,a);this.nb=b;this.ta=c;this.aq=this.SG()?7:6;if(this.nb!=D.o||this.ta!=D.o)this.eb=new D.gP(this),this.eb.Ne(this),D.hP.Hl()?(this.oa(D.Ye.eg,this.yT,D.p,this),this.oa(D.Ye.rk,this.dea,D.p,this),this.oa(D.Ye.Pi,this.wT,D.p,this),this.oa(D.$e,this.KD,D.p,this)):(this.oa(D.af,this.tT,D.p,this),this.oa(D.bf,this.sT,D.p,this),this.oa(D.$e,this.KD,D.p,this),this.oa(D.qk,this.HM,D.p,this),this.oa(D.rk,this.f1,D.p,this));this.X5=0};
D.Gp.prototype.El=function(a,b,c){c==D.o&&(c=this.fb);a=this.be(a);var d=this.be(b);a<this.Ms||d>(0,D.iP)(this)||(b=window.Math.max(d-a,(0,D.jP)(this)),0<b&&(0<=a&&d<=c)&&(d=this.na(1),this.Rb()?(0,D.kP)(this,d,c-(a+b)):(0,D.kP)(this,d,a),(0,D.lP)(this,d,b),(0,D.mP)(this)))};D.nP=function(a){return a.UV==D.o?D.p:-1!=a.UV.indexOf("zoom")};
D.Gp.prototype.U=function(a,b,c){if(a==D.o){var d=this.rb,e=this.Yb,f=this.na(1),g=(0,D.oP)(this,f);f!=D.o&&0!=g&&(this.gna=D.hP.pg(d,e,g,this.fb));this.Sk()}b!=D.o&&c!=D.o&&(this.fb=b,this.tb=c);a&&(a=this.UH(a),this.nw(a));a=this.nb!=D.o||this.ta!=D.o;this.WK(b,c);if(a){e=(d=this.Oc())?new D.D(this.j(),0,0,b,0,"window"):new D.D(this.j(),0,0,0,c,"window");e.ra(this.uY,this.LEa);(0,D.Ij)(e);if(!(0,D.nP)(this)){var h=(0,D.pP)(),j=(0,D.qP)();if(d){var l=(b-36)/2,m=D.K.moveTo(l,0)+D.K.bd(l+3,6,l+8,8)+
D.K.lineTo(l+28,8)+D.K.bd(l+33,6,l+36,0);D.K.closePath();g=D.K.moveTo(l,0)+D.K.bd(l+3,-6,l+8,-8)+D.K.lineTo(l+28,-8)+D.K.bd(l+33,-6,l+36,0);D.K.closePath();var f=new D.D(this.j(),0,0,b,h,"lhb"),h=new D.D(this.j(),0,0,b,h,"rhb"),n="row-resize";if(this.J5)var q=(0,D.rP)(this,b,10),l=(0,D.rP)(this,b,10);else q=(0,D.sP)(this,l),l=(0,D.sP)(this,l)}else l=(c-36)/2,m=D.K.moveTo(0,l)+D.K.bd(6,l+3,8,l+8)+D.K.lineTo(8,l+28)+D.K.bd(6,l+33,0,l+36),D.K.closePath(),g=D.K.moveTo(0,l)+D.K.bd(-6,l+3,-8,l+8)+D.K.lineTo(-8,
l+28)+D.K.bd(-6,l+33,0,l+36),D.K.closePath(),f=new D.D(this.j(),0-j,0,h,c,"lhb"),h=new D.D(this.j(),j,0,h,c,"rhb"),n="col-resize",this.J5?(q=(0,D.rP)(this,10,c),l=(0,D.rP)(this,10,c)):(q=(0,D.sP)(this,l),l=(0,D.sP)(this,l));f.ra(this.uY,0);h.ra(this.uY,0);(0,D.Ij)(f);(0,D.Ij)(h);m=new D.Ei(this.j(),m,"lh");g=new D.Ei(this.j(),g,"rh");m.ra(this.FO);m.Ya(this.FO);g.ra(this.FO);g.Ya(this.FO);this.uY==this.FO&&((0,D.Ij)(m),(0,D.Ij)(g));f.setCursor(n);h.setCursor(n);m.setCursor(n);g.setCursor(n);q.setCursor(n);
l.setCursor(n);e.k(f);e.k(m);e.k(q);e.k(h);e.k(g);e.k(l)}e.setCursor("move");this.k(e);e=d?new D.Hj(this.j(),b-this.vR(),0,b-this.vR(),c,"tab"):"above"==this.pX?new D.Hj(this.j(),0,(0,D.tP)(this),b,(0,D.tP)(this),"tab"):new D.Hj(this.j(),0,c-(0,D.tP)(this),b,c-(0,D.tP)(this),"tab");e.Ya(this.vEa,this.wEa);(0,D.Ij)(e);this.Una=e;this.k(e);this.Gt()&&(d?(e=new D.D(this.j(),0,0,b,0,"lbg"),f=new D.D(this.j(),0,0,b,0,"rbg")):(e=new D.D(this.j(),0,0,0,c,"lbg"),f=new D.D(this.j(),0,0,0,c,"rbg")),e.ra(this.Mka,
this.BBa),this.k(e),f.ra(this.lna,this.UDa),this.k(f),D.hP.Hl()&&j!=D.i&&((0,D.qP)(),d?(d=new D.D(this.j(),0,0,b,j,"lbgrh"),j=new D.D(this.j(),0,0,b,j,"rbgrh")):(d=new D.D(this.j(),0,0,j,c,"lbgrh"),j=new D.D(this.j(),0,0,j,c,"rbgrh")),d.ra(this.Mka,0),this.k(d),j.ra(this.lna,0),this.k(j)))}if(this.lQ!=D.o){this.Oc();j=(0,D.uP)(this);for(d=0;d<this.lQ.length;d++)f=this.lQ[d],e=(0,window.parseInt)(f.B("time"),10),e=this.be(e),f=f.B("label"),g=0,d+1<this.lQ.length?(g=(0,window.parseInt)(this.lQ[d+1].B("time"),
10),g=this.be(g)-e):g=j-e,this.Rb()&&(e=j-e),this.RK(e,b,c,"tick"+d),this.OK(e,f,b,c,g,"label"+d)}if(this.n5!=D.o)for(j=0;j<this.n5.length;j++)f=this.n5[j],d=b,e=c,n=(0,window.parseInt)(f.B("rs"),10),g=(0,window.parseInt)(f.B("re"),10),f=f.B("c"),n!=D.o&&g!=D.o&&(h=(0,D.uP)(this),n=this.be(n),g=this.be(g)-n,this.Rb()&&(n=h-n-g),d=this.Oc()?new D.D(this.j(),0,n,d-this.vR(),g,"ftr"):new D.D(this.j(),n,"above"==this.pX?(0,D.tP)(this):0,g,e-(0,D.tP)(this),"ftr"),f!=D.o&&d.ra(f,0.4),d.setCursor("move"),
(0,D.Ij)(d),this.k(d));this.D4==D.o||(0,window.isNaN)(this.D4)||(j=this.be(this.D4),this.Oc()?j=new D.Hj(this.j(),0,j,b,j,"ocd"):(this.Rb()&&(j=b-j),j=new D.Hj(this.j(),j,0,j,c,"ocd")),j.Ya(this.pza),(0,D.Ij)(j),this.k(j));this.jS(b,c);a&&(g=this.na(1),this.Oc()?(a=g.qa(),j=a+0.5,d=a+g.getHeight(),q=d-0.5,e=0,f=0.5,m=b-0.5,g=new D.Hj(this.j(),e,j,b,j,"lh"),h=new D.Hj(this.j(),e,q,b,q,"rh"),n=new D.Hj(this.j(),f,0,f,a,"ltb"),b=new D.Hj(this.j(),f,d,f,c,"rtb"),q=new D.Hj(this.j(),m,a,m,d,"bb"),c=new D.Hj(this.j(),
f,a,f,d,"tb")):(a=0,j=a+0.5,d=c,q=d-0.5,e=g.pa(),f=e+0.5,c=e+g.getWidth(),m=c-0.5,g=new D.Hj(this.j(),f,a,f,d,"lh"),h=new D.Hj(this.j(),m,a,m,d,"rh"),n=new D.Hj(this.j(),0,j,e+1,j,"ltb"),b=new D.Hj(this.j(),c-1,j,b,j,"rtb"),q=new D.Hj(this.j(),e,q,c,q,"bb"),c=new D.Hj(this.j(),e,j,c,j,"tb")),(0,D.Ij)(g),(0,D.Ij)(h),(0,D.Ij)(n),(0,D.Ij)(b),(0,D.Ij)(q),(0,D.Ij)(c),"none"!=this.PEa&&g.Ya(this.OEa),this.k(g),"none"!=this.REa&&h.Ya(this.QEa),this.k(h),"none"!=this.Gya&&this.K3&&(n.Ya(this.K3),b.Ya(this.K3)),
this.k(n),this.k(b),"none"!=this.NEa&&q.Ya(this.MEa),this.k(q),"none"!=this.TEa&&c.Ya(this.SEa),this.k(c),this.SG()&&(b=this.Oc()?D.K.moveTo(6,0)+D.K.lineTo(0,5)+D.K.lineTo(5,5)+D.K.lineTo(5,17)+D.K.lineTo(0,17)+D.K.lineTo(6,22)+D.K.lineTo(12,17)+D.K.lineTo(7,17)+D.K.lineTo(7,5)+D.K.lineTo(12,5)+D.K.closePath():D.K.moveTo(5,0)+D.K.lineTo(0,6)+D.K.lineTo(5,12)+D.K.lineTo(5,7)+D.K.lineTo(17,7)+D.K.lineTo(17,12)+D.K.lineTo(22,6)+D.K.lineTo(17,0)+D.K.lineTo(17,4)+D.K.lineTo(5,4)+D.K.lineTo(5,0)+D.K.closePath(),
b=new D.Ei(this.j(),b,"arr"),b.ra("#ffffff"),b.Ya("#000000"),b.xb(D.p),this.k(b),this.dK=b),a=this.Oc(),c=this.na(1),b=(0,D.uP)(this),j=a?this.tb:this.fb,e=this.Ja,f=this.rb,g=this.Yb,a=this.gna,d=D.hP.pg(f,g,0,e),e=D.hP.pg(f,g,j,e),d=this.be(d),j=window.Math.min(j,this.be(e)),a=this.be(a),j-=d,this.Rb()?(0,D.kP)(this,c,b-a-j):(0,D.kP)(this,c,a),(0,D.lP)(this,c,j),(0,D.mP)(this),c=this.Ja,a=this.rb,j=this.Yb,d=D.hP.pg(a,j,1,b),b=D.hP.pg(a,j,2,b),d=D.hP.be(a,j,d,c),this.lJ=D.hP.be(a,j,b,c)-d);this.aka!=
D.o&&(this.X5=window.Math.max(0,D.hP.be(this.rb,this.Yb,this.aka,this.Ja)));0<this.X5&&(b=this.X5/this.lJ,this.Rb()&&(b=0-b),(0,D.vP)(this,b))};D.Gp.prototype.render=D.Gp.prototype.U;D.x=D.Gp.prototype;D.x.tqa=function(){return new D.wP(this)};D.x.UH=function(a){return this.tqa(a).parse(a)};
D.x.nw=function(a){this.rb=a.start;this.Yb=a.end;this.Ja=a.width;this.gna=a.Hba;this.D4=a.currentTime;this.aka=a.OJa;this.Yxa=a.uoa;this.Ms=window.Math.max(0,a.vKa);this.eK=window.Math.max(0,a.wLa);(0,window.isNaN)(this.Ms)&&(this.Ms=0);(0,window.isNaN)(this.eK)&&(this.eK=0);this.HF=a.orientation;this.pX=a.Sra;this.qBa=a.Laa;a.dpa!=D.o&&(this.UV=a.dpa.split(" "));a.dba!=D.o&&0<a.dba&&(this.qla=a.dba);this.Fya=a.mFa;this.mQ=a.vsa;a.vsa!=D.o&&(this.lQ=this.mQ.$La);this.n5=a.wGa;this.Gya=a.borderTopStyle;
this.K3=a.borderTopColor;this.uY=a.ica;this.LEa=a.Asa;this.TEa=a.qca;this.REa=a.oca;this.NEa=a.kca;this.PEa=a.mca;this.SEa=a.pca;this.QEa=a.nca;this.MEa=a.jca;this.OEa=a.lca;this.XAa=a.uaa;this.FO=a.saa;this.J5=a.Jqa;this.Lja=a.Vqa;this.Gja=a.Sqa;this.yCa=a.kba;this.pza=a.W9;this.xEa=a.bca;this.vEa=a.tsa;this.wEa=a.usa;this.Mka=a.sra;this.BBa=a.rra;this.lna=a.hsa;this.UDa=a.gsa};D.x.be=function(a){return window.Math.max(0,D.hP.be(this.rb,this.Yb,a,(0,D.uP)(this)))+this.Ms};
D.x.pg=function(a){return D.hP.pg(this.rb,this.Yb,window.Math.max(0,a-this.Ms),(0,D.uP)(this))};D.x.Rb=function(){return!this.Oc()&&"true"==this.qBa};D.x.Oc=function(){return"vertical"==this.HF};D.uP=function(a){return a.Oc()?a.tb-a.Ms-a.eK:a.fb-a.Ms-a.eK};D.iP=function(a){return a.Oc()?a.tb-a.eK:a.fb-a.eK};D.jP=function(a){return a.b7!=D.o?a.b7:a.qla!=D.o?(a.b7=D.hP.be(a.rb,a.Yb,a.rb+a.qla,(0,D.uP)(a)),a.b7):10};D.qP=function(){return D.hP.Hl()?(0,D.pP)()/2:0};
D.pP=function(){return D.hP.Hl()?30:10};D.xP=function(a){var b=a.getId();return"lh"==b||"rh"==b||"lhb"==b||"rhb"==b||"grpy"==b||"lbgrh"==b||"rbgrh"==b||a.getParent()!=D.o&&"grpy"==a.getParent().getId()};D.Gp.prototype.vR=function(){if(this.mQ==D.o)return 0;if(this.nQ==D.o){var a=(0,window.parseInt)(this.mQ.width,10);this.nQ=!(0,window.isNaN)(a)&&a<this.fb?a:40}return this.nQ};
D.tP=function(a){if(a.mQ==D.o)return 0;if(a.Tna==D.o){var b=(0,window.parseInt)(a.mQ.height,10);a.Tna=!(0,window.isNaN)(b)&&b<a.tb?b:20}return a.Tna};D.yP=function(a){return D.hP.Hl()&&a.targetTouches!=D.o?0<a.targetTouches.length?a.targetTouches[0].pageX:D.o:a.pageX};D.zP=function(a){return D.hP.Hl()&&a.targetTouches!=D.o?0<a.targetTouches.length?a.targetTouches[0].pageY:D.o:a.pageY};D.Gp.prototype.Gt=(0,D.ba)(D.p);D.AP=function(a){return a.Gt()?a.na(3):D.o};
D.BP=function(a){return a.Gt()?a.na(4):D.o};D.CP=function(a){return a.Gt()&&!(0,D.nP)(a)?a.na(6):D.o};D.DP=function(a){return a.na(a.Ma()-(a.aq-1))};D.EP=function(a,b,c,d){a.Oc()?(-1!=c&&b.Gl(c),-1!=d&&b.vn(d)):(-1!=c&&b.Fl(c),-1!=d&&b.um(d))};D.FP=function(a,b){return a.Oc()?b.yq():b.jp()};D.Gp.prototype.$I=function(a){a=a.target;if(a!=D.o){var b=a.getId();if(b==D.o)return D.o;if("_border"==b.substr(b.length-7))return this.x$(a);if("tick"!=b.substr(0,4)&&"ltb"!=b&&"rtb"!=b&&"bb"!=b&&"tab"!=b)return a}return D.o};
D.GP=function(a){return"window"==a.getId()||"ftr"==a.getId()||"sta"==a.getId()||(0,D.xP)(a)?D.k:D.p};D.Gp.prototype.SG=function(){return window&&window.SG};D.Gp.prototype.WK=function(a,b){var c=new D.D(this.j(),0,0,a,b,"bg");c.ra(this.yCa);(0,D.Ij)(c);this.k(c);return c};D.rP=function(a,b,c){a=new D.sf(a.j(),a.J5,(b-a.Lja)/2,(c-a.Gja)/2,a.Lja,a.Gja,"grpy");a.ua(D.p);return a};
D.sP=function(a,b){var c=new D.C(a.j(),"grpy"),d=a.XAa;if(a.Oc()){for(var e=8+b,f=3,g=0;9>g;g++){var h=new D.Hj(a.j(),e+2*g,f,e+2*g+1,f,"dot1"+g);h.Ya(d);c.k(h);f+=2;h=new D.Hj(a.j(),e+1+2*g,f,e+1+2*g+1,f,"dot2"+g);h.Ya(d);c.k(h);f+=2;h=new D.Hj(a.j(),e+2*g,f,e+2*g+1,f,"dot3"+g);h.Ya(d);c.k(h);f=3}h=new D.Hj(a.j(),e+18,f,e+18+1,f,"dot4");h.Ya(d);c.k(h);f+=4;h=new D.Hj(a.j(),e+18,f,e+18+1,f,"dot5")}else{e=3;f=8+b;for(g=0;9>g;g++)h=new D.Hj(a.j(),e,f+2*g,e,f+2*g+1,"dot1"+g),h.Ya(d),c.k(h),e+=2,h=new D.Hj(a.j(),
e,f+1+2*g,e,f+1+2*g+1,"dot2"+g),h.Ya(d),c.k(h),e+=2,h=new D.Hj(a.j(),e,f+2*g,e,f+2*g+1,"dot3"+g),h.Ya(d),c.k(h),e=3;h=new D.Hj(a.j(),e,f+18,e,f+18+1,"dot4");h.Ya(d);c.k(h);e+=4;h=new D.Hj(a.j(),e,f+18,e,f+18+1,"dot5")}h.Ya(d);c.k(h);(0,D.Ij)(c);return c};D.HP=function(a,b){return a.Oc()?b.getHeight():b.getWidth()};D.oP=function(a,b){return a.Oc()?b.Q():b.V()};
D.kP=function(a,b,c){c=window.Math.max(0,c);a.Oc()?b.W(c):b.K(c);if(a.Gt()){(0,D.AP)(a).sa(c);b=c+(0,D.HP)(a,b);var d=(0,D.BP)(a);d.ja(b);d.sa(window.Math.max(0,a.fb-b));D.hP.Hl()&&!(0,D.nP)(a)&&(d=(0,D.qP)(),(a.Gt()&&!(0,D.nP)(a)?a.na(5):D.o).ja(c-d),(0,D.CP)(a).ja(b))}};
D.lP=function(a,b,c){c=window.Math.max((0,D.jP)(a),c);var d=c=window.Math.min(a.Oc()?a.tb:a.fb,c);a.Oc()?b.Ia(d):b.sa(d);if(a.Gt()){var d=(0,D.oP)(a,b)+c,e=(0,D.BP)(a);e.ja(d);e.sa(window.Math.max(0,a.fb-d));D.hP.Hl()&&!(0,D.nP)(a)&&(0,D.CP)(a).ja(d)}(0,D.nP)(a)||(d=b.na(3),e=b.na(4),b=b.na(5),a.Oc()?(e.W(c),d.W(c-(0,D.pP)()),b.W(c-10)):(e.K(c),d.K(c-(0,D.pP)()),b.K(c-10)))};
D.Gp.prototype.RK=function(a,b,c,d){a=this.Oc()?new D.Hj(this.j(),0,a,b,a,d):new D.Hj(this.j(),a,0,a,c,d);b=new D.Wg(this.xEa);b.ca(1,3);a.ea(b);(0,D.Ij)(a);this.k(a)};
D.Gp.prototype.OK=function(a,b,c,d,e,f){this.Oc()?(b=new D.lg(this.j(),b,4,a,f),b.Na(new D.I("font-weight:bold"))):(c="above"==this.pX?2:d-(0,D.tP)(this)+2,b=new D.lg(this.j(),b,a+5,c,f),b.Na(new D.I("font-weight:bold")),this.Rb()&&(this.k(b),f=b.I(),this.removeChild(b),e-=10,b.ja(a-window.Math.min(f.e,e)-5)));D.yf.wc(b,e,window.Infinity,this);b.XCa=b.io()};D.Gp.prototype.jS=(0,D.s)();
D.vP=function(a,b){var c=a.na(1);c.na(3);c.na(4);c.na(5);if(b!=(0,D.oP)(a,c)){var d=a.na(a.Ma()-a.aq),e=(0,D.DP)(a),f=a.na(a.Ma()-(a.aq-2)),g=a.na(a.Ma()-(a.aq-3)),h=a.na(a.Ma()-(a.aq-4)),j=a.na(a.Ma()-(a.aq-5));if(a.Oc())var l=c.Q,m=c.W,n=d.yq,q=d.Gl,r=d.tv,t=d.vn,u=e.yq,A=e.Gl,z=e.tv,E=e.vn,U=f.tv,L=f.vn,O=g.yq,Z=g.Gl,W=h.yq,ia=h.Gl,sa=h.tv,Va=h.vn,Na=j.yq,gb=j.Gl,wb=j.tv,qb=j.vn;else l=c.V,m=c.K,n=d.jp,q=d.Fl,r=d.Lr,t=d.um,u=e.jp,A=e.Fl,z=e.Lr,E=e.um,U=f.Lr,L=f.um,O=g.jp,Z=g.Fl,W=h.jp,ia=h.Fl,
sa=h.Lr,Va=h.um,Na=j.jp,gb=j.Fl,wb=j.Lr,qb=j.um;var xb=a.Ms,bc=(0,D.iP)(a),yb=(0,D.HP)(a,c);b=window.Math.max(xb,window.Math.min(bc-yb,b));xb="off"!==a.Yxa?new D.ms(a.j(),0.5,0,D.HD):D.o;(0,D.IP)(xb,c,l,m,b);(0,D.IP)(xb,d,n,q,b);(0,D.IP)(xb,d,r,t,b);(0,D.IP)(xb,e,u,A,b+yb);(0,D.IP)(xb,e,z,E,b+yb);(0,D.IP)(xb,f,U,L,b+1);(0,D.IP)(xb,g,O,Z,b+yb-1);(0,D.IP)(xb,h,W,ia,b);(0,D.IP)(xb,j,Na,gb,b);(0,D.IP)(xb,h,sa,Va,b+yb);(0,D.IP)(xb,j,wb,qb,b+yb);a.Gt()&&(c=(0,D.AP)(a),(0,D.IP)(xb,c,c.getWidth,c.sa,b),yb=
b+yb,c=(0,D.BP)(a),d=c.getWidth,e=c.sa,f=c.pa,g=c.ja,h=a.Oc()?a.tb:a.fb,(0,D.IP)(xb,c,d,e,h-yb),(0,D.IP)(xb,c,f,g,yb),D.hP.Hl()&&!(0,D.nP)(a)&&(c=(0,D.qP)(),d=a.Gt()&&!(0,D.nP)(a)?a.na(5):D.o,e=d.pa,f=d.ja,g=(0,D.CP)(a),h=g.pa,j=g.ja,(0,D.IP)(xb,d,e,f,b-c),(0,D.IP)(xb,g,h,j,yb)));xb!=D.o&&xb.play()}};D.IP=function(a,b,c,d,e){a!=D.o?(0,D.S)(a,"typeNumber",b,c,d,e):d.call(b,e)};D.x=D.Gp.prototype;
D.x.tT=function(a){var b=this.$I(a);if(b&&!("bg"==b.getId()||"ocd"==b.getId()))if("label"==b.getId().substr(0,5)&&(b instanceof D.lg||b instanceof D.il))b.Pk()&&this.j().qd().jM(a.pageX,a.pageY,b.XCa,"#000000");else if(this.dK!=D.o&&(0,D.xP)(b)&&(a=(0,D.qv)(this.j(),a.pageX,a.pageY),a=this.oc(a),this.Oc()?(0,D.N)(this.dK,a.x+6,a.y-10):(0,D.N)(this.dK,a.x-6,a.y-20),this.dK.xb(D.k)),"window"==b.getId()||"ftr"==b.getId()||"arr"==b.getId()||(0,D.xP)(b))this.SG()&&this.setCursor("move");else return b};
D.x.sT=function(a){this.Jo==D.o&&this.setCursor("default");a=this.$I(a);if(a!=D.o)return(0,D.xP)(a)&&this.dK!=D.o&&this.dK.xb(D.p),a};
D.x.KD=function(a,b,c){a.stopPropagation();var d=this.$I(a);if(d&&!("window"==d.getId()||(0,D.xP)(d)))if("bg"==d.getId()||"label"==d.getId().substr(0,5)||"ocd"==d.getId()||"lbg"==d.getId()||"rbg"==d.getId()){b==D.i&&(b=a.pageX);c==D.i&&(c=a.pageY);a=(0,D.qv)(this.j(),b,c);a=this.oc(a);this.Oc()?(c=a.y,d=this.tb):(c=a.x,d=this.fb);a=this.na(1);b=c-(0,D.HP)(this,a)/2;(0,D.vP)(this,b);this.Rb()&&(c=this.fb-c);var e=this.pg(c);c=new D.JP("scrollTime");c.setTime(e);b=window.Math.max(0,window.Math.min(b,
d-(0,D.HP)(this,a)));this.Rb()?(d=this.pg(this.fb-(b+(0,D.HP)(this,a))),a=this.pg(this.fb-b)):(d=this.pg(b),a=this.pg(b+(0,D.HP)(this,a)));(0,D.KP)(c,d);(0,D.LP)(c,a);this.dispatchEvent(c)}else return d};
D.x.EQ=function(a,b,c){a=this.$I(a);if(a!=D.o&&(0,D.GP)(a)){if("ftr"==a.getId()||"sta"==a.getId())a=this.na(1);this.rW=b;this.Yja=c;if((0,D.xP)(a)){b=this.na(1);this.Rb()?(this.l7=this.fb-b.pa(),this.u7=this.l7-b.getWidth()):(this.u7=b.pa(),this.l7=this.u7+b.getWidth());"grpy"==a.getParent().getId()&&(a=a.getParent());c=a.getId();"grpy"==c&&(a=b.VQ(a),c=a.getId());if("lh"==c||"rh"==c)a=b.VQ(a),c=a.getId();"lbgrh"==c&&(a=b.na(0));"rbgrh"==c&&(a=b.na(b.Ma()-3));D.hP.Hl()||(this.Oc()?(a.Ea(-20),a.Ia(2*
(a.getHeight()+20))):(a.ja(-20),a.sa(2*(a.getWidth()+20))));b=a.getCursor();c=this.na(1);c!=D.o&&c.setCursor(b);if(this.Gt()){c=(0,D.AP)(this);var d=(0,D.BP)(this);c!=D.o&&d!=D.o&&(c.setCursor(b),d.setCursor(b))}}this.Jo=a;a=new D.JP("dropCallback");this.dispatchEvent(a);return D.k}return D.p};
D.x.ZK=function(){if(this.Jo!=D.o){if("window"==this.Jo.getId())this.gpa(0,0);else if((0,D.xP)(this.Jo)){this.i$();D.hP.Hl()||(this.Oc()?(this.Jo.Ea(0),this.Jo.Ia((0,D.pP)())):(this.Jo.ja(0),this.Jo.sa((0,D.pP)())));var a=this.na(1);a!=D.o&&a.setCursor("move");if(this.Gt()){var a=(0,D.AP)(this),b=(0,D.BP)(this);a!=D.o&&b!=D.o&&(a.setCursor("default"),b.setCursor("default"))}}this.Jo=D.o;this.rW=-1}};
D.x.FQ=function(a,b,c){if(this.Jo!=D.o&&-1!=this.rW){var d=b-this.rW,e=c-this.Yja;this.rW=b;this.Yja=c;"window"==this.Jo.getId()?this.Wqa(0,d,e):"lh"==this.Jo.getId()||"lhb"==this.Jo.getId()?(0,D.MP)(this,a,d,e,D.k):("rh"==this.Jo.getId()||"rhb"==this.Jo.getId())&&this.taa(a,d,e)}};
D.x.yT=function(a){var b=a.touches;this.EK=b[0].pageX;this.fG=b[0].pageY;2==b.length&&(a.preventDefault(),this.FK=b[1].pageX,this.vQ=b[1].pageY,20>window.Math.abs(this.fG-this.vQ)?this.WN=0:this.vQ=this.FK=this.fG=this.EK=D.o)};
D.x.dea=function(a){a.preventDefault();a=a.touches;if(this.FK!=D.o&&this.vQ!=D.o)50>this.WN?this.WN++:(this.taa(D.o,a[1].pageX-this.FK,0),this.FK=a[1].pageX,this.WN=0);else{var b=window.Math.abs(this.fG-a[0].pageY);if(3<window.Math.abs(this.EK-a[0].pageX)||3<b)this.fG=this.EK=D.o}};D.x.wT=function(a){this.FK!=D.o&&this.vQ!=D.o?this.i$():this.EK!=D.o&&this.fG!=D.o&&this.KD(a,this.EK,this.fG);this.vQ=this.FK=this.fG=this.EK=D.o};
D.x.HM=function(a){var b=a.keyCode;if(37===b||39===b)b=37===b?-1:1,(a.shiftKey?this.taa:this.Wqa).call(this,a,b,b)};D.x.f1=function(a){var b=a.keyCode;if(37===b||39===b)b=37===b?-1:1,(a.shiftKey?this.i$:this.gpa).call(this,b,b)};D.x.Wqa=function(a,b,c){(0,D.NP)(this,"scrollPos",b,c)};D.x.gpa=function(a,b){(0,D.NP)(this,"scrollEnd",a,b)};
D.NP=function(a,b,c,d){var e=a.na(1),f=(0,D.oP)(a,e),g=(0,D.HP)(a,e),h=a.Ms,j=(0,D.iP)(a);c=a.Oc()?d:c;f+c<=h?((0,D.kP)(a,e,h),g=a.Rb()?-2:-1):f+g+c>=j?((0,D.kP)(a,e,j-g),g=a.Rb()?-1:-2):((0,D.kP)(a,e,f+c),g=a.Rb()?(j-g-f-a.Ms)*a.lJ:(f-a.Ms)*a.lJ);(0,D.mP)(a);b=new D.JP(b);b.Mi(g);a.Rb()?(g=a.pg(a.fb-(f+(0,D.HP)(a,e))),e=a.pg(a.fb-f)):(g=a.pg(f),e=a.pg(f+(0,D.HP)(a,e)));(0,D.KP)(b,g);(0,D.LP)(b,e);a.dispatchEvent(b)};D.Gp.prototype.taa=function(a,b,c){(0,D.MP)(this,a,b,c,D.p)};
D.MP=function(a,b,c,d,e){var f=(0,D.uP)(a);d=a.Oc()?d:c;if(0!=d){c=a.na(1);var g=(0,D.oP)(a,c),h=(0,D.HP)(a,c);if(e){if(h-d<=(0,D.jP)(a)||g+d<=a.Ms)return;b=a.Oc()?(0,D.qv)(a.j(),(0,D.yP)(b),(0,D.zP)(b)).y:(0,D.qv)(a.j(),(0,D.yP)(b),(0,D.zP)(b)).x;b=a.oc(b);if(0<d&&b<=g||0>d&&b>=g)return;(0,D.kP)(a,c,g+d);(0,D.lP)(a,c,h-d)}else{if(h+d<=(0,D.jP)(a)||g+h+d>=(0,D.iP)(a))return;b=a.Oc()?(0,D.qv)(a.j(),(0,D.yP)(b),(0,D.zP)(b)).y:(0,D.qv)(a.j(),(0,D.yP)(b),(0,D.zP)(b)).x;b=a.oc(b);if(0<d&&b<=g+h||0>d&&
b>=g+h)return;(0,D.lP)(a,c,h+d)}(0,D.mP)(a);b=a.pg((0,D.HP)(a,c));b=f*(a.Yb-a.rb)/(b-a.rb);f=new D.JP("rangeChanging");(0,D.Km)(f,"newSize",b);b=a.Rb()?e:!e;(0,D.Km)(f,"endHandle",b);e?(0,D.Km)(f,"expand",0>d):(0,D.Km)(f,"expand",0<d);a.Rb()?(e=a.pg(a.fb-((0,D.oP)(a,c)+(0,D.HP)(a,c))),c=a.pg(a.fb-(0,D.oP)(a,c))):(e=a.pg((0,D.oP)(a,c)),c=a.pg((0,D.oP)(a,c)+(0,D.HP)(a,c)));(0,D.KP)(f,e);(0,D.LP)(f,c);a.dispatchEvent(f)}};
D.Gp.prototype.i$=function(){var a=this.rb,b=this.Yb,c=this.Ja,d=(0,D.uP)(this),e=this.na(1),f=this.pg((0,D.HP)(this,e)),a=d*(b-a)/(f-a),b=this.pg(this.u7),d=this.pg(this.l7);this.Rb()?(f=this.pg(this.fb-((0,D.oP)(this,e)+(0,D.HP)(this,e))),e=this.pg(this.fb-(0,D.oP)(this,e))):(f=this.pg((0,D.oP)(this,e)),e=this.pg((0,D.oP)(this,e)+(0,D.HP)(this,e)));var g=new D.JP("rangeChange");(0,D.Km)(g,"oldSize",c);(0,D.Km)(g,"newSize",a);(0,D.Km)(g,"oldStartTime",b);(0,D.Km)(g,"oldEndTime",d);(0,D.KP)(g,f);
(0,D.LP)(g,e);this.dispatchEvent(g)};D.mP=function(a){var b=a.na(1),c=(0,D.oP)(a,b),d=c+0.5,b=c+(0,D.HP)(a,b)-0.5,e=a.na(a.Ma()-a.aq),f=(0,D.DP)(a),g=a.na(a.Ma()-(a.aq-2)),h=a.na(a.Ma()-(a.aq-3)),j=a.na(a.Ma()-(a.aq-4)),l=a.na(a.Ma()-(a.aq-5));(0,D.EP)(a,e,d,d);(0,D.EP)(a,f,b,b);(0,D.EP)(a,g,-1,c);(0,D.EP)(a,h,(0,D.FP)(a,f),-1);(0,D.EP)(a,j,(0,D.FP)(a,e),(0,D.FP)(a,f));(0,D.EP)(a,l,(0,D.FP)(a,e),(0,D.FP)(a,f))};D.Gp.prototype.dispatchEvent=function(a){D.LC.dispatchEvent(this.nb,this.ta,this,a)};
D.Gp.prototype.aa=function(){D.hP.Hl()?(this.ib(D.Ye.eg,this.yT,D.p,this),this.ib(D.Ye.rk,this.dea,D.p,this),this.ib(D.Ye.Pi,this.wT,D.p,this),this.ib(D.$e,this.KD,D.p,this)):(this.ib(D.af,this.tT,D.p,this),this.ib(D.bf,this.sT,D.p,this),this.ib(D.$e,this.KD,D.p,this),this.ib(D.qk,this.HM,D.p,this),this.ib(D.rk,this.f1,D.p,this));D.Gp.u.aa.call(this)};
D.wP=function(a){this.Init(a)};D.y.q(D.wP,D.y,"DvtOverviewParser");D.wP.prototype.Init=(0,D.v)("N");D.wP.prototype.parse=function(a){return this.$x(a)};
D.wP.prototype.$x=function(a){var b={};b.uoa=a.animationOnClick;a.startTime!=D.o&&(b.start=a.startTime);a.endTime!=D.o&&(b.end=a.endTime);b.start==D.o&&(b.start=(new window.Date).getTime());if(b.end==D.o||b.end<=b.start)b.end=b.start+864E5;a.currentTime!=D.o&&(b.currentTime=a.currentTime);a.initialFocusTime!=D.o&&(b.OJa=a.initialFocusTime);b.orientation="horizontal";a.orientation!=D.o&&(b.orientation=a.orientation);b.dpa=a.featuresOff;b.dba=a.minimumWindowSize;b.vKa=a.leftMargin;b.wLa=a.rightMargin;
if(a.viewportEndTime!=D.o){var c=a.viewportEndTime,d=b.start;a.viewportStartTime!=D.o&&a.viewportStartTime<c&&(d=a.viewportStartTime);b.width=a.viewportEndPos!=D.o?(0,D.OP)(b.start,b.end,d,c,a.viewportEndPos):(0,D.OP)(b.start,b.end,d,c,this.N.fb);b.Hba=d}else b.Hba=b.start;0==b.width&&(b.width=1E3);b.Sra="below";b.sS="none";b.Laa=(0,D.F)(this.N.j()).toString();a.rtl!=D.o&&(b.Laa=a.rtl.toString());b.saa="#FFFFFF";b.uaa="#B3C6DB";b.ica="#FFFFFF";b.Asa=1;b.qca="solid";b.oca="solid";b.kca="solid";b.mca=
"solid";b.pca="#4F4F4F";b.nca="#4F4F4F";b.jca="#4F4F4F";b.lca="#4F4F4F";b.kba="#E6ECF3";b.W9="#C000D1";b.bca="#BCC7D2";b.tsa="#e5e5e5";b.usa=1;b.sra="#FFFFFF";b.rra=0.7;b.hsa="#FFFFFF";b.gsa=0.7;a.style!=D.o&&(a.style.handleFillColor!=D.o&&(b.saa=a.style.handleFillColor),a.style.handleTextureColor!=D.o&&(b.uaa=a.style.handleTextureColor),a.style.handleBackgroundImage!=D.o&&(b.Jqa=a.style.handleBackgroundImage),a.style.handleWidth!=D.o&&(b.Vqa=a.style.handleWidth),a.style.handleHeight!=D.o&&(b.Sqa=
a.style.handleHeight),a.style.windowBackgroundColor!=D.o&&(b.ica=a.style.windowBackgroundColor),a.style.windowBackgroundAlpha!=D.o&&(b.Asa=a.style.windowBackgroundAlpha),a.style.windowBorderTopStyle!=D.o&&(b.qca=a.style.windowBorderTopStyle),a.style.windowBorderRightStyle!=D.o&&(b.oca=a.style.windowBorderRightStyle),a.style.windowBorderBottomStyle!=D.o&&(b.kca=a.style.windowBorderBottomStyle),a.style.windowBorderLeftStyle!=D.o&&(b.mca=a.style.windowBorderLeftStyle),a.style.windowBorderTopColor!=D.o&&
(b.pca=a.style.windowBorderTopColor),a.style.windowBorderRightColor!=D.o&&(b.nca=a.style.windowBorderRightColor),a.style.windowBorderBottomColor!=D.o&&(b.jca=a.style.windowBorderBottomColor),a.style.windowBorderLeftColor!=D.o&&(b.lca=a.style.windowBorderLeftColor),a.style.overviewBackgroundColor!=D.o&&(b.kba=a.style.overviewBackgroundColor),a.style.currentTimeIndicatorColor!=D.o&&(b.W9=a.style.currentTimeIndicatorColor),a.style.timeIndicatorColor!=D.o&&(b.bca=a.style.timeIndicatorColor),a.style.leftFilterPanelColor!=
D.o&&(b.sra=a.style.leftFilterPanelColor),a.style.leftFilterPanelAlpha!=D.o&&(b.rra=a.style.leftFilterPanelAlpha),a.style.rightFilterPanelColor!=D.o&&(b.hsa=a.style.rightFilterPanelColor),a.style.rightFilterPanelAlpha!=D.o&&(b.gsa=a.style.rightFilterPanelAlpha));return b};D.OP=function(a,b,c,d,e){a=e*(b-a);c=d-c;return 0==a||0==c?0:a/c};
D.JP=function(a){this.Init("overview");this.bm=a};D.y.q(D.JP,D.$j,"DvtOverviewEvent");D.JP.prototype.oj=(0,D.w)("bm");D.JP.prototype.setTime=function(a){(0,D.Km)(this,"time",a)};D.JP.prototype.getTime=function(){return this.Ii("time")};D.KP=function(a,b){(0,D.Km)(a,"newStartTime",b)};D.LP=function(a,b){(0,D.Km)(a,"newEndTime",b)};D.JP.prototype.Mi=function(a){(0,D.Km)(this,"pos",a)};D.JP.prototype.$f=function(){return this.Ii("pos")};
D.gP=function(a){this.Init(a.j(),a.ze,a);this.sc=a};D.y.q(D.gP,D.Xk,"DvtOverviewEventManager");D.x=D.gP.prototype;D.x.Ne=function(a){D.gP.u.Ne.call(this,a);D.wn.BQ(this.sc,this.GF,this.FF,this.EF,this)};D.x.GF=function(a){return(0,D.Ze)()?this.CP(a):this.zP(a)};D.x.FF=function(a){return(0,D.Ze)()?this.BP(a):this.yP(a)};D.x.EF=function(a){return(0,D.Ze)()?this.AP(a):this.xP(a)};D.x.ug=function(a,b){this.fi||(this.fi=(0,D.yn)(this.Y));return new D.H(a-this.fi.x,b-this.fi.y)};
D.x.zP=function(a){if(2!=a.button){var b=this.ug(a.pageX,a.pageY);(0,D.ji)(a);this.j().Uc.fy.parentNode.focus();return this.sc.EQ(a,b.x,b.y)}return D.p};D.x.yP=function(a){var b=this.ug(a.pageX,a.pageY);a.stopPropagation();this.sc.FQ(a,b.x,b.y);return D.k};D.x.xP=function(a){a.stopPropagation();this.sc.ZK();this.fi=D.o};D.x.CP=function(a){var b=a.touches;a.stopPropagation();return 1==b.length?(b=this.ug(b[0].pageX,b[0].pageY),a.preventDefault(),this.sc.EQ(a,b.x,b.y)):D.p};
D.x.BP=function(a){var b=a.touches;1==b.length&&(b=this.ug(b[0].pageX,b[0].pageY),this.sc.FQ(a,b.x,b.y),a.preventDefault());a.stopPropagation()};D.x.AP=function(a){this.sc.ZK();(0,D.ji)(a);this.fi=D.o};
  return D;
});