/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.bR=(0,D.s)();D.y.q(D.bR,D.y,"DvtAttrGroups");D.bR.prototype.get=(0,D.s)();
D.dR=function(){this.ZP=[]};D.y.q(D.dR,D.bR,"DvtDiscreteAttrGroups");D.dR.prototype.add=function(a,b,c){this.ZP.push({group:a,dJa:b,lba:c})};D.dR.prototype.get=function(a){if(a===D.o)return D.o;for(var b=0;b<this.ZP.length;b++)if(this.ZP[b].group==a)return this.ZP[b].lba;return D.o};
D.cR=function(a,b,c,d,e){this.Aj=a;this.Zj=b;this.QBa=c?c:this.Aj;this.JBa=d?d:this.Zj;this.aK=e;this.Pma=this.Zj-this.Aj};D.y.q(D.cR,D.bR,"DvtContinuousAttrGroups");D.cR.prototype.get=function(a){if((0,window.isNaN)(a)||a===D.o)return D.o;a=0<this.Pma?(a-this.Aj)/this.Pma:0.5;a=window.Math.max(window.Math.min(a,1),0);a*=this.aK.length-1;return a===window.Math.round(a)?this.aK[a]:D.J.DL(this.aK[window.Math.floor(a)],this.aK[window.Math.ceil(a)],a-window.Math.floor(a))};D.cR.prototype.kR=(0,D.w)("QBa");
D.eR=(0,D.s)();D.y.q(D.eR,D.y,"DvtLegendAttrGroupsRenderer");D.eR.jwa=0.4;D.eR.Pfa=1;D.eR.Rfa=50;D.eR.Qfa=10;D.eR.E2=5;D.eR.hwa=11;D.eR.ega="#636363";D.eR.$Ma="#333333";D.eR.Bba=function(a,b,c,d,e,f,g){var h=D.o;f&&(f instanceof D.cR?h=D.eR.aDa(a,b,c,d,f,g):f instanceof D.dR&&(h=D.eR.bDa(a,c,d,e,f,g)));return h};
D.eR.aDa=function(a,b,c,d,e,f){var g=(0,D.F)(a),h=D.eR.Qfa/2+D.eR.Pfa,j=new D.C(a);c.k(j);c=e.kR();var l=new D.lg(a,c,0,h);l.Na(f.eA);l.Xf();j.k(l);var m=new D.D(a,0,D.eR.Pfa,D.eR.Rfa,D.eR.Qfa),n=g?e.aK.slice(0).slice().reverse():e.aK.slice(0);m.O(new D.Ug(0,n));f.borderColor&&m.Ya(f.borderColor);j.k(m);n=D.eR.Rfa+D.eR.E2;e=e.JBa;a=new D.lg(a,e,0,h);a.Na(f.eA);a.Xf();j.k(a);g?(f=a.Lb().e+D.eR.E2,m.K(f),l.ja(f+n)):(f=l.Lb().e+D.eR.E2,m.K(f),a.ja(f+n));b.Ba(m,new D.Ok(c+" - "+e));j.I().e>d&&(j.removeChild(l),
j.removeChild(a),m.K(0));return j};D.eR.bDa=function(a,b,c,d,e,f){var g=new D.C(a);b.k(g);b=[];e=e.ZP.slice(0);for(var h=0;h<e.length;h++){var j=e[h];b.push({text:j.dJa,color:j.lba.color,pattern:j.lba.pattern,borderColor:f.borderColor})}f={sections:[{items:b}],orientation:"horizontal",layout:{outerGapWidth:0,outerGapHeight:0},textStyle:f.eA.toString()};b=(0,D.Ko)(a);b.setId(D.o);g.k(b);d=b.uq(f,c,d*D.eR.jwa);b.U(f,c,d.g);c=b.jv();a=new D.D(a,0,0,c.e,d.g);(0,D.Aj)(a);g.Ua(a,0);return g};
D.Jt=function(a){this.Init("breadcrumbsDrill");this.jb=a};D.y.q(D.Jt,D.$j,"DvtBreadcrumbsDrillEvent");D.Jt.prototype.getId=(0,D.w)("jb");
D.Ws=function(a,b,c,d){this.Init(a,b,c,d)};D.y.q(D.Ws,D.C,"DvtBreadcrumbs");D.x=D.Ws.prototype;D.x.Init=function(a,b,c,d){D.Ws.u.Init.call(this,a);this.Yba(d);this.Xa=new D.fR(this,a,b,c);this.Xa.Ne(this);this.setId("breadcrumbs1000"+window.Math.floor(1E9*window.Math.random()));this.tB=-1;this.yV=this.t6=D.o};D.x.Yba=function(a){this.Ae=D.gR.ej(a)};D.x.U=function(a,b){this.va=a?D.vm.ia(a):this.va;this.Sk();this.yV=D.o;D.hR.U(this,this,b)};D.x.lj=(0,D.w)("Xa");
D.x.qc=function(){var a=this.tB;this.tB=-1;this.Ez(a,this.tB)};D.x.Ez=function(a,b){var c=this.t6,d=D.o,e=(0,D.yu)(this,b);if(e){var f=this.Xa.za(e);f&&f.jm&&f.jm()?(d=this.j(),f=e.I(),e=e.Da(),this.t6=d=new D.zh(d,this,f,e)):this.t6=D.o}c&&c.mn();d&&d.show()};D.yu=function(a,b){var c=a.yV;return 0>b||!c||b>=c.length?D.o:c[b]};D.wu=function(a,b){for(var c=a.yV,d=0;d<c.length;d++)if(c[d]==b)return d};
D.gR={};D.y.q(D.gR,D.y,"DvtBreadcrumbsDefaults");D.gR.v2={labelStyle:"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #003286;",disabledLabelStyle:"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px;",iU:2,rxa:"\x3e"};D.gR.ej=function(a){var b=D.gR.yO(a);return a?D.vm.Dd(a,b):b};D.gR.yO=function(){return D.vm.ia(D.gR.v2)};D.gR.J$=function(a,b){return window.Math.ceil(b*a.layout.gapRatio)};
D.fR=function(a,b,c,d){this.Init(b,c,d);this.Jm=a};D.y.q(D.fR,D.Xk,"DvtBreadcrumbsEventManager");D.fR.prototype.Wg=function(a){D.fR.u.Wg.call(this,a);(0,D.iR)(this,this.za(a.target))};D.fR.prototype.Rt=function(a){(0,D.iR)(this,this.za(a.target))};D.iR=function(a,b){if(b&&b instanceof D.jR&&b.jm()){var c=new D.Jt(b.getId());a.gh(c,a.Jm)}};
D.fR.prototype.Ct=function(a){var b=D.k,c=a.keyCode;if(9==c){var c=this.Jm,d=c.tB,e;e=d;var f=!a.shiftKey;e=-1==e?f?0:c.va.Dx.length-2:f?e==c.va.Dx.length-2?-1:++e:0==e?-1:--e;c.tB=e;c.Ez(d,c.tB);c=c.tB;-1==c?b=D.p:this.fw((0,D.yu)(this.Jm,c))}else 13==c&&(0,D.iR)(this,this.za((0,D.yu)(this.Jm,this.Jm.tB)));b&&(0,D.ji)(a);return b};
D.jR=function(a,b){this.Init();this.jb=a;this.yN=D.p;this.jh=b};D.y.q(D.jR,D.Ok,"DvtBreadcrumbsPeer");D.jR.prototype.getId=(0,D.w)("jb");D.jR.prototype.jm=(0,D.w)("yN");D.jR.prototype.Vba=(0,D.v)("yN");D.jR.prototype.ya=(0,D.w)("jh");
D.hR={};D.y.q(D.hR,D.y,"DvtBreadcrumbsRenderer");D.hR.ZA=3;D.hR.U=function(a,b,c){for(var d=a.j(),e=(a.va?a.va:{}).Dx?(a.va?a.va:{}).Dx:[],f=a.Ae,g=a.lj(),h=[],j=[],l=0;l<e.length;l++){var m=e[l];if(m){var n=D.hR.BE(d,m.label?m.label:"",f,l<e.length-1);h.push(n);m=new D.jR(m.id,n);g.Ba(n,m);j.push(m);l<e.length-1&&m.Vba(D.k)}}a.yV=h;(0,D.F)(d)?D.hR.KCa(a,b,c,h,j):D.hR.JCa(a,b,c,h,j)};
D.hR.sV=function(a,b,c){b=new D.lg(a,b,0,0);b.ua(D.p);b.Na(c);var d=(0,D.wf)(c,"padding-top"),e=(0,D.wf)(c,"padding-right"),f=(0,D.wf)(c,"padding-bottom"),g=(0,D.wf)(c,"padding-left"),h=(0,D.fh)(a,b);a=new D.D(a,0,0,h.e+g+e,h.g+d+f);(0,D.Aj)(a);a.Na(c);(0,D.N)(b,g,d);a.k(b);return a};
D.hR.BE=function(a,b,c,d){if(d&&(c.i_||c.h_)){var e=new D.I(c.eA);d=new D.I(c.i_);c=new D.I(c.h_);e=D.hR.sV(a,b,e);d=D.hR.sV(a,b,d);c=D.hR.sV(a,b,c);a=new D.ef(a,e,d,c);a.xd("link");a.Wb("label",b)}else d=new D.I(d?c.eA:c.b$),(0,D.wf)(d,"padding-left")||(0,D.wf)(d,"padding-right")||(0,D.wf)(d,"padding-top")||(0,D.wf)(d,"padding-bottom")?a=D.hR.sV(a,b,d):(a=new D.lg(a,b,0,0),a.Na(d));return a};D.hR.lja=function(a){if(a instanceof D.ef)return a=a.Il.na(0),a.bf();a instanceof D.D&&(a=a.na(0));return a.bf()};
D.hR.ioa=function(a,b){if(a instanceof D.ef){var c=a.Il.na(0);D.yf.wc(c,window.Math.max(b-c.V(),0),window.Infinity,c.getParent());c=a.qj.na(0);D.yf.wc(c,window.Math.max(b-c.V(),0),window.Infinity,c.getParent());c=a.Ei.na(0);D.yf.wc(c,window.Math.max(b-c.V(),0),window.Infinity,c.getParent())}else a instanceof D.D?(c=a.na(0),D.yf.wc(c,window.Math.max(b-c.V(),0),window.Infinity,c.getParent())):D.yf.wc(a,b,window.Infinity,a.getParent())};
D.hR.JCa=function(a,b,c,d,e){for(var f=a.Ae,g=a.lj(),h=[],j=0,l=0;l<d.length;l++){b.k(d[l]);var m=d[l].I();h[l]=m;j=window.Math.max(m.g,j);b.removeChild(d[l])}for(var n=0,l=0;l<d.length;l++){b.k(d[l]);m=h[l];(0,D.N)(d[l],n,0.5*(j-m.g));if((0,D.Ze)()){var q=new D.D(b.j(),-D.hR.ZA,-D.hR.ZA,m.e+2*D.hR.ZA,m.g+2*D.hR.ZA);(0,D.Aj)(q);d[l].k(q);l<e.length&&g.Ba(q,e[l])}if(n+m.e>c){a=D.hR.lja(d[l]);D.hR.ioa(d[l],c-n);l<e.length?e[l].Pv(a):g.Ba(d[l],new D.Ok(a));break}else n+=m.e+f.iU;if(l<d.length-1){m=D.hR.zla(a);
b.k(m);q=m.I();(0,D.N)(m,n,0.5*(j-q.g));q=q.e;if(n+q>c){b.removeChild(m);break}n+=q+f.iU}}};
D.hR.KCa=function(a,b,c,d,e){for(var f=a.Ae,g=a.lj(),h=0;h<d.length;h++){b.k(d[h]);var j=d[h].I();if((0,D.Ze)()){var l=new D.D(b.j(),-D.hR.ZA,-D.hR.ZA,j.e+2*D.hR.ZA,j.g+2*D.hR.ZA);(0,D.Aj)(l);d[h].k(l);h<e.length&&g.Ba(l,e[h])}if(0>c-j.e){a=D.hR.lja(d[h]);D.hR.ioa(d[h],c);d[h].K(0);h<e.length?e[h].Pv(a):g.Ba(d[h],new D.Ok(a));break}else d[h].K(c-j.e),c-=j.e+f.iU;if(h<d.length-1)if(j=D.hR.zla(a),b.k(j),l=j.I().e,0>c-l){b.removeChild(j);break}else j.K(c-l),c-=l+f.iU}};
D.hR.zla=function(a){var b=a.Ae;a=new D.lg(a.j(),b.rxa,0,0);a.Na(new D.I(b.eA));return a};
D.qR=function(a,b){this.Init("dvtPanelDrawerEvent");this.bm=a;this.wxa=b};D.y.q(D.qR,D.$j,"DvtPanelDrawerEvent");D.qR.prototype.oj=(0,D.w)("bm");
D.ws=function(a,b,c,d){this.Init(a,b,c,d)};D.y.q(D.ws,D.C,"DvtPanelDrawer");
D.ws.prototype.Init=function(a,b,c,d){D.ws.u.Init.call(this,a,D.o,"panelDrawer"+d);this.jEa=d;this.xa=new D.kR(a,b,c);this.xa.Ne(this);this.xa.Ru.push(D.ws);this.xa.Ba(this,this);(0,D.Ze)()||(0,D.Yl)(this.xa,new D.lR(this.xa,this));this.nb=b;this.ta=c;this.ax={};this.wr=[];this.xi=this.Fh=window.Number.MAX_VALUE;this.qr=5;this.hP=0;this.mO;this.kz;this.Np=this.ri=D.p;this.ga;this.iI;this.Lf;this.l4;this.zj;this.Vj;this.Un={};this.vu="left";this.xB="top";this.cz=D.p;this.ba=D.o;c&&(this.ba=c.Jr());
this.Sl=(0,D.Ku)(this.ba,"backgroundAlpha",1);this.us=(0,D.Ku)(this.ba,"border-color","#bbc7d0");this.wj=(0,window.parseInt)((0,D.Ku)(this.ba,"border-radius",2));this.By=(0,D.Ku)(this.ba,"background-color","#ffffff");this.iha=(0,D.Ku)(this.ba,"tab-color-inactive","#dee4e7");this.jha=(0,D.Ku)(this.ba,"tab-border-color-inactive","#c1cede");(0,D.Ij)(this);this.Zq=10};D.As=function(a,b,c,d,e,f,g){a.ax[g]={panel:b,iconUp:c,iconOver:d,iconDown:e,tooltip:f};a.wr.push(g);a.hP=15+42*a.wr.length};D.x=D.ws.prototype;
D.x.Jv=(0,D.v)("Fh");D.x.uZ=function(){return this.Fh-2*this.Zq};D.x.U_=(0,D.v)("xi");D.x.jR=function(){return this.xi-2*this.Zq};D.x.EM=function(a){return this.ax[a].icon};D.Js=function(a,b,c,d){a.kz=a.mO;a.mO=b;a.mb()&&(a.oM(),(0,D.mR)(a,b,c,d));a.kz=D.o};D.vs=function(a){var b=a.mO;return!b&&0<a.wr.length?a.wr[0]:b};
D.ws.prototype.ef=function(a,b,c){if(!this.Np){var d=this.ri;this.ri=a;if(d!=a)if(this.Np=D.k,a){(0,D.nR)(this,(0,D.vs)(this));a=-(0.8*this.Lf.getWidth());"right"==this.vu&&(a=-a,this.Lf.ja((0.8-1)*this.Lf.getWidth()));if(b)this.ga.K(a),c&&c(),this.Np=D.p;else if(b=new D.ms(this.j(),0.25),b.Dl(D.xD),(0,D.S)(b,"typeNumber",this.ga,this.ga.V,this.ga.K,a),c&&(0,D.im)(b,c),b){var e=this;(0,D.im)(b,function(){e.Np=D.p});b.play()}this.oM()}else if(b)this.ga.K(0),this.Xea(),c&&c(),this.oM(),this.Np=D.p;
else{b=new D.ms(this.j(),0.25);b.Dl(D.zD);(0,D.S)(b,"typeNumber",this.ga,this.ga.V,this.ga.K,0);(0,D.im)(b,this.Xea,this);(0,D.im)(b,this.oM,this);c&&(0,D.im)(b,c);var f=this;(0,D.im)(b,function(){f.Np=D.p});b.play()}}};D.ws.prototype.mb=(0,D.w)("ri");
D.ws.prototype.Hq=function(){this.ga||(this.ga=new D.C(this.j(),"pd_contentPane"),this.k(this.ga),this.iI=new D.C(this.j(),"pdcp_activeContent"),this.ga.k(this.iI));if(!this.cz){var a=-42;"right"==this.vu&&(a=0);var b=15;if("top"==this.xB)for(var c=0;c<this.wr.length;c++){var d=this.wr[c],d=(0,D.oR)(this,d);(0,D.N)(d,a,b);b+=42}else if("bottom"==this.xB){b=-57;for(c=this.wr.length-1;0<=c;c--)d=this.wr[c],d=(0,D.oR)(this,d),(0,D.N)(d,a,b),b-=42}}};
D.oR=function(a,b){var c,d;switch(a.vu){case "right":d=["M",0,0,"L",42-a.wj,0,"A",a.wj,a.wj,0,0,1,42,a.wj,"L",42,42-a.wj,"A",a.wj,a.wj,0,0,1,42-a.wj,42,"L",0,42];break;default:d=["M",42,0,"L",a.wj,0,"A",a.wj,a.wj,0,0,0,0,a.wj,"L",0,42-a.wj,"A",a.wj,a.wj,0,0,0,a.wj,42,"L",42,42]}c=d;d=new D.pR(a.j(),c,b,a);(0,D.Ij)(d);d.setCursor("pointer");a.ga.Ua(d,0);d.ra(a.iha,a.Sl);d.Ya(a.jha,1,1);var e=a.ax[b],f=new D.Ei(a.j(),c);(0,D.Aj)(f);(0,D.N)(e.iconUp,9,9);f.k(e.iconUp);var g=new D.Ei(a.j(),c);(0,D.Aj)(g);
(0,D.N)(e.iconOver,9,9);g.k(e.iconOver);c=new D.Ei(a.j(),c);(0,D.Aj)(c);(0,D.N)(e.iconDown,9,9);c.k(e.iconDown);f=new D.ef(a.j(),f,g,c);f.tE=D.k;e.icon=f;d.k(f);a.Un[b]=d;a.xa.Ba(d,{Fe:function(){a.kz=(0,D.vs)(a);a.mO=b;var c=a.Un[b].Nc(),d=function(){var b=a.j().qd();b&&b.Vc()};a.mb()?a.kz==b?a.ef(D.p,D.p,d):(a.oM(),(0,D.mR)(a,b,D.p)):(a.ef(D.k,D.p,d),a.yD());a.kz=D.o;a.uc(new D.qR(a.mb()?"show":"hide",a.mO));c&&(0,D.Dn)(a.j(),a)},ce:function(){return a.ax[b].tooltip}});d.mq();return d};
D.mR=function(a,b,c,d){var e=D.o;c||(e=new D.ms(a.j(),0.25));a.kz&&(c=a.ax[a.kz].panel)&&a.As.removeChild(c);(0,D.nR)(a,b,e);e?(a.yD(),d&&(0,D.im)(e,d),e.play()):d&&d()};D.ws.prototype.Xea=function(){this.Lf&&(this.l4=D.o,this.As.Sk(),(0,D.hA)(this.iI),this.Lf.aa(),this.iI.removeChild(this.Lf),this.Vj=this.zj=this.As=this.Lf=D.o)};
D.nR=function(a,b,c){a.Lf||(a.Lf=new D.D(a.j(),0,0,1,1,"pdcp_expandedContent"),a.iI.k(a.Lf),a.Lf.ra(a.By,a.Sl),a.As=new D.C(a.Y),a.Lf.k(a.As),(0,D.N)(a.As,a.Zq,a.Zq));var d=a.ax[b].panel;if(d){a.As.k(d);if(a.kz){var e=a.ax[a.kz].panel;e&&e.ib("dvtResizeEvent",a.Vda,D.p,a)}d.oa("dvtResizeEvent",a.Vda,D.p,a)}a.zj||(a.zj=new D.Ei(a.j(),["M",0,0,"L",1,1],"pdcp_expandedBorder"),a.Vj=new D.Ei(a.j(),["M",0,0,"L",1,1],"pdcp_expandedBorderResizable"),a.Lf.k(a.zj),a.Lf.k(a.Vj),a.zj.Ya(a.us,1),a.zj.O(D.o),a.Vj.Ya(a.us,
1),a.Vj.O(D.o),(0,D.Ij)(a.zj),(0,D.Ij)(a.Vj));var f=a.ax[b].panel,d=2*a.Zq,e=2*a.Zq,g=0,h=0;f&&(f=f.gm(),d=(0,D.rR)(a,f.e),e=(0,D.Ks)(a,f.g),g=f.x,h=f.y);(0,D.sR)(a,b,c,d,e,g,h)};D.ws.prototype.Vda=function(a){var b=new D.ms(this.j(),0.25),c=a.getWidth(),d=a.getHeight(),c=(0,D.rR)(this,c),d=(0,D.Ks)(this,d),e=a.pa()?a.pa():0;a=a.qa()?a.qa():0;(0,D.sR)(this,(0,D.vs)(this),b,c,d,e,a);b.play()};
D.sR=function(a,b,c,d,e,f,g){var h=a.ax[b].panel;c?(0,D.S)(c,"typeNumber",h,h.V,h.K,-f):h.K(-f);c?(0,D.S)(c,"typeNumber",h,h.Q,h.W,-g):h.W(-g);f=new D.B(a.Zq,a.Zq,d-2*a.Zq,e-2*a.Zq);g=1.25*d;c?((0,D.S)(c,"typeNumber",a.Lf,a.Lf.getWidth,a.Lf.sa,g),(0,D.S)(c,"typeNumber",a.Lf,a.Lf.getHeight,a.Lf.Ia,e),(0,D.S)(c,"typeRectangle",a,a.dAa,a.xna,f),"left"==a.vu?(0,D.S)(c,"typeNumber",a.ga,a.ga.V,a.ga.K,-d):"right"==a.vu&&((0,D.S)(c,"typeNumber",a.ga,a.ga.V,a.ga.K,d),(0,D.S)(c,"typeNumber",a.zj,a.zj.V,a.zj.K,
d),(0,D.S)(c,"typeNumber",a.Vj,a.Vj.V,a.Vj.K,d),(0,D.S)(c,"typeNumber",a.Lf,a.Lf.V,a.Lf.K,-d)),"bottom"==a.xB&&((0,D.S)(c,"typeNumber",a.zj,a.zj.Q,a.zj.W,e),(0,D.S)(c,"typeNumber",a.Vj,a.Vj.Q,a.Vj.W,e),(0,D.S)(c,"typeNumber",a.Lf,a.Lf.Q,a.Lf.W,-e))):(a.Lf.sa(g),a.Lf.Ia(e),"right"==a.vu&&(a.Lf.K(-d),a.zj.K(d),a.Vj.K(d)),"bottom"==a.xB&&(a.Lf.W(-e),a.zj.W(e),a.Vj.W(e)),a.xna(f));f=a.Un[b];var j;b=d;"right"==a.vu&&(b=-d);"top"==a.xB?f?(j=["M",0,0,"L",0,f.Q(),"M",0,f.Q()+42],d=a.Un[a.wr[a.wr.length-1]],
j.push("L",0,d.Q()+42),a.zj.po(j),j=["M",0,d.Q()+42,"L",0,e,"L",1.25*b,e]):(j=["M",0,0,"L",0,e,"L",b,e],a.zj.po(j)):"bottom"==a.xB&&(f?(j=["M",0,0,"L",0,f.Q()+42,"M",0,f.Q()],d=a.Un[a.wr[0]],j.push("L",0,d.Q()),a.zj.po(j),b*=1.25,j=["M",0,d.Q(),"L",0,-e,"L",b,-e]):(j=["M",0,0,"L",0,-e,"L",b,-e],a.zj.po(j)));c?(0,D.S)(c,"typePath",a.Vj,a.Vj.sG,a.Vj.po,j):a.Vj.po(j)};
D.ws.prototype.xna=function(a){if(this.As&&a){var b=new D.ih("pdcp"+this.jEa);(0,D.kh)(b,a.x,a.y,a.e,a.g);(0,D.lh)(this.As,b)}this.l4=a};D.ws.prototype.dAa=(0,D.w)("l4");D.rR=function(a,b){var c=b+2*a.Zq;if((a.qr||0==a.qr)&&c<a.qr)c=a.qr;a.Fh&&c>a.Fh&&(c=a.Fh);return c};D.Ks=function(a,b){var c=b+2*a.Zq;if((a.hP||0==a.hP)&&c<a.hP)c=a.hP;a.xi&&c>a.xi&&(c=a.xi);return c};D.tR=function(a,b){if(a.Lf){var c=a.Lf.kc().ia();c.F(b);a.Lf.O(c)}for(var d in a.Un){var e=a.Un[d];e&&(c=e.kc().ia(),c.F(b),e.O(c))}};
D.uR=function(a){if(a.zj){var b=a.zj.Cc().ia();b.F(1);a.zj.ea(b)}a.Vj&&(b=a.Vj.Cc().ia(),b.F(1),a.Vj.ea(b));for(var c in a.Un){var d=a.Un[c];d&&(b=d.Cc().ia(),b.F(1),d.ea(b))}};D.x=D.ws.prototype;D.x.Y9=function(){this.ua(D.p);(0,D.tR)(this,1);(0,D.uR)(this);this.As&&this.As.F(1);for(var a in this.Un){var b=this.EM(a);b&&b.F(1)}};D.x.X9=function(){this.ua(D.k);(0,D.tR)(this,this.Sl);(0,D.uR)(this);this.As&&this.As.F(1);for(var a in this.Un){var b=this.EM(a);b&&b.F(1)}this.xn(D.o)};D.x.so=function(){this.yD()};
D.x.xn=function(){this.oE||this.b0()};D.x.yD=function(){(0,D.tR)(this,1)};D.x.b0=function(){(0,D.tR)(this,this.Sl)};D.x.oM=function(){for(var a in this.Un){var b=this.Un[a];b&&(a==(0,D.vs)(this)&&this.mb()?(b.ra(this.By,this.Sl),b.Ya(this.us,1),b.ef(D.k)):(b.ra(this.iha,this.Sl),b.Ya(this.jha,1),b.ef(D.p)));var c=this.mb()&&a==(0,D.vs)(this),d=this.EM(a);d&&(0,D.ki)(d,c);c?this.iI.k(b):this.ga.Ua(b,0)}};D.ys=function(a,b){if(!a.W6||a.W6<b)a.W6=b};
D.ws.prototype.I=function(a){a=D.ws.u.I.call(this,a);a.e/=1.25;return a};D.ws.prototype.lj=(0,D.w)("xa");
D.pR=function(a,b,c,d){this.Init(a,b,c,d)};D.y.q(D.pR,D.Ei,"DvtPanelDrawerTab");D.x=D.pR.prototype;D.x.Init=function(a,b,c,d){D.pR.u.Init.call(this,a,b,"pdcp_tab_"+c);this.Bb=d;this.aF=D.p;this.DCa=c};D.x.Mj=function(a){var b=a.keyCode;if(13==b||32==b){var b=this.Bb.lj(),c=(0,D.Df)(this,new D.H(0,0));a=D.Ef.aL(a,b.Y,c.x,c.y);a.target=this;b.SD(a)}};D.x.mb=(0,D.w)("aF");D.x.ef=function(a){this.aF!=a?(this.aF=a,this.eca()):this.aF=a};
D.x.mc=function(){var a=[];a.push(this.mb()?(0,D.M)("DvtUtilBundle","STATE_EXPANDED"):(0,D.M)("DvtUtilBundle","STATE_COLLAPSED"));return(0,D.ql)(this.Bb.ax[this.DCa].tooltip,a)};D.x.mq=function(){this.xd("button");(0,D.Cf)()||this.Wb("label",this.mc())};D.x.eca=function(){(0,D.Cf)()||this.Wb("label",this.mc())};D.x.Ze=function(a){return this.I(a)};D.x.Ej=function(){return this.Fa()};D.x.ke=function(){this.Ub=D.k;this.Zi||this.vV();this.Zi.show();(0,D.yh)(this.Y,this)};
D.x.qc=function(){this.Ub=D.p;this.Zi||this.vV();this.Zi.mn()};D.x.Nc=(0,D.w)("Ub");D.x.Td=function(a){return this.Bb.lj().yh.Td(this,a)};D.x.vV=function(){var a=this.I();this.Zi=new D.zh(this.j(),this,new D.B(a.x+1,a.y+1,a.e-2,a.g-2),D.o,D.o,D.k)};
D.kR=function(a,b,c){this.Init(a,b,c)};D.y.q(D.kR,D.Xk,"DvtPanelDrawerEventManager");D.x=D.kR.prototype;D.x.Wg=function(a){var b=this.za((0,D.Bn)(a));D.kR.u.Wg.call(this,a);b&&(b.Fe&&b.Fe(a),a.stopPropagation())};D.x.uo=function(a){D.kR.u.uo.call(this,a);var b=this.za((0,D.Bn)(a));b&&(b.Ji&&(b.Ji()&&b.Cp)&&b.Cp(a),a.stopPropagation())};D.x.Zx=function(a){D.kR.u.Zx.call(this,a);var b=this.za((0,D.Bn)(a));b&&b.so&&b.so(a)};
D.x.Yx=function(a){D.kR.u.Yx.call(this,a);var b=this.za((0,D.Bn)(a));b&&b.xn&&b.xn(a)};D.x.JA=function(a){var b=this.za((0,D.Bn)(a));D.kR.u.JA.call(this,a);b&&(b.Fe&&b.Fe(a),a.stopPropagation())};
D.lR=function(a,b){this.Init(a,b)};D.y.q(D.lR,D.On,"DvtPanelDrawerKeyboardHandler");D.lR.prototype.Init=function(a,b){D.lR.u.Init.call(this,a);this.Bb=b};D.lR.prototype.Gj=function(a){var b=a.keyCode,c=this.xa.Jd();return 9==b?(b=D.o,(0,D.ji)(a),b=c?c:this.Bb.Un[this.Bb.wr[0]]):13==b||32==b?(c.Mj(a),D.o):D.lR.u.Gj.call(this,a)};
D.lR.prototype.Td=function(a,b){if(!(40==b.keyCode||38==b.keyCode))return a;for(var c=a,d=40==b.keyCode?D.k:D.p,e=this.Bb.wr,f=-1,g=0;g<e.length;g++)if(a==this.Bb.Un[e[g]]){f=d?g==e.length-1?-1:g+1:0==g?-1:g-1;break}0<=f&&(c=this.Bb.Un[e[f]]);return c};
D.SA=function(a,b,c,d,e,f,g){this.Init(a,b,c,d,e,f,g)};D.y.q(D.SA,D.C,"DvtAccordion");D.SA.prototype.Init=function(a,b,c,d,e,f,g){D.SA.u.Init.call(this,a,D.o,b);this.Tm=f;this.ba=(new D.MQ).ej(g);this.UX={};this.Wu=[];this.Fh=c;this.qr=0;this.xi=d;this.CU=this.o3=D.p;this.xa=e};D.XA=function(a,b,c,d,e){e||(e="accordion_"+b.replace(/ /g,"_")+window.Math.floor(1E9*window.Math.random()));b=new D.cB(a.j(),c,b,d,D.k,a,a.xa,e,a.Tm,a.ba);a.UX[e]=b;a.Wu.push(e);a.k(b)};
D.SA.prototype.U=function(){for(var a=(0,D.YA)(this),b=D.p,c=0;c<this.Wu.length;c++){var d=(0,D.NQ)(this,c);d.U(a);b&&!this.CU&&d.setActive(D.p);d.jr&&d.$E&&(b=D.k)}!b&&(0<this.Wu.length&&!this.o3)&&(0,D.NQ)(this,0).setActive(D.k);(0,D.OQ)(this)};D.SA.prototype.U_=(0,D.v)("xi");D.SA.prototype.Jv=(0,D.v)("Fh");
D.SA.prototype.update=function(a){a=this.UX[a];var b=a.jr;if(b){if(b)if(a.$E)if(this.o3)b=D.k;else{for(var c=0,d=0;d<this.Wu.length;d++)b=(0,D.NQ)(this,d),b.jr&&c++;b=1<c}else b=D.p;b&&a.setActive(D.p)}else{if(!this.CU)for(b=0;b<this.Wu.length;b++)(0,D.NQ)(this,b).setActive(D.p);a.setActive(D.k)}(0,D.OQ)(this)};
D.YA=function(a){if(!a.kla){for(var b=0,c=a.ba.paddingX,d=0;d<a.Wu.length;d++){var e=(0,D.NQ)(a,d),f;f=e;if(!f.BK){var g=new D.lg(f.Y,f.Bi);g.Na(f.Yna);if(g=g.Lb())g.e=g.e+f.Xja+f.sEa;f.BK=g}f=f.BK;f.e>b&&(b=f.e);e=e.jv().e+2*c;e>b&&(b=e)}b=window.Math.min(b,a.Fh);b=window.Math.max(b,a.qr);a.kla=b}return a.kla};
D.SA.prototype.I$=function(){if(!this.xi){for(var a=0,b=0,c=0;c<this.Wu.length;c++){var d=(0,D.NQ)(this,c),e=d,f=D.o;0>e.Pf(e.ah)?(e.k(e.ah),e.ah.K(e.qX),e.ah.W(e.VE+e.rX),f=e.gm(),e.removeChild(e.ah)):f=e.gm();e=f.g;if(d.$E&&e>a)a=e;else if(!d.$E||this.CU)b+=e}this.xi=a+b}return this.xi};D.NQ=function(a,b){return 0<=b&&b<a.Wu.length?a.UX[a.Wu[b]]:D.o};
D.OQ=function(a){for(var b=0,c=0;c<a.Wu.length;c++){var d=(0,D.NQ)(a,c);d.W(b);d.jr?(d.expand(),b+=d.gm().g,b+=a.ba.paddingY):(d.collapse(),b+=a.ba.sectionHeader.headerHeight)}b=a.gm();a.uc(new D.oC(b.e,b.g,0,0))};D.SA.prototype.FZ=function(){for(var a=[],b=0;b<this.Wu.length;b++)a.push((0,D.NQ)(this,b));return a};
D.cB=function(a,b,c,d,e,f,g,h,j,l){this.Init(a,b,c,d,e,f,g,h,j,l)};D.y.q(D.cB,D.C,"DvtAccordionSection");D.x=D.cB.prototype;
D.x.Init=function(a,b,c,d,e,f,g,h,j,l){D.cB.u.Init.call(this,a,D.o,h);this.lg=f;this.Tm=j;this.Bi=c;this.jb=h;this.ah=b;this.pu=this.xu=D.o;this.jr=(this.$E=e)?d:D.k;this.xa=g;this.ba=l;this.VE=this.ba.sectionHeader.headerHeight;this.qX=this.ba.paddingX;this.rX=this.ba.paddingY;this.Yna=this.ba.sectionHeader.styleEna;this.Xja=this.ba.sectionHeader.imageWidth;this.gBa=this.ba.sectionHeader.imageHeight;this.sEa=this.ba.sectionHeader.textPadding};D.x.getId=(0,D.w)("jb");D.x.rv=(0,D.w)("Bi");
D.x.setActive=(0,D.v)("jr");D.x.jv=function(){var a=D.o;0>this.Pf(this.ah)?(this.k(this.ah),a=this.ah.I(),this.removeChild(this.ah)):a=this.ah.I();return a};
D.x.U=function(a){var b=this.VE;if(this.$E){var c,d,e;this.Tm.B?(c=(0,D.RQ)(this,0,this.Tm.B("sectionExpEna"),this.Bi,a,b),d=(0,D.RQ)(this,1,this.Tm.B("sectionExpOvr"),this.Bi,a,b),e=(0,D.RQ)(this,2,this.Tm.B("sectionExpDwn"),this.Bi,a,b)):(c=(0,D.RQ)(this,0,this.Tm.sectionExpEna,this.Bi,a,b),d=(0,D.RQ)(this,1,this.Tm.sectionExpOvr,this.Bi,a,b),e=(0,D.RQ)(this,2,this.Tm.sectionExpDwn,this.Bi,a,b));this.xu=new D.ef(this.Y,c,d,e);this.xu.xd("button");c=(0,D.ql)(this.Bi,[(0,D.M)("DvtUtilBundle","STATE_EXPANDED")]);
this.xu.Wb("label",c);this.Tm.B?(c=(0,D.RQ)(this,0,this.Tm.B("sectionColEna"),this.Bi,a,b),d=(0,D.RQ)(this,1,this.Tm.B("sectionColOvr"),this.Bi,a,b),e=(0,D.RQ)(this,2,this.Tm.B("sectionColDwn"),this.Bi,a,b)):(c=(0,D.RQ)(this,0,this.Tm.sectionColEna,this.Bi,a,b),d=(0,D.RQ)(this,1,this.Tm.sectionColOvr,this.Bi,a,b),e=(0,D.RQ)(this,2,this.Tm.sectionColDwn,this.Bi,a,b));this.pu=new D.ef(this.Y,c,d,e);this.pu.xd("button");c=(0,D.ql)(this.Bi,[(0,D.M)("DvtUtilBundle","STATE_COLLAPSED")]);this.pu.Wb("label",
c);this.xa.Ba(this.xu,this);this.xa.Ba(this.pu,this)}else a=(0,D.SQ)(this,3,a,b),b=(0,D.TQ)(this,this.Bi),this.M5=new D.C(this.Y),this.M5.k(a),this.M5.k(b);this.$E?this.jr?(this.Ua(this.xu,0),this.k(this.ah),this.ah.K(this.qX),this.ah.W(this.VE+this.rX)):this.k(this.pu):(this.Ua(this.M5,0),this.k(this.ah),this.ah.K(this.qX),this.ah.W(this.VE+this.rX))};
D.x.collapse=function(){this.$E&&(0<=this.Pf(this.xu)&&this.removeChild(this.xu),0<=this.Pf(this.ah)&&this.removeChild(this.ah),this.k(this.pu),this.setActive(D.p),this.Nc()&&this.ke())};D.x.expand=function(){0<=this.Pf(this.pu)&&this.removeChild(this.pu);this.k(this.xu);this.k(this.ah);this.ah.K(this.qX);this.ah.W(this.VE+this.rX);this.setActive(D.k);this.Nc()&&this.ke()};
D.RQ=function(a,b,c,d,e,f){var g=a.Xja,h=a.gBa,j=(a.VE-h)/2,l=new D.C(a.Y);b=(0,D.SQ)(a,b,e,f);l.k(b);(c=c?new D.sf(a.Y,c,0,j,g,h):D.o)&&l.k(c);d=(0,D.TQ)(a,d,e-g-0,f,l);(0,D.F)(a.Y)?(f=d.Lb(),d.K(e-f.e-g),c&&c.K(e-g)):d.K(g);a.Zi||a.vV(c?c:d);return l};D.TQ=function(a,b,c,d,e){var f=D.o;if(b){f=new D.lg(a.Y,b);f.Na(a.Yna);D.yf.wc(f,c,d,e);b=f.Lb();if(!a.BK||a.BK.e<b.e||a.BK.g<b.g)a.BK=b;f.W((a.VE-b.g)/2)}return f};
D.SQ=function(a,b,c,d){var e=D.o;switch(b){case 1:e=a.ba.sectionHeader.styleOvr;break;case 2:e=a.ba.sectionHeader.styleDwn;break;case 3:e=a.ba.sectionHeader.styleDis;break;default:e=a.ba.sectionHeader.styleEna}a=new D.D(a.Y,0,0,c,d);a.ea((0,D.UQ)(e));a.O((0,D.VQ)(e));return a};D.VQ=function(a){var b=a.D("background-color");a=(0,D.Tg)(a);var c=D.o;if(a&&a instanceof D.Le){var b=a.Ql,c=a.Pl,d=a.ny;a=a.em();c=new D.Ug(a,b,c,d)}else b&&(c=new D.Mo(b,1));return c};
D.UQ=function(a){a=a.D("border-color");return new D.Wg(a,1,1)};D.x=D.cB.prototype;D.x.Ze=function(){var a=this.jr?this.xu:this.pu,b=a.I(),c=(0,D.Df)(a,new D.H(b.x,b.y)),a=(0,D.Df)(a,new D.H(b.x+b.e,b.y+b.g));return new D.B(c.x,c.y,a.x-c.x,a.y-c.y)};D.x.Ej=function(){return(this.jr?this.xu:this.pu).Fa()};D.x.ke=function(){this.Ub=D.k;this.Zi.show();(0,D.yh)(this.Y,this.jr?this.xu:this.pu)};D.x.qc=function(){this.Ub=D.p;this.Zi.mn()};D.x.Nc=(0,D.w)("Ub");
D.x.Td=function(a){return this.xa.yh.Td(this,a)};D.x.vV=function(a){var b=a.I(),c=a.V()||b.x;a=a.Q()||b.y;this.Zi=new D.zh(this.j(),this,new D.B(c,a,b.e,b.g),D.o,D.o,D.k)};
D.MQ=function(){this.Init({skyros:D.PQ,alta:D.QQ})};D.y.q(D.MQ,D.Vk,"DvtAccordionDefaults");
D.PQ={skin:"alta",sectionHeader:{styleEna:new D.I("font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:bold;color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),styleOvr:new D.I("font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:bold;color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),styleDwn:new D.I("font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:bold;color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),styleDis:new D.I("font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:14px;font-weight:bold;color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),
headerHeight:33,imageWidth:24,imageHeight:24,textPadding:5},paddingX:0,paddingY:0};D.QQ={};
D.jj=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};D.y.q(D.jj,D.C,"DvtTrain");D.jj.prototype.Init=function(a,b,c,d,e,f){D.jj.u.Init.call(this,a,D.o,e);this.pQ=a.qd();this.Yl=c;this.jB=d;this.qV=c.length;this.Cy=(0,window.Array)(this.qV);this.gq=0;this.lBa=f;this.UD(b)};D.jj.prototype.ES=function(a){0<=a&&a<this.qV&&(0,D.ZQ)(this,this.gq,a)};
D.jj.prototype.Fe=function(a){(0,D.ji)(a);for(var b=0;b<this.Cy.length;b++){var c=a.target;if(this.Cy[b]===c||this.Cy[b]===c.getParent()){a=this.gq;(0,D.ZQ)(this,a,b);a!=b&&(b=new D.$Q(this.gq),this.uc(b,D.p));break}}};D.ZQ=function(a,b,c){a.gq=c;if(b=a.Cy[b])b.qj&&b.qj.setCursor("pointer"),b.Ei&&b.Ei.setCursor("pointer"),(0,D.ki)(b,D.p);if(b=a.Cy[c])b.qj&&b.qj.setCursor("default"),b.Ei&&b.Ei.setCursor("default"),(0,D.ki)(b,D.k)};
D.jj.prototype.UD=function(a){var b=(0,D.F)(this.j()),c;if(!this.XU){if(this.jB&&(c=this.jB[0]))this.XU=(0,D.Dr)(c.getWidth());this.XU||(this.XU=8)}c=this.XU;for(var d=0;d<this.qV;d++){var e,f=e=this.Tv(c,d==this.gq,this.Yl[d]);f.oa(D.Ye.eg,this.Fe,D.p,this);(0,D.Ze)()||f.oa(D.$e,this.Fe,D.p,this);f=d;b&&(f=this.qV-1-d);a&&a.Ba(e,e);(0,D.N)(e,f*(c+3),this.lBa?0:1);this.k(e);this.Cy[d]=e}};D.jj.prototype.Zr=function(a,b){return new D.sf(this.j(),a,0,0,b,b)};
D.aR=function(a,b,c,d){var e=a.jB?a.jB[c]:D.o;if(e=e?e.D("content"):D.o)a=a.Zr(e,b);else{var f,g,h;2==c?(h=0,g="#61bde3",e="#0066ff",a.jB&&(f=a.jB[2])):(h=1,g="#c0cbd5",e="#5d7891",a.jB&&(f=a.jB[0]));f&&(f.D("border-color")&&(e=f.D("border-color")),f.D("background-color")&&(g=f.D("background-color")));a=new D.D(a.j(),h,h,b-2*h,b-2*h);a.ra(g);a.Ya(e)}a.setCursor(0==c||d?"default":"pointer");return a};
D.jj.prototype.Tv=function(a,b,c){a=new D.ef(this.j(),(0,D.aR)(this,a,0,b),(0,D.aR)(this,a,1,b),(0,D.aR)(this,a,2,b),D.o);a.Pv(c);a.tE=D.k;b&&(0,D.ki)(a,b);return a};
D.$Q=function(a){this.Init("dvtTrain");this.type=this.$a();this.Mn=a};(0,D.ca)("DvtTrainEvent",D.$Q);D.y.q(D.$Q,D.$j,"DvtTrainEvent");D.$Q.TYPE="dvtTrain";D.$Q.prototype.Ra=(0,D.w)("Mn");D.$Q.prototype.getIndex=D.$Q.prototype.Ra;
D.DvtOverviewWindow=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};D.y.q(D.DvtOverviewWindow,D.C,"DvtOverviewWindow");D.DvtOverviewWindow.w2="viewport-bg-color";D.DvtOverviewWindow.z2="viewport-border-color";D.DvtOverviewWindow.Eea="isOverviewDisclosed";D.x=D.DvtOverviewWindow.prototype;D.x.Init=function(a,b,c,d,e,f){D.DvtOverviewWindow.u.Init.call(this,a,D.o,b);this.Db=c;this.Zb=d;this.hi=e;this.wi=f;this.nC=D.o};
D.x.U=function(){this.fP=D.p;this.G7=D.k;this.sc&&((0,D.Ze)()?(this.sc.ib(D.Ye.eg,this.YW,D.p,this),this.sc.ib(D.Ye.rk,this.ZW,D.p,this),this.sc.ib(D.Ye.Pi,this.kP,D.p,this)):(this.sc.ib(D.cf,this.YW,D.p,this),this.sc.ib(D.Wr,this.ZW,D.p,this),this.sc.ib(D.df,this.kP,D.p,this),this.sc.ib(D.bf,this.ula,D.p,this)),(0,D.lh)(this.sc,D.o));this.Sk();this.sc=this.Be=D.o;var a=new D.ih(this.getId());(0,D.kh)(a,0,0,this.hi,this.wi);this.sc=new D.D(this.Y,0,0,this.hi,this.wi);(0,D.lh)(this.sc,a);(0,D.Aj)(this.sc);
this.k(this.sc);this.Be=new D.D(this.Y,0,0,0,0,this.getId()+":viewport");a=this.JG(D.DvtOverviewWindow.w2);this.Be.Ya(this.JG(D.DvtOverviewWindow.z2),D.o,2);this.Be.ra(a);this.Be.ua(D.p);this.sc.k(this.Be);(0,D.Ze)()?(this.sc.oa(D.Ye.eg,this.YW,D.p,this),this.sc.oa(D.Ye.rk,this.ZW,D.p,this),this.sc.oa(D.Ye.Pi,this.kP,D.p,this)):(this.sc.oa(D.cf,this.YW,D.p,this),this.sc.oa(D.Wr,this.ZW,D.p,this),this.sc.oa(D.df,this.kP,D.p,this),this.sc.oa(D.bf,this.ula,D.p,this))};D.x.mb=(0,D.w)("aF");D.x.ef=(0,D.v)("aF");
D.x.jv=function(){return new D.B(this.Db,this.Zb,this.hi,this.wi)};D.Is=function(a,b,c){var d=(0,D.WQ)(a,b.x,b.y,c),e=(0,D.WQ)(a,b.x+b.e,b.y+b.g,c);b=d.x;var f=d.y,g=e.x-d.x,d=e.y-d.y;c?((0,D.S)(c,"typeNumber",a.Be,a.Be.pa,a.Be.ja,b),(0,D.S)(c,"typeNumber",a.Be,a.Be.qa,a.Be.Ea,f),(0,D.S)(c,"typeNumber",a.Be,a.Be.getWidth,a.Be.sa,g),(0,D.S)(c,"typeNumber",a.Be,a.Be.getHeight,a.Be.Ia,d)):(a.Be.ja(b),a.Be.Ea(f),a.Be.sa(g),a.Be.Ia(d))};
D.Ss=function(a){var b=(0,D.XQ)(a,a.Be.pa(),a.Be.qa());a=(0,D.XQ)(a,a.Be.pa()+a.Be.getWidth(),a.Be.qa()+a.Be.getHeight());return new D.B(b.x,b.y,a.x-b.x,a.y-b.y)};D.x=D.DvtOverviewWindow.prototype;D.x.YW=function(a){if(!this.fP&&this.G7){this.fP=D.k;var b=this.ug(a);a=new D.pF((0,D.Ss)(this),(0,D.YQ)(this,b),a);this.uc(a)}};D.x.ZW=function(a){if(this.fP&&this.G7){var b=this.ug(a);a=new D.pF((0,D.Ss)(this),(0,D.YQ)(this,b),a);this.uc(a)}};D.x.kP=function(){this.fP&&this.G7&&(this.fP=D.p)};
D.x.ula=function(){this.kP()};D.x.ug=function(a){var b,c;(0,D.Ze)()?(a=a.touches,0<a.length&&(b=a[0].pageX,c=a[0].pageY)):(b=a.pageX,c=a.pageY);return(0,D.qv)(this.Y,b,c)};D.XQ=function(a,b,c){var d=0,e=0,f=1,g=1;a.uk&&(d=a.uk.V(),e=a.uk.Q(),f=a.uk.Jc(),g=a.uk.Kc());return new D.H((b-d)/f,(c-e)/g)};
D.WQ=function(a,b,c,d){var e=0,f=0,g=1,h=1;a.uk&&(e=d?(0,D.Bq)(d,a.uk,a.uk.V,D.k):a.uk.V(),f=d?(0,D.Bq)(d,a.uk,a.uk.Q,D.k):a.uk.Q(),g=d?(0,D.Bq)(d,a.uk,a.uk.Jc,D.k):a.uk.Jc(),h=d?(0,D.Bq)(d,a.uk,a.uk.Kc,D.k):a.uk.Kc());return new D.H(b*g+e,c*h+f)};D.DvtOverviewWindow.prototype.vL=(0,D.w)("nC");D.DvtOverviewWindow.prototype.pH=(0,D.v)("nC");D.DvtOverviewWindow.prototype.JG=function(a){return this.nC&&"undefined"!=this.nC[a]?this.nC[a]:D.o};
D.YQ=function(a,b){var c=(0,D.Df)(a.sc,new D.H(0,0)),d=a.Be.I(),e=b.x-c.x-d.e/2,f=b.y-c.y-d.g/2,c=(0,D.XQ)(a,e,f),d=(0,D.XQ)(a,e+d.e,f+d.g);return new D.B(c.x,c.y,d.x-c.x,d.y-c.y)};D.DvtOverviewWindow.prototype.lfa=function(a){this.Be.ja(a.x);this.Be.Ea(a.y);this.Be.sa(a.e);this.Be.Ia(a.g)};D.DvtOverviewWindow.prototype.Z0=function(){return new D.B(this.Be.pa(),this.Be.qa(),this.Be.getWidth(),this.Be.getHeight())};
D.DvtOverviewWindow.prototype.I=function(a){var b=new D.B(0,0,this.hi,this.wi);return!a||a===this?b:(0,D.Fh)(this,b,a)};D.DvtOverviewWindow.prototype.gm=function(a){return this.I(a)};
(0,D.Bh)("DvtSubcomponentBundle",{CONTROL_PANEL:"Control Panel",CONTROL_PANEL_ZOOMANDCENTER:"Zoom and Center",CONTROL_PANEL_PAN:"Pan",CONTROL_PANEL_LAYOUT:"Layout",CONTROL_PANEL_LAYOUT_VERT_TOP:"Vertical, Top Down",CONTROL_PANEL_LAYOUT_VERT_BOTTOM:"Vertical, Bottom Up",CONTROL_PANEL_LAYOUT_HORIZ_START:"Horizontal, Start-to-End",CONTROL_PANEL_LAYOUT_HORIZ_LEFT:"Horizontal, Left-to-Right",CONTROL_PANEL_LAYOUT_HORIZ_RIGHT:"Horizontal, Right-to-Left",CONTROL_PANEL_LAYOUT_RADIAL:"Radial",CONTROL_PANEL_LAYOUT_TREE:"Tree",
CONTROL_PANEL_LAYOUT_CIRCLE:"Circle",CONTROL_PANEL_SYNC:"View",CONTROL_PANEL_ZOOMTOFIT:"Zoom to Fit",CONTROL_PANEL_ZOOMIN:"Zoom In",CONTROL_PANEL_ZOOMOUT:"Zoom Out",CONTROL_PANEL_RESET:"Reset Map",CONTROL_PANEL_DRILLUP:"Drill Up",CONTROL_PANEL_DRILLDOWN:"Drill Down",LEGEND:"Legend",OVERVIEW:"Overview",PALETTE:"Palette",SEARCH:"Search",SEARCH_TEXT:"Search",SEARCH_TEXT_ALTA:"Find",SEARCH_RESULTS:"Search Results [{0}]",SEARCH_RESULTS_ALTA:"{0} Results",SEARCH_RESULTS_CLOSE:"Close",SEARCH_RESULTS_NO_DATA:"No results to display"});
  return D;
});