/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){function d(a,c,d,f,h,k){this.oc=a;this.kba=c;this.Eq=d;this.gy=f;h&&(h.Uga&&(this.Bba=h.Uga),h.Kga&&(this.dba=h.Kga),h.WZ&&(this.Cba=h.WZ),h.KZ&&(this.eba=h.KZ),h.VZ&&(this.Aba=h.VZ),h.JZ&&(this.cba=h.JZ));k&&(k.i_&&(this.wV=k.i_),k.Hfa&&(this.tF=k.Hfa),k.bfa&&(this.fo=k.bfa),k.fh&&(this.$x=k.fh),k.cj&&(this.pA=k.cj));this.ey=!0;this.Qq=0;a=navigator.userAgent.toLowerCase();if(-1!==a.indexOf("gecko/"))this.l4=!0;else if(-1!==a.indexOf("opera"))this.m4=
!0;else if(-1!==a.indexOf("applewebkit")||-1!==a.indexOf("safari"))this.n4=!0}d.prototype.Hl=function(a){var c=this;if(a){this.A5();this.R5(this.Bba,this.Cba,this.Aba);this.C5(this.dba,this.eba,this.cba);var e=this.Hi,f=this.GA;f?(this.jy=f.offsetWidth,this.iy=e.offsetHeight):(f=this.YA,this.jy=e.offsetWidth,this.iy=f.offsetHeight);this.Dz();this.Cz();this.av=function(a){c.P9(a)};d.$e(this.oc,"mousewheel",this.av);d.$e(this.oc,"wheel",this.av);this.AI=function(a){c.IG(a)};d.$e(this.Nd,"touchstart",
this.AI);this.yI=function(a){c.HG(a)};d.$e(this.Nd,"touchmove",this.yI);this.Lv=function(a){c.EG(a)};d.$e(this.Nd,"touchend",this.Lv);d.$e(this.Nd,"touchcancel",this.Lv);this.sH=0}else this.SU();this.xE();this.nO(a);this.Mf(!0);a&&this.$x&&(this.vg=function(){c.Mf(!1)},this.$x.call(this.fo,this.oc,this.vg),this.$x.call(this.fo,this.nm,this.vg))};d.prototype.destroy=function(){var a=this.oc;d.Pd(a,"mousewheel",this.av);d.Pd(a,"wheel",this.av);d.Pd(this.Nd,"touchstart",this.AI);d.Pd(this.Nd,"touchmove",
this.yI);d.Pd(this.Nd,"touchend",this.Lv);d.Pd(this.Nd,"touchcancel",this.Lv);this.Lv=this.yI=this.AI=this.av=null;this.pA&&this.vg&&(this.pA.call(this.fo,a,this.vg),this.pA.call(this.fo,this.nm,this.vg));this.vg=null;d.Fca(this.CE,a);this.vO=null;this.tI?a.removeChild(this.tI):(a.removeChild(this.Nd),a.removeChild(this.YA),a.removeChild(this.aJ));this.YA=this.aJ=this.nH=this.BH=this.GA=this.sI=this.tI=this.CE=this.Nd=this.nm=this.Ij=this.Hi=null;this.xE();this.Eq=this.fo=this.pA=this.$x=this.tF=
this.wV=this.oc=null};d.Gca=function(a,c,e){var f=null;e&&(f=d.ME(),c.appendChild(f));var h=null;for(a=a.childNodes;0<a.length;){h||(h=[]);var k=a[0];if(1===k.nodeType){e||(f=d.ME(),c.appendChild(f));var l=d.Ay();l.appendChild(k);f.appendChild(l);h.push(k)}else e?f.appendChild(k):c.appendChild(k)}return h};d.Fca=function(a,c){if(a)for(var d=a.childNodes;0<d.length;){var f=d[0];if(1===f.nodeType){for(var h=f.childNodes;0<h.length;){var k=h[0];1===k.nodeType?(c.appendChild(k.firstChild),f.removeChild(k)):
c.appendChild(k)}a.removeChild(f)}else c.appendChild(f)}};d.fu=function(a){var c=a.ownerDocument.defaultView,d=null;return d=c?c.getComputedStyle(a,null):a.currentStyle};d.L7=function(a){a=d.fu(a);return d.Kf(a.width)};d.K7=function(a){a=d.fu(a);return d.Kf(a.height)};d.Kf=function(a){return 0<a.length&&"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0};d.$e=function(a,c,d){a.addEventListener?a.addEventListener(c,d,!1):a.attachEvent&&a.attachEvent("on"+c,d)};d.Pd=function(a,c,d){a.removeEventListener?
a.removeEventListener(c,d,!1):a.detachEvent&&a.detachEvent("on"+c,d)};d.O8=function(a){var c=0;return c=null!=a.wheelDelta?a.wheelDelta:null!=a.deltaY?-a.deltaY:-a.detail};d.EP=function(){var a=document.createElement("div");a.style.display="table";return a};d.ME=function(){var a=document.createElement("div");a.style.display="table-row";return a};d.Ay=function(){var a=document.createElement("div");a.style.display="table-cell";return a};d.eX=function(a,c,d,f){var h=document.createElement("div"),k=h.style;
k.display="inline-block";h.appendChild(a);c.appendChild(h);d&&(k.maxWidth=h.offsetWidth+"px");f&&(k.maxHeight=h.offsetHeight+"px");return h};d.prototype.Fb=function(){return"horizontal"===this.kba};d.prototype.baa=function(){return!this.$Q().hasChildNodes()};d.prototype.SU=function(){this.sH=this.tg();this.gP();this.fI(0);this.Dz();this.Cz()};d.prototype.xE=function(){this.BA=this.Qd=null};d.prototype.Mf=function(a){a||this.SU();this.xE();this.Qd&&this.BA||(this.Qd=this.PT());a||this.nO(!1);a=this.Qd;
this.W3(a.Gc,a.Fg)};d.prototype.W3=function(a,c){var d=this.Hi.style,f=this.Ij.style;if(this.Fb()){var h=.5*(c-this.iy);d.top=h+"px";f.top=h+"px"}else h=.5*(a-this.jy),this.gy?(d.left=-h+"px",f.left=-h+"px"):(d.left=h+"px",f.left=h+"px")};d.prototype.nO=function(a){var c=this.nm,e=this.Fb(),f=e?d.L7(this.oc):d.K7(this.oc);(e?c.offsetWidth:c.offsetHeight)>f&&this.PV(f);this.Zu=0;this.Xu=e?c.offsetWidth-f+this.jy:c.offsetHeight-f+this.iy;0>this.Xu&&(this.Xu=0);this.Dz();this.Cz();this.Fr(a?this.Zu:
this.sH,!0);this.sH=0};d.prototype.A5=function(){var a=this,c=this.Fb(),e=document.createElement("div");this.Nd=e;var f=e.style;f.overflow="hidden";f.display=this.gu();f.position="relative";c&&(f.verticalAlign="top");var h=this.oc,k=document.createElement("div");this.nm=k;var l=k.style;l.position="relative";c&&(l.display="inline-block");e.appendChild(k);l=null;if(c){this.tI=l=d.EP();var m=d.ME(),n=d.Ay();this.sI=n;var q=d.Ay(),p=d.Ay();this.GA=p;var r=p.style;n.style.verticalAlign="top";r.verticalAlign=
"top";q.appendChild(e);m.appendChild(n);m.appendChild(q);m.appendChild(p);l.appendChild(m)}m=d.EP();n=d.Gca(h,m,c);if(this.Eq)for(n=[],q=this.Eq.children,p=q.length,r=0;r<p;r++){var t=q[r];1===t.nodeType&&n.push(t)}(this.vO=n)&&0<n.length&&(this.CE=m,k.appendChild(m));l?h.appendChild(l):(this.aJ=l=document.createElement("div"),this.YA=m=document.createElement("div"),h.appendChild(l),h.appendChild(e),h.appendChild(m));c&&(c=e.offsetHeight,k=k.offsetHeight,c>k&&(f.marginBottom=k-c+"px"));d.$e(e,"scroll",
function(){a.X9()})};d.prototype.gu=function(){return this.Fb()?"inline-block":"block"};d.prototype.R5=function(a,c,e){var f=this,h=document.createElement("div");this.Ij=h;a&&h.setAttribute("id",a);h.setAttribute("class",c);h.setAttribute("aria-hidden","true");a=h.style;a.display=this.gu();a.position="relative";if(c=this.Fb())a.verticalAlign="top";d.$e(h,"click",function(){f.yV()});this.sI?this.BH=d.eX(h,this.sI,c,!c):this.aJ.appendChild(h);e&&h.appendChild(e)};d.prototype.C5=function(a,c,e){var f=
this,h=document.createElement("div");this.Hi=h;a&&h.setAttribute("id",a);h.setAttribute("class",c);h.setAttribute("aria-hidden","true");a=h.style;a.display=this.gu();a.position="relative";if(c=this.Fb())a.verticalAlign="top";d.$e(h,"click",function(){f.xV()});this.GA?this.nH=d.eX(h,this.GA,c,!c):this.YA.appendChild(h);e&&h.appendChild(e)};d.prototype.$Q=function(){var a=this.Eq;a||(a=this.nm);return a};d.prototype.PT=function(){var a=this.CE,c=this.vO,d={Gc:0,Fg:0},f=[];if(this.$Q().hasChildNodes()&&
a&&c&&0<c.length)for(var a=this.Fb(),h=0,h=this.nm.offsetWidth,k=0,l=null,m=0;m<c.length;m++){var n=c[m];if(1===n.nodeType){var q=n.offsetWidth,p=n.offsetHeight,r={Gc:q,Fg:p,id:n.id};if(a){var t=n.offsetLeft;this.Eq||0!==t||(n=n.parentNode,t=n.offsetLeft);r.start=this.gy?h-(t+q):t;0===m&&(k=r.start);r.start-=k;d.Gc=r.start+q;d.Fg=Math.max(d.Fg,p);r.end=d.Gc-1}else t=n.offsetTop,this.Eq||0!==t||(n=n.parentNode,t=n.offsetTop),r.start=t,d.Gc=Math.max(d.Gc,q),d.Fg=r.start+p,r.end=d.Fg-1;l&&l.end>=r.start&&
(q=l.end-(r.start-1),l.end-=q,a?l.Gc-=q:l.Fg-=q);f.push(r);l=r}}this.BA=f;return d};d.prototype.Zq=function(){if(!this.BA){var a=this.PT();this.Qd||(this.Qd=a)}return this.BA};d.prototype.SF=function(){return this.nH?this.nH:this.Hi};d.prototype.YF=function(){return this.BH?this.BH:this.Ij};d.prototype.Ida=function(){this.SF().style.display=this.gu()};d.prototype.Jda=function(){this.YF().style.display=this.gu()};d.prototype.Cz=function(){this.SF().style.display="none"};d.prototype.Dz=function(){this.YF().style.display=
"none"};d.prototype.lr=function(){return"none"!==this.SF().style.display};d.prototype.Qu=function(){return"none"!==this.YF().style.display};d.prototype.yF=function(){return this.Fb()?this.jy:this.iy};d.prototype.sea=function(a){var c=this.yF(),d=this.tg(),f=this.Tq(),h=this.$z();a<=this.Zu?(this.Qu()&&(f+=c,d-=c),this.Dz()):h&&(this.Qu()||(f-=c,d+=c),this.Jda());a>=this.Xu?(this.lr()&&(f+=c),this.Cz()):h&&(this.lr()||(f-=c),this.Ida());this.fI(d);h?this.PV(f):this.gP()};d.prototype.PV=function(a){var c=
this.Nd.style;a+="px";this.Fb()?c.maxWidth=a:c.maxHeight=a};d.prototype.gP=function(){var a=this.Nd.style;this.Fb()?a.maxWidth="":a.maxHeight=""};d.prototype.fI=function(a){var c=this.Nd;this.Fb()?c.scrollLeft=this.FE(a):c.scrollTop=a};d.prototype.Tq=function(){var a=this.Nd;return this.Fb()?a.offsetWidth:a.offsetHeight};d.prototype.Fr=function(a,c){this.hm||(this.ey=!1,this.IV(a,c))};d.prototype.IV=function(a,c){if(!this.baa()){this.hm=!0;a=this.j5(a);this.sea(a);var e=this.wV;if(c||!e||a===this.tg())this.eU(this.ey?
this.tg():a);else{var f=this;e.call(this.fo,this.Nd,this.FE(a),Math.abs(this.tg()-a)/d.T2,function(){f.eU(a)})}}};d.prototype.tg=function(){var a=this.Nd;return this.Fb()?this.p5(a.scrollLeft):a.scrollTop};d.prototype.$z=function(){var a=this.nm,c=this.Nd;return this.Fb()?a.offsetWidth>c.offsetWidth:a.offsetHeight>c.offsetHeight};d.prototype.j5=function(a){!this.$z()||a<this.Zu?a=this.Zu:a>this.Xu&&(a=this.Xu);return a};d.prototype.P9=function(a){var c=this.hm;if(this.$z()&&!this.hm){var e=d.O8(a);
0>e&&this.lr()?(c=!0,this.xV()):0<e&&this.Qu()&&(c=!0,this.yV())}c&&(a.preventDefault(),a.stopPropagation())};d.prototype.IG=function(a){a=a.touches;this.$z()&&!this.hm&&1===a.length&&(this.xi=!0,a=a[0],this.LA=this.Fb()?a.pageX:a.pageY,this.BI=this.tg(),this.iea=this.NO(),this.jea=this.OO(),this.PW=this.lr(),this.QW=this.Qu())};d.prototype.HG=function(a){var c=this.Fb(),e=a.touches[0],e=(c?e.pageX:e.pageY)-this.LA,f=c&&this.gy?0<e:0>e,h=f&&this.PW||!f&&this.QW;if(this.xi&&h){h=this.Nd;if(Math.abs(e)<
d.i3*(c?h.offsetWidth:h.offsetHeight)){if(this.Fr(this.BI-e,!0),this.PW&&!this.lr()||this.QW&&!this.Qu())this.xi=!1}else this.Fr(f?this.iea:this.jea,!1),this.xi=!1;this.Dr=!0}this.Dr&&(a.preventDefault(),a.stopPropagation())};d.prototype.EG=function(){this.xi&&this.Fr(this.BI,!1);this.Dr=this.xi=!1};d.prototype.X9=function(){this.ey&&!this.hm&&this.IV(this.tg(),!0)};d.prototype.eU=function(a){this.fI(a);this.dda();this.hm=!1;if(this.tF){this.Qq=this.LO();a=this.MO();var c=this.Zq(),d=c[this.Qq];this.Qq!==
a&&this.tg()>d.start&&this.Qq<c.length-2&&(this.Qq++,d=c[this.Qq]);this.e7=d.id;this.tF.call(this.fo,this.e7)}};d.prototype.dda=function(){var a=this;window.setTimeout(function(){a&&(a.ey=!0)},0)};d.prototype.xV=function(){this.hm||this.Fr(this.NO(),!1)};d.prototype.yV=function(){this.hm||this.Fr(this.OO(),!1)};d.prototype.NO=function(){var a=this.G4(),c=0;return c=a===this.LO()?this.tg()+this.Tq():this.I4(a)};d.prototype.OO=function(){var a=this.H4(),c=0,c=a===this.MO()?this.tg()-this.Tq():this.F4(a);
this.lr()||(c+=this.yF());c<this.yF()&&(c=this.Zu);return c};d.prototype.I4=function(a){return this.Zq()[a].start};d.prototype.F4=function(a){return this.Zq()[a].end-this.Tq()+1};d.prototype.LO=function(){var a=this.ly(this.tg());return 0>a?0:a};d.prototype.MO=function(){var a=this.ly(this.tg()+this.Tq()-1),c=this.Zq();return 0>a?c.length-1:a};d.prototype.H4=function(){var a=this.ly(this.tg()-1);return 0>a?0:a};d.prototype.G4=function(){var a=this.ly(this.tg()+this.Tq()),c=this.Zq();return 0>a?c.length-
1:a};d.prototype.ly=function(a){for(var c=this.Zq(),d=0;d<c.length;d++)if(a<=c[d].end)return d;return-1};d.prototype.FE=function(a){var c=a;if(this.gy&&this.Fb())if(this.l4)c=-a;else if(this.n4||this.m4)c=this.nm.offsetWidth-this.Nd.offsetWidth-a;return c};d.prototype.p5=function(a){return this.FE(a)};d.T2=1.1;d.i3=.33;(function(){a.Da("oj.ojConveyorBelt",f.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{orientation:"horizontal",contentParent:null},_ComponentCreate:function(){this._super();
this.element.addClass("oj-conveyorbelt oj-component");this.options.disabled&&a.u.warn(b);this.za(!0)},refresh:function(){this._super();var a="rtl"===this.hc()!==this.cf;a&&this.VE();this.za(a)},tk:function(){this._super();this.Nc&&this.za(this.Nc[0])},Zl:function(){this._super();this.Nc&&this.za(this.Nc[0])},za:function(b){if(this.Mt()){this.Nc=null;this.cf="rtl"===this.hc();var e=this.element,g=this.options;if(b&&!this.ny){var h=g.orientation,k=null,l=null,m=null,n=null,q=null;"vertical"!==h?(k=
"oj-enabled oj-conveyorbelt-overflow-indicator oj-start oj-default",l="oj-enabled oj-conveyorbelt-overflow-indicator oj-end oj-default",m=this.xy("oj-conveyorbelt-overflow-icon oj-start"),n=this.xy("oj-conveyorbelt-overflow-icon oj-end"),q=this.a4):(k="oj-enabled oj-conveyorbelt-overflow-indicator oj-top oj-default",l="oj-enabled oj-conveyorbelt-overflow-indicator oj-bottom oj-default",m=this.xy("oj-conveyorbelt-overflow-icon oj-top"),n=this.xy("oj-conveyorbelt-overflow-icon oj-bottom"),q=this.b4);
var p={};p.WZ=k;p.KZ=l;p.VZ=m;p.JZ=n;k={};k.fh=a.C.fh;k.cj=a.C.cj;"enabled"!==a.ba.DJ()&&(k.i_=q);q=null;g.contentParent&&(q=f(g.contentParent)[0]);this.ny=new d(e[0],h,q,this.cf,p,k)}this.ny.Hl(b);b&&(b=e.find(".oj-conveyorbelt-overflow-indicator"),this.zda(b))}else e=!1,this.Nc&&(e=this.Nc[0]),this.Nc=[b||e]},_destroy:function(){this.VE();this.element.removeClass("oj-conveyorbelt oj-component");this._super()},_setOption:function(c,d,f){var h=!1;switch(c){case "containerParent":case "orientation":h=
!0;break;case "disabled":a.u.warn(b)}h&&this.VE();this._super(c,d,f);h&&this.za(!0)},VE:function(){var a=this.ny;a&&(this.element.find(".oj-conveyorbelt-overflow-indicator").off(this.eventNamespace),a.destroy());this.ny=null},Mt:function(){var a=document.createElement("div"),b=a.style;b.width="10px";b.height="10px";b=this.element[0];b.appendChild(a);var d=!1;try{d=0<a.offsetWidth&&0<a.offsetHeight}catch(f){}b.removeChild(a);return d},zda:function(a){a.on("mousedown"+this.eventNamespace,function(a){f(a.currentTarget).addClass("oj-active")}).on("mouseup"+
this.eventNamespace,function(a){f(a.currentTarget).removeClass("oj-active")}).on("mouseenter"+this.eventNamespace,function(a){a=a.currentTarget;f(a).addClass("oj-hover");f(a).removeClass("oj-default")}).on("mouseleave"+this.eventNamespace,function(a){a=a.currentTarget;f(a).removeClass("oj-hover");f(a).removeClass("oj-active");f(a).addClass("oj-default")})},xy:function(a){var b=document.createElement("span");b.setAttribute("class","oj-component-icon "+a);return b},a4:function(a,b,d,h){var k={};k.scrollLeft=
b;f(a).animate(k,d,"swing",h)},b4:function(a,b,d,h){var k={};k.scrollTop=b;f(a).animate(k,d,"swing",h)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-conveyorbelt-start-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-start")[0]:"oj-conveyorbelt-end-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-end")[0]:"oj-conveyorbelt-top-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-top")[0]:
"oj-conveyorbelt-bottom-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-bottom")[0]:null}});var b="JET ConveyorBelt: 'disabled' option not supported"})()});