/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","promise","ojs/ojdatacollection-common"],function(a,f){a.Wa=function(a,b){this.Init();this.ca=a;this.xg=b;this.Kp()};o_("Cube",a.Wa,a);a.b.ga(a.Wa,a.b,"oj.Cube");a.Wa.prototype.Init=function(){a.Wa.q.Init.call(this)};a.Wa.prototype.ml=function(){var a=this.JR(),b=[];Array.prototype.push.apply(b,a?a.ml():this.bf);for(a=2;a<this.bf.length;a++)b.push(this.bf[a]);return b};a.b.i("Cube.prototype.getAxes",{ml:a.Wa.prototype.ml});a.Wa.prototype.TF=function(){return this.bf};
a.Wa.prototype.sl=function(a){var b=this.JR();a=b.hba(a);for(a=b=b.dX(a,0,[]);Array.isArray(a)&&1===a.length;)if(a=a[0],!Array.isArray(a))return a;return b};a.b.i("Cube.prototype.getValues",{sl:a.Wa.prototype.sl});a.Wa.prototype.setPage=function(a){this.wH=a instanceof Array?a:[a]};a.Wa.prototype.TZ=function(d,b,c,e,g){var f=this.xg,k=this.FQ(d);if(!k)return!1;d=null;c<f.length?d=this.FQ(c):(d={axis:c,levels:[]},f.push(d));c=k.levels;f=d.levels;d=b<c.length?c[b]:null;if(!d)return!1;e>=f.length?(f.push(d),
c.splice(b,1)):g===a.Wa.HC.SWAP?(c[b]=f[e],f[e]=d):(g===a.Wa.HC.AFTER&&e++,f.splice(e,0,d),f===c&&e<b&&b++,c.splice(b,1));this.Kp();return!0};a.b.i("Cube.prototype.pivot",{TZ:a.Wa.prototype.TZ});a.Wa.prototype.FQ=function(a){for(var b=0;b<this.xg.length;b++)if(this.xg[b].axis===a)return this.xg[b];return null};a.Wa.prototype.wY=function(){return this.xg};a.b.i("Cube.prototype.getLayout",{wY:a.Wa.prototype.wY});a.Wa.HC={BEFORE:"before",AFTER:"after",SWAP:"swap"};o_("Cube.PivotType",a.Wa.HC,a);a.Wa.prototype.dX=
function(a,b,c){var e=[];if(0===a.length)return b=c.slice(0),this.Bo(b);var g=a.slice(1),f=a[0].start;a=a[0].count;for(c[b]=f;c[b]<f+a;c[b]++)e.push(this.dX(g,b+1,c));return e};a.Wa.prototype.hba=function(a){var b=[];if(!a)return b;for(var c=Math.min(a.length,this.bf.length),e=0;e<c;e++){var g=a[e];g instanceof Object&&(g.hasOwnProperty("start")||g.hasOwnProperty("count"))?g.hasOwnProperty("start")?g.hasOwnProperty("count")?b.push(this.Sy(g.start,g.count,e)):b.push(this.Sy(g.start,1,e)):b.push(this.Sy(0,
g.count,e)):b.push(this.Sy(g,1,e))}return b};a.Wa.prototype.Sy=function(a,b,c){c=this.ml()[c].Rb();if(a>=c||0>a)a=0;b=Math.min(b,c-a);return{start:a,index:a,count:b}};a.Wa.prototype.Bo=function(d){var b=this.x5(d);return b&&(b=b.Mn(),0<b.length&&(b=this.f[b[0].key]))?new a.yf(b.value,d,b.bB,b.rows,b.Bn):new a.yf(null,d,void 0,[])};a.Wa.prototype.q0=function(){var a=this.q8();this.wH=[];for(var b=0;b<a.length;b++)this.so(a[b].axis,a[b].levels),this.wH.push({axis:a[b].axis,index:0});if(0===a.length)for(a=
this.TF(),b=0;b<a.length;b++)this.so(a[b].axis,a[b].levels)};a.Wa.prototype.q8=function(){for(var a=[],b=0;b<this.xg.length;b++)1<this.xg[b].axis&&a.push(this.xg[b]);return a};a.Wa.prototype.TF=function(){for(var a=[],b=0;b<this.xg.length;b++)2>this.xg[b].axis&&a.push(this.xg[b]);return a};a.Wa.prototype.Kp=function(){this.bf=[];this.f=[];this.PE=[];this.q0();if(null!==this.ca)for(var d=0;d<this.ca.length;d++){for(var b=new a.gi,c=2;c<this.bf.length;c++)b=this.bf[c].RL(this.ca[d],b);for(var b=b.Mn(),
e=0;e<b.length;e++){var c=b[e].key,g=this.PE[c];g||(g=this.PE[c]=this.oC(this.TF()));for(var f=new a.gi,k=g.bf.length,c=0;c<k;c++)f=g.bf[c].RL(this.ca[d],f);f=c=f.Mn();if(void 0!==b[e].MX)for(f=[],k=0;k<c.length;k++)f.push(b[e]);g.Pda(c,f,this.ca[d])}}};a.Wa.prototype.Pda=function(a,b,c){for(var e=0;e<a.length;e++)this.f[a[e].key]=this.V3(b[e],this.f[a[e].key],c)};a.Wa.prototype.JR=function(){return this.PE[this.V7(this.wH)]};a.Wa.prototype.V7=function(d){var b=new a.gi;if(d&&0<d.length){d.sort(function(a,
b){return a.axis-b.axis});for(var c=this.bf,e=0;e<d.length;e++)b=c[d[e].axis].Zw(d[e].index,b)}return b.Mn()[0].key};a.Wa.yT=function(a){return a?void 0!==a.value&&null!==a.value:!1};a.Wa.prototype.uc=function(a,b,c,e,g){c.push(e);e={};for(var f in g)g.hasOwnProperty(f)&&(e[f]=g[f]);e.value=a;e.bB=b;e.rows=c;return e};a.Wa.Md=function(d){return a.Ba.pd(d.value)?!1:!isNaN(d.value)};a.Wa.prototype.V3=function(d,b,c){var e=this.qC(d.MX),g=e.Wr,f=a.Wa.yT(b),k=a.Wa.yT(d),l=f&&a.Wa.Md(b),m=k&&a.Wa.Md(d);
switch(g){case a.xf.SUM:return f&&k?l&&m?this.uc(b.value+d.value,g,b.rows,c,{}):this.uc(NaN,g,b.rows,c,{}):k&&!f?m?this.uc(d.value,g,[],c,{}):this.uc(NaN,g,[],c,{}):b;case a.xf.AVERAGE:return f&&k?l&&m?this.uc((b.Hs+d.value)/(b.rows.length+1),g,b.rows,c,{Hs:b.Hs+d.value}):this.uc(NaN,g,b.rows,c,{Hs:b.Hs}):k&&!f?m?this.uc(d.value,g,[],c,{Hs:d.value}):this.uc(NaN,g,[],c,{Hs:NaN}):b;case a.xf.VARIANCE:case a.xf.STDDEV:return f&&k?l&&m?(f=b.value+(d.value-b.value)/(b.rows.length+1),this.uc(f,g,b.rows,
c,{Bn:b.Bn+(d.value-b.value)*(d.value-f)})):this.uc(NaN,g,b.rows,c,{Bn:NaN}):k&&!f?m?this.uc(d.value,g,[],c,{Bn:0}):this.uc(NaN,g,[],c,{Bn:NaN}):b;case a.xf.NONE:return this.uc(null,g,f?b.rows:[],c,{});case a.xf.FIRST:return f?this.uc(b.value,g,b.rows,c,{}):k?this.uc(d.value,g,[],c,{}):b;case a.xf.MIN:return f&&k?l&&m?this.uc(Math.min(b.value,d.value),g,b.rows,c,{}):this.uc(NaN,g,b.rows,c,{}):k&&!f?m?this.uc(d.value,g,[],c,{}):this.uc(NaN,g,[],c,{}):b;case a.xf.MAX:return f&&k?l&&m?this.uc(Math.max(b.value,
d.value),g,b.rows,c,{}):this.uc(NaN,g,b.rows,c,{}):k&&!f?m?this.uc(d.value,g,[],c,{}):this.uc(NaN,g,[],c,{}):b;case a.xf.COUNT:return f&&k?this.uc(b.value+1,g,b.rows,c,{}):k&&!f?this.uc(1,g,[],c,{}):b;case a.xf.CUSTOM:return d=e.Xb.call(this,f?b.value:void 0,k?d.value:void 0),this.uc(d,g,f?b.rows:[],c,{})}};a.Wa.prototype.so=function(d,b){d>=this.bf.length&&Array.prototype.push.apply(this.bf,Array(d-this.bf.length+1));this.bf[d]||(this.bf[d]=new a.Oe(b,d,this));return this.bf[d]};a.Wa.prototype.x5=
function(d){for(var b=this.ml(),c=new a.gi,e=0;e<d.length;e++)c=b[e].Zw(d[e],c);return c};a.Wa.prototype.Up=function(){a.j.Xa()};a.Wa.prototype.oC=function(){a.j.Xa()};a.Wa.prototype.pC=function(){a.j.Xa()};a.Wa.prototype.qC=function(){a.j.Xa();return{}};a.xf={SUM:"sum",AVERAGE:"avg",STDDEV:"stddev",VARIANCE:"variance",NONE:"none",FIRST:"first",MIN:"min",MAX:"max",COUNT:"count",CUSTOM:"custom"};o_("CubeAggType",a.xf,a);a.$b=function(a,b,c,e){this.Init();this.kd=[];this.So=e;this.g6=c;this.f={};this.f.value=
a;this.f.label=b};o_("CubeAxisValue",a.$b,a);a.b.ga(a.$b,a.b,"oj.CubeAxisValue");a.$b.prototype.Init=function(){a.$b.q.Init.call(this)};a.$b.prototype.qp=function(){return this.g6};a.b.i("CubeAxisValue.prototype.getLevel",{qp:a.$b.prototype.qp});a.$b.prototype.Td=function(){return 1};a.b.i("CubeAxisValue.prototype.getDepth",{Td:a.$b.prototype.Td});a.$b.prototype.yY=function(){for(var a=[],b=this.So;b&&b.So;)a.unshift(b),b=b.So;return a};a.b.i("CubeAxisValue.prototype.getParents",{yY:a.$b.prototype.yY});
a.$b.prototype.getChildren=function(){return this.kd};a.b.i("CubeAxisValue.prototype.getChildren",{getChildren:a.$b.prototype.getChildren});a.$b.prototype.Rb=function(){if(-1<this.Oq)return this.Oq;if(this.kd&&0!==this.kd.length)for(var a=this.Oq=0;a<this.getChildren().length;a++)this.Oq+=this.getChildren()[a].Rb();else this.Oq=1;return this.Oq};a.b.i("CubeAxisValue.prototype.getExtent",{Rb:a.$b.prototype.Rb});a.$b.prototype.ua=function(){if(-1<this.bh)return this.bh;if(!this.So)return 0;for(var a=
this.So.ua(),b=this.So.MR(this);b;)a+=b.Rb(),b=this.So.MR(b);return this.bh=a};a.b.i("CubeAxisValue.prototype.getStart",{ua:a.$b.prototype.ua});a.$b.prototype.Pc=function(){return this.f.value};a.b.i("CubeAxisValue.prototype.getValue",{Pc:a.$b.prototype.Pc});a.$b.prototype.LJ=function(){return this.f.label?this.f.label:this.Pc()};a.b.i("CubeAxisValue.prototype.getLabel",{LJ:a.$b.prototype.LJ});a.$b.prototype.r0=function(a){var b=this.u7();if(null===b)return null;if(b.ts())return this.E7(a);if(a=a[b.attribute])for(b=
0;b<this.kd.length;b++)if(this.kd[b].Pc()===a)return this.kd[b];return null};a.$b.prototype.E7=function(a){for(var b=0;b<this.kd.length;b++){var c=this.kd[b].Pc();if(a.hasOwnProperty(c)&&a[c]===c)return this.kd[b]}return null};a.$b.prototype.u7=function(){return this.kd&&0<this.kd.length?this.kd[0].qp():null};a.$b.prototype.s0=function(a){return this.lF(a,0,this.kd.length-1)};a.$b.prototype.lF=function(a,b,c){if(b>c)return null;var e=Math.floor((b+c)/2),g=this.kd[e],f=g.ua();return f>a?this.lF(a,
b,e-1):f+g.Rb()-1<a?this.lF(a,e+1,c):g};a.$b.prototype.dC=function(d,b,c){for(var e=0;e<this.kd.length;e++)if(this.kd[e].Pc()===d)return this.kd[e];d=new a.$b(d,b,c,this);this.kd.push(d);return d};a.$b.prototype.t0=function(){var a={};a[this.qp().attribute]=this.Pc();return a};a.$b.prototype.MR=function(a){for(var b=0;b<this.kd.length;b++)if(this.kd[b]===a){if(0<b)return this.kd[b-1];break}return null};a.Oe=function(d,b,c){this.Init();this.axis=b;this.FT=[];for(b=0;b<d.length;b++)this.FT.push(c.pC(d[b],
this));this.Vt=c;this.Wm=new a.$b(null,null,null,null)};o_("CubeAxis",a.Oe,a);a.b.ga(a.Oe,a.b,"oj.CubeAxis");a.Oe.prototype.Init=function(){a.Oe.q.Init.call(this)};a.Oe.prototype.Wj=function(){return this.FT};a.b.i("CubeAxis.prototype.getLevels",{Wj:a.Oe.prototype.Wj});a.Oe.prototype.Rb=function(){return this.Wm.Rb()};a.b.i("CubeAxis.prototype.getExtent",{Rb:a.Oe.prototype.Rb});a.Oe.prototype.sl=function(a){for(var b=[],c=this.Wm;c;)(c=c.s0(a))&&b.push(c);return b};a.b.i("CubeAxis.prototype.getValues",
{sl:a.Oe.prototype.sl});a.Oe.prototype.Vh=function(a){a=a?JSON.parse(a):{};for(var b=this.Wm,c=null;b;)c=b,b=b.r0(a);return c?c.ua():-1};a.b.i("CubeAxis.prototype.getIndex",{Vh:a.Oe.prototype.Vh});a.Oe.prototype.Zw=function(a,b){return this.FL(a,this.Wj().length-1,b)};a.Oe.prototype.FL=function(a,b,c){a=this.sl(a);b=this.Wj()[b];for(var e=0;e<a.length;e++){var g=a[e];g.qp().ts()?c.cC(g.Pc()):c.PC(g);if(g.qp()===b)break}return c};a.Oe.prototype.RL=function(a,b){return this.Vt.Up(this,0,this.Wm,a,b,
!0)};a.fg=function(a,b,c){this.Init();this.attribute=a;this.zO=b;this.axis=b.axis;this.OP=c};o_("CubeLevel",a.fg,a);a.b.ga(a.fg,a.b,"oj.CubeLevel");a.fg.prototype.Init=function(){a.fg.q.Init.call(this)};a.fg.prototype.Pc=function(a){if(a=this.zO.sl(a))for(var b=0;b<a.length;b++)if(a[b].qp()===this)return a[b];return null};a.b.i("CubeLevel.prototype.getValue",{Pc:a.fg.prototype.Pc});a.fg.prototype.ts=function(){return this.OP};a.b.i("CubeLevel.prototype.isDataValue",{ts:a.fg.prototype.ts});a.fg.prototype.OP=
!1;a.fg.prototype.zO=null;a.gi=function(){this.bH=[];this.f=[]};a.gi.prototype.PC=function(a){this.bH.push(a)};a.gi.prototype.cC=function(a,b){this.f.push({name:a,value:b})};a.gi.prototype.Mn=function(){var a=[],b=this.x4();if(0===this.f.length)a.push({key:JSON.stringify(b)});else for(var c=0;c<this.f.length;c++){var e=f.extend(!0,{},b);e[this.f[c].name]=this.f[c].name;a.push({key:JSON.stringify(e),MX:this.f[c].name,value:this.f[c].value})}return a};a.gi.prototype.x4=function(){for(var a={},b=0;b<
this.bH.length;b++){var c=this.bH[b].t0(),e;for(e in c)c.hasOwnProperty(e)&&(a[e]=c[e])}return a};a.ei=function(d,b){var c=b.row?b.row.start:0,e=b.row?b.row.count:0,g=b.column?b.column.start:0,f=b.column?b.column.count:0;a.j.pc(c,null);a.j.pc(e,null);a.j.pc(g,null);a.j.pc(f,null);this.Vt=d;this.rI={row:c,column:g};this.Wm=this.Vt.sl([{start:g,count:f},{start:c,count:e}]);f=this.Wm.length;0<f&&(e=this.Wm[0].length);this.t5={row:e,column:f}};o_("CubeCellSet",a.ei,a);a.ei.prototype.getData=function(a){return(a=
this.Wm[a.column-this.rI.column][a.row-this.rI.row])?a.Pc():null};a.b.i("CubeCellSet.prototype.getData",{getData:a.ei.prototype.getData});a.ei.prototype.getMetadata=function(a){var b={keys:{}};b.keys.row=this.QQ(a,"row",2);b.keys.column=this.QQ(a,"column",1);return b};a.b.i("CubeCellSet.prototype.getMetadata",{getMetadata:a.ei.prototype.getMetadata});a.ei.prototype.QQ=function(d,b,c){var e=this.Vt.ml();return void 0!==d[b]&&e.length>=c?(c=new a.gi,c=e[a.Cb.uP(b)].Zw(d[b],c),c.Mn()[0].key):null};a.ei.prototype.ua=
function(a){return this.rI[a]};a.b.i("CubeCellSet.prototype.getStart",{ua:a.ei.prototype.ua});a.ei.prototype.Q=function(a){return this.t5[a]};a.b.i("CubeCellSet.prototype.getCount",{Q:a.ei.prototype.Q});a.zf=function(d,b,c){this.Init();this.om=c;this.Eea=c.valueAttr;this.raa=c.labelAttr;var e=c.defaultAggregation;this.PP=e?a.zf.G7(e):{Wr:a.xf.SUM};this.ND=c.aggregation;this.XD();a.zf.q.constructor.call(this,d,b)};o_("DataColumnCube",a.zf,a);a.b.ga(a.zf,a.Wa,"oj.DataColumnCube");a.zf.prototype.Init=
function(){a.zf.q.Init.call(this)};a.zf.prototype.Kp=function(){a.zf.q.Kp.call(this)};a.zf.prototype.qC=function(a){return this.Hq[a]?this.Hq[a]:this.PP};a.zf.prototype.oC=function(d){return new a.zf(null,d,this.om)};a.zf.prototype.pC=function(d,b){return d.attribute===this.raa?new a.fg(d.attribute,b,!0):new a.fg(d.attribute,b,!1)};a.zf.prototype.Up=function(a,b,c,e,g,f){if(b>=a.Wj().length)return g;var k=a.Wj()[b],l=e[k.attribute];c=c.dC(l,null,k);k.ts()?g.cC(l,e[this.Eea]):g.PC(c);return this.Up(a,
b+1,c,e,g,f)};a.zf.G7=function(d){return a.Ba.pd(d)?{Wr:d}:{Wr:d.aggregation,Xb:d.callback}};a.zf.prototype.XD=function(){this.Hq=[];if(this.ND)for(var a=0;a<this.ND.length;a++){var b=this.ND[a],c=b.aggregation;this.Hq[b.value]=c?{Wr:c,Xb:b.callback}:this.PP}};a.yf=function(a,b,c,e,g){this.Init();this.f={};this.f.value=a;this.f.pga=b;this.f.bB=c;this.f.rows=e;this.f.Bn=g};o_("CubeDataValue",a.yf,a);a.b.ga(a.yf,a.b,"oj.CubeDataValue");a.yf.prototype.Init=function(){a.yf.q.Init.call(this)};a.yf.prototype.Pc=
function(){switch(this.f.bB){case a.xf.STDDEV:return Math.sqrt(this.jS());case a.xf.VARIANCE:return this.jS();default:return this.f.value}};a.b.i("CubeDataValue.prototype.getValue",{Pc:a.yf.prototype.Pc});a.yf.prototype.vY=function(){return this.f.pga};a.b.i("CubeDataValue.prototype.getIndices",{vY:a.yf.prototype.vY});a.yf.prototype.BY=function(){return this.f.rows};a.b.i("CubeDataValue.prototype.getRows",{BY:a.yf.prototype.BY});a.yf.prototype.bY=function(){return this.f.bB};a.b.i("CubeDataValue.prototype.getAggregation",
{bY:a.yf.prototype.bY});a.yf.prototype.jS=function(){if(isNaN(this.f.Bn))return NaN;var a=this.f.rows.length;return 1<a?this.f.Bn/(a-1):0};a.Af=function(d,b,c){this.Init();this.om=c;this.XD();a.Af.q.constructor.call(this,d,b)};o_("DataValueAttributeCube",a.Af,a);a.b.ga(a.Af,a.Wa,"oj.DataValueAttributeCube");a.Af.prototype.ca=null;a.Af.prototype.Init=function(){a.Af.q.Init.call(this)};a.Af.prototype.Kp=function(){a.Af.q.Kp.call(this)};a.Af.prototype.qC=function(a){return this.Hq[a]};a.Af.prototype.pC=
function(d,b){return d.dataValue?new a.fg(null,b,!0):new a.fg(d.attribute,b,!1)};a.Af.prototype.oC=function(d){return new a.Af(null,d,this.om)};a.Af.prototype.Up=function(a,b,c,e,g,f){if(b>=a.Wj().length)return g;var k=a.Wj()[b];if(k.ts())return this.Hba(a,c,e,b,g);c=c.dC(e[k.attribute],null,k);f&&g.PC(c);return this.Up(a,b+1,c,e,g,f)};a.Af.prototype.Hba=function(a,b,c,e,g){for(var f=!0,k=0;k<this.om.length;k++){var l=this.om[k].attribute,m=this.om[k].label;c.hasOwnProperty(l)&&(m=b.dC(l,m,a.Wj()[e]),
g.cC(l,c[l]),this.Up(a,e+1,m,c,g,f),f=!1)}return g};a.Af.prototype.XD=function(){this.Hq=[];for(var d=0;d<this.om.length;d++){var b=this.om[d];this.Hq[b.attribute]=b.aggregation?{Wr:b.aggregation,Xb:b.callback}:{Wr:a.xf.SUM,Xb:b.callback}}};a.ze=function(a,b,c,e){this.Vt=b;this.Jt=a;this.bh=void 0===c?0:c;this.s5=void 0===e?this.Jt.Rb():Math.min(e,this.Jt.Rb()-c);this.tQ=c+e-1};o_("CubeHeaderSet",a.ze,a);a.ze.prototype.getData=function(a,b){var c=this.Bo(a,b);return c?c.LJ():null};a.b.i("CubeHeaderSet.prototype.getData",
{getData:a.ze.prototype.getData});a.ze.prototype.getMetadata=function(d,b){var c=new a.gi,c=this.Jt.FL(d,b,c);return(c=c.Mn())&&0<c.length?{key:c[0].key}:null};a.b.i("CubeHeaderSet.prototype.getMetadata",{getMetadata:a.ze.prototype.getMetadata});a.ze.prototype.Uf=function(){return this.Jt.Wj().length};a.b.i("CubeHeaderSet.prototype.getLevelCount",{Uf:a.ze.prototype.Uf});a.ze.prototype.Rb=function(a,b){var c=this.Bo(a,b),e=c.Rb(),c=c.ua(),g=c+e-1,f=a<c+e-1;c<this.bh&&(e-=this.bh-c);g>this.tQ&&(e-=
g-this.tQ);return{extent:e,more:{before:a>c,after:f}}};a.b.i("CubeHeaderSet.prototype.getExtent",{Rb:a.ze.prototype.Rb});a.ze.prototype.Td=function(a,b){return this.Bo(a,b).Td()};a.b.i("CubeHeaderSet.prototype.getDepth",{Td:a.ze.prototype.Td});a.ze.prototype.Q=function(){return this.s5};a.b.i("CubeHeaderSet.prototype.getCount",{Q:a.ze.prototype.Q});a.ze.prototype.ua=function(){return this.bh};a.b.i("CubeHeaderSet.prototype.getStart",{ua:a.ze.prototype.ua});a.ze.prototype.Bo=function(a,b){void 0===
b&&(b=0);var c=this.Jt.sl(a);return c&&c.length>b?c[b]:null};a.Cb=function(d){a.Cb.q.constructor.call(this,d)};o_("CubeDataGridDataSource",a.Cb,a);a.b.ga(a.Cb,a.fc,"oj.CubeDataGridDataSource");a.Cb.prototype.l_=function(a){this.data=a;this.IQ()};a.b.i("CubeDataGridDataSource.prototype.setCube",{l_:a.Cb.prototype.l_});a.Cb.prototype.setPage=function(a){this.data.setPage(a);this.IQ()};a.b.i("CubeDataGridDataSource.prototype.setPage",{setPage:a.Cb.prototype.setPage});a.Cb.prototype.IQ=function(){this.handleEvent("change",
{source:this,operation:"refresh"})};a.Cb.prototype.Q=function(a){return(a=this.so(a))?a.Rb():0};a.b.i("CubeDataGridDataSource.prototype.getCount",{Q:a.Cb.prototype.Q});a.Cb.prototype.Rf=function(){return"exact"};a.b.i("CubeDataGridDataSource.prototype.getCountPrecision",{Rf:a.Cb.prototype.Rf});a.Cb.prototype.Sd=function(d,b,c){var e=new a.ze(this.so(d.axis),this.data,d.start,d.count);b.success.call(c?c.success:void 0,e,d)};a.b.i("CubeDataGridDataSource.prototype.fetchHeaders",{Sd:a.Cb.prototype.Sd});
a.Cb.prototype.ke=function(d,b,c){for(var e={},g=0;g<d.length;g++){var f=void 0===d[g].start?0:d[g].start;if("row"===d[g].axis){var k=void 0===d[g].count?this.data.ml()[1].Rb():d[g].count;e.row={start:f,count:k}}"column"===d[g].axis&&(k=void 0===d[g].count?this.data.ml()[0].Rb():d[g].count,e.column={start:f,count:k})}e=new a.ei(this.data,e);b.success.call(c?c.success:void 0,e,d)};a.b.i("CubeDataGridDataSource.prototype.fetchCells",{ke:a.Cb.prototype.ke});a.Cb.prototype.keys=function(a){var b={},b=
this.um(a,"row",b),b=this.um(a,"column",b);return Promise.resolve(b)};a.b.i("CubeDataGridDataSource.prototype.keys",{keys:a.Cb.prototype.keys});a.Cb.prototype.um=function(d,b,c){var e=this.so(b);d=d[b];var g=new a.gi,g=e?e.Zw(d,g):"";c[b]=g.Mn()[0].key;return c};a.Cb.prototype.oe=function(a){var b={},b=this.Jd(a,"row",b),b=this.Jd(a,"column",b);return Promise.resolve(b)};a.b.i("CubeDataGridDataSource.prototype.indexes",{oe:a.Cb.prototype.oe});a.Cb.prototype.Jd=function(a,b,c){c[b]=this.so(b).Vh(a[b]);
return c};a.Cb.prototype.sort=function(){a.j.Xa()};a.b.i("CubeDataGridDataSource.prototype.sort",{sort:a.Cb.prototype.sort});a.Cb.prototype.move=function(){a.j.Xa()};a.b.i("CubeDataGridDataSource.prototype.move",{move:a.Cb.prototype.move});a.Cb.prototype.Zi=function(){return"invalid"};a.b.i("CubeDataGridDataSource.prototype.moveOK",{Zi:a.Cb.prototype.Zi});a.Cb.prototype.getCapability=function(a){switch(a){case "sort":return"none";case "move":return"none"}return null};a.b.i("CubeDataGridDataSource.prototype.getCapability",
{getCapability:a.Cb.prototype.getCapability});a.Cb.uP=function(a){return"row"===a?1:0};a.Cb.prototype.so=function(d){d=a.Cb.uP(d);var b=this.data.ml();return b.length>d?b[d]:null}});