/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojinputtext","ojs/ojvalidation","ojs/ojpopup","ojs/ojbutton"],function(a,f){function d(a){return this.options.converter.parse(a)}function b(b,c){var d=b.translations.dateTimeRange||{},e=[{category:"hint",entries:["min","max","inRange"]},{category:"messageDetail",entries:["rangeUnderflow","rangeOverflow"]},{category:"messageSummary",entries:["rangeUnderflow","rangeOverflow"]}],g={min:b.min,max:b.max,converter:c};if(!f.isEmptyObject(d))for(var h=
0,k=e.length;h<k;h++){var s=d[e[h].category];if(s){for(var v={},x=e[h].entries,u=0,w=x.length;u<w;u++)v[x[u]]=s[x[u]];g[e[h].category]=v}}return a.na.Jp(a.Vc.VALIDATOR_TYPE_DATETIMERANGE).createValidator(g)}function c(a,b){var c=a.filter("span");b?c.addClass("oj-disabled").removeClass("oj-enabled oj-default"):c.removeClass("oj-disabled").addClass("oj-enabled oj-default")}function e(a,b,c){if(!a||b===c.length)return a;var d=b+1;return e(a[c[b]],d,c)||e(a["*"],d,c)}function g(a,b){b.setHours(a.getHours());
b.setMinutes(a.getMinutes());b.setSeconds(a.getSeconds());b.setMilliseconds(a.getMilliseconds());return b}function h(a){return a.delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-calendar td a","mouseout",function(){f(this).removeClass("oj-hover")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-calendar td a",
"mouseover",function(){f(this).addClass("oj-hover")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-calendar td a","focus",function(){f(this).addClass("oj-focus")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-calendar td a",
"blur",function(){f(this).removeClass("oj-focus")})}var k=a.na.jl(a.gj.CONVERTER_TYPE_DATETIME).createConverter({year:"numeric"});a.Da("oj.ojInputDate",f.oj.inputBase,{version:"1.0.0",widgetEventPrefix:"oj",_CLASS_NAMES:"oj-inputdatetime-input",_WIDGET_CLASS_NAMES:"oj-inputdatetime-date-only oj-component oj-inputdatetime",_ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES:"",_INPUT_HELPER_KEY:"inputHelp",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],_GET_INIT_OPTIONS_PROPS:[{W:"disabled",ra:!1,rc:!0},{W:"pattern",
ra:""},{W:"title",ra:""},{W:"placeholder",ra:""},{W:"value",ra:null,je:d},{W:"required",ra:!1,je:!0,rc:!0},{W:"readonly",option:"readOnly",ra:!1,rc:!0},{W:"min",ra:null,je:d},{W:"max",ra:null,je:d}],CD:"oj-inputdatetime-input-trigger",BD:"oj-inputdatetime-calendar-icon",zM:"oj-datepicker-current-day",FM:"oj-datepicker-days-cell-over",bO:"oj-datepicker-unselectable",DM:"oj-datepicker-desc",XC:"oj-datepicker-calendar",g2:"oj-datepicker-div",K1:"oj-datepicker-inline",dD:" oj-inputdatetime-input-container",
L1:" oj-inputdatetime-inline",options:{datePicker:{footerLayout:"",changeMonth:"select",changeYear:"select",currentMonthPos:0,daysOutsideMonth:"hidden",numberOfMonths:1,showOn:"image",stepMonths:"numberOfMonths",stepBigMonths:12,weekDisplay:"none",yearRange:"c-10:c+10"},converter:a.na.jl(a.gj.CONVERTER_TYPE_DATETIME).createConverter({day:"2-digit",month:"2-digit",year:"2-digit"}),max:void 0,min:void 0,dayFormatter:null},xx:function(){this.Yc=null;this.RG=!1;this.Wu=4;this.rm=this.Aj=this.Gk=this.zi=
this.yj=0;this.Yt={};var a=this.element[0].nodeName.toLowerCase();this.Ld="div"===a||"span"===a;this.yd=h(f("\x3cdiv id\x3d'"+this.Wl(this.g2)+"' role\x3d'region' aria-describedby\x3d'"+this.Wl(this.DM)+"' class\x3d'oj-datepicker-content'\x3e\x3c/div\x3e"));f("body").append(this.yd);if(this.Ld)this._WIDGET_CLASS_NAMES+=this.L1,this._CLASS_NAMES="";else{this._ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES+=this.dD;var b=this;this.xH=this.yd.ojPopup({initialFocus:"none",open:function(){b.yd.find(".oj-datepicker-calendar").focus()}})}},
_ComponentCreate:function(){this.xx();var a=this._super();this.options.dayMetaData&&(this.options.dayFormatter=function(a){return function(b){return e(a,0,[b.fullYear,b.month,b.date])}}(this.options.dayMetaData));this.tA(this.cz());this.Ld?(this.element.append(this.yd),this.element.addClass(this.K1),this.yd.css("display","block")):this.RD();return a},Sg:function(){var a=this._superApply(arguments);this.fQ(this.options.disabled);return a},_setOption:function(b,c,d){var g=null;if("value"===b)return c||
(c=null),g=this._super(b,c,d),this.tA(c),this.Dk()&&this.Um(),g;if("dayMetaData"===b)this._setOption("dayFormatter",function(a){return e(c,0,[a.fullYear,a.month,a.date])},d);else return g=this._super(b,c,d),"disabled"===b?this.fQ(c):"max"===b||"min"===b?(this.Yt[a.Vc.VALIDATOR_TYPE_DATETIMERANGE]=this.uz("min"),this.Xp()):"readOnly"===b&&c?this.hide():"dayFormatter"===b&&(this.Yt[a.Vc.VALIDATOR_TYPE_DATERESTRICTION]=this.uz("dayFormatter"),this.Xp()),"datePicker"===b&&"currentMonthPos"===d.subkey&&
this.tA(this.options.value),d={max:!0,min:!0,dayFormatter:!0,datePicker:!0,translations:!0},this.Dk()&&b in d&&this.Um(),g},TC:function(){return this.Yc},_destroy:function(){var a=this._super();this.element.off("focus");this.Yc&&this.Yc.remove();this.Ld&&(this.element.removeProp("disabled"),this.element.removeProp("readonly"));this.yd.remove();return a},Dk:function(){return this.Ld||this.xH.ojPopup("isOpen")},RD:function(){var a=this.options.datePicker.showOn,b=f("\x3cspan\x3e").addClass(this.CD);
if("focus"===a)this.element.on("focus",f.proxy(this.show,this));a=f("\x3cspan title\x3d'"+this.AF()+"'/\x3e").addClass(this.BD+" oj-clickable-icon-nocontext oj-component-icon");b.append(a);var c=this;a.on("click",function(){c.Dk()?c.hide():c.show();return!1}).on("mouseenter",function(){f(this).addClass("oj-hover")}).on("mousedown",function(){f(this).addClass("oj-active")}).on("mouseup",function(){f(this).removeClass("oj-active")}).on("mouseleave",function(){f(this).removeClass("oj-hover oj-active")});
this.OI=a;this.Yc=b;this.element.after(b)},u6:function(a){var b;b=!1;var c=f.ui.keyCode,d=this.Ki;if(this.Dk())switch(a.keyCode){case 84:a.altKey&&a.ctrlKey&&(this.yd.find(".oj-datepicker-current").focus(),b=!0);break;case c.TAB:this.hide();break;case c.ENTER:return b=f("td."+this.FM+":not(."+this.zM+")",this.yd),b[0]&&this.AV(this.zi,this.Aj,b[0],a),a.preventDefault(),a.stopPropagation(),!1;case c.ESCAPE:this.hide();this.element.focus();b=!0;break;case c.PAGE_UP:a.ctrlKey&&a.altKey?this.af(-this.options.datePicker.stepBigMonths,
"M",!0):a.altKey?this.af(-1,"Y",!0):this.af(-this.xu(),"M",!0);b=!0;break;case c.PAGE_DOWN:a.ctrlKey&&a.altKey?this.af(+this.options.datePicker.stepBigMonths,"M",!0):a.altKey?this.af(1,"Y",!0):this.af(+this.xu(),"M",!0);b=!0;break;case c.END:this.yj=this.ju(this.Aj,this.zi);this.Um(!0);b=!0;break;case c.HOME:this.yj=1;this.Um(!0);b=!0;break;case c.LEFT:this.af(d?1:-1,"D",!0);a.originalEvent.altKey&&this.af(a.ctrlKey?-this.options.datePicker.stepBigMonths:-this.xu(),"M",!0);b=!0;break;case c.UP:this.af(-7,
"D",!0);b=!0;break;case c.RIGHT:this.af(d?-1:1,"D",!0);a.originalEvent.altKey&&this.af(a.ctrlKey?+this.options.datePicker.stepBigMonths:+this.xu(),"M",!0);b=!0;break;case c.DOWN:this.af(7,"D",!0),b=!0}else a.keyCode===c.HOME&&a.ctrlKey&&(this.show(),b=!0);b&&(a.preventDefault(),a.stopPropagation())},Um:function(a){this.Wu=4;var b=this.j7();this.yd.empty().append(b.html);var c=f("button",this.yd);0<c.length&&(1===c.length&&f(c[0]).addClass("oj-datepicker-single-button"),f.each(c,function(a,b){f(b).ojButton()}));
this.g4();b.NX&&this.yd.find(".oj-datepicker-calendar").attr("aria-activedescendant",b.NX);b=this.UF();c=b[1];this.yd.removeClass("oj-datepicker-multi-2 oj-datepicker-multi-3 oj-datepicker-multi-4").width("");1<c&&this.yd.addClass("oj-datepicker-multi-"+c).css("width",17*c+"em");this.yd[(1!==b[0]||1!==b[1]?"add":"remove")+"Class"]("oj-datepicker-multi");this.Dk()&&this.element.is(":visible")&&!this.element.is(":disabled")&&(a?(a=this.yd.find(".oj-datepicker-calendar"),a[0]!==document.activeElement&&
a.focus()):this.Ld||this.element[0]===document.activeElement||this.element.focus())},af:function(a,b,c){this.options.disabled||(this.mO(a+("M"===b?this.options.datePicker.currentMonthPos:0),b),this.Um(c))},Q8:function(){var a=new Date;this.yj=a.getDate();this.Gk=this.zi=a.getMonth();this.rm=this.Aj=a.getFullYear();this.af()},BV:function(b,c){var d=parseInt(b.options[b.selectedIndex].value,10);"M"===c?this.zi=this.Gk=d:this.Aj=this.rm=d;f("#"+this.Wl(this.XC)).html(this.pj(this.options.monthWide[this.Gk])+
" "+k.format(a.cb.dateToLocalIso(new Date(this.rm,this.Gk,1))));this.af(0,0,!0)},AV:function(b,c,d,e){f(d).hasClass(this.bO)||this.options.disabled||(this.yj=f("a",d).html(),this.zi=b,this.Aj=c,b=a.cb,(c=this.options.value?b.isoToLocalDate(this.options.value):null)?(d=new Date(this.Aj,this.zi,this.yj),g(c,d),c=d):c=new Date(this.Aj,this.zi,this.yj),b=b.dateToLocalIso(c),c=this.Lc().format(b),this.sj(c),this.tc(b,e),this.hide())},WE:function(b,c){return b?"string"===typeof b?a.cb.isoToLocalDate(b):
new Date(b.getTime()):c},tA:function(a){a=this.WE(a,this.fS());this.yj=a.getDate();this.Gk=this.zi=a.getMonth();this.rm=this.Aj=a.getFullYear();this.mO()},xu:function(){var a=this.options.datePicker.stepMonths;return f.isNumeric(a)?a:this.options.datePicker.numberOfMonths},g4:function(){var a=this.xu(),b=this;this.yd.find("[data-handler]").map(function(){f(this).bind(this.getAttribute("data-event"),{prev:function(c){b.af(-a,"M",!0);c.preventDefault()},next:function(c){b.af(+a,"M",!0);c.preventDefault()},
today:function(a){if("keyup"===a.type&&13===a.keyCode||"click"===a.type)b.Q8(),a.preventDefault(),a.stopPropagation()},selectDay:function(a){b.AV(+this.getAttribute("data-month"),+this.getAttribute("data-year"),this,a);return!1},selectMonth:function(){b.BV(this,"M");return!1},selectYear:function(){b.BV(this,"Y");return!1},calendarKey:function(a){b.u6(a)}}[this.getAttribute("data-handler")])})},lba:function(a,b,c){b=b?new Date(b.getFullYear(),b.getMonth(),b.getDate()):null;c=c?new Date(c.getFullYear(),
c.getMonth(),c.getDate()):null;return null!==b&&a<b||null!==c&&a>c},j7:function(){var b,c,d,e,g,f,h=this.options.dayWide,k=this.options.dayNarrow,v=this.options.monthWide,x=this.options.monthAbbreviated,u=this.options.firstDayOfWeek,w,z,D,y,E,B,H,C="",A,G,F,J,N,T,O,I,M=new Date,M=new Date(M.getFullYear(),M.getMonth(),M.getDate()),R=this.Ki;f=this.options.datePicker.footerLayout;var P=this.UF(),K=this.options.datePicker.currentMonthPos,ca=this.options.dayFormatter;I=null;var W=1!==P[0]||1!==P[1],U=
this.kz("min"),V=this.kz("max"),K=this.Gk-K,L=this.rm,ea=new Date(this.Aj,this.zi,this.yj),X=new Date(this.cz()),ba=X.getDate(),S=X.getMonth(),Y=X.getFullYear(),Z=this.options.disabled,fa=this.pj(this.D("weekText")),Q=a.cb;X.setHours(0);X.setMinutes(0);X.setSeconds(0);X.setMilliseconds(0);0>K&&(K+=12,L--);if(U)for(b=new Date(U.getFullYear(),U.getMonth(),U.getDate()),b=V&&V<b?V:b;new Date(L,K,this.ju(L,K))<b;)K++,11<K&&(K=0,L++);if(V)for(b=new Date(V.getFullYear(),V.getMonth()-P[0]*P[1]+1,V.getDate()),
b=U&&b<U?U:b;new Date(L,K,1)>b;)K--,0>K&&(K=11,L--);this.Gk=K;this.rm=L;b=this.pj(this.D("prevText"));b=this.TO(-1,L,K)&&!Z?"\x3ca href\x3d'#' class\x3d'oj-datepicker-prev-icon oj-enabled oj-default oj-component-icon oj-clickable-icon-nocontext' data-handler\x3d'prev' data-event\x3d'click' title\x3d'"+b+"'\x3e\x3c/a\x3e":"\x3ca class\x3d'oj-datepicker-prev-icon oj-disabled oj-component-icon oj-clickable-icon-nocontext' title\x3d'"+b+"'\x3e\x3c/a\x3e";c=this.pj(this.D("nextText"));c=this.TO(1,L,K)&&
!Z?"\x3ca href\x3d'#' class\x3d'oj-datepicker-next-icon oj-enabled oj-default oj-component-icon oj-clickable-icon-nocontext' data-handler\x3d'next' data-event\x3d'click' title\x3d'"+c+"'\x3e\x3c/a\x3e":"\x3ca class\x3d'oj-datepicker-next-icon oj-disabled oj-component-icon oj-clickable-icon-nocontext' title\x3d'"+c+"'\x3e\x3c/a\x3e";d=this.pj(this.D("currentText"));g="";e="\x3cbutton type\x3d'button' class\x3d'oj-datepicker-current oj-priority-secondary' data-handler\x3d'today' data-event\x3d'click keyup'\x3e"+
d+"\x3c/button\x3e";if(1<f.length){d=0;f=[{index:f.indexOf("today"),content:this.kT(M)?e:""}];for(f.sort(function(a,b){return a.index-b.index});d<f.length&&0>f[d].index;)d++;for(;d<f.length;)g+=f[d++].content;0<g.length&&(g="\x3cdiv class\x3d'oj-datepicker-buttonpane'\x3e"+g+"\x3c/div\x3e")}f=this.options.datePicker.weekDisplay;d=this.options.datePicker.daysOutsideMonth;e="";w="all";for(z=0;z<P[0];z++){D="";this.Wu=4;for(y=0;y<P[1];y++){w="all";A="";if(W){A+="\x3cdiv class\x3d'oj-datepicker-group";
if(1<P[1])switch(y){case 0:A+=" oj-datepicker-group-first";w=R?"right":"left";break;case P[1]-1:A+=" oj-datepicker-group-last";w=R?"left":"right";break;default:A+=" oj-datepicker-group-middle",w=""}A+="'\x3e"}A+="\x3cdiv class\x3d'oj-datepicker-header"+(Z?" oj-disabled ":" oj-enabled oj-default ")+"'\x3e"+(/all|left/.test(w)&&0===z?R?c:b:"")+(/all|right/.test(w)&&0===z?R?b:c:"")+this.k7(K,L,U,V,0<z||0<y,v,x,W)+"\x3c/div\x3e\x3ctable class\x3d'oj-datepicker-calendar"+(Z?" oj-disabled ":" oj-enabled oj-default ")+
"' tabindex\x3d-1 data-handler\x3d'calendarKey' data-event\x3d'keydown' aria-readonly\x3d'true' role\x3d'grid' aria-labelledby\x3d'"+this.Wl(this.XC)+"'\x3e\x3cthead role\x3d'presentation'\x3e\x3ctr role\x3d'row'\x3e";G="number"===f?"\x3cth class\x3d'oj-datepicker-week-col'\x3e"+this.pj(this.D("weekHeader"))+"\x3c/th\x3e":"";for(w=0;7>w;w++)F=(w+parseInt(u,10))%7,G+="\x3cth role\x3d'columnheader' aria-label\x3d'"+h[F]+"'"+(5<=(w+u+6)%7?" class\x3d'oj-datepicker-week-end'":"")+"\x3e\x3cspan title\x3d'"+
h[F]+"'\x3e"+k[F]+"\x3c/span\x3e\x3c/th\x3e";A+=G+"\x3c/tr\x3e\x3c/thead\x3e\x3ctbody role\x3d'presentation'\x3e";G=this.ju(L,K);L===Y&&K===S&&(ba=Math.min(ba,G));w=(this.Q7(L,K)-u+7)%7;G=Math.ceil((w+G)/7);this.Wu=G=W?this.Wu>G?this.Wu:G:G;F=new Date(L,K,1-w);for(J=0;J<G;J++){A+="\x3ctr role\x3d'row'\x3e";w=this.Lc().Zm(Q.dateToLocalIso(F));N="none"===f?"":"\x3ctd class\x3d'oj-datepicker-week-col' role\x3d'rowheader' aria-label\x3d'"+fa+" "+w+"'\x3e"+w+"\x3c/td\x3e";for(w=0;7>w;w++){O=F.getMonth()!==
K;E=F.getTime()===X.getTime();B="oj-dp-"+this.uuid+"-"+J+"-"+w+"-"+z+"-"+y;(H=F.getTime()===ea.getTime()&&K===this.zi)&&(C=B);T=[!0,""];I=F.getFullYear();var aa=F.getMonth(),ga=F.getDate();ca&&(I=ca({fullYear:I,month:aa+1,date:ga}))&&(T=[!I.disabled,I.className||""],I.tooltip&&T.push(I.tooltip));aa=F.getTime()===X.getTime();I=O&&"selectable"!==d||!T[0]||this.lba(F,U,V);N+="\x3ctd role\x3d'gridcell' aria-disabled\x3d'"+!!I+"' aria-selected\x3d'"+E+"' id\x3d'"+B+"' class\x3d'"+(5<=(w+u+6)%7?" oj-datepicker-week-end":
"")+(O?" oj-datepicker-other-month":"")+(H?" "+this.FM:"")+(I||Z?" "+this.bO+" oj-disabled":" oj-enabled ")+(O&&"hidden"===d?"":" "+T[1]+(E?" "+this.zM:"")+(F.getTime()===M.getTime()?" oj-datepicker-today":""))+"'"+(O&&"hidden"===d||!T[2]?"":" title\x3d'"+T[2].replace(/'/g,"\x26#39;")+"'")+(I?"":" data-handler\x3d'selectDay' data-event\x3d'click' data-month\x3d'"+F.getMonth()+"' data-year\x3d'"+F.getFullYear()+"'")+"\x3e"+(O&&"hidden"===d?"\x26#xa0;":I||Z?"\x3cspan class\x3d'oj-disabled'\x3e"+F.getDate()+
"\x3c/span\x3e":"\x3ca class\x3d'oj-enabled"+(aa?" oj-selected":"")+(O?" oj-priority-secondary":"")+"' "+(aa||H?"":"tabindex\x3d'-1' ")+" href\x3d'#'\x3e"+F.getDate()+"\x3c/a\x3e")+"\x3c/td\x3e";F.setDate(F.getDate()+1)}A+=N+"\x3c/tr\x3e"}K++;11<K&&(K=0,L++);A+="\x3c/tbody\x3e\x3c/table\x3e"+(W?"\x3c/div\x3e"+(0<P[0]&&y===P[1]-1?"\x3cdiv class\x3d'oj-datepicker-row-break'\x3e\x3c/div\x3e":""):"");D+=A}e+=D}return{html:e+g,NX:C}},k7:function(b,c,d,e,g,f,h,s){var v,x,u,w,z=this.options.datePicker.changeMonth,
D=this.options.datePicker.changeYear,y=a.La.hZ()?"before":"after",E="\x3cdiv class\x3d'oj-datepicker-title' role\x3d'header'\x3e",B="",H=this.options.disabled,C=a.cb;if(g||"none"===z)B+="\x3cspan class\x3d'oj-datepicker-month'\x3e"+f[b]+"\x3c/span\x3e";else{v=d&&d.getFullYear()===c;x=e&&e.getFullYear()===c;B+="\x3cselect tabindex\x3d'-1' class\x3d'oj-datepicker-month "+(H?"oj-disabled' disabled":"oj-enabled'")+" data-handler\x3d'selectMonth' data-event\x3d'change' role\x3d'listbox'\x3e";for(u=0;12>
u;u++)(!v||u>=d.getMonth())&&(!x||u<=e.getMonth())&&(B+="\x3coption role\x3d'option' value\x3d'"+u+"' aria-selected\x3d'"+(u===b?"true' selected\x3d'selected'":"false'")+"\x3e"+h[u]+"\x3c/option\x3e");B+="\x3c/select\x3e"}"before"===y&&(E+=B+(g||"select"!==z||"select"!==D?"\x26#xa0;":""));if(!this.Jl)if(this.Jl="",g||"none"===D)E+="\x3cspan class\x3d'oj-datepicker-year'\x3e"+k.format(C.dateToLocalIso(new Date(c,b,1)))+"\x3c/span\x3e";else{v=this.options.datePicker.yearRange.split(":");w=(new Date).getFullYear();
x=function(a){a=a.match(/c[+\-].*/)?c+parseInt(a.substring(1),10):a.match(/[+\-].*/)?w+parseInt(a,10):parseInt(a,10);return isNaN(a)?w:a};h=x(v[0]);v=Math.max(h,x(v[1]||""));h=d?Math.max(h,d.getFullYear()):h;v=e?Math.min(v,e.getFullYear()):v;for(this.Jl+="\x3cselect tabindex\x3d'-1' class\x3d'oj-datepicker-year "+(H?"oj-disabled' disabled":"oj-enabled'")+" data-handler\x3d'selectYear' data-event\x3d'change' role\x3d'listbox'\x3e";h<=v;h++)this.Jl+="\x3coption role\x3d'option' value\x3d'"+h+"' aria-selected\x3d'"+
(h===c?"true' selected\x3d'selected'":"false'")+"\x3e"+k.format(C.dateToLocalIso(new Date(h,b,1)))+"\x3c/option\x3e";this.Jl+="\x3c/select\x3e";E+=this.Jl;this.Jl=null}"after"===y&&(E+=(g||"select"!==z||"select"!==D?"\x26#xa0;":"")+B);s&&g||(E+="\x3cspan class\x3d'oj-helper-hidden-accessible' id\x3d'"+this.Wl(this.XC)+"'\x3e"+f[b]+" "+k.format(C.dateToLocalIso(new Date(c,b,1)))+"\x3c/span\x3e",E+="\x3cspan class\x3d'oj-helper-hidden-accessible' id\x3d'"+this.Wl(this.DM)+"'\x3e"+this.pj(this.D("datePicker"))+
"\x3c/span\x3e");return E+"\x3c/div\x3e"},mO:function(a,b){var c=this.rm+("Y"===b?a:0),d=this.Gk+("M"===b?a:0),e=Math.min(this.yj,this.ju(c,d))+("D"===b?a:0),c=new Date(c,d,e);this.yj=c.getDate();this.Gk=this.zi=c.getMonth();this.rm=this.Aj=c.getFullYear()},UF:function(){var a=this.options.datePicker.numberOfMonths,a="string"===typeof a?parseInt(a,10):a;return null==a?[1,1]:"number"===typeof a?[1,a]:a},kz:function(a){return this.WE(this.options[a],null)},ju:function(a,b){return 32-(new Date(a,b,32)).getDate()},
Q7:function(a,b){return(new Date(a,b,1)).getDay()},TO:function(a,b,c){var d=this.UF();b=new Date(b,c+(0>a?a:d[0]*d[1]),1);0>a&&b.setDate(this.ju(b.getFullYear(),b.getMonth()));return this.kT(b)},kT:function(a){var b,c,d=this.kz("min"),e=this.kz("max"),g=null,f=null;if(b=this.options.datePicker.yearRange)b=b.split(":"),c=(new Date).getFullYear(),g=parseInt(b[0],10),f=parseInt(b[1],10),b[0].match(/[+\-].*/)&&(g+=c),b[1].match(/[+\-].*/)&&(f+=c);return(!d||a.getTime()>=d.getTime())&&(!e||a.getTime()<=
e.getTime())&&(!g||a.getFullYear()>=g)&&(!f||a.getFullYear()<=f)},AF:function(){return this.pj(this.D("tooltipCalendar"+(this.options.disabled?"Disabled":"")))},fQ:function(a){this.Yc&&(c(this.Yc.children(),a),this.Yc.find("."+this.BD).attr("title",this.AF()));a&&this.hide();this.Ld&&this.Um()},SC:function(){this.Ld||this._superApply(arguments)},rH:function(a){this.Ld||this._superApply(arguments)},bA:function(a){if(!this.Ld){this._superApply(arguments);var b=f.ui.keyCode,c=!1;if(this.Dk())switch(a.keyCode){case b.TAB:this.hide();
break;case b.ESCAPE:this.hide();c=!0;break;case b.UP:case b.DOWN:this.yd.find(".oj-datepicker-calendar").focus(),c=!0}else switch(a.keyCode){case b.UP:case b.DOWN:this.tc(this.mg(),a),this.show(),c=!0}if(c)return a.preventDefault(),a.stopPropagation(),!1}},sj:function(a){this.Ld||this._superApply(arguments);this.tA(this.cz());this.Dk()&&this.Um()},Lc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputDate.prototype.options.converter},dq:function(){return this.options.value||
""},_GetDefaultStyleClass:function(){return"oj-inputdate"},ht:function(){var b=this._superApply(arguments);if(null!=this.options.min||null!=this.options.max)this.Yt[a.Vc.VALIDATOR_TYPE_DATETIMERANGE]=this.uz("min");null!=this.options.dayFormatter&&(this.Yt[a.Vc.VALIDATOR_TYPE_DATERESTRICTION]=this.uz("dayFormatter"));return f.extend(this.Yt,b)},ti:function(){this.hide()},$l:function(){this.hide()},uz:function(c){var d=null;"min"===c||"max"===c?d=b(this.options,this.Lc()):"dayFormatter"===c&&(c={dayFormatter:this.options.dayFormatter,
converter:this.Lc()},f.extend(c,this.options.translations.dateRestriction||{}),d=a.na.Jp(a.Vc.VALIDATOR_TYPE_DATERESTRICTION).createValidator(c));return d},fS:function(){var a=new Date;a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a},cz:function(){return this.WE(this.options.value,this.fS())},getNodeBySubId:function(a){var b=null,c=a&&a.subId,d=this.yd;if(c)switch(c){case "oj-datepicker-content":b=d[0];break;case "oj-inputdatetime-calendar-icon":b=f(".oj-inputdatetime-calendar-icon",
this.Yc)[0];break;case "oj-datepicker-prev-icon":b=f(".oj-datepicker-prev-icon",d)[0];break;case "oj-datepicker-next-icon":b=f(".oj-datepicker-next-icon",d)[0];break;case "oj-datepicker-month":b=f(".oj-datepicker-month",d)[0];break;case "oj-datepicker-year":b=f(".oj-datepicker-year",d)[0];break;case "oj-datepicker-current":b=f(".oj-datepicker-current",d)[0];break;case "oj-inputdatetime-date-input":b=this.Ld?null:this.element[0];break;default:b=null}return b||this._superApply(arguments)},getSubIdByNode:function(a){var b=
this.yd,c=null,d=[{selector:".oj-inputdatetime-calendar-icon",ele:this.Yc},{selector:".oj-datepicker-prev-icon",ele:b},{selector:".oj-datepicker-next-icon",ele:b},{selector:".oj-datepicker-month",ele:b},{selector:".oj-datepicker-year",ele:b},{selector:".oj-datepicker-current",ele:b}];if(a===b[0])return"oj-datepicker-content";if(!this.Ld&&a===this.element[0])return"oj-inputdatetime-date-input";for(var b=0,e=d.length;b<e;b++){var g=d[b],h=f(g.selector,g.ele);if(1===h.length&&h[0]===a){c=g.selector.substr(1);
break}}return c||this._superApply(arguments)},hide:function(){this.Dk()&&!this.Ld&&(this.xH.ojPopup("close"),"focus"===this.options.datePicker.showOn&&(this.RG=!0),this.element.focus());return this},refresh:function(){this.Yc&&this.Yc.find("."+this.BD).attr("title",this.AF());return this._superApply(arguments)||this},show:function(){if(!(this.Dk()||this.options.disabled||this.options.readOnly))if(this.RG)this.RG=!1;else{var b=this.Ki;this.yd.empty();this.Um();b=a.fd.Ig({my:"start top",at:"start bottom",
of:this.element,collision:"fit"},b);this.xH.ojPopup("open",this.OI,b);return this}}});a.Components.SB({ojInputDate:{firstDayOfWeek:a.Components.ds(function(){return a.La.pY()}),dayWide:a.Components.ds(function(){return a.La.gw("wide")}),dayNarrow:a.Components.ds(function(){return a.La.gw("narrow")}),monthWide:a.Components.ds(function(){return a.La.iw("wide")}),monthAbbreviated:a.Components.ds(function(){return a.La.iw("abbreviated")})}});a.Da("oj.ojInputTime",f.oj.inputBase,{version:"1.0.0",widgetEventPrefix:"oj",
_CLASS_NAMES:"oj-inputdatetime-input",_WIDGET_CLASS_NAMES:"oj-inputdatetime-time-only oj-component oj-inputdatetime",dD:"oj-inputdatetime-input-container",_ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES:"",_INPUT_HELPER_KEY:"inputHelp",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],_GET_INIT_OPTIONS_PROPS:[{W:"disabled",ra:!1,rc:!0},{W:"pattern",ra:""},{W:"title",ra:""},{W:"placeholder",ra:""},{W:"value",ra:null,je:d},{W:"required",ra:!1,je:!0,rc:!0},{W:"readonly",option:"readOnly",ra:!1,rc:!0},{W:"min",ra:null,
je:d},{W:"max",ra:null,je:d}],o3:"ojInputTime",CD:"oj-inputdatetime-input-trigger",DD:"oj-inputdatetime-time-icon",options:{converter:a.na.jl(a.gj.CONVERTER_TYPE_DATETIME).createConverter({hour:"2-digit",hour12:!0,minute:"2-digit"}),max:void 0,min:void 0,datePickerComp:null,timePicker:{timeIncrement:"00:30:00:00"}},ae:function(b,c){this._super(b,c);null===this.options.datePickerComp&&a.Be.vl(this._GET_INIT_OPTIONS_PROPS,c,this)},xx:function(){this.wI={};this.Ck=this.options.datePickerComp;this.Of=
f("\x3cdiv id\x3d'"+this.Wl(this.o3)+"' class\x3d'oj-listbox-drop' style\x3d'display:none'\x3e\x3c/div\x3e");f("body").append(this.Of);var a=this;this.yH=this.Of.ojPopup({initialFocus:"none",rootAttributes:{"class":"datetimepicker-dropdown"},chrome:"none",open:function(){var b=f("[aria-selected]",a.Of);1===b.length&&a.YO(b.parent(),!0);f("ul",a.Of).focus()},beforeClose:function(){a.KW=f("ul",a.Of).scrollTop()}});this.Bm()&&(this._ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES+=this.dD)},Jv:function(){return this.yH.ojPopup("isOpen")},
_ComponentCreate:function(){this.xx();var a=this._superApply(arguments);this.Sk()&&!this.hT()&&(this._CLASS_NAMES="");this.RD();return a},Sg:function(){var a=this._superApply(arguments);c(this.Yc.children(),this.options.disabled);return a},_setOption:function(d,e,g){var f=null;if("value"===d)return e||(e=null),f=this._super(d,e,g),this.Ty(),f;f=this._superApply(arguments);"disabled"===d?(e&&this.hide(),this.Yc.find("."+this.DD).attr("title",this.iG()),c(this.Yc.children(),e)):"max"!==d&&"min"!==d||
this.Sk()?"readOnly"===d&&e&&this.hide():(this.wI[a.Vc.VALIDATOR_TYPE_DATETIMERANGE]=b(this.options,this.Lc()),this.Xp());d in{max:!0,min:!0,converter:!0,timePicker:!0}&&this.Ty();return f},_destroy:function(){var a=this._super();this.Yc&&this.Yc.remove();this.Of.remove();return a},SC:function(){this.Bm()&&this._superApply(arguments)},TC:function(){return this.Yc},bA:function(a){if(this.Bm()){this._superApply(arguments);var b=f.ui.keyCode,c=!1;if(this.Jv())switch(a.keyCode){case b.TAB:this.hide();
break;case b.ESCAPE:this.hide();c=!0;break;case b.UP:case b.DOWN:f("ul",this.Of).focus(),c=!0}else switch(a.keyCode){case b.UP:case b.DOWN:this.tc(this.mg(),a),this.show(),c=!0}if(c||a.keyCode===b.ENTER)return a.preventDefault(),a.stopPropagation(),!1}},iG:function(){return this.pj(this.D("tooltipTime"+(this.options.disabled?"Disabled":"")))},RD:function(){var a=this.Bm(),b=a?f(f("\x3cspan\x3e").addClass(this.CD)):f("+ span",this.element),c=f("\x3cspan title\x3d'"+this.iG()+"'/\x3e").addClass(this.DD+
" oj-clickable-icon-nocontext oj-component-icon");b.append(c);var d=this;c.on("click",function(){d.Jv()?d.hide():d.show()}).on("mouseenter",function(){f(this).addClass("oj-hover")}).on("mousedown",function(){f(this).addClass("oj-active")}).on("mouseup",function(){f(this).removeClass("oj-active")}).on("mouseleave",function(){f(this).removeClass("oj-hover oj-active")});this.OI=c;this.Yc=b;a&&this.element.after(b)},r$:function(a,b,c){return null!==b&&a<b||null!==c&&a>c},Bo:function(){return this.Sk()?
this.Ck.widget.OY():this.options.value},Ty:function(){var b=this.Bo(),c=this.Lc(),d=f("\x3cul class\x3d'oj-listbox-results' tabindex\x3d'-1' role\x3d'listbox'\x3e\x3c/ul\x3e"),c=b?c.format(b):"",e=[],g,b=b?a.cb.isoToLocalDate(b):new Date;b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);e=this.L8(b);c=c||e[0].value;this.Of.empty();b=0;for(g=e.length;b<g;b++){var h=e[b].value,k=e[b].minMaxRange,s=f("\x3cli class\x3d'oj-listbox-result "+(k?"oj-disabled":"")+"' role\x3d'presentation'\x3e"),
v=this.uuid+"_sel"+b,k=f("\x3cdiv class\x3d'oj-listbox-result-label' "+(k?"aria-disabled ":"")+"data-value\x3d'"+h+"' role\x3d'option' id\x3d'"+v+"'\x3e"+e[b].label+"\x3c/li\x3e");c===h&&(k.attr("aria-selected","true"),s.addClass("oj-hover"),d.attr("aria-activedescendant",v));s.append(k);d.append(s)}this.Of.append(d);f(".oj-listbox-result",d).on("mousemove",function(){var a=f(this);a.hasClass("oj-disabled")||(f(".oj-hover",d).removeClass("oj-hover"),a.addClass("oj-hover"),d.attr("aria-activedescendant",
a.children()[0].id))});var x=this;d.on("click",function(a){var b=f(a.target);b.hasClass("oj-disabled")||void 0!==b.attr("aria-disabled")||(x.hide(),x.zU(a))}).on("keydown",function(a){x.cea(a)})},L8:function(b){var c=[],d=this.Lc();if(b){var e=this.options.timePicker.timeIncrement.split(":"),g=a.cb,f=this.Sk(),h=f?this.Ck.widget.options.min:this.options.min,f=f?this.Ck.widget.options.max:this.options.max,h=h?g.isoToLocalDate(h):null,f=f?g.isoToLocalDate(f):null;if(4===e.length){var k=parseInt(e[0].substring(0),
10),v=parseInt(e[1],10),x=parseInt(e[2],10),e=parseInt(e[3],10),u=new Date(b),w="";do w=d.format(g.dateToLocalIso(u)),c.push({label:w,value:w,minMaxRange:this.r$(u,h,f)}),u.setHours(u.getHours()+k),u.setMinutes(u.getMinutes()+v),u.setSeconds(u.getSeconds()+x),u.setMilliseconds(u.getMilliseconds()+e);while(u.getDate()===b.getDate())}else throw Error("timeIncrement value should be in the format of hh:mm:ss:SS");}return c},cea:function(a){if(this.Jv()){var b=f.ui.keyCode,c=!1;switch(a.keyCode){case b.TAB:this.hide();
break;case b.ESCAPE:this.hide();this.element.focus();c=!0;break;case b.UP:this.uU(a,"prev");c=!0;break;case b.DOWN:this.uU(a,"next");c=!0;break;case b.ENTER:this.zU(a),c=!0}if(c)return a.preventDefault(),a.stopPropagation(),!1}},uU:function(a,b){var c=f(".oj-hover",this.Of),d=f("ul",this.Of),e=null;1===c.length?(e=c[b](),1===e.length&&c.removeClass("oj-hover")):e=f(d.children()[0]);e&&1===e.length&&(e.addClass("oj-hover"),d.attr("aria-activedescendant",e.children()[0].id),this.YO(e))},zU:function(a){var b=
this.Of,c=f("[aria-selected]",b),d=f("ul",b),b=f(".oj-hover div",b);1===b.length&&(1===c.length&&(c.removeAttr("aria-selected"),c.parent().removeClass("oj-hover")),b.attr("aria-selected","true"),b.parent().addClass("oj-hover"),this.hide(),this.sj(b.attr("data-value")),this.tc(b.attr("data-value"),a),d.attr("aria-activedescendant",b[0].id),this.element.focus(),this.Sk()&&this.Ck.widget.hide())},rH:function(a){this.Bm()&&this._superApply(arguments)},show:function(){if(!this.options.disabled&&!this.options.readOnly){this.Sk()&&
this.Ck.widget.hide();this.Ty();var b=this.Of,c=this.yH;b.width(this.element.parent().width());b.css({position:"relative"});b=a.fd.Ig({my:"start top",at:"start bottom",of:this.element,collision:"fit"},this.Ki);c.ojPopup("open",this.OI,b)}},hide:function(){this.Jv()&&(this.yH.ojPopup("close"),this.element.focus())},refresh:function(){this.Yc&&this.Yc.find("."+this.DD).attr("title",this.iG());return this._superApply(arguments)||this},sj:function(a){this.Bm()&&this._superApply(arguments);this.Jv()&&
this.Ty()},tc:function(b,c,d){if(this.Sk()){this._super(b,null,d);try{var e=this.Lc().parse(b),f=a.cb,h=this.Ck.widget,k=h.OY(),s=k?f.isoToLocalDate(k):new Date,v=g(e?f.isoToLocalDate(e):new Date,new Date(s)),x=f.dateToLocalIso(v);s.getTime()!=v.getTime()&&h.Aha(x,c)}catch(u){}}else this._superApply(arguments)},ft:function(){return this.Bm()},Bm:function(){return!this.Sk()||this.hT()},_GetDefaultStyleClass:function(){return"oj-inputtime"},dq:function(){return this.options.value||""},ht:function(){var c=
this._superApply(arguments);null==this.options.min&&null==this.options.max||this.Sk()||(this.wI[a.Vc.VALIDATOR_TYPE_DATETIMERANGE]=b(this.options,this.Lc()));return f.extend(this.wI,c)},Lc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputTime.prototype.options.converter},YO:function(a,b){var c=a.parent();b&&this.KW&&f(c).scrollTop(this.KW);var d=f(c).scrollTop(),e=d+f(c).height(),g=a[0].offsetTop,h=g+f(a).height();g<d?f(c).scrollTop(g):h>e&&f(c).scrollTop(h-f(c).height())},
Sk:function(){return null!==this.Ck},hT:function(){return this.Ck.inline},ti:function(){this.hide()},$l:function(){this.hide()},getNodeBySubId:function(a){var b=null,c=a&&a.subId;if(c)switch(c){case "oj-listbox-drop":b=this.Of[0];break;case "oj-inputdatetime-time-icon":b=f(".oj-inputdatetime-time-icon",this.Yc)[0];break;case "oj-inputdatetime-time-input":b=this.element[0];break;default:b=null}return b||this._superApply(arguments)},getSubIdByNode:function(a){var b=f(".oj-inputdatetime-time-icon",this.Yc),
c=null;a===this.Of[0]?c="oj-listbox-drop":a===b[0]?c="oj-inputdatetime-time-icon":a===this.element[0]&&(c="oj-inputdatetime-time-input");return c||this._superApply(arguments)},widget:function(){return this.Bm()?this._super():this.Ck.widget.widget()}});a.Da("oj.ojInputDateTime",f.oj.ojInputDate,{version:"1.0.0",widgetEventPrefix:"oj",_WIDGET_CLASS_NAMES:"oj-inputdatetime-date-time oj-component oj-inputdatetime",_INPUT_HELPER_KEY:"inputHelpBoth",options:{converter:a.na.jl(a.gj.CONVERTER_TYPE_DATETIME).createConverter({day:"2-digit",
month:"2-digit",year:"2-digit",hour:"2-digit",hour12:!0,minute:"2-digit"}),timePicker:{timeIncrement:"00:30:00:00"}},xx:function(){this._super();this.Nr=this.element;this.gA=this.HA=this.Nf=null},_ComponentCreate:function(){var b=this._super(),c=this.eS(this.Lc());if(null===c)throw Error("Please use ojInputDate if you do not have time portion");if(this.Ld){var d=f("\x3cinput type\x3d'text'\x3e");d.insertAfter(this.element);this.Nr=d}for(var d=["title","placeholder","disabled","required","readOnly"],
e={},g=0,h=d.length;g<h;g++)e[d[g]]=this.options[d[g]];this.Nf=this.Nr.ojInputTime(f.extend(e,{converter:c,displayOptions:{converterHint:"none",title:"none",messages:this.options.displayOptions.messages},value:a.cb.dateToLocalIso(this.cz()),timePicker:this.options.timePicker,datePickerComp:{widget:this,inline:this.Ld}}));return b},_setOption:function(a,b,c){var d=this._superApply(arguments);"value"===a&&(this.gA=b);this.Nf&&(a in{disabled:!0,readOnly:!0}?this.Nf.ojInputTime("option",a,b):"timePicker"===
a?this.Nf.ojInputTime("option","timePicker.timeIncrement",b.timeIncrement):"converter"===a&&(this.HA=null,this.Nf.ojInputTime("option",a,this.eS(this.Lc()))));return d},_destroy:function(){var a=this._super();this.Nf.ojInputTime("destroy");this.Ld&&this.Nr.remove();return a},eS:function(b){if(null!==this.HA)return this.HA;b=b.resolvedOptions();var c={},d="hour hour12 minute second millisecond timeFormat".split(" "),e,g;e=0;for(g=d.length;e<g;e++)d[e]in b&&("timeFormat"===d[e]&&(c.formatType="time"),
c[d[e]]=b[d[e]]);if(f.isEmptyObject(c))throw Error("Plase use ojInputDateTime's converter is lacking the time portion");return this.HA=b=a.na.jl(a.gj.CONVERTER_TYPE_DATETIME).createConverter(c)},Aha:function(a,b){this.sj(this.Lc().format(a));this.tc(a,b)},OY:function(){return this.isValid()?this.options.value:this.gA?this.Lc().parse(this.gA):null},tc:function(a,b,c){this._superApply(arguments);this.gA=a},bA:function(a){var b=f.ui.keyCode,c=!1;switch(a.keyCode){case b.UP:case b.DOWN:a.shiftKey&&(this.tc(this.mg(),
a),this.Nf.ojInputTime("show"),c=!0)}return c?(a.preventDefault(),a.stopPropagation(),!1):this._superApply(arguments)},show:function(){this.Nf.ojInputTime("hide");return this._super()},showTimePicker:function(){this.hide();return this.Nf.ojInputTime("show")},hideTimePicker:function(){return this.Nf.ojInputTime("hide")},refresh:function(){var a=this._superApply(arguments)||this;this.Nf.ojInputTime("refresh");return a},getNodeBySubId:function(a){var b=a&&a.subId,c=null;b&&("oj-listbox-drop"===b||"oj-inputdatetime-time-icon"===
b?c=this.Nf.ojInputTime("getNodeBySubId",a):"oj-inputdatetime-date-input"===b&&(c=this.Ld?this.Nr[0]:this.element[0]));return c||this._superApply(arguments)},getSubIdByNode:function(a){var b=null;this.Ld?a===this.Nr[0]&&(b="oj-inputdatetime-date-input"):a===this.element[0]&&(b="oj-inputdatetime-date-input");return b||this.Nf.ojInputTime("getSubIdByNode",a)||this._superApply(arguments)},Lc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputDateTime.prototype.options.converter},
ti:function(){this._superApply(arguments);this.Nf&&this.hideTimePicker()},$l:function(){this._superApply(arguments);this.Nf&&this.hideTimePicker()},_GetMessagingLauncherElement:function(){return this.Ld?this.Nr:this._super()},_GetDefaultStyleClass:function(){return"oj-inputdatetime"},tx:function(){return"oj-ojInputDate"}})});