/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery"],function(a,f){a.Mg=function(a){this.data=a;this.Init()};o_("DataSource",a.Mg,a);a.b.ga(a.Mg,a.Ng,"oj.DataSource");a.Mg.prototype.Init=function(){a.Mg.q.Init.call(this)};a.b.i("DataSource.prototype.Init",{Init:a.Mg.prototype.Init});a.Mg.prototype.getCapability=function(){return null};a.b.i("DataSource.prototype.getCapability",{getCapability:a.Mg.prototype.getCapability});a.Uc=function(d){a.Uc.q.constructor.call(this,d)};o_("TreeDataSource",a.Uc,a);a.b.ga(a.Uc,a.Mg,"oj.TreeDataSource");
a.Uc.prototype.nf=function(){return-1};a.b.i("TreeDataSource.prototype.getChildCount",{nf:a.Uc.prototype.nf});a.Uc.prototype.Rd=function(){a.j.Xa()};a.b.i("TreeDataSource.prototype.fetchChildren",{Rd:a.Uc.prototype.Rd});a.Uc.prototype.ll=function(){a.j.Xa()};a.b.i("TreeDataSource.prototype.fetchDescendants",{ll:a.Uc.prototype.ll});a.Uc.prototype.sort=function(){a.j.Xa()};a.b.i("TreeDataSource.prototype.sort",{sort:a.Uc.prototype.sort});a.Uc.prototype.lw=function(){return{key:null,direction:"none"}};
a.b.i("TreeDataSource.prototype.getSortCriteria",{lw:a.Uc.prototype.lw});a.Uc.prototype.move=function(){a.j.Xa()};a.b.i("TreeDataSource.prototype.move",{move:a.Uc.prototype.move});a.Uc.prototype.Zi=function(){return"valid"};a.b.i("TreeDataSource.prototype.moveOK",{Zi:a.Uc.prototype.Zi});a.Uc.prototype.getCapability=function(){return null};a.b.i("TreeDataSource.prototype.getCapability",{getCapability:a.Uc.prototype.getCapability});a.hq=function(){this.id=null;this.depth=0;this.parent=null;this.children=
[];this.pK=this.attr=this.title=null};a.hq.prototype.f4=function(a){return function(b,c){return b.attr&&c.attr&&b.attr[a]&&c.attr[a]?b.attr[a]<c.attr[a]?-1:b.attr[a]===c.attr[a]?0:1:b[a]<c[a]?-1:b[a]===c[a]?0:1}};a.hq.prototype.n6=function(a){return function(b,c){return b.attr&&c.attr&&b.attr[a]&&c.attr[a]?b.attr[a]<c.attr[a]?1:b.attr[a]===c.attr[a]?0:-1:b[a]<c[a]?1:b[a]===c[a]?0:-1}};a.hq.prototype.pW=function(a){var b=a.key;"ascending"===a.direction?this.children.sort(this.f4(b)):"descending"===
a.direction&&this.children.sort(this.n6(b));for(var b=0,c=this.children.length;b<c;b++)this.children[b].pW(a)};a.Ic=function(d){var b;b=new a.hq;d.id||(b.id="root");this.data=this.GP({count:0},b,d);a.Ic.q.constructor.call(this,b)};o_("JsonTreeDataSource",a.Ic,a);a.b.ga(a.Ic,a.Uc,"oj.JsonTreeDataSource");a.Ic.prototype.Init=function(){a.Ic.q.Init.call(this)};a.b.i("JsonTreeDataSource.prototype.Init",{Init:a.Ic.prototype.Init});a.Ic.prototype.GP=function(d,b,c,e){var g,f,k,l,m,n,q;e||(e=0);for(l in c)if("children"==
l||0==e&&c instanceof Array)for(g=0==e&&c instanceof Array?c:c[l],e++,q=0;q<g.length;q++){k=g[q];f=new a.hq;k.id||(d.count++,k.attr?k.attr.id||(k.attr.id="rid_"+d.count):f.id="rid_"+d.count);for(m in k)for(n in f)m==n&&"children"!=m&&(f[n]=k[m]),"depth"==n&&(f[n]=e);b.children.push(f);for(n in k)"children"==n&&this.GP(d,b.children[q],k,e)}return b};a.Ic.prototype.nf=function(a){a||(a=this.data.id);a=this.Rm(this.data,a);return a.children?a.children.length:0};a.b.i("JsonTreeDataSource.prototype.getChildCount",
{nf:a.Ic.prototype.nf});a.Ic.prototype.Rd=function(d,b,c){var e,g,f,k,l;f=[];d||(d=this.data.id);k=this.Rm(this.data,d);b||(b=[],b.start=0,b.count=k.children.length);b.count||(b.count=k.children.length);b.start||(b.start=0);e=b.start;g=Math.min(k.children.length,e+b.count);for(b=e;b<g;b+=1)l=new a.hq,k.children[b].attr&&(l.attr=k.children[b].attr),k.children[b].id&&(l.id=k.children[b].id),k.children[b].depth&&(l.depth=k.children[b].depth),k.children[b].title&&(l.title=k.children[b].title),k.children[b].parent&&
(l.parent=k.children[b].parent),l.pK=0<k.children[b].children.length?!1:!0,f.push(l);d=new a.Fe(e,g,f,d);null!=c&&null!=c.success&&c.success.call(null,d)};a.b.i("JsonTreeDataSource.prototype.fetchChildren",{Rd:a.Ic.prototype.Rd});a.Ic.prototype.ll=function(d,b){var c,e,g,f;g=[];d||(d=this.data.id);f=this.Rm(this.data,d);c=[];c.start=0;c.count=f.children.length;e=c.start;for(c=Math.min(f.children.length,e+c.count);e<c;e+=1)f.children[e].pK=0<f.children[e].children.length?!1:!0,g.push(f.children[e]);
g=new a.Fe(0,g.length,g,d);null!=b&&null!=b.success&&b.success.call(null,g)};a.b.i("JsonTreeDataSource.prototype.fetchDescendants",{ll:a.Ic.prototype.ll});a.Ic.prototype.move=function(d,b,c,e){var g;g=b;if(!g||g==this.data.id){if("inside"!=c){a.u.log("Error: root can not be the reference node if position equals to "+c);return}g||(g=this.data.id)}d=this.Rm(null,d);this.Rm(d,g)?a.u.log("Error: the node to move contains the reference node as its sub-tree."):(b=this.Rm(null,g),g=this.XF(g),this.qca(d),
"inside"==c?(this.fl(d,d.depth-(b.depth+1)),b.children.push(d)):"before"==c?(this.fl(d,d.depth-b.depth),c=g.children.indexOf(b),-1<c&&(0!=c?g.children.splice(c-1,0,d):g.children.unshift(d))):"after"==c?(this.fl(d,d.depth-b.depth),c=g.children.indexOf(b),-1<c&&g.children.splice(c,0,d)):"first"==c?(this.fl(d,d.depth-b.depth),g.children.unshift(d)):"last"==c&&(this.fl(d,d.depth-b.depth),g.children.push(d)),null!=e&&null!=e.success&&e.success.call(null,this.data))};a.b.i("JsonTreeDataSource.prototype.move",
{move:a.Ic.prototype.move});a.Ic.prototype.sort=function(a,b){var c;c=this.Rm(this.data,this.data.id);c.pW(a);null!=b&&null!=b.success&&b.success.call(null,c)};a.b.i("JsonTreeDataSource.prototype.sort",{sort:a.Ic.prototype.sort});a.Ic.prototype.XF=function(a,b){var c,e=null;if(a==this.data.id)return null;b||(b=this.data);if(b.children&&0<b.children.length){for(c=0;c<b.children.length;c++)if(b.children[c].id&&b.children[c].id==a||b.children[c].attr&&b.children[c].attr.id==a)return b;for(c=0;c<b.children.length&&
!(e=this.XF(a,b.children[c]));c++);}return e};a.Ic.prototype.Rm=function(a,b){var c,e=null;a||(a=this.data);if(a.id&&a.id==b||a.attr&&a.attr.id==b)return a;if(null!=a.children)for(c=0;c<a.children.length&&!e;c++)e=a.children[c].id&&a.children[c].id==b||a.children[c].attr&&a.children[c].attr.id==b?a.children[c]:this.Rm(a.children[c],b);return e};a.Ic.prototype.fl=function(a,b){var c;a.depth-=b;if(a.children&&0!=a.children.length)for(c=0;c<a.children.length;c++)this.fl(a.children[c],b)};a.Ic.prototype.qca=
function(a){var b;a.id?b=a.id:a.attr&&(b=a.attr.id);(b=this.XF(b))||(b=this.data);a=b.children.indexOf(a);-1<a&&b.children.splice(a,1)};a.Ic.prototype.getCapability=function(a){return"fetchDescendants"===a?"enable":"sort"===a?"default":"batchFetch"===a?"disable":"move"===a?"full":null};a.b.i("JsonTreeDataSource.prototype.getCapability",{getCapability:a.Ic.prototype.getCapability});a.R=function(d,b){if(this.constructor==a.R)throw Error(a.R.nc.Rha+"\n"+a.R.nc.Qha);this.data=d;this.options=b;this.aa=
0;this.Init()};o_("TableDataSource",a.R,a);a.b.ga(a.R,a.Mg,"oj.TableDataSource");a.R.prototype.Init=function(){a.R.q.Init.call(this)};a.b.i("TableDataSource.prototype.Init",{Init:a.R.prototype.Init});a.R.prototype.at=function(){a.j.Xa();return Promise.reject()};a.b.i("TableDataSource.prototype.at",{at:a.R.prototype.at});a.R.prototype.fetch=function(){a.j.Xa();return Promise.reject()};a.b.i("TableDataSource.prototype.fetch",{fetch:a.R.prototype.fetch});a.R.prototype.get=function(){a.j.Xa();return Promise.reject()};
a.b.i("TableDataSource.prototype.get",{get:a.R.prototype.get});a.R.prototype.getCapability=function(){return null};a.b.i("TableDataSource.prototype.getCapability",{getCapability:a.R.prototype.getCapability});a.R.prototype.sort=function(){a.j.Xa();return Promise.reject()};a.b.i("TableDataSource.prototype.sort",{sort:a.R.prototype.sort});a.R.prototype.totalSize=function(){a.j.Xa();return 0};a.b.i("TableDataSource.prototype.totalSize",{totalSize:a.R.prototype.totalSize});a.R.J={ADD:"add",REMOVE:"remove",
RESET:"reset",REFRESH:"refresh",SORT:"sort",CHANGE:"change",REQUEST:"request",SYNC:"sync",ERROR:"error"};o_("TableDataSource.EventType",a.R.J,a);a.R.nc={_ERR_TABLE_DATASOURCE_INSTANTIATED_SUMMARY:"oj.TableDataSource constructor called.",_ERR_TABLE_DATASOURCE_INSTANTIATED_DETAIL:"Please do not instantiate oj.TableDataSource. Please use one of the subclasses instead such as oj.ArrayTableDataSource or oj.CollectionTableDataSource.",_ERR_DATA_INVALID_TYPE_SUMMARY:"Invalid data type.",_ERR_DATA_INVALID_TYPE_DETAIL:"Please specify the appropriate data type."};
a.Ja=function(d,b){this.data={};if(!(d instanceof Array)&&"function"!=typeof d&&"function"!=typeof d.wha)throw Error(a.R.nc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+a.R.nc._ERR_DATA_INVALID_TYPE_DETAIL);null!=b&&null!=b.idAttribute||a.u.info(a.Ja.nc._INFO_ARRAY_TABLE_DATASOURCE_IDATTR);a.Ja.q.constructor.call(this,d,b);this.nd=[];this.ca=[];if(null!=d&&void 0!==d&&(this.PG=null,null!=b&&null!=b.idAttribute&&(this.PG=b.idAttribute),this.f=d instanceof Array?d:d(),this.ca=this.xm(this.f),this.Qd=this.f.length,
!(d instanceof Array))){var c=this;d.subscribe(function(a){var b,d=[],f=[];for(b=0;b<a.length;b++)"deleted"===a[b].status&&d.push(a[b].value);c.Qm(d,null);d=[];f=[];for(b=0;b<a.length;b++)"added"===a[b].status&&(d.push(a[b].value),f.push(a[b].index));c.add(d,{at:f})},null,"arrayChange")}if(null!=b&&("enabled"==b.startFetch||null==b.startFetch)||null==b)this.Ev=!0};o_("ArrayTableDataSource",a.Ja,a);a.b.ga(a.Ja,a.R,"oj.ArrayTableDataSource");a.Ja.prototype.Init=function(){a.Ja.q.Init.call(this)};a.b.i("ArrayTableDataSource.prototype.Init",
{Init:a.Ja.prototype.Init});a.Ja.prototype.add=function(a,b){b=b||{};return this.Q3(a,b.at,b)};a.b.i("ArrayTableDataSource.prototype.add",{add:a.Ja.prototype.add});a.Ja.prototype.at=function(a){var b;b=0>a||a>=this.ca.length?null:{data:this.ca.data[a],index:a,key:this.ca.keys[a]};return new Promise(function(a){a(b)})};a.b.i("ArrayTableDataSource.prototype.at",{at:a.Ja.prototype.at});a.Ja.prototype.change=function(d,b){b=b||{};var c=b.silent,e,g,f,k={data:[],keys:[],indexes:[]};d instanceof Array||
(d=[d]);for(e=0;e<d.length;e++)g=d[e],null!=g&&(f=this.nu(g),f=this.Xg(f,null),k.data.push(g),k.keys.push(f.key),k.indexes.push(f.index),this.ca.data[f.index]=g);!c&&0<k.data.length&&a.R.q.handleEvent.call(this,a.R.J.CHANGE,k);return Promise.resolve(k)};a.b.i("ArrayTableDataSource.prototype.change",{change:a.Ja.prototype.change});a.Ja.prototype.fetch=function(a){a=a||{};return"init"!=a.fetchType||this.Ev?this.ee(a):Promise.resolve()};a.b.i("ArrayTableDataSource.prototype.fetch",{fetch:a.Ja.prototype.fetch});
a.Ja.prototype.get=function(a,b){return Promise.resolve(this.Xg(a,b))};a.b.i("ArrayTableDataSource.prototype.get",{get:a.Ja.prototype.get});a.Ja.prototype.getCapability=function(){return"full"};a.b.i("ArrayTableDataSource.prototype.getCapability",{getCapability:a.Ja.prototype.getCapability});a.Ja.prototype.remove=function(a,b){b=b||{};return this.Qm(a,b)};a.b.i("ArrayTableDataSource.prototype.remove",{remove:a.Ja.prototype.remove});a.Ja.prototype.reset=function(d,b){b=b||{};b.previousRows=this.ca;
var c=b.silent;this.ca.data=[];this.ca.keys=[];this.ca.indexes=[];this.Qd=0;null!=d&&this.add(d,b);c||a.R.q.handleEvent.call(this,a.R.J.RESET,null);return Promise.resolve()};a.b.i("ArrayTableDataSource.prototype.reset",{reset:a.Ja.prototype.reset});a.Ja.prototype.sort=function(d){if(null==d)return this.comparator=null,Promise.resolve();var b=d.key,c=d.direction,e=null;"ascending"==c?e=function(a){return f.isFunction(a[b])?a[b]():a[b]}:"descending"==c&&(e=function(a,c){var d,e;f.isFunction(a[b])?(d=
a[b](),e=c[b]()):(d=a[b],e=c[b]);return d===e?0:d>e?-1:1});this.comparator=e;this.direction=c;var g=this;return new Promise(function(b){d=d||{};if(g.xz()){var c=g.comparator;g.ca.data.sort(function(b,d){return a.Ja.oW(b,d,c,g)});g.Vba(g.ca);g.Mda=!0;var e={header:d.key,direction:d.direction};a.R.q.handleEvent.call(g,a.R.J.SORT,e);b(e)}})};a.b.i("ArrayTableDataSource.prototype.sort",{sort:a.Ja.prototype.sort});a.Ja.prototype.totalSize=function(){return this.Qd};a.b.i("ArrayTableDataSource.prototype.totalSize",
{totalSize:a.Ja.prototype.totalSize});a.Ja.prototype.Q3=function(d,b,c){var e,g,f;c=c||{};var k=c.silent,l={data:[],keys:[],indexes:[]};d instanceof Array||(d=[d]);null==b||b instanceof Array||(b=[b]);for(c=0;c<d.length;c++)if(g=d[c],null!=g){f=this.nu(g);l.data.push(g);l.keys.push(f);if(!0==this.Mda&&0<this.ca.data.length)for(e=0;e<this.ca.data.length;e++)if(0>a.Ja.oW(g,this.ca.data[e],this.comparator,this)){this.ca.data.splice(e,0,g);this.ca.keys.splice(e,0,f);l.indexes.push(e);break}else{if(e==
this.ca.data.length-1){this.ca.data.push(g);this.ca.keys.push(f);l.indexes.push(e+1);break}}else null==b?(this.ca.data.push(g),this.ca.keys.push(f),l.indexes.push(this.ca.data.length-1)):(this.ca.data.splice(b[c],0,g),this.ca.keys.splice(b[c],0,f),l.indexes.push(b[c]));this.Qd++;this.nv()}!k&&0<l.data.length&&a.R.q.handleEvent.call(this,a.R.J.ADD,l);return Promise.resolve(l)};a.Ja.prototype.ee=function(d){d=d||{};this.Dv(d);var b;try{b=0<d.pageSize?d.pageSize:-1;this.aa||(this.aa=0);if(null==this.ca||
0==this.ca.length)this.ca=this.xm(this.f),this.Qd=this.f.length;this.aa=null==d.startIndex?this.aa:d.startIndex;var c=a.Ja.ez(this.ca,this.aa,b),e=[],g=[],f;for(f=this.aa;f<=c;f++)e[f-this.aa]=this.ca.data[f],g[f-this.aa]=this.ca.keys[f]}catch(k){return this.sg(d,null,k),Promise.reject(k)}c<this.aa&&(this.aa=c+1);d.pageSize=b;d.startIndex=this.aa;d.refresh=!0;b={data:e,keys:g,startIndex:this.aa};this.sg(d,b,null);return Promise.resolve(b)};a.Ja.prototype.Xg=function(a){var b,c,e,g,h=null;for(b=0;b<
this.ca.data.length;b++)if(e=this.ca.data[b],void 0!==e)if(g=this.ca.keys[b],f.isArray(g)&&f.isArray(a)){if(g.length==a.length){var k=!0;for(c=0;c<a.length;c++)if(g[c]!=a[c]){k=!1;break}k&&(h={data:e,key:g,index:this.ca.indexes[b]})}}else g==a&&(h={data:e,key:g,index:this.ca.indexes[b]});return h};a.Ja.prototype.xz=function(){var a=this.comparator;return void 0!==a&&null!==a};a.Ja.prototype.nv=function(){for(var a=0;a<this.ca.data.length;a++)this.ca.indexes[a]=a};a.Ja.prototype.Vba=function(a){var b;
for(b=0;b<a.data.length;b++)a.keys[b]=this.nu(a.data[b])};a.Ja.prototype.Qm=function(d,b){var c,e;b=b||{};var g=b.silent,f=[];f.data=[];f.keys=[];f.indexes=[];d instanceof Array||(d=[d]);var k=[];for(c=0;c<d.length;c++)e=d[c],null!=e&&(e=this.nu(e),e=this.Xg(e,null),k.push({data:e.data,key:e.key,index:e.index}));k.sort(function(a,b){return a.index-b.index});for(c=0;c<k.length;c++)f.data.push(k[c].data),f.keys.push(k[c].key),f.indexes.push(k[c].index);for(c=f.indexes.length-1;0<=c;c--)this.ca.data.splice(f.indexes[c],
1),this.ca.keys.splice(f.indexes[c],1),this.ca.indexes.splice(f.indexes[c],1),this.Qd--,this.nv();!g&&0<f.data.length&&a.R.q.handleEvent.call(this,a.R.J.REMOVE,f);return Promise.resolve(f)};a.Ja.prototype.Dv=function(d){d.silent||a.R.q.handleEvent.call(this,a.R.J.REQUEST,{startIndex:d.startIndex})};a.Ja.prototype.sg=function(d,b,c){null!=c?a.R.q.handleEvent.call(this,a.R.J.ERROR,c):d.silent||a.R.q.handleEvent.call(this,a.R.J.SYNC,b)};a.Ja.Ak=function(a,b,c){if("descending"==c){if(a<b)return 1;if(b<
a)return-1}else{if(a>b)return 1;if(b>a)return-1}return 0};a.Ja.ez=function(a,b,c){var e=a.data.length-1;0<c&&(e=b+c-1,e=e>a.data.length-1?a.data.length-1:e);return e};a.Ja.um=function(a,b){return f.isFunction(a[b])?a[b]():a[b]};a.Ja.prototype.xm=function(a){var b=a.length-1,c={},e,g;c.data=[];c.keys=[];c.indexes=[];this.It=null;for(e=0;e<=b;e++){var f={},k=a[e];for(g in k)k.hasOwnProperty(g)&&(f[g]=k[g],0==e&&(null==this.It&&(this.It=[]),this.It.push(g)));c.data[e]=f;c.keys[e]=this.nu(f);c.indexes[e]=
e}return c};a.Ja.prototype.nu=function(a){var b,c=this.KF();if("string"===f.type(c))b=a[c];else if(f.isArray(c)){var e;b=[];for(e=0;e<c.length;e++)b[e]=a[c[e]]}return b};a.Ja.prototype.KF=function(){return null!=this.PG?this.PG:this.It.hasOwnProperty("id")?"id":this.It};a.Ja.oW=function(d,b,c,e){var g,h;if(f.isFunction(c)){if(1===c.length){g=c.call(e,d);h=c.call(e,b);d=a.Ba.pd(g)?g.split(","):[g];b=a.Ba.pd(h)?h.split(","):[h];for(c=0;c<d.length;c++)if(g=a.Ja.Ak(d[c],b[c],e.direction),0!==g)return g;
return 0}return c.call(e,d,b)}if(a.Ba.pd(c)){var k=c.split(",");for(c=0;c<k.length;c++)if(g=a.Ja.um(d,k[c]),h=a.Ja.um(b,k[c]),g=a.Ja.Ak(g,h,e.direction),0!==g)return g}return 0};a.Ja.nc={_INFO_ARRAY_TABLE_DATASOURCE_IDATTR:"idAttribute option has not been specified. Will default to using 'id' if the field exists. If not, will use all the fields."};a.Tc=function(d,b){this.data={};if(!(d instanceof a.l))throw Error(a.R.nc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+a.R.nc._ERR_DATA_INVALID_TYPE_DETAIL);a.Tc.q.constructor.call(this,
d,b);this.ic=d;this.B3();this.Init();if(null!=b&&("enabled"==b.startFetch||null==b.startFetch)||null==b)this.Ev=!0};o_("CollectionTableDataSource",a.Tc,a);a.b.ga(a.Tc,a.R,"oj.CollectionTableDataSource");a.Tc.prototype.Init=function(){a.Tc.q.Init.call(this)};a.b.i("CollectionTableDataSource.prototype.Init",{Init:a.Tc.prototype.Init});a.Tc.prototype.at=function(d,b){b=b||{};b.deferred=!0;var c=this.ic.at(d,b),e=this;e.Pu=!0;var g;return new Promise(function(b,f){null!=c?c.then(function(a){e.Pu=!1;g=
{data:a.attributes,index:d,key:a.id};b(g)},function(b){e.Pu=!1;a.R.q.handleEvent.call(e,a.R.J.ERROR,b);f(b)}):b(null)})};a.b.i("CollectionTableDataSource.prototype.at",{at:a.Tc.prototype.at});a.Tc.prototype.fetch=function(a){a=a||{};return"init"!=a.fetchType||this.Ev?this.ee(a):Promise.resolve()};a.b.i("CollectionTableDataSource.prototype.fetch",{fetch:a.Tc.prototype.fetch});a.Tc.prototype.get=function(d,b){b=b||{};b.deferred=!0;var c=this.ic.get(d,b),e=this,g;return new Promise(function(b,d){null!=
c?c.then(function(a){g={data:a.attributes,index:a.index,key:a.id};b(g)},function(b){a.R.q.handleEvent.call(e,a.R.J.ERROR,b);d(b)}):b(null)})};a.b.i("CollectionTableDataSource.prototype.get",{get:a.Tc.prototype.get});a.Tc.prototype.sort=function(a){if(null==a)return Promise.resolve();var b=this;return new Promise(function(c){b.ada(a);b.ic.sort(null);c({header:a.key,direction:a.direction})})};a.b.i("CollectionTableDataSource.prototype.sort",{sort:a.Tc.prototype.sort});a.Tc.prototype.totalSize=function(){var a=
0<=this.ic.totalResults?this.ic.totalResults:-1;if(-1<a){var b=this.ic.size();return b>a?b:a}0<this.jF&&(a=this.jF);return a};a.b.i("CollectionTableDataSource.prototype.totalSize",{totalSize:a.Tc.prototype.totalSize});a.Tc.prototype.B3=function(){var d=this;this.ic.on(a.$.J.SYNC,function(b){if(b instanceof a.l&&!d.Pu&&!d.iT){var c=b.offset,e=b.lastFetchCount;0<e?(d.aa=c,d.Ra=e,d.Pu=!0,b.Pp(c,c+e).then(function(a){d.Pu=!1;var b=[],e=[],f;for(f=0;f<a.length;f++)null!=a[f]&&(b.push(a[f].attributes),
e.push(a[f].id));d.sg.call(d,{silent:!1},{data:b,keys:e,startIndex:c},null)})):(b=d.xm(),d.sg.call(d,{silent:!1},b,null))}});this.ic.on(a.$.J.ALLADDED,function(b,c){var e=[],g=[],f=[],k;for(k=0;k<c.length;k++)e.push(c[k].attributes),g.push(c[k].id),f.push(c[k].index);a.R.q.handleEvent.call(d,a.R.J.ADD,{data:e,keys:g,indexes:f})});this.ic.on(a.$.J.ALLREMOVED,function(b,c){var e=[],g=[],f=[],k;for(k=0;k<c.length;k++)e.push(c[k].attributes),g.push(c[k].id),f.push(c[k].index);a.R.q.handleEvent.call(d,
a.R.J.REMOVE,{data:e,keys:g,indexes:f})});this.ic.on(a.$.J.RESET,function(b){a.R.q.handleEvent.call(d,a.R.J.RESET,b)});this.ic.on(a.$.J.SORT,function(b,c){null!=c&&c.add||a.R.q.handleEvent.call(d,a.R.J.SORT,b)});this.ic.on(a.$.J.CHANGE,function(b){a.R.q.handleEvent.call(d,a.R.J.CHANGE,{data:[b.attributes],keys:[b.id],indexes:[b.index]})});this.ic.on(a.$.J.DESTROY,function(b){a.R.q.handleEvent.call(d,a.R.J.DESTROY,b)});this.ic.on(a.$.J.REFRESH,function(b){a.R.q.handleEvent.call(d,a.R.J.REFRESH,b)});
this.ic.on(a.$.J.ERROR,function(b,c,e){a.R.q.handleEvent.call(d,a.R.J.ERROR,b,c,e)})};a.Tc.prototype.ee=function(a){this.Dv(a);a=a||{};var b=this;this.gaa=0<a.pageSize?!0:!1;this.aa=null==a.startIndex?this.aa:a.startIndex;this.Hz=!0;this.Ra=0<a.pageSize?a.pageSize:-1;a.pageSize=this.Ra;a.startIndex=this.aa;a.refresh=!0;return new Promise(function(c,e){if(b.gaa)b.ic.Rw(b.aa,b.Ra).then(function(e){var g=[],f=[],m;for(m=0;m<e.models.length;m++)g[m]=e.models[m].attributes,f[m]=e.models[m].id;g={data:g,
keys:f,startIndex:b.aa};e.models.length<b.Ra?0>b.totalSize()&&(b.jF=b.aa+e.models.length):b.jF=null;b.sg.call(b,a,g,null);c(g)},function(c){b.sg.call(b,a,null,c);e(c)});else if(0<b.ic.size()){var g=b.xm();b.sg.call(b,a,g,null);c(g)}else b.ic.fetch({success:function(e){b.ic=e;e=b.xm();b.sg.call(b,a,e,null);c(e)},error:function(c,g){b.ic=c;b.sg.call(b,a,null,g);e(g)}})})};a.Tc.prototype.Dv=function(d){this.iT=!0;d.silent||a.R.q.handleEvent.call(this,a.R.J.REQUEST,{startIndex:d.startIndex})};a.Tc.prototype.sg=
function(d,b,c){this.iT=!1;null!=c?a.R.q.handleEvent.call(this,a.R.J.ERROR,c):d.silent||a.R.q.handleEvent.call(this,a.R.J.SYNC,b)};a.Tc.prototype.ada=function(a){if(null==a)this.ic.comparator=null;else{var b=a.key;a=a.direction;var c=null;this.ic.$a()?(this.ic.comparator=b,this.ic.sortDirection="ascending"===a?1:-1):("ascending"==a?c=function(a){return f.isFunction(a.get)?a.get(b):a[b]()}:"descending"==a&&(c=function(a,c){var d,k;f.isFunction(a.get)?(d=a.get(b),k=c.get(b)):(d=a[b](),k=c[b]());return d===
k?0:d>k?-1:1}),this.ic.comparator=c)}};a.Tc.prototype.xm=function(){var a=this.ic.size()-1,b=[],c=[],e;for(e=0;e<=a;e++)b[e]=this.ic.at(e).attributes,c[e]=this.ic.at(e).id;return{data:b,keys:c,startIndex:this.aa}};a.ij=function(a,b,c){c=c||{};this.f=b;this.au=a;this.Pq=c.fetchSize;this.Pq=0<this.Pq?this.Pq:25;this.qr=c.maxCount;this.qr=0<this.qr?this.qr:500;this.ZH=0;this.yW=c.success;this.L6=c.error;f(this.au).on("scroll.domscroller",function(a){var b=f(a.target).scrollTop();a=f(a.target)[0].scrollHeight-
f(a.target)[0].clientHeight;0<a&&this.Z9(b,a)}.bind(this))};a.ij.prototype.destroy=function(){f(this.au).off("scroll.domscroller")};a.b.i("DomScroller.prototype.destroy",{destroy:a.ij.prototype.destroy});a.ij.prototype.checkViewport=function(){return this.P4()?Promise.resolve(null):this.DQ()};a.b.i("DomScroller.prototype.checkViewport",{checkViewport:a.ij.prototype.checkViewport});a.ij.prototype.Z9=function(a,b){if(1>=b-a){var c=this;this.DQ().then(function(a){null!=c.yW&&c.yW(a)},this.L6)}};a.ij.prototype.P4=
function(){var a=this.au;return 0<a[0].clientHeight&&a[0].scrollHeight>a[0].clientHeight?!0:!1};a.ij.prototype.DQ=function(){var a=this.qr-this.ZH;if(0<a){var b=this.Pq,c=this;a<this.Pq&&(b=a);var e=this.V6({pageSize:b});return a<this.Pq?new Promise(function(a){e.then(function(b){null!=b&&(b.maxCount=c.qr,b.maxCountLimit=!0,c.ZH=b.data.length+b.startIndex);a(b)})}):new Promise(function(a){e.then(function(b){null!=b&&(c.ZH=b.data.length+b.startIndex);a(b)})})}return Promise.resolve({maxCount:this.qr,
maxCountLimit:!0})};a.ij.prototype.V6=function(a){a=a||{};var b=a.pageSize;this.zj=this.zj?this.zj+b:b;if(-1==this.f.totalSize()||this.f.totalSize()>this.zj){var c=this;return new Promise(function(a,d){c.f.fetch({startIndex:c.zj,pageSize:b}).then(function(b){a(b)},function(){d(null)})})}return Promise.resolve()};a.gc=function(){};o_("PagingModel",a.gc,a);a.gc.prototype.getPage=function(){};a.b.i("PagingModel.prototype.getPage",{getPage:a.gc.prototype.getPage});a.gc.prototype.setPage=function(){};
a.b.i("PagingModel.prototype.setPage",{setPage:a.gc.prototype.setPage});a.gc.prototype.getStartItemIndex=function(){};a.b.i("PagingModel.prototype.getStartItemIndex",{getStartItemIndex:a.gc.prototype.getStartItemIndex});a.gc.prototype.getEndItemIndex=function(){};a.b.i("PagingModel.prototype.getEndItemIndex",{getEndItemIndex:a.gc.prototype.getEndItemIndex});a.gc.prototype.getPageCount=function(){};a.b.i("PagingModel.prototype.getPageCount",{getPageCount:a.gc.prototype.getPageCount});a.gc.prototype.totalSize=
function(){};a.b.i("PagingModel.prototype.totalSize",{totalSize:a.gc.prototype.totalSize});a.gc.J={BEFOREPAGE:"beforePage",PAGE:"page",PAGECOUNT:"pageCount"};o_("PagingModel.EventType",a.gc.J,a);a.pa=function(d){if(!(d instanceof a.R))throw Error(a.R.nc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+a.R.nc._ERR_DATA_INVALID_TYPE_DETAIL);this.Ec=d;this.Ai=this.aa=0;this.Init()};o_("PagingTableDataSource",a.pa,a);a.b.ga(a.pa,a.R,"oj.PagingTableDataSource");a.pa.prototype.Init=function(){a.pa.q.Init.call(this)};
a.b.i("PagingTableDataSource.prototype.Init",{Init:a.pa.prototype.Init});a.pa.prototype.getWrappedDataSource=function(){return this.Ec};a.b.i("PagingTableDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:a.pa.prototype.getWrappedDataSource});a.pa.prototype.getPage=function(){return"loadMore"==this.Ly?0:this.mz()};a.b.i("PagingTableDataSource.prototype.getPage",{getPage:a.pa.prototype.getPage});a.pa.prototype.setPage=function(d,b){b=b||{};d=parseInt(d,10);try{a.pa.q.handleEvent.call(this,
a.gc.J.BEFOREPAGE,{page:d,previousPage:this.mz()})}catch(c){return Promise.reject(null)}var e=this.mz();this.Ra=null!=b.pageSize?b.pageSize:this.Ra;b.pageSize=this.Ra;b.startIndex=d*this.Ra;this.aa=null==b.startIndex?this.aa:b.startIndex;this.Ly="page";var g=this;return new Promise(function(c,d){0<g.Ra?g.Ec.fetch(b).then(function(b){b.startIndex=0;g.SA();a.pa.q.handleEvent.call(g,a.gc.J.PAGE,{page:g.mz(),previousPage:e});c(null)},function(){g.aa=e*g.Ra;d(null)}):c(null)})};a.b.i("PagingTableDataSource.prototype.setPage",
{setPage:a.pa.prototype.setPage});a.pa.prototype.getStartItemIndex=function(){return"loadMore"==this.Ly?0:this.aa};a.b.i("PagingTableDataSource.prototype.getStartItemIndex",{getStartItemIndex:a.pa.prototype.getStartItemIndex});a.pa.prototype.getEndItemIndex=function(){return this.Ai};a.b.i("PagingTableDataSource.prototype.getEndItemIndex",{getEndItemIndex:a.pa.prototype.getEndItemIndex});a.pa.prototype.getPageCount=function(){var a=this.totalSize();return-1==a?-1:Math.ceil(a/this.Ra)};a.b.i("PagingTableDataSource.prototype.getPageCount",
{getPageCount:a.pa.prototype.getPageCount});a.pa.prototype.at=function(a,b){return this.Ec.at(a,b)};a.b.i("PagingTableDataSource.prototype.at",{at:a.pa.prototype.at});a.pa.prototype.fetch=function(a){a=a||{};if(null==a.startIndex)return this.setPage(this.getPage());this.Ly="loadMore";this.aa=null==a.startIndex?this.aa:a.startIndex;var b=null!=a.pageSize?a.pageSize:this.Ra;a.pageSize=b;a.startIndex=this.aa;var c=this;return new Promise(function(e,g){0<b?c.Ec.fetch(a).then(function(a){c.SA();e(a)},
function(a){g(a)}):e(null)})};a.b.i("PagingTableDataSource.prototype.fetch",{fetch:a.pa.prototype.fetch});a.pa.prototype.get=function(a,b){return this.Ec.get(a,b)};a.b.i("PagingTableDataSource.prototype.get",{get:a.pa.prototype.get});a.pa.prototype.getCapability=function(a){return this.Ec.getCapability(a)};a.b.i("PagingTableDataSource.prototype.getCapability",{getCapability:a.pa.prototype.getCapability});a.pa.prototype.on=function(d,b){var c=this,e=this.Ec;if(d==a.R.J.SYNC){var g=function(a){c.c$(a,
b)};e.on(d,g);return g}if(d==a.R.J.ADD||d==a.R.J.REMOVE||d==a.R.J.CHANGE)return g=function(a){c.V9(a,b)},e.on(d,g),g;if(d==a.R.J.REFRESH||d==a.R.J.RESET)return g=function(a){c.aa=0;b(a)},e.on(d,g),g;if(d==a.gc.J.PAGE||d==a.gc.J.PAGECOUNT)a.pa.q.on.call(this,d,b);else e.on(d,b);return b};a.b.i("PagingTableDataSource.prototype.on",{on:a.pa.prototype.on});a.pa.prototype.off=function(d,b){return d==a.gc.J.PAGE||d==a.gc.J.PAGECOUNT?(a.pa.q.off.call(this,d,b),b):this.Ec.off(d,b)};a.b.i("PagingTableDataSource.prototype.off",
{off:a.pa.prototype.off});a.pa.prototype.sort=function(a){return this.Ec.sort(a)};a.b.i("PagingTableDataSource.prototype.sort",{sort:a.pa.prototype.sort});a.pa.prototype.totalSize=function(){return this.Ec.totalSize()};a.b.i("PagingTableDataSource.prototype.totalSize",{totalSize:a.pa.prototype.totalSize});a.pa.prototype.mz=function(){return 0<this.Ra?Math.floor(this.aa/this.Ra):0};a.pa.prototype.V9=function(a,b){var c=[],e;for(e=0;e<a.indexes.length;e++){var g=a.indexes[e];void 0!==g&&(g-=this.aa,
(0>g||g>=this.aa+this.Ra)&&c.push(e))}if(0<c.length)for(c.sort(function(a,b){return a-b}),e=c.length-1;0<=e;e--)a.data.splice(c[e],1),a.indexes.splice(c[e],1),a.keys.splice(c[e],1);this.SA();a.startIndex=this.aa;b(a)};a.pa.prototype.c$=function(d,b){d.startIndex!=this.aa&&(this.aa=d.startIndex);this.SA();if("page"==this.Ly){var c={};a.Ac.Pf(c,d);c.startIndex=0;b(c)}else b(d)};a.pa.prototype.SA=function(){var a=this.totalSize();this.Ai=this.aa+this.Ra-1;0<a&&(this.Ai=this.Ai>a-1?a-1:this.Ai)};a.pa.J=
{ADD:"add",REMOVE:"remove",RESET:"reset",SYNC:"sync",REFRESH:"refresh",SORT:"sort"};o_("PagingTableDataSource.EventType",a.pa.J,a);a.Fe=function(d,b,c,e){a.j.pc(d,null);a.j.pc(b,null);this.Gga=e;this.qn=d;this.EB=b;this.tf=c};o_("JsonNodeSet",a.Fe,a);a.Fe.prototype.getParent=function(){return this.Gga};a.b.i("JsonNodeSet.prototype.getParent",{getParent:a.Fe.prototype.getParent});a.Fe.prototype.ua=function(){return this.qn};a.b.i("JsonNodeSet.prototype.getStart",{ua:a.Fe.prototype.ua});a.Fe.prototype.Q=
function(){return Math.max(0,this.EB-this.qn)};a.b.i("JsonNodeSet.prototype.getCount",{Q:a.Fe.prototype.Q});a.Fe.prototype.getData=function(d){a.j.assert(d<=this.EB&&d>=this.qn);d-=this.qn;return this.tf[d]?this.tf[d].attr:null};a.b.i("JsonNodeSet.prototype.getData",{getData:a.Fe.prototype.getData});a.Fe.prototype.getMetadata=function(d){var b=[];a.j.assert(d<=this.EB&&d>=this.qn);d-=this.qn;b.key=this.tf[d].id?this.tf[d].id:this.tf[d].attr.id;b.leaf=this.tf[d].pK;b.depth=this.tf[d].depth;null==b.leaf&&
(b.leaf=this.tf[d].children&&0<this.tf[d].children.length?!1:!0);return b};a.b.i("JsonNodeSet.prototype.getMetadata",{getMetadata:a.Fe.prototype.getMetadata});a.Fe.prototype.fl=function(a,b){var c;b++;a.depth=b;if(a.children&&0!=a.children.length)for(c=0;c<a.children.length;c++)this.fl(a.children[c],b)};a.Fe.prototype.pf=function(d){var b,c,e;a.j.assert(d<=this.EB&&d>=this.qn);d-=this.qn;c=this.tf[d].depth;b=this.tf[d].children;if(0==b.length)return null;d=this.tf[d].id?this.tf[d].id:this.tf[d].attr.id;
for(e=0;e<b.length;e++)this.fl(b[e],c);return new a.Fe(0,b.length,b,d)};a.b.i("JsonNodeSet.prototype.getChildNodeSet",{pf:a.Fe.prototype.pf});a.fc=function(d){a.fc.q.constructor.call(this,d)};o_("DataGridDataSource",a.fc,a);a.b.ga(a.fc,a.Mg,"oj.DataGridDataSource");a.fc.prototype.Q=function(){return 0};a.b.i("DataGridDataSource.prototype.getCount",{Q:a.fc.prototype.Q});a.fc.prototype.Rf=function(){return"exact"};a.b.i("DataGridDataSource.prototype.getCountPrecision",{Rf:a.fc.prototype.Rf});a.fc.prototype.Sd=
function(){a.j.Xa()};a.b.i("DataGridDataSource.prototype.fetchHeaders",{Sd:a.fc.prototype.Sd});a.fc.prototype.ke=function(){a.j.Xa()};a.b.i("DataGridDataSource.prototype.fetchCells",{ke:a.fc.prototype.ke});a.fc.prototype.keys=function(){a.j.Xa();return null};a.b.i("DataGridDataSource.prototype.keys",{keys:a.fc.prototype.keys});a.fc.prototype.oe=function(){a.j.Xa();return null};a.b.i("DataGridDataSource.prototype.indexes",{oe:a.fc.prototype.oe});a.fc.prototype.sort=function(){a.j.Xa()};a.b.i("DataGridDataSource.prototype.sort",
{sort:a.fc.prototype.sort});a.fc.prototype.move=function(){a.j.Xa()};a.b.i("DataGridDataSource.prototype.move",{move:a.fc.prototype.move});a.fc.prototype.Zi=function(){return"valid"};a.b.i("DataGridDataSource.prototype.moveOK",{Zi:a.fc.prototype.Zi});a.fc.prototype.getCapability=function(){return null};a.b.i("DataGridDataSource.prototype.getCapability",{getCapability:a.fc.prototype.getCapability})});