/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/internal-deps/datagrid/DvtDataGrid","ojs/ojcomponentcore","ojs/ojdatacollection-common","ojs/ojinputnumber","ojs/ojmenu","ojs/ojdialog","ojs/ojpagingcontrol"],function(a,f,d){a.gb=function(b,c){if(!(b instanceof Array)&&"function"!=typeof b&&"function"!=typeof b.wha)throw Error("_ERR_DATA_INVALID_TYPE_SUMMARY\n_ERR_DATA_INVALID_TYPE_DETAIL");null!=c&&(this.Fp=c.rowHeader,this.columns=c.columns);a.gb.q.constructor.call(this,b)};o_("ArrayDataGridDataSource",a.gb,a);
a.b.ga(a.gb,a.fc,"oj.ArrayDataGridDataSource");a.gb.prototype.Init=function(){null==this.columns&&(this.columns=this.z7(this.Vi()));this.P$();"function"==typeof this.data&&this.data.subscribe(this.Rda.bind(this),null,"arrayChange");a.gb.q.Init.call(this)};a.b.i("ArrayDataGridDataSource.prototype.Init",{Init:a.gb.prototype.Init});a.gb.prototype.P$=function(){var a;a=this.Vi();for(this.tp=0;this.tp<a.length;this.tp+=1)a[this.tp].ojKey=this.tp.toString()};a.gb.prototype.z7=function(a){var c,d;if("number"!==
typeof a.length||0===a.length)return[];d=[];for(c in a[0])a[0].hasOwnProperty(c)&&(void 0!=this.Fp&&c==this.Fp||d.push(c));return d};a.gb.prototype.Q=function(a){return"row"===a?this.Mi():"column"===a?this.columns.length:0};a.b.i("ArrayDataGridDataSource.prototype.getCount",{Q:a.gb.prototype.Q});a.gb.prototype.pR=function(a,c){var d;if("row"===a)return d=this.Vi(),void 0!=this.Fp?d[c][this.Fp]:0<d.length&&d[0]instanceof Array?void 0===this.uu(c)?c.toString():this.uu(c):null;if("column"===a)return this.columns[c]};
a.gb.prototype.Y7=function(a,c){return"row"===a&&void 0!=this.Fp?{key:this.uu(c)}:{key:this.pR(a,c)}};a.gb.prototype.Sd=function(b,c,d){var g,f,k,l;g=b.axis;f=b.start;k=b.count;a.j.assert("row"===g||"column"===g);a.j.assert(f<this.Q(g));a.j.assert(0<k);f=Math.max(0,f);"column"===g?k=Math.min(this.columns.length,f+k):(l=this.Vi(),k=void 0!==this.Fp||0<l.length&&l[0]instanceof Array?Math.min(l.length,f+k):f);g=new a.sd(f,k,g,this);null!=c&&null!=c.success&&(null==d&&(d={}),c.success.call(d.success,
g,b))};a.b.i("ArrayDataGridDataSource.prototype.fetchHeaders",{Sd:a.gb.prototype.Sd});a.gb.prototype.s7=function(a,c){var d=this.columns[c];return this.Vi()[a][d]};a.gb.prototype.t7=function(a,c){return{keys:{row:this.uu(a),column:this.columns[c]}}};a.gb.prototype.ke=function(b,c,d){var g,f,k,l,m,n;for(g=0;g<b.length;g+=1)f=b[g],a.j.assert("row"===f.axis||"column"===f.axis),a.j.assert(f.start<this.Q(f.axis)),a.j.assert(0<f.count),"row"===f.axis?(k=f.start,l=Math.min(this.Mi(),k+f.count)):"column"===
f.axis&&(m=f.start,n=Math.min(this.columns.length,m+f.count));void 0===l||void 0===n?null!=c&&null!=c.error&&(null==d&&(d={}),c.error.call(d.error)):(g=new a.wf(k,l,m,n,this),null!=c&&null!=c.success&&(null==d&&(d={}),c.success.call(d.success,g,b)))};a.b.i("ArrayDataGridDataSource.prototype.fetchCells",{ke:a.gb.prototype.ke});a.gb.prototype.keys=function(a){var c=a.row,d=a.column;return new Promise(function(a){a({row:this.uu(c),column:this.columns[d]})}.bind(this))};a.b.i("ArrayDataGridDataSource.prototype.keys",
{keys:a.gb.prototype.keys});a.gb.prototype.oe=function(a){var c=a.row,d=a.column;return new Promise(function(a){a({row:this.qz(c),column:this.columns.indexOf(d)})}.bind(this))};a.b.i("ArrayDataGridDataSource.prototype.indexes",{oe:a.gb.prototype.oe});a.gb.prototype.sort=function(a,c,d){var g=[],f=[],k,l;null!=c&&null==d&&(d={});if(null==a)this.XH(c,d);else if(k=a.axis,l=a.key,a=a.direction,"column"===k)void 0==this.Bp&&(this.Bp=this.data.slice()),this.Vi().sort(this.ZT(a,l)),null!=c&&null!=c.success&&
c.success.call(d.success);else if("row"===k){l=this.qz(l);for(k=0;k<this.columns.length;k+=1)g[k]=this.Vi()[l][this.columns[k]];g.sort(this.ZT(a));for(k=0;k<this.columns.length;k+=1)f[k]=this.columns[g.indexOf(this.Vi()[l][this.columns[k]])];this.PZ=this.columns;this.columns=f;null!=c&&null!=c.success&&c.success.call(d.success)}else null!==c&&null!=c.error&&c.error.call(d.error,"Invalid axis value")};a.b.i("ArrayDataGridDataSource.prototype.sort",{sort:a.gb.prototype.sort});a.gb.prototype.XH=function(a,
c){null!=this.Bp&&(this.data=this.Bp);null!=this.PZ&&(this.columns=this.PZ);null!=a&&null!=a.success&&a.success.call(c.success)};a.gb.prototype.getCapability=function(a){return"sort"===a?"column":"move"===a?"row":null};a.b.i("ArrayDataGridDataSource.prototype.getCapability",{getCapability:a.gb.prototype.getCapability});a.gb.prototype.ZT=function(a,c){if("ascending"===a)return function(a,b){var d,f;void 0!=c&&(a instanceof Array?(a=a[parseInt(c,10)],b=b[parseInt(c,10)]):(a=a[c],b=b[c]));d=isNaN(a);
f=isNaN(b);a instanceof Date&&(a=a.toISOString(),d=!0);b instanceof Date&&(b=b.toISOString(),f=!0);return d&&f?a<b?-1:a===b?0:1:d?1:f?-1:a-b};if("descending"===a)return function(a,b){var d,f;void 0!=c&&(a instanceof Array?(a=a[parseInt(c,10)],b=b[parseInt(c,10)]):(a=a[c],b=b[c]));d=isNaN(a);f=isNaN(b);a instanceof Date&&(a=a.toISOString(),d=!0);b instanceof Date&&(b=b.toISOString(),f=!0);return d&&f?a>b?-1:a===b?0:1:d?-1:f?1:b-a}};a.gb.prototype.move=function(a,c){var d,g,f;d=this.qz(a);g=this.data.splice(d,
1)[0];this.data instanceof Array&&(d=this.Cj("delete",a,null,d,-1,!0),this.handleEvent("change",d));null===c?this.data.push(g):(f=this.qz(c),this.data.splice(f,0,g));this.data instanceof Array&&(d=this.Cj("insert",a,null,f,-1),this.handleEvent("change",d));null!=this.Bp&&(this.Bp=this.data.slice())};a.b.i("ArrayDataGridDataSource.prototype.move",{move:a.gb.prototype.move});a.gb.prototype.Vi=function(){return"function"===typeof this.data?this.data():this.data};a.gb.prototype.qz=function(a){var c,d=
this.Vi();for(c=0;c<d.length;c++)if(d[c].ojKey===a)return c;return-1};a.gb.prototype.uu=function(a){var c=this.Vi();return c[a]?c[a].ojKey:null};a.gb.prototype.Cj=function(a,c,d,g,f,k){var l={source:this};l.operation=a;l.keys={row:c,column:d};l.indexes={row:g,column:f};l.silent=k;return l};a.gb.prototype.Rda=function(a){var c,d,g,f=!1;d=!1;var k=[],l=[];for(c=0;c<a.length;c++){g=a[c];if(void 0!==g.moved){d=!0;g=this.Cj("refresh",null,null);this.handleEvent("change",g);break}"added"===g.status&&(f=
!0)}if(!d){for(c=0;c<a.length;c++)g=a[c],"deleted"===g.status&&(d=g.value,g=g.index,d=d.ojKey,k.push({row:d,column:-1}),l.push({row:g,column:-1}));0<k.length&&(g={source:this,operation:"delete",keys:k,indexes:l,silent:f},this.handleEvent("change",g));for(c=0;c<a.length;c++)g=a[c],"added"===g.status&&(d=g.value,g=g.index,null==d.ojKey&&(d.ojKey=this.tp.toString(),this.tp++),d=d.ojKey,g=this.Cj("insert",d,null,g,-1),this.handleEvent("change",g))}null!=this.Bp&&(this.Bp=this.data.slice())};a.gb.prototype.Mi=
function(){return this.Vi().length};a.gb.prototype.AY=function(){return this.Fp};a.b.i("ArrayDataGridDataSource.prototype.getRowHeaderKey",{AY:a.gb.prototype.AY});a.gb.prototype.gn=function(){return this.columns};a.b.i("ArrayDataGridDataSource.prototype.getColumns",{gn:a.gb.prototype.gn});a.gb.prototype.getData=function(){return this.data};a.b.i("ArrayDataGridDataSource.prototype.getData",{getData:a.gb.prototype.getData});a.wh=function(b,c){this.gha=b;this.Bha=c;this.Pa={};this.Pa.datagrid="oj-datagrid";
this.Pa.cell="oj-datagrid-cell";this.Pa.cellcontent="oj-datagrid-cell-content";this.Pa.celltext="oj-datagrid-cell-text";this.Pa.banded="oj-datagrid-banded";this.Pa.row="oj-datagrid-row";this.Pa.databody="oj-datagrid-databody";this.Pa.topcorner="oj-datagrid-top-corner";this.Pa.bottomcorner="oj-datagrid-bottom-corner";this.Pa.rowheaderspacer="oj-datagrid-row-header-spacer";this.Pa.colheaderspacer="oj-datagrid-column-header-spacer";this.Pa.status="oj-datagrid-status";this.Pa.emptytext="oj-datagrid-empty-text";
this.Pa.header="oj-datagrid-header";this.Pa.groupingcontainer="oj-datagrid-header-grouping";this.Pa.headercell="oj-datagrid-header-cell";this.Pa.headercelltext="oj-datagrid-header-cell-text";this.Pa.headercellcontent="oj-datagrid-header-cell-content";this.Pa.rowheader="oj-datagrid-row-header";this.Pa.colheader="oj-datagrid-column-header";this.Pa.colheadercell="oj-datagrid-column-header-cell";this.Pa.rowheadercell="oj-datagrid-row-header-cell";this.Pa["scroller-mobile"]="oj-datagrid-scroller-touch";
this.Pa.scroller="oj-datagrid-scroller";this.Pa.scrollers="oj-datagrid-scrollers";this.Pa.focus="oj-focus";this.Pa.hover="oj-hover";this.Pa.active="oj-active";this.Pa.selected="oj-selected";this.Pa.disabled="oj-disabled";this.Pa.enabled="oj-enabled";this.Pa["default"]="oj-default";this.Pa.sortcontainer="oj-datagrid-sort-icon-container";this.Pa.sortascending="oj-datagrid-sort-ascending-icon";this.Pa.sortdescending="oj-datagrid-sort-descending-icon";this.Pa.icon="oj-component-icon";this.Pa.clickableicon=
"oj-clickable-icon-nocontext";this.Pa.info="oj-helper-hidden-accessible";this.Pa.rowexpander="oj-rowexpander";this.Pa.cut="oj-datagrid-cut";this.Pa.selectaffordancetop="oj-datagrid-touch-selection-affordance-top";this.Pa.selectaffordancebottom="oj-datagrid-touch-selection-affordance-bottom";this.Pa.toucharea="oj-datagrid-touch-area";this.Pa.draggable="oj-draggable";this.Pa.drag="oj-drag";this.Pa.drop="oj-drop";this.Pa.activedrop="oj-active-drop";this.Pa.validdrop="oj-valid-drop";this.Pa.invaliddrop=
"oj-invalid-drop";this.Bg={};this.Bg.sortCol="oj-datagrid-sortCol";this.Bg.sortColAsc="oj-datagrid-sortColAsc";this.Bg.sortColDsc="oj-datagrid-sortColDsc";this.Bg.sortRow="oj-datagrid-sortRow";this.Bg.sortRowAsc="oj-datagrid-sortRowAsc";this.Bg.sortRowDsc="oj-datagrid-sortRowDsc";this.Bg.resize="oj-datagrid-resize";this.Bg.resizeWidth="oj-datagrid-resizeWidth";this.Bg.resizeHeight="oj-datagrid-resizeHeight";this.Bg.cut="oj-datagrid-cut";this.Bg.paste="oj-datagrid-paste";this.Bg.discontiguousSelection=
"oj-datagrid-discontiguousSelection";this.attributes={};this.attributes.key="data-oj-key";this.attributes.resizable="data-oj-resizable";this.attributes.sortable="data-oj-sortable";this.attributes.sortDir="data-oj-sortdir";this.attributes.expander="data-oj-expander";this.attributes.expanderIndex="data-oj-expander-index";this.attributes.container=a.Components.Cx;this.attributes.extent="data-oj-extent";this.attributes.start="data-oj-start";this.attributes.depth="data-oj-depth";this.attributes.level=
"data-oj-level"};o_("DataGridResources",a.wh,a);a.wh.prototype.iZ=function(){return"rtl"===this.gha?!0:!1};a.b.i("DataGridResources.prototype.isRTLMode",{iZ:a.wh.prototype.iZ});a.wh.prototype.NY=function(a,c){return this.Bha(a,c)};a.b.i("DataGridResources.prototype.getTranslatedText",{NY:a.wh.prototype.NY});a.wh.prototype.OJ=function(a){return null!=a?this.Pa[a]:null};a.b.i("DataGridResources.prototype.getMappedStyle",{OJ:a.wh.prototype.OJ});a.wh.prototype.sB=function(a){return null!=a?this.Bg[a]:
null};a.b.i("DataGridResources.prototype.getMappedCommand",{sB:a.wh.prototype.sB});a.wh.prototype.NJ=function(a){return null!=a?this.attributes[a]:null};a.b.i("DataGridResources.prototype.getMappedAttribute",{NJ:a.wh.prototype.NJ});a.Da("oj.ojDataGrid",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{bandingInterval:{row:0,column:0},data:null,gridlines:{horizontal:"visible",vertical:"visible"},scrollPosition:null,selectionMode:null,dnd:{reorder:{row:"disable"}},scrollPolicy:"auto",selection:[],
header:{row:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",style:null},column:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",style:null}},cell:{className:null,renderer:null,style:null},resize:null,sort:null,optionChange:null},_ComponentCreate:function(){this._super();this.root=this.element[0];this.Jg=this.root.getAttribute("id");this.grid=new d;this.grid.setVisibility(d.VISIBILITY_STATE_RENDER);f(this.root).addClass("oj-datagrid oj-component");
this.PK={data:"all",header:["className","renderer","style","template"]}},Sg:function(){var b=this;this.Ov(this.root);f(this.root).empty();this._super();this.Ep=new a.wh(this.hc(),this.kG.bind(b));this.JV();this.Bv();null!=this.kc&&(this.gO(),this.grid.SetDataSource(this.kc));this.grid.SetOptions(this.options);this.grid.SetResources(this.Ep);this.grid.SetCreateContextCallback(this.Uaa.bind(b));this.grid.SetRemoveCallback(this.PH.bind(b));this.grid.addListener("resize",function(a){b._trigger("resize",
a.event,a.ui)});this.grid.addListener("select",function(a){b.option("selection",a.ui.selection,{_context:{originalEvent:a.event,mb:!0},changed:!0})});this.grid.addListener("sort",function(a){b._trigger("sort",a.event,a.ui)});this.grid.addListener("keydown",function(a){b._trigger("keydown",a.event,a.ui)});this.grid.addListener("active",function(a){b._trigger("active",a.event,a.ui)});this.gv();null!=this.kc&&this.Pm(this.root)},refresh:function(){this._super();this.Ov(this.root);f(this.root).empty();
!0===this.Cea&&(this.options.contextMenu=null);this.JV();null!=this.kc&&(this.kc instanceof a.Ya&&(this.kc.Ae(),this.kc.Init()),this.gO(),this.grid.SetDataSource(this.kc));this.grid.SetOptions(this.options);this.grid.SetResources(this.Ep);this.grid.getVisibility()!=d.VISIBILITY_STATE_RENDER&&this.grid.setVisibility(d.VISIBILITY_STATE_REFRESH);this.gv();null!=this.kc&&this.Pm(this.root)},_destroy:function(){null!=this.kc&&this.kc.Ae&&this.kc.Ae();this.grid.destroy();this.Ov(this.root);f(this.root).empty()},
_setOptions:function(a,c){var d;this.kc?(d=this.Gda(a),this._super(a,c),d?this.refresh():this.grid.UpdateOptions(a)):(this._super(a,c),null!=a.data&&this.refresh())},tk:function(){this._super();this.gv()},$l:function(){this._super();this.grid.getVisibility()===d.VISIBILITY_STATE_VISIBLE&&this.grid.setVisibility(d.VISIBILITY_STATE_HIDDEN)},Zl:function(){this._super();this.gv()},ti:function(){this._super();this.grid.getVisibility()===d.VISIBILITY_STATE_VISIBLE&&this.grid.setVisibility(d.VISIBILITY_STATE_HIDDEN)},
Gda:function(b){var c,d,g,f,k,l;g=!1;for(d in b)if(d in this.PK)if("data"===d){g=!0;break}else if("header"==d)for(f in b.header){if("column"==f||"row"==f||"cell"==f)for(k in b.header[f]){for(c=0;c<this.PK.header.length;c++)if(k==this.PK.header[c])for(l in this.options.header[f])if(l==k&&b.header[f][k]!=this.options.header[f][k]){g=!0;break}if(g)break}if(g)break}else for(l in this.options)if(l==d&&!a.b.Cg(b[d],this.options[l])){g=!0;break}return g},Lz:function(a,c){return this.options.header[a]&&this.options.header[a].resizable?
"disable"!==this.options.header[a].resizable[c]:!1},vT:function(a){return this.options.header[a]?"disable"!==this.options.header[a].sortable:!1},gO:function(){var b,c,d=null,g=null,h=null,k=null,l,m;b=this;if(null==this.options.contextMenu){if(null!=this.kc){c=f("\x3cul\x3e");c.css("display","none").attr("id",this.Jg+"contextmenu");f(this.root).append(c);if(this.Lz("column","width")||this.Lz("column","height")||this.Lz("row","width")||this.Lz("row","height"))d=this.yi("resize");l=this.kc.getCapability("sort");
!this.vT("column")||"column"!==l&&"full"!==l||(g=this.yi("sortCol"));!this.vT("row")||"row"!==l&&"full"!==l||(g=null!=g?g.add(this.yi("sortRow")):this.yi("sortRow"));if("enable"===this.options.dnd.reorder.row)switch(this.kc.getCapability("move")){case "none":break;default:k=this.Hf("cut").add(this.Hf("paste"))}this.Fi()&&a.C.sf()&&(this.Ey=!1,h=this.Hf("discontiguousSelection"));if(null!=d||null!=g||null!=k||null!=h)c.append(d).append(g).append(k).append(h),c.ojMenu(),this.Cea=!0,this._setOption("contextMenu",
"#"+c.attr("id")),c.on("ojselect",this.Ei.bind(this))}}else null==this.iH&&(this.iH=[]),c=f(this.options.contextMenu),d=c.find("[data-oj-command]"),m=[],d.each(function(){var a;a=f(this).children("a");if(0===a.length||-1!=b.iH.indexOf(a.get(0)))a=f(this).attr("data-oj-command").split("-"),a=b.yi(a[a.length-1]),f(this).replaceWith(a),m.push(a.children("a").get(0))}),this.iH=m,c.ojMenu("refresh"),c.on("ojselect",this.Ei.bind(this))},yi:function(a){if("resize"===a)return this.Hf("resize").append(f("\x3cul\x3e\x3c/ul\x3e").append(this.Hf("resizeWidth")).append(this.Hf("resizeHeight")));
if("sortCol"===a)return this.Hf("sortCol").append(f("\x3cul\x3e\x3c/ul\x3e").append(this.Hf("sortColAsc")).append(this.Hf("sortColDsc")));if("sortRow"===a)return this.Hf("sortRow").append(f("\x3cul\x3e\x3c/ul\x3e").append(this.Hf("sortRowAsc")).append(this.Hf("sortRowDsc")));if(-1!=Object.keys(this.Ep.Bg).indexOf(a))return f(this.Hf(a))},Hf:function(a){var c=f("\x3cli\x3e\x3c/li\x3e");c.attr("data-oj-command",this.Kk(a));c.append(this.YD(a));return c},YD:function(a){var c="label"+a.charAt(0).toUpperCase()+
a.slice(1);"discontiguousSelection"===a&&(c="labelEnableNonContiguous");return f('\x3ca href\x3d"#"\x3e\x3c/a\x3e').text(this.kG(c))},eR:function(){return f(this.options.contextMenu).get(0)},kG:function(a,c){return this.D(a,c)},U9:function(){var a=f("#"+this.Jg+"spinner").ojInputNumber("option","value");f("#"+this.Jg+"dialog").ojDialog("close");this.grid.handleContextMenuReturn(this.bs,this.Yi,a);this.bs.target.focus()},z4:function(a,c){var d,g,h,k,l;d=f("#"+this.Jg+"dialog");h=f("#"+this.Jg+"spinner");
0===d.length||0===h.length?(d=f("\x3cdiv\x3e"),d.attr("id",this.Jg+"dialog"),d.attr("title",a),g=f('\x3cdiv class\x3d"oj-dialog-body"\x3e\x3c/div\x3e'),k=f('\x3cdiv class\x3d"oj-dialog-footer"\x3e\x3c/div\x3e'),d.append(g).append(k),h=f('\x3cinput id\x3d"'+this.Jg+'spinner"/\x3e'),l=f('\x3cbutton id\x3d"'+this.Jg+'dialogsubmit"/\x3e'),g.append(h),k.append(l),f(this.root).append(d),l.ojButton({Aa:"ojButton",label:"OK"}),l.on("click",this.U9.bind(this)),h.ojInputNumber({Aa:"ojInputNumber",max:1E3,min:20,
step:1,value:c}),d.ojDialog({initialVisibility:"show",position:{my:"center center",at:"center center",collision:"none",of:f(this.root)}})):(h.ojInputNumber("option","value",c),f("#"+this.Jg+"dialog").ojDialog("open"))},Ei:function(a,c){var d;this.Yi=c.item.attr("data-oj-command");this.Yi===this.Kk("sortColAsc")||this.Yi===this.Kk("sortColDsc")||this.Yi===this.Kk("cut")||this.Yi===this.Kk("paste")?this.grid.handleContextMenuReturn(this.bs,this.Yi,null):this.Yi===this.Kk("resizeWidth")||this.Yi===this.Kk("resizeHeight")?
(d=f(this.bs.target).closest("."+this.ef("cell")),0==d.length&&(d=f(this.bs.target).closest("."+this.ef("headercell"))),0<d.length&&(d=this.Yi===this.Kk("resizeWidth")?d.outerWidth():d.outerHeight(),this.z4(c.item.text(),d))):this.Yi===this.Kk("discontiguousSelection")&&(this.Ey=!this.Ey,this.grid.handleContextMenuReturn(this.bs,this.Yi,this.Ey),d=this.Ey?"labelDisableNonContiguous":"labelEnableNonContiguous",c.item.children().first().text(this.kG(d)))},Xe:function(a,c,d){this.grid.handleContextMenuGesture(c,
d,this.o5.bind(this))},o5:function(a,c,d){var g;null!=a&&(this.bs=c.originalEvent,g=a.launcher,a=a.capabilities,this.Kaa(a),g="keyboard"===d?{position:{of:g},launcher:f(g)}:{launcher:f(g)},this.Ye(c,d,g))},C3:function(a){var c;c=f(this.eR());c.find("[data-oj-command\x3d"+a+"]").hasClass("oj-disabled")||c.find("[data-oj-command\x3d"+a+"]").addClass("oj-disabled")},mca:function(a){f(this.eR()).find("[data-oj-command\x3d"+a+"]").removeClass("oj-disabled")},Kaa:function(a){var c,d;for(c in a)a.hasOwnProperty(c)&&
(d=this.Ep.sB(c),"disable"===a[c]?this.C3(d):this.mca(d))},c7:function(a){var c;c=a.parent();a=a.index();return{rowIndex:c.index()-1,columnIndex:a}},Zha:function(a){var c;c=this.B8().children().eq(0).children().eq(a.rowIndex+1);a=this.y7().children().eq(0).children().eq(a.columnIndex);return{rowHeader:c,columnHeader:a}},mR:function(){return f(this.root)},y7:function(){return f("#"+this.Jg+"\\:columnHeader")},B8:function(){return f("#"+this.Jg+"\\:rowHeader")},F7:function(){return f("#"+this.Jg+"\\:databody ."+
this.ef("row"))},JV:function(){this.kc=null!=this.options.data?this.options.data:null},Bv:function(){var a=this.options.selection;null!=a&&this.grid.SetSelection(a)},Uaa:function(a){a.component=this},sA:function(a){this.grid.SetAccessibleContext(a)},Ov:function(b){b&&this.ah&&a.C.cj(b,this.ah)},Pm:function(b){b&&(null==this.ah&&(this.ah=this.Mf.bind(this)),a.C.fh(b,this.ah))},Mf:function(a,c){0<a&&0<c&&(this.gv(),this.grid.HandleResize(a,c))},getNodeBySubId:function(a){var c,d,g,h;if(null==a)return this.element?
this.element[0]:null;c=a.subId;return"oj-datagrid-cell"===c?(c=a.rowIndex-this.grid.getStartRow(),a=a.columnIndex-this.grid.getStartColumn(),this.F7().eq(c).children().eq(a).get(0)):"oj-datagrid-sort-icon"===c||"oj-datagrid-header"===c?(h=a.axis,g=a.index,a=null==a.level?0:a.level,"column"===h?d=this.oR(g,a,f("#"+this.Jg+"\\:columnHeader"),this.grid.getStartColumnHeader()):"row"===h&&(d=this.oR(g,a,f("#"+this.Jg+"\\:rowHeader"),this.grid.getStartRowHeader())),null==d?null:"oj-datagrid-sort-icon"===
c?d.children("."+this.ef("sortcontainer")).children().get(0):d.get(0)):null},getSubIdByNode:function(a){var c,d,g;c=f(a).closest("."+this.ef("cell"));if(0<c.length)return a=this.c7(c),{subId:"oj-datagrid-cell",rowIndex:a.rowIndex+this.grid.getStartRow(),columnIndex:a.columnIndex+this.grid.getStartColumn()};d=f(a).closest("."+this.ef("headercell"));return 0<d.length?(g=d.hasClass(this.ef("colheadercell"))?"column":"row",c=this.W7(d),d=this.X7(d),a=f(a).hasClass(this.ef("sortascending"))||f(a).hasClass(this.ef("sortdescending"))?
"oj-datagrid-sort-icon":"oj-datagrid-header",{subId:a,index:c,axis:g,level:d}):null},ef:function(a){return this.Ep.OJ(a)},Uq:function(a){return this.Ep.NJ(a)},Kk:function(a){return this.Ep.sB(a)},aaa:function(){return null!=this.root.offsetParent?!0:!1},gv:function(){var a=this.grid.getVisibility();this.aaa()?(a===d.VISIBILITY_STATE_RENDER?this.grid.render(this.root):a===d.VISIBILITY_STATE_REFRESH&&this.grid.refresh(this.root),this.grid.setVisibility(d.VISIBILITY_STATE_VISIBLE)):a===d.VISIBILITY_STATE_VISIBLE&&
this.grid.setVisibility(d.VISIBILITY_STATE_HIDDEN)},oR:function(a,c,d,g){if(0>c)return null;if(d.children().first().children().last().hasClass(this.ef("headercell")))return d.children().first().children("."+this.ef("headercell")).eq(a-g);d=this.nR(a,c,0,d.children().first().children());return null==d?null:c!=parseInt(d.attr(this.Uq("level")),10)?(g=parseInt(d.attr(this.Uq("start")),10),a=a-g+1,d.children().eq(a)):d.children().eq(0)},nR:function(a,c,d,g){var f,k,l;if(null==g.eq(1)||g.eq(1).hasClass(this.ef("headercell")))return c===
d?g.eq(0).parent():null;for(l=g.parent().parent().hasClass(this.ef("colheader"))?0:1;l<g.length;l++)if(f=parseInt(g.eq(l).attr(this.Uq("start")),10),k=parseInt(g.eq(l).attr(this.Uq("extent")),10),a>=f&&a<f+k)return c===d?g.eq(l):this.nR(a,c,d+1,g.eq(l).children());return null},W7:function(a){var c;if(a.parent().hasClass(this.ef("groupingcontainer"))){c=parseInt(a.parent().attr(this.Uq("start")),10);if(a.get(0)===a.parent().children(":first").get(0))return c;c--}else c=a.hasClass(this.ef("rowheadercell"))?
this.grid.getStartRowHeader()-1:this.grid.getStartColumnHeader();return c+=a.index()},X7:function(a){var c;return a.parent().hasClass(this.ef("groupingcontainer"))?(c=parseInt(a.parent().attr(this.Uq("level")),10),a.get(0)===a.parent().children(":first").get(0)?c:c+1):0},Fi:function(){return null==this.options.selectionMode||"multiple"!==this.options.selectionMode.row&&"multiple"!==this.options.selectionMode.cell?!1:!0},PH:function(a){f(a).remove()}});a.xh=function(b,c,d,g,f,k){a.j.pc(b,null);a.j.pc(c,
null);a.j.pc(d,null);a.j.pc(g,null);a.j.Xv(k);this.$h=b;this.wp=c;this.ak=d;this.vp=g;this.zb=f;this.Fd=k};o_("FlattenedTreeCellSet",a.xh,a);a.xh.prototype.getData=function(b){var c;c=this.OR(b);if(null==c)return null;b=c[0];c=c[1];a.j.assert(b<this.zb.ua()+this.zb.Q()&&c<this.Fd.length);c=this.Fd[c];b=this.zb.getData(b);return null!=b?b.get?b.get(c):b[c]:null};a.b.i("FlattenedTreeCellSet.prototype.getData",{getData:a.xh.prototype.getData});a.xh.prototype.getMetadata=function(b){var c;c=this.OR(b);
if(null==c)return null;b=c[0];c=c[1];a.j.assert(b<this.zb.ua()+this.zb.Q()&&c<this.Fd.length);c=this.Fd[c];b=this.zb.getMetadata(b);b.keys={row:b.key,column:c};return b};a.b.i("FlattenedTreeCellSet.prototype.getMetadata",{getMetadata:a.xh.prototype.getMetadata});a.xh.prototype.OR=function(b){var c;a.j.ie(b);if(null==this.zb||0==this.zb.length)return null;c=b.row-this.$h+this.zb.ua();b=b.column;a.j.pc(c,null);a.j.pc(b,null);a.j.assert(0<=c&&0<=b);return[c,b]};a.xh.prototype.ua=function(a){return"row"===
a?this.$h:"column"===a?this.ak:0};a.b.i("FlattenedTreeCellSet.prototype.getStart",{ua:a.xh.prototype.ua});a.xh.prototype.Q=function(a){return"row"===a?Math.min(this.wp-this.$h,this.zb.Q()):"column"===a?this.vp-this.ak:0};a.b.i("FlattenedTreeCellSet.prototype.getCount",{Q:a.xh.prototype.Q});a.Qe=function(b,c,d,g,f){a.j.pc(b,null);a.j.pc(c,null);a.j.Xv(d);this.ec=b;this.Ud=c;this.FB=d;this.zb=g;this.Yf=f};o_("FlattenedTreeHeaderSet",a.Qe,a);a.Qe.prototype.getData=function(b,c){var d;a.j.assert(b<=this.Ud&&
b>=this.ec,"index out of bounds");a.j.assert(null==c||0==c,"level out of bounds");return null!=this.Yf&&null!=this.zb?(d=this.zb.getData(b),null!=d?d.get?d.get(this.Yf):d[this.Yf]:null):this.FB[b]};a.b.i("FlattenedTreeHeaderSet.prototype.getData",{getData:a.Qe.prototype.getData});a.Qe.prototype.getMetadata=function(b,c){a.j.assert(b<=this.Ud&&b>=this.ec,"index out of bounds");a.j.assert(null==c||0==c,"level out of bounds");return null!=this.Yf&&null!=this.zb?this.zb.getMetadata(b):{key:this.getData(b)}};
a.b.i("FlattenedTreeHeaderSet.prototype.getMetadata",{getMetadata:a.Qe.prototype.getMetadata});a.Qe.prototype.Q=function(){return null!=this.Yf&&null!=this.zb?Math.min(this.zb.Q(),this.Ud-this.ec):Math.max(0,this.Ud-this.ec)};a.b.i("FlattenedTreeHeaderSet.prototype.getCount",{Q:a.Qe.prototype.Q});a.Qe.prototype.Uf=function(){return 0<this.Q()?1:0};a.b.i("FlattenedTreeHeaderSet.prototype.getLevelCount",{Uf:a.Qe.prototype.Uf});a.Qe.prototype.Rb=function(b,c){a.j.assert(b<=this.Ud&&b>=this.ec,"index out of bounds");
a.j.assert(null==c||0==c,"level out of bounds");return{extent:1,more:{before:!1,after:!1}}};a.b.i("FlattenedTreeHeaderSet.prototype.getExtent",{Rb:a.Qe.prototype.Rb});a.Qe.prototype.Td=function(b,c){a.j.assert(b<=this.Ud&&b>=this.ec,"index out of bounds");a.j.assert(null==c||0==c,"level out of bounds");return 1};a.b.i("FlattenedTreeHeaderSet.prototype.getDepth",{Td:a.Qe.prototype.Td});a.wf=function(b,c,d,g,f){a.j.pc(b,null);a.j.pc(c,null);a.j.pc(d,null);a.j.pc(g,null);this.$h=b;this.wp=c;this.ak=
d;this.vp=g;this.Xi=f};o_("ArrayCellSet",a.wf,a);a.wf.prototype.getData=function(a){return this.Xi.s7(a.row,a.column)};a.b.i("ArrayCellSet.prototype.getData",{getData:a.wf.prototype.getData});a.wf.prototype.getMetadata=function(a){return this.Xi.t7(a.row,a.column)};a.b.i("ArrayCellSet.prototype.getMetadata",{getMetadata:a.wf.prototype.getMetadata});a.wf.prototype.ua=function(a){return"row"==a?this.$h:"column"==a?this.ak:-1};a.b.i("ArrayCellSet.prototype.getStart",{ua:a.wf.prototype.ua});a.wf.prototype.Q=
function(a){return"row"===a?Math.max(0,this.wp-this.$h):"column"===a?Math.max(0,this.vp-this.ak):0};a.b.i("ArrayCellSet.prototype.getCount",{Q:a.wf.prototype.Q});a.wf.prototype.getStartRow=function(){return this.$h};a.b.i("ArrayCellSet.prototype.getStartRow",{getStartRow:a.wf.prototype.getStartRow});a.wf.prototype.getStartColumn=function(){return this.ak};a.b.i("ArrayCellSet.prototype.getStartColumn",{getStartColumn:a.wf.prototype.getStartColumn});a.Ya=function(b,c){a.Ya.q.constructor.call(this,b,
c)};o_("FlattenedTreeDataGridDataSource",a.Ya,a);a.b.ga(a.Ya,a.ma,"oj.FlattenedTreeDataGridDataSource");a.Ya.prototype.Init=function(){a.Ya.q.Init.call(this);this.Fd=a.Ya.q.jw.call(this,"columns");this.Yf=a.Ya.q.jw.call(this,"rowHeader")};a.b.i("FlattenedTreeDataGridDataSource.prototype.Init",{Init:a.Ya.prototype.Init});a.Ya.prototype.Rf=function(a){return"row"===a?"estimate":"actual"};a.b.i("FlattenedTreeDataGridDataSource.prototype.getCountPrecision",{Rf:a.Ya.prototype.Rf});a.Ya.prototype.Q=function(a){return"row"===
a?-1:"column"===a?this.Fd.length:0};a.b.i("FlattenedTreeDataGridDataSource.prototype.getCount",{Q:a.Ya.prototype.Q});a.Ya.prototype.Sd=function(b,c,d){var g,f;g=b.axis;if("column"===g)g=b.start+b.count,g>this.Q("column")&&(g=this.Q("column")-b.start),f=new a.Qe(b.start,g,this.Fd);else if("row"===g){if(null!=this.Yf){this.$j={range:b,callbacks:c,callbackObjects:d};return}f=new a.sd(b.start,b.start,g,null)}null!=f&&null!=c&&null!=c.success&&(null==d&&(d={}),c.success.call(d.success,f,b))};a.b.i("FlattenedTreeDataGridDataSource.prototype.fetchHeaders",
{Sd:a.Ya.prototype.Sd});a.Ya.prototype.ke=function(b,c,d){var g,f,k,l;for(g=0;g<b.length;g++)if(f=b[g],"row"==f.axis){k=f.start;l=f.count;break}a.Ya.q.np.call(this,{start:k,count:l},{success:function(a){this.wG(a,b,c,d,0)}.bind(this),error:function(a){this.t9(a,{start:k,count:l},c,d)}.bind(this)})};a.b.i("FlattenedTreeDataGridDataSource.prototype.fetchCells",{ke:a.Ya.prototype.ke});a.Ya.prototype.keys=function(b){var c,d;c=b.row;d=b.column;return new Promise(function(b){c>a.Ya.q.Rfa.call(this).end||
d>this.Fd.length?b(null):b({row:a.Ya.q.getKey.call(this,c),column:this.Fd[d]})}.bind(this))};a.b.i("FlattenedTreeDataGridDataSource.prototype.keys",{keys:a.Ya.prototype.keys});a.Ya.prototype.oe=function(b){var c,d,g,f,k;g=b.row;f=b.column;return new Promise(function(b){c=a.Ya.q.Vh.call(this,g);for(k=0;k<this.Fd.length;k++)if(this.Fd[k]===f){d=k;break}0<=c||0<=d?b({row:c,column:d}):b(null)}.bind(this))};a.b.i("FlattenedTreeDataGridDataSource.prototype.indexes",{oe:a.Ya.prototype.oe});a.Ya.prototype.sort=
function(b,c,d){return a.Ya.q.getWrappedDataSource.call(this).sort(b,{success:function(){this.b$(c,d)}.bind(this),error:c.error})};a.b.i("FlattenedTreeDataGridDataSource.prototype.sort",{sort:a.Ya.prototype.sort});a.Ya.prototype.b$=function(a,c){this.refresh();a.success&&(null==c&&(c={}),a.success.call(c.success))};a.Ya.prototype.move=function(b,c,d,g){a.Ya.q.getWrappedDataSource.call(this).move(b,c,d,g)};a.b.i("FlattenedTreeDataGridDataSource.prototype.move",{move:a.Ya.prototype.move});a.Ya.prototype.getCapability=
function(b){return"default"===a.Ya.q.getWrappedDataSource.call(this).getCapability(b)?"column":"none"};a.b.i("FlattenedTreeDataGridDataSource.prototype.getCapability",{getCapability:a.Ya.prototype.getCapability});a.Ya.prototype.rw=function(b,c){a.Ya.q.rw.call(this,b,c)};a.Ya.prototype.wG=function(b,c,d,g){var f,k,l,m,n,q;for(f=0;f<c.length;f++)k=c[f],"row"==k.axis?(l=k.start,m=k.count):"column"==k.axis&&(n=k.start,q=k.count,n+q>this.Q("column")&&(q=this.Q("column")-n));this.$j&&(f=this.$j.range,f.start==
l&&f.count==m&&this.BG(b,f,this.$j.callbacks,this.$j.callbackObjects),this.$j=null);b=new a.xh(l,l+m,n,n+q,b,this.Fd);d.success&&(null==g&&(g={}),d.success.call(g.success,b,c))};a.Ya.prototype.t9=function(a,c,d,g){var f;this.$j&&(f=this.$j.range,f.start==c.start&&f.count==c.count&&(c=this.$j.callbacks,f=this.$j.callbackObjects,c.error&&(null==f&&(f={}),c.error.call(f.error,a))),this.$j=null);d.error&&(null==g&&(g={}),d.success.call(g.error,a))};a.Ya.prototype.BG=function(b,c,d,g){b=new a.Qe(c.start,
c.start+c.count,this.Fd,b,this.Yf);d.success&&(null==g&&(g={}),d.success.call(g.success,b,c))};a.Ya.prototype.yB=function(b,c,d){var g,f,k,l;g=null;this.Yf&&(g=new a.Qe(b,b+d.Q(),this.Fd,d,this.Yf));c=new a.xh(b,b+d.Q(),0,this.Fd.length,d,this.Fd);k=[];l=[];for(f=0;f<d.Q();f++)k.push({row:this.ug(b+f).key}),l.push({row:b+f,column:-1});b={source:this,operation:"insert"};b.result=c;g&&(b.header=g);b.keys=k;b.indexes=l;a.Ya.q.handleEvent.call(this,"change",b)};a.Ya.prototype.RB=function(b){var c,d,g;
c=[];g=[];for(d=0;d<b.length;d++)c.push({row:b[d].key}),g.push({row:b[d].index,column:-1});b={source:this,operation:"delete"};b.keys=c;b.indexes=g;a.Ya.q.handleEvent.call(this,"change",b)};a.Ya.prototype.WJ=function(b,c){c.success.call(null,new a.Ce(null,b.start))};a.Ch=function(a,c){this.CB=a;this.Ap=c};o_("PagingCellSet",a.Ch,a);a.Ch.prototype.getData=function(a){return this.CB.getData({column:a.column,row:a.row+this.Ap})};a.b.i("PagingCellSet.prototype.getData",{getData:a.Ch.prototype.getData});
a.Ch.prototype.getMetadata=function(a){return this.CB.getMetadata({column:a.column,row:a.row+this.Ap})};a.b.i("PagingCellSet.prototype.getMetadata",{getMetadata:a.Ch.prototype.getMetadata});a.Ch.prototype.Q=function(a){return this.CB.Q(a)};a.b.i("PagingCellSet.prototype.getCount",{Q:a.Ch.prototype.Q});a.Ch.prototype.eY=function(){return this.CB};a.b.i("PagingCellSet.prototype.getCellSet",{eY:a.Ch.prototype.eY});a.Ch.prototype.mw=function(){return this.Ap};a.b.i("PagingCellSet.prototype.getStartIndex",
{mw:a.Ch.prototype.mw});a.Zd=function(a,c){this.xp=a;this.Ap=c};o_("PagingHeaderSet",a.Zd,a);a.Zd.prototype.getData=function(a,c){return this.xp.getData(a+this.Ap,c)};a.b.i("PagingHeaderSet.prototype.getData",{getData:a.Zd.prototype.getData});a.Zd.prototype.getMetadata=function(a,c){return this.xp.getMetadata(a+this.Ap,c)};a.b.i("PagingHeaderSet.prototype.getMetadata",{getMetadata:a.Zd.prototype.getMetadata});a.Zd.prototype.Q=function(){return this.xp.Q()};a.b.i("PagingHeaderSet.prototype.getCount",
{Q:a.Zd.prototype.Q});a.Zd.prototype.Uf=function(){return this.xp.Uf()};a.b.i("PagingHeaderSet.prototype.getLevelCount",{Uf:a.Zd.prototype.Uf});a.Zd.prototype.Rb=function(a,c){return this.xp.Rb(a,c)};a.b.i("PagingHeaderSet.prototype.getExtent",{Rb:a.Zd.prototype.Rb});a.Zd.prototype.Td=function(a,c){return this.xp.Td(a,c)};a.b.i("PagingHeaderSet.prototype.getDepth",{Td:a.Zd.prototype.Td});a.Zd.prototype.sY=function(){return this.xp};a.b.i("PagingHeaderSet.prototype.getHeaderSet",{sY:a.Zd.prototype.sY});
a.Zd.prototype.mw=function(){return this.Ap};a.b.i("PagingHeaderSet.prototype.getStartIndex",{mw:a.Zd.prototype.mw});a.Ta=function(b){if(!(b instanceof a.fc))throw new a.X("Not a datagridatasource","Not a datagridatasource",a.X.Ob.ERROR);this.Ec=b;this.aa=0;this.Init()};o_("PagingDataGridDataSource",a.Ta,a);a.b.ga(a.Ta,a.fc,"oj.PagingDataGridDataSource");a.Ta.prototype.Init=function(){a.Ta.q.Init.call(this);this.OH()};a.b.i("PagingDataGridDataSource.prototype.Init",{Init:a.Ta.prototype.Init});a.Ta.prototype.OH=
function(){this.Ec.on("change",this.W8.bind(this))};a.Ta.prototype.getPage=function(){return this.Jc};a.b.i("PagingDataGridDataSource.prototype.getPage",{getPage:a.Ta.prototype.getPage});a.Ta.prototype.setPage=function(b,c){c=c||{};b=parseInt(b,10);try{a.Ta.q.handleEvent.call(this,a.gc.J.BEFOREPAGE,{page:b,previousPage:this.Jc})}catch(d){return Promise.reject(null)}this.Ra=null!=c.pageSize?c.pageSize:this.Ra;c.startIndex=b*this.Ra;var g=this.Jc;this.Jc=b;this.aa=c.startIndex;var f=this;return new Promise(function(a,
b){f.ee(c).then(function(){a(null)},function(){f.Jc=g;f.aa=f.Jc*f.Ra;b(null)})})};a.b.i("PagingDataGridDataSource.prototype.setPage",{setPage:a.Ta.prototype.setPage});a.Ta.prototype.ee=function(a){this.Rk=!0;this.aa=a.startIndex;var c=this;return new Promise(function(a){c.handleEvent("change",{operation:"sync",pageSize:c.Ra});a(void 0)})};a.Ta.prototype.fetch=function(a){this.Ra=a.pageSize+a.startIndex;a.startIndex=0;return this.ee(a)};a.b.i("PagingDataGridDataSource.prototype.fetch",{fetch:a.Ta.prototype.fetch});
a.Ta.prototype.getStartItemIndex=function(){return this.aa};a.b.i("PagingDataGridDataSource.prototype.getStartItemIndex",{getStartItemIndex:a.Ta.prototype.getStartItemIndex});a.Ta.prototype.getEndItemIndex=function(){return this.Ai};a.b.i("PagingDataGridDataSource.prototype.getEndItemIndex",{getEndItemIndex:a.Ta.prototype.getEndItemIndex});a.Ta.prototype.getPageCount=function(){var a=this.totalSize();return-1==a?-1:Math.ceil(a/this.Ra)};a.b.i("PagingDataGridDataSource.prototype.getPageCount",{getPageCount:a.Ta.prototype.getPageCount});
a.Ta.prototype.W8=function(b){switch(b.operation){case "refresh":this.aa=0;this.handleEvent("change",{operation:"sync",pageSize:this.Ra});this.handleEvent(a.pa.J.REFRESH,null);break;case "reset":this.handleEvent(a.pa.J.RESET,null);break;case "insert":this.handleEvent(a.pa.J.ADD,{index:b.indexes.row});break;case "delete":this.handleEvent(a.pa.J.REMOVE,null);break;case "update":b.indexes.row=0<=b.indexes.row-this.aa?b.indexes.row-this.aa:-1;this.handleEvent("change",b);break;default:this.handleEvent("change",
b),this.handleEvent(a.pa.J.SYNC,null)}};a.Ta.prototype.Q=function(a){return this.Ec.Q(a)};a.b.i("PagingDataGridDataSource.prototype.getCount",{Q:a.Ta.prototype.Q});a.Ta.prototype.Rf=function(a){return this.Ec.Rf(a)};a.b.i("PagingDataGridDataSource.prototype.getCountPrecision",{Rf:a.Ta.prototype.Rf});a.Ta.prototype.Sd=function(b,c,d){var g;null==this.Rk?(g=new a.sd(0,0,b.axis,null),null!=c&&c.success&&c.success.call(d.success,g,b)):"row"===b.axis?(b.start+=this.aa,b.start+b.count>this.aa+this.Ra&&
(b.count=this.Ra-b.start),this.wr={callbacks:c,callbackObjects:d},this.Ec.Sd(b,{success:this.BG.bind(this),error:this.W9.bind(this)},d)):this.Ec.Sd(b,c,d)};a.b.i("PagingDataGridDataSource.prototype.fetchHeaders",{Sd:a.Ta.prototype.Sd});a.Ta.prototype.BG=function(b,c){c.start-=this.aa;this.wr.callbacks.success.call(this.wr.callbackObjects.success,new a.Zd(b,this.aa),c);this.wr=null};a.Ta.prototype.W9=function(a){this.wr.callbacks.error.call(this.wr.callbackObjects.error,a);this.wr=null};a.Ta.prototype.ke=
function(b,c,d){var g;if(null==this.Rk)g=new a.wf(0,0,0,0,null),null!=c&&c.success&&c.success.call(d.success,g,b);else{for(g=0;g<b.length;g+=1)"row"===b[g].axis&&(b[g].start+=this.aa,b[g].start+b[g].count>this.aa+this.Ra&&(b[g].count=this.Ra-b[g].start));this.vr={callbacks:c,callbackObjects:d};this.Ec.ke(b,{success:this.V8.bind(this),error:this.U8.bind(this)},d)}};a.b.i("PagingDataGridDataSource.prototype.fetchCells",{ke:a.Ta.prototype.ke});a.Ta.prototype.V8=function(b,c){var d;for(d=0;d<c.length;d+=
1)"row"===c[d].axis&&(c[d].start-=this.aa);this.vr.callbacks.success.call(this.vr.callbackObjects.success,new a.Ch(b,this.aa),c);this.vr=null;this.Ai=this.aa+b.Q("row")-1;this.handleEvent("sync",{data:Array(b.Q("row")),startIndex:this.aa})};a.Ta.prototype.U8=function(a){this.vr.callbacks.error.call(this.vr.callbackObjects.error,a);this.vr=null};a.Ta.prototype.keys=function(a){return this.Ec.keys({column:a.column,row:a.row+this.aa})};a.b.i("PagingDataGridDataSource.prototype.keys",{keys:a.Ta.prototype.keys});
a.Ta.prototype.oe=function(a){a=this.Ec.oe(a);-1!=a.row&&(a.row-=this.aa);return a};a.b.i("PagingDataGridDataSource.prototype.indexes",{oe:a.Ta.prototype.oe});a.Ta.prototype.getCapability=function(a){return this.Ec.getCapability(a)};a.b.i("PagingDataGridDataSource.prototype.getCapability",{getCapability:a.Ta.prototype.getCapability});a.Ta.prototype.size=function(){var a;if(null==this.Rk)return-1;a=this.Ec.Q("row");return this.Ec.Q("row")>this.Ra?this.Ra:a};a.b.i("PagingDataGridDataSource.prototype.size",
{size:a.Ta.prototype.size});a.Ta.prototype.sort=function(a,c,d){this.Ec.sort(a,c,d)};a.b.i("PagingDataGridDataSource.prototype.sort",{sort:a.Ta.prototype.sort});a.Ta.prototype.totalSize=function(){return null==this.Rk?-1:this.Ec.Q("row")};a.b.i("PagingDataGridDataSource.prototype.totalSize",{totalSize:a.Ta.prototype.totalSize});a.Ta.prototype.move=function(a,c,d,g,f){this.Ec.move(a,c,d,g,f)};a.b.i("PagingDataGridDataSource.prototype.move",{move:a.Ta.prototype.move});a.sd=function(b,c,d,g){a.j.pc(b,
null);a.j.pc(c,null);this.ec=b;this.Ud=c;this.rZ=d;this.Xi=g};o_("ArrayHeaderSet",a.sd,a);a.sd.prototype.getData=function(b,c){if(null==this.Xi)return null;a.j.assert(b<=this.Ud&&b>=this.ec,"index out of bounds");a.j.assert(null==c||0==c,"level out of bounds");return this.Xi.pR(this.rZ,b)};a.b.i("ArrayHeaderSet.prototype.getData",{getData:a.sd.prototype.getData});a.sd.prototype.getMetadata=function(b,c){if(null==this.Xi)return null;a.j.assert(b<=this.Ud&&b>=this.ec,"index out of bounds");a.j.assert(null==
c||0==c,"level out of bounds");return this.Xi.Y7(this.rZ,b)};a.b.i("ArrayHeaderSet.prototype.getMetadata",{getMetadata:a.sd.prototype.getMetadata});a.sd.prototype.Uf=function(){return 0<this.Q()?1:0};a.b.i("ArrayHeaderSet.prototype.getLevelCount",{Uf:a.sd.prototype.Uf});a.sd.prototype.Rb=function(b,c){a.j.assert(b<=this.Ud&&b>=this.ec,"index out of bounds");a.j.assert(null==c||0==c,"level out of bounds");return{extent:1,more:{before:!1,after:!1}}};a.b.i("ArrayHeaderSet.prototype.getExtent",{Rb:a.sd.prototype.Rb});
a.sd.prototype.Td=function(b,c){a.j.assert(b<=this.Ud&&b>=this.ec,"index out of bounds");a.j.assert(null==c||0==c,"level out of bounds");return 1};a.b.i("ArrayHeaderSet.prototype.getDepth",{Td:a.sd.prototype.Td});a.sd.prototype.Q=function(){return null==this.Xi?0:Math.max(0,this.Ud-this.ec)};a.b.i("ArrayHeaderSet.prototype.getCount",{Q:a.sd.prototype.Q});a.sd.prototype.ua=function(){return this.ec};a.b.i("ArrayHeaderSet.prototype.getStart",{ua:a.sd.prototype.ua})});