/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtDiagram"],function(a,f,d,b,c){a.Da("oj.ojDiagram",f.oj.dvtBaseComponent,{widgetEventPrefix:"oj",options:{optionChange:null},Gf:function(b){this.options._logger=a.u;this.options._templateFunction&&(this.options.renderer=this.K8(this.options._templateFunction));this.options.renderer&&(this.options._contextHandler=this.C7());return this._super(b)},K8:function(a){var b=this;return function(c){var d=document.createElement("div");
d.style.display="none";d.dF=b.If;b.element.append(d);a({parentElement:d,data:c.data});return(c=d.children[0])&&"http://www.w3.org/2000/svg"===c.namespaceURI?(f(d).remove(),c):c?b.gt(c):null}},C7:function(){var b=this;return function(c,d,f,l,m){return{component:a.Components.Eg(b.element),parentElement:c,rootElement:d,data:f,state:l,previousState:m,id:f.id,type:"node",label:f.label}}},renderDefaultHover:function(a){a.previousState&&a.state.hovered==a.previousState.hovered||this.gt(this.element).processDefaultHoverEffect(a.id,
a.state.hovered)},renderDefaultSelection:function(a){a.previousState&&a.state.selected==a.previousState.selected||this.gt(this.element).processDefaultSelectionEffect(a.id,a.state.selected)},renderDefaultFocus:function(a){a.previousState&&a.state.focused==a.previousState.focused||this.gt(this.element).processDefaultFocusEffect(a.id,a.state.focused)},Ef:function(a,b,d){return c.DvtDiagram.newInstance(a,b,d)},mj:function(a){var b=a.subId;"oj-diagram-link"==b?b="link["+a.index+"]":"oj-diagram-node"==
b&&(b="node["+a.index+"]");return b},nj:function(a){var b={};0==a.indexOf("link")?(b.subId="oj-diagram-link",b.index=this.ri(a)):0==a.indexOf("node")&&(b.subId="oj-diagram-node",b.index=this.ri(a));return b},He:function(){var a=this._super();a.push("oj-diagram");return a},pi:function(){var a=this._super();a["oj-diagram-node-label"]={path:"styleDefaults/nodeDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-diagram-node oj-selected"]={path:"styleDefaults/nodeDefaults/selectionColor",property:"border-color"};
a["oj-diagram-node oj-hover"]=[{path:"styleDefaults/nodeDefaults/hoverOuterColor",property:"border-top-color"},{path:"styleDefaults/nodeDefaults/hoverInnerColor",property:"border-bottom-color"}];a["oj-diagram-link"]={path:"styleDefaults/linkDefaults/color",property:"color"};a["oj-diagram-link-label"]={path:"styleDefaults/linkDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-diagram-link oj-selected"]={path:"styleDefaults/linkDefaults/selectionColor",property:"border-color"};a["oj-diagram-link oj-hover"]=
[{path:"styleDefaults/linkDefaults/hoverOuterColor",property:"border-top-color"},{path:"styleDefaults/linkDefaults/hoverInnerColor",property:"border-bottom-color"}];return a},qi:function(){return["optionChange"]},Gh:function(){var a=this.options.translations,b=this._super();b["DvtUtilBundle.DIAGRAM"]=a.componentName;return b},si:function(a){(a&&a.getType?a.getType():null)===c.DvtSelectionEvent.TYPE?this.Cc("selection",a.getSelection()):this._super(a)},getNodeCount:function(){return this.qa.getAutomation().getNodeCount()},
getNode:function(a){return this.qa.getAutomation().getNode(a)},getLinkCount:function(){return this.qa.getAutomation().getLinkCount()},getLink:function(a){return this.qa.getAutomation().getLink(a)}})});