/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","hammerjs","ojs/ojjquery-hammer","ojs/ojcomponentcore","ojs/ojvalidation","ojs/ojpopup"],function(a,f,d){a.eb=function(a){this.Init(a)};a.Sa.QB(a.Sa.Wc.cx,a.eb);a.b.ga(a.eb,a.mc,"oj.PopupMessagingStrategy");a.eb.aq={ojRadioset:{position:"launcher",Uj:{open:"focus focusin mouseover",close:"mouseout"}},ojCheckboxset:{position:"launcher",Uj:{open:"focusin mouseover",close:"mouseout"}},ojInputText:{position:"launcher",Uj:{open:"focusin"}},ojTextArea:{position:"launcher",
Uj:{open:"focusin"}},ojInputPassword:{position:"launcher",Uj:{open:"focusin"}},ojSwitch:{position:"launcher",Uj:{open:"focusin mouseover",close:"mouseout"}},"default":{position:"launcher-wrapper",Uj:{open:"focusin"}}};a.eb.rD="oj-form-control-hint";a.eb.U2="oj-form-control-hint-converter";a.eb.W2="oj-form-control-hint-validator";a.eb.V2="oj-form-control-hint-title";a.eb.prototype.Ym=function(b){a.eb.q.Ym.call(this,b);this.D$()};a.eb.prototype.Cp=function(b){a.eb.q.Cp.call(this,b);this.YW()};a.eb.prototype.update=
function(){a.eb.q.update.call(this);this.YW()};a.eb.prototype.Tj=function(){this.qea();this.o6();a.eb.q.Tj.call(this)};a.eb.prototype.kP=function(){this.rT()&&this.we.ojPopup("close")};a.eb.prototype.D$=function(){this.dA||this.gca()};a.eb.prototype.iU=function(){var b,c;if(this.L4()&&(c=this.HO(),!a.Ba.Wh(c))){var d=this.LR();b=d.ojPopup("isOpen");b?b&&(b=d[0],b.innerHTML="",b.innerHTML=c,d.ojPopup("refresh")):(b=d[0],b.innerHTML="",b.innerHTML=c,d.ojPopup("open",this.yh()))}};a.eb.prototype.L4=
function(){var a=this.hi().options,b=a.readOnly||!1;return!(a.disabled||b)};a.eb.prototype.YW=function(){var a;a=!1;var b,c;if(this.rT()){var d=this.LR();a=d.ojPopup("isOpen");b=this.HO();c=document.activeElement===this.yh()[0]?!0:!1;a?b?(a=d[0],a.innerHTML="",a.innerHTML=b,d.ojPopup("refresh")):d.ojPopup("close"):c&&b&&this.iU()}};a.eb.prototype.qea=function(){var b=a.eb.aq[this.hi().widgetName],b=b?b.Uj:a.eb.aq["default"].Uj;if(b.open){var c=this.dA;delete this.dA;c&&this.yh().off(b.open,c)}b.close&&
(c=this.lP)&&this.yh().off(b.close,c)};a.eb.prototype.gca=function(){var b=this.yh(),c=a.eb.aq[this.hi().widgetName],c=c?c.Uj:a.eb.aq["default"].Uj;if(c.open){var d=this.dA;d||(d=this.dA=f.proxy(this.iU,this));b.on(c.open,d)}c.close&&(d=this.lP,d||(d=this.lP=f.proxy(this.kP,this)),b.on(c.close,d))};a.eb.prototype.x8=function(){var b,c=a.eb.aq[this.hi().widgetName];(c=c?c.position:a.eb.aq["default"].position)&&("launcher"===c?b=this.yh():"launcher-wrapper"===c&&(b=this.yh().parent()));b||(b=this.hi().widget());
return{my:"start bottom",at:"end top",collision:"flipcenter",of:b}};a.eb.prototype.LR=function(){if(this.we)return this.we;var b=a.ed.xY(),c=this.x8();b.ojPopup("option","position",c);b.ojPopup("option","close",f.proxy(this.vba,this));b.ojPopup("option","open",f.proxy(this.wba,this));return this.we=b};a.eb.prototype.wba=function(b){var c=f(b.target),d=this;window.setTimeout(function(){a.Components.dK(c)?c.ojPopup("option","autoDismiss","focusLoss"):delete d.we},10)};a.eb.prototype.vba=function(b){b=
f(b.target);a.Components.dK(b)&&(b.ojPopup("option","autoDismiss","none"),b.ojPopup("option","open",null),b.ojPopup("option","close",null));delete this.we;b.children().remove()};a.eb.prototype.o6=function(){this.kP();a.ed.Afa()};a.eb.prototype.HO=function(){var b="",c=this.hi().document[0],d=[],e=!1;this.cM()&&d.push(this.ZD(c));(this.KC()||this.eM()||this.dM())&&d.push(this.v4(c));f.each(d,function(d,g){g&&(e?b=b.concat(a.Na.Yfa(c)):e=!0,b=b.concat(g))});return b};a.eb.prototype.ZD=function(b){var c;
c="";var d=this.rC();this.zC()&&(c=this.sC(),c=a.Na.sX(b,c,d,!1));return c};a.eb.prototype.v4=function(b){var c=[],d,e="";this.KC()&&(c=this.EL(),c=c.length?c[0]:"",e+=a.Na.gJ(b,a.eb.U2,c,!1,a.eb.rD));if(this.eM())for(c=this.w0(),d=0;d<c.length;d++)e+=a.Na.gJ(b,a.eb.W2,c[d],!1,a.eb.rD);this.dM()&&(e+=a.Na.gJ(b,a.eb.V2,this.v0(),!0,a.eb.rD));return e?"\x3cdiv class\x3d'oj-form-control-hints'\x3e"+e+"\x3c/div\x3e":""};a.eb.prototype.rT=function(){return this.we?a.Components.dK(this.we):!1};a.Na={};
a.Na.gJ=function(b,c,d,e,g){var h;d&&(h=f(b.createElement("div")),h.addClass(g+(" "+c)),h.append(a.Na.cS(b,d,e)));return h?h.get(0).outerHTML:""};a.Na.DY=function(b){var c;switch(b){case a.X.Ob.FATAL:c=a.ha.D("oj-message.fatal");break;case a.X.Ob.ERROR:c=a.ha.D("oj-message.error");break;case a.X.Ob.WARNING:c=a.ha.D("oj-message.warning");break;case a.X.Ob.INFO:c=a.ha.D("oj-message.info");break;case a.X.Ob.CONFIRMATION:c=a.ha.D("oj-message.confirmation")}return c};a.Na.Yfa=function(a){return(a=f(a.createElement("hr")))?
a.get(0).outerHTML:""};a.Na.sX=function(b,c,d,e){var g="",h,f,k,l,u={};l=[];for(h=0;h<c.length;h++)k=c[h],l=k instanceof a.X?k:new a.X(k.summary,k.detail,k.severity),f=a.X.ps(l.severity),u[f]||(u[f]=[]),u[f].push(l);for(h=d;h>=a.X.Ob.CONFIRMATION;h--)for(l=u[h]||[],c=0;c<l.length;c++)k=l[c],a.j.Va(k,a.X),f=a.X.ps(k.severity),d=a.Na.DY(f),d=k.summary||d,k=k.detail||"",g=g.concat(a.Na.rX(b,d,k,f,e));return g};a.Na.rX=function(b,c,d,e,g){var h,k;k=a.Na.DY(e);h=f(b.createElement("div"));h.addClass(a.Na.X2);
g&&h.addClass(a.Na.F8(e));g=f(b.createElement("span"));g.addClass(a.Na.E8(e)).attr("title",k).attr("role","img");h.append(g);e=f(b.createElement("span"));e.addClass(a.Na.a3);k=f(b.createElement("div"));k.addClass(a.Na.e3).text(c);e.append(k);d&&(c=a.Na.cS(b,d,!0),b=f(b.createElement("div")),b.addClass(a.Na.b3).append(c),e.append(b));h.append(e);return h?h.get(0).outerHTML:""};a.Na.E8=function(b){var c;switch(b){case a.X.Ob.FATAL:c=a.Na.KN;break;case a.X.Ob.ERROR:c=a.Na.KN;break;case a.X.Ob.WARNING:c=
a.Na.g3;break;case a.X.Ob.INFO:c=a.Na.d3;break;case a.X.Ob.CONFIRMATION:c=a.Na.Z2}return a.Na.m1+c};a.Na.F8=function(b){switch(b){case a.X.Ob.FATAL:b=a.Na.JN;break;case a.X.Ob.ERROR:b=a.Na.JN;break;case a.X.Ob.WARNING:b=a.Na.f3;break;case a.X.Ob.INFO:b=a.Na.c3;break;default:b=a.Na.Y2}return b};a.Na.cS=function(b,c,d){var e=null;a.Ba.pd(c)&&(d&&a.C.zga(c)?e=a.C.efa(c.substring(6,c.length-7)):(e=b.createElement("span"),e.textContent=c));return e};a.Na.m1="oj-component-icon oj-message-status-icon ";
a.Na.X2="oj-message";a.Na.e3="oj-message-summary";a.Na.b3="oj-message-detail";a.Na.a3="oj-message-content";a.Na.KN="oj-message-error-icon";a.Na.g3="oj-message-warning-icon";a.Na.d3="oj-message-info-icon";a.Na.Z2="oj-message-confirmation-icon";a.Na.JN="oj-message-error";a.Na.f3="oj-message-warning";a.Na.c3="oj-message-info";a.Na.Y2="oj-message-confirmation";a.ed={};a.ed.xY=function(){var b=a.ed.KR(),c=b.find("."+a.ed.sD);0===c.length?(c=f(a.ed.w8()).hide(),c.appendTo(b),c.ojPopup({rootAttributes:{"class":a.ed.h3},
initialFocus:"none",tail:"simple",autoDismiss:"none"})):c=f(c[0]);return c};a.ed.Afa=function(){if(0<a.ed.S7()){var b=a.ed.xY();b.ojPopup("destroy");b.remove()}};a.ed.KR=function(){var b=f("#"+a.ed.gN);if(0<b.length)return b;b=f("\x3cdiv\x3e");b.attr("id",a.ed.gN);b.attr("role","presentation");b.appendTo(f(document.body));return b};a.ed.S7=function(){return a.ed.KR().find("."+a.ed.sD).length};a.ed.w8=function(){return"\x3cdiv class\x3d'"+a.ed.sD+"'\x3e\x3c/div\x3e"};a.ed.sD="oj-messaging-popup-container";
a.ed.h3="oj-messaging-popup";a.ed.gN="__oj_messaging_popup_pool";var b={f0:1,sL:2,vL:3,SL:4,TL:5,VL:6,M0:7,V0:8,iM:9,jM:10,X0:11},c={cn:!0,ci:b.sL},e={cn:!0,ci:b.vL},g={cn:!0,ci:b.VL},h={cn:!0,ci:b.SL},k={cn:!0,ci:b.TL},l={cn:!0,ci:b.jM};a.Da("oj.editableValue",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{disabled:!1,displayOptions:void 0,help:{definition:null,source:null},messagesCustom:void 0,messagesHidden:void 0,messagesShown:void 0,required:void 0,title:void 0,validators:void 0,value:void 0},
getNodeBySubId:function(a){return this._super(a)},isValid:function(){void 0===this.ZI&&(this.ZI=this.N8());return this.ZI},refresh:function(){this._super();this.jQ(!0)},reset:function(){this.oy();this.xv(this.vi.M0);this.LH(this.options.value,!0)},showMessages:function(){var b=this.options.messagesHidden,c,d=!1,e,g=[];for(e=0;e<b.length;e++)d=!0,c=b[e],c instanceof a.Bc&&c.h7(),g.push(c.clone());d&&(this.Ot("messagesHidden"),this.TA("messagesShown",g))},validate:function(){return this.tc(this.mg(),
null,this.FD)},xt:{zL:1,W0:2,WL:3},vi:b,FD:{mp:!1,ci:b.iM},ae:function(a,b){this._super(a,b)},_ComponentCreate:function(){var a=this.element,b=this.QM(a);this._super();this.options.messagesCustom=this.options.messagesCustom||[];this.options.messagesHidden=[];this.options.messagesShown=0<this.options.messagesCustom.length?this.Z4(this.options.messagesCustom):[];this.tD(a);this.vx()&&(this.oq(this.options.placeholder),this.QE=!0);f.each(["required","title"],function(c,d){d in b&&a.removeAttr(d)})},
Sg:function(){this._super();this.F5();this.jQ(!1);this.Fz();this.xv(this.vi.f0);0<this.options.messagesShown.length&&this.Av("messagesShown",this.options.messagesShown,null,!0);this.widget().addClass("oj-form-control")},ut:function(a){this.j3(a)},mq:function(a){this.S2(a)},pM:function(a,b){switch(a){case "disabled":this.qM(a,e);break;case "converter":this.Z0(a);break;case "displayOptions":this.Fz();break;case "help":this.Vg(a,this.options[a]);break;case "messagesCustom":this.Raa(b);break;case "placeholder":this.uba(b);
break;case "readOnly":this.qM(a,h);break;case "required":this.$0(a);break;case "title":this.dea();break;case "translations":this.refresh();break;case "value":this.a1(a,b);break;case "validators":this.Xp(a)}},Z0:function(a){var b=!1;this.Q2();this.yz()&&(b=!0);b?(this.py(),this.VA(c)):this.Vg(a,this.options[a],!0)},qM:function(a,b){var c=!this.options[a];this.Vg(a,this.options[a]);c&&this.tV(b)},$0:function(a){this.Vg(a,this.options[a]);this.tV(g)},a1:function(a,b){var c=!1,d,e=b?b._context:null;e&&
(c=e.originalEvent?!0:!1,d=e.cn||!1);c||(d||this.oy(null),this.xv(this.vi.X0));this.Vg(a,this.options[a],!0)},Xp:function(){var a=!1;this.IN();this.yz()&&(a=!0);a&&(this.py(),this.VA(l))},px:function(){var a=this.options.readOnly||!1;return this.options.disabled||a?!1:!0},_destroy:function(){this.widget();var b=this._super();this.oy(null,!0);this.Sq().Tj();this.lc&&null!=a.Components.Eg(this.lc[0])&&this.lc._ojLabel("destroy");return b},Focus:function(){this.lg().focus();return!0},_setOption:function(b,
c,d){var e;e=!1;if("string"===typeof b&&void 0!==c)switch(b){case "messagesHidden":e=!0;break;case "messagesShown":e=!0}if(e)return a.u.error(b+" option cannot be set"),this;e=this._superApply(arguments);this.pM(b,d);return e},lg:function(){return this.element},D1:function(){var a=this.PQ(this.element);if(null!==a&&0!==a.length)return a;a=this.element.prop("id");if(void 0!==a&&(a=f("label[for\x3d'"+a+"']"),0!==a.length))return a;a=this.element.closest("[aria-labelledby]");return 0!==a.length&&(a=
this.PQ(a),null!==a&&0!==a.length)?a:null},dq:function(){return this.element.val()},_GetMessagingLauncherElement:function(){return this.lg()},Lc:function(){this.Dc||(this.Dc=a.cb.getConverterInstance(this.options.converter));return this.Dc||null},ht:function(){this.MS||(this.MS={});return this.MS},mg:function(){return this.lg().val()},PM:function(){if(!this.Dt){var b=[],c=this.options.validators,d,e=!0,g=this.ht(),h=[],f,k;k=Object.keys(g);f=k.length;if(0<f){for(var l=0;l<f;l++)d=k[l],h.push(g[d]);
b=b.concat(h)}if(c){h=[];for(k=0;k<c.length;k++)d=c[k],"object"===typeof d?(d.validate&&"function"===typeof d.validate||(e=!1),e||(f=d.type)&&"string"===typeof f&&((g=a.na.Jp(f))?(d=a.Ac.Pf({},d.options)||{},d.converter=d.converter||this.Lc(),d.label=d.label||this.MF(),d=g.createValidator(d)):a.u.error("Unable to locate a validatorFactory for the requested type: "+f)),h.push(d)):a.u.error("Unable to parse the validator provided:"+d);b=b.concat(h)}this.Dt=b}return this.Dt||[]},IN:function(){this.Dt&&
(this.Dt.length=0);this.Dt=null;this.Sq().update(this.Jh(this.Ug.kM))},Q2:function(){this.Dc=null;this.Sq().update(this.Jh(this.Ug.rL))},gq:function(){return this.options.required},ux:function(a){var b=this.mg();this.tc(b,a)},Vg:function(a,b,c){switch(a){case "converter":b=this.options.value;this.LH(b,c);break;case "disabled":this.PU("disabled",this.options.disabled);break;case "help":b=this.options.help.definition;c=this.options.help.source;a=this.wF();this.lc&&(this.lc._ojLabel("option","describedById",
a),this.lc._ojLabel("option","help",{definition:b,source:c}));break;case "required":this.PU("required",this.gq());this.pD(b);this.lc&&(a=this.wF(),this.lc._ojLabel("option",{describedById:a,ariaRequiredUnsupported:this.kx()}),this.lc._ojLabel("option","required",b));break;case "value":this.LH(b,c)}},pD:function(a){var b=this.lg();a&&b?b.attr("aria-required",a):b.removeAttr("aria-required")},kx:function(){return!1},qD:function(){this.lc&&this.lc._ojLabel("refresh");this.Dc=this.SG=null;this.IN()},
sj:function(a){var b=this.lg();b.val()!==a&&b.val(a)},tD:function(a){"boolean"===typeof this.options.disabled&&a.prop("disabled",this.options.disabled)},oq:function(a){this.lg().attr("placeholder",a)},MN:function(a){this.options.placeholder=a},vx:function(){return this.options.placeholder},AM:function(){this.MN("");this.oq("")},tc:function(b,c,d){var e=d&&"boolean"===typeof d.mp?d.mp:!0;if(void 0===b)return a.u.warn("Attempt to set a value of undefined"),!1;if(e&&b===this.cU)a.u.Ew>a.u.Ql&&a.u.info("Validation skipped and value option not updated as submitted value '"+
b.toString?b.toString():b+" same as previous.");else if(b=this.cO(b,c,d),void 0!==b&&this.isValid())return this.$W(b,c,d&&d.ci),!0;return!1},cO:function(b,c,d){var e=d&&d.Jha?d.Jha:this.xt.zL,g=d&&d.ci?d.ci:this.vi.V0;d=d&&d.cn||!1;if(void 0===b)a.u.warn("Attempt to set a value of undefined");else if(this.px()){d||this.oy(c);this.NV(b);try{return this.Rca(b,e,g,c)}catch(h){}}else a.u.Ew>a.u.Ql&&a.u.info("Validation skipped and value option not set as component state does not  allow setting value. For example if the component is readonly or disabled.")},
et:function(b,c,d){return"value"===b?a.b.Cg(c,d):0===b.indexOf("messages")?this.Saa(c,d):this._superApply(arguments)},_GetDefaultStyleClass:function(){a.j.Xa();return""},Ug:{Ks:1,lM:2,rL:3,kM:4,gM:5},dm:{disabled:"oj-disabled",required:"oj-required"},oy:function(a,b){b?(this.options.messagesHidden=[],this.options.messagesShown=[],this.options.messagesCustom=[]):(this.Ot("messagesHidden",a),this.Ot("messagesShown",a),this.Ot("messagesCustom",a))},py:function(){var b=this.options.messagesShown,c=b.length,
d;this.Ot("messagesHidden");for(var e=c-1;0<=e;e--)d=b[e],d instanceof a.Bc&&b.splice(e,1);b.length!==c&&this.Av("messagesShown",b,null,!0)},Av:function(a,b,c,d){var e={},g=0===b.length&&0===this.options[a].length;if(d||!g)e._context={originalEvent:c,rd:!0,mb:!0},e.changed=d||!g,this.Ica(),this.option(a,b,e),this.xea()},Ot:function(a,b){this.Av(a,[],b)},Z4:function(b){var c,d=[],e;if(b&&0<b.length)for(e=0;e<b.length;e++)c=b[e],c instanceof a.X?d.push(c.clone()):(c=new a.X(c.summary,c.detail,c.severity),
c=Object.freeze?Object.freeze(c):c,d.push(c));return d},F5:function(){if(this.lc=this.D1()){var a=this.options.help.definition,b=this.options.help.source,c=this.kx(),d=this.A3(b,a,this.options.required,c);this.lc._ojLabel({rootAttributes:{"class":this._GetDefaultStyleClass()+"-label"},describedById:d,required:this.options.required,ariaRequiredUnsupported:c,help:{definition:a,source:b}})}},jQ:function(a){var b=!1;a?(this.qD(),this.Fz(),this.yz()&&(b=!0),this.py(),b?this.VA(k):(this.gq()&&this.xv(k.ci),
this.Vg("value",this.options.value,!0))):(this.Vg("value",this.options.value),this.Vg("required",this.options.required));this.Vg("disabled",this.options.disabled)},cia:function(){return this.dU},bia:function(){return this.cU},PQ:function(a){a=a.attr("aria-labelledby");return void 0!==a?f("label[id\x3d'"+a+"']"):null},wF:function(){this.element.uniqueId();return this.element.prop("id")+"Icons"},A3:function(a,b,c,d){var e=this.wF();(a||b||c&&d)&&this.ID(e);return e},ID:function(a){this.lg().each(function(){var b=
f(this).attr("aria-describedby");b?f(this).attr("aria-describedby",b+" "+a):f(this).attr("aria-describedby",a)})},jz:function(){return this.options.messagesShown.concat(this.options.messagesHidden)},MF:function(){if(this.lc)return this.lc.text()},hS:function(){this.cX||(this.cX=new a.di(this.isValid(),this.jz()));return this.cX},JG:function(){return!a.X.isValid(this.jz())},yz:function(){return!this.isValid()&&0<this.options.messagesShown.length},h$:function(){for(var b=this.options.messagesShown,
c,d,e=0;e<b.length;e++)c=b[e],c instanceof a.Bc&&c.mT()&&(d=d||[],d.push(c));return void 0===d?!1:!a.X.isValid(d)},Fz:function(){var a=this.Sq(),b=this._GetMessagingLauncherElement(),c=this.Jh(this.Ug.Ks);this.QE||this.AM();a.Ym(b,c)},Raa:function(b){var c=this.options.messagesCustom,d=[],e,g,h=this.options.messagesShown,f=b?b._context:null;for(g=0;g<h.length;g++)e=h[g],e instanceof a.Bc&&e.mT()&&d.push(e);for(g=0;g<c.length;g++)d.push(c[g]);this.Av("messagesShown",d,f?f.originalEvent:null,b&&b.changed)},
uba:function(a){a=(a&&a._context||{}).yga?!1:!0;this.oq(this.options.placeholder);a?(this.QE=!0,this.Lc()&&this.Fz()):this.QE=!1},lda:function(a){this.dU=a},NV:function(a){this.cU=a},dea:function(){this.Sq().update(this.Jh(this.Ug.gM))},TA:function(a,b,c){var d,e,g;if("object"===typeof b&&Array.isArray(b))for(g=this.options[a],d=b.length,e=0;e<d;e++)g.push(b[e]);this.Av(a,g,c,!0)},xea:function(){this.Sq().update(this.Jh())},$W:function(a,b,c){var d={};b&&(d.originalEvent=b);switch(c){case this.vi.sL:case this.vi.vL:case this.vi.SL:case this.vi.TL:case this.vi.VL:case this.vi.iM:case this.vi.jM:d.rd=
!0,d.cn=!0}this.option({value:a},{_context:d})},Ica:function(){this.ZI=void 0},N8:function(){var a=this.jz(),b=!0;a&&0!==a.length&&(b=!this.JG());return b},uF:function(b){var c=b,d=this.Lc();d&&"object"===typeof d&&(d.format&&"function"===typeof d.format?c=d.format(b):a.u.Ew>a.u.Ql&&a.u.info("converter does not support the format method."));return c},Sq:function(){this.mo||(this.mo=new a.Sa(this));return this.mo},Z7:function(a){var b,c=[];b="";var d;this.gq()&&(b=this.rR(),b.getHint&&"function"===
typeof b.getHint&&(b=b.getHint())&&c.push(b));for(d=0;d<a.length;d++)b=a[d],"object"===typeof b&&b.getHint&&"function"===typeof b.getHint&&(b=b.getHint())&&c.push(b);return c},rR:function(){var b;b={};var c;null==this.SG&&(b=this.options.translations?this.options.translations.required||{}:{},c={hint:b.hint||null,label:this.MF(),messageSummary:b.messageSummary||null,messageDetail:b.messageDetail||null},this.SG=(b=a.na.Jp(a.Vc.VALIDATOR_TYPE_REQUIRED))?b.createValidator(c):null);return this.SG},Jh:function(a){var b=
{},c=this.Lc(),d="",e=[];a=a||this.Ug.lM;if(a===this.Ug.Ks||a===this.Ug.lM)e=this.jz(),this.hS().update(this.isValid(),e),b.X_=this.hS();if(a===this.Ug.Ks||a===this.Ug.rL)c&&"object"===typeof c&&c.getHint&&"function"===typeof c.getHint&&(d=c.getHint()||""),b.CX=d;if(a===this.Ug.Ks||a===this.Ug.kM)c=this.PM(),e=this.Z7(c)||[],b.Kha=e;if(a===this.Ug.Ks||a===this.Ug.gM)b.title=this.options.title||"";return b},Saa:function(b,c){var d=-1,e,g=!0,h=f.extend([],b),k=f.extend([],c);if(h.length!==k.length)return!1;
f.each(h,function(b,c){c instanceof a.X?e=c:(e=new a.X(c.summary,c.detail,c.severity),e=Object.freeze?Object.freeze(e):e);d=-1;f.each(k,function(a,b){e.en(b)&&(d=a)});-1<d?k.splice(d,1):g=!1});return g},vH:function(b){var c=this.Lc(),d=b;c&&"object"===typeof c&&(c.parse&&"function"===typeof c.parse?d=c.parse(b):a.u.Ew>a.u.Ql&&a.u.info("converter does not support the parse method."));return d},KD:function(b,c){var d,e,g;b instanceof a.ye||b instanceof a.Qg?(d=b.ms(),a.j.Va(d,a.X),g=d.severity,e=d.summary,
d=d.detail):(g=a.X.Ob.ERROR,e=a.ha.D("oj-message.error"),d=b.message||a.ha.D("oj-converter.detail"));c.push({summary:e,detail:d,severity:g})},DH:function(b,c,d){var e={},g=[],h=b.Yu||[];e.context=c||0;e.display=d||a.Bc.Mp.IC;0===h.length&&this.KD(b,h);for(c=0;c<h.length;c++)b=h[c],g.push(this.w5(b.summary,b.detail,b.severity,e));return g||null},w5:function(b,c,d,e){b=new a.Bc(b,c,d,e);return b=Object.seal?Object.seal(b):b},LH:function(a,b){var c=a||this.options.value,d;d=this.dU;(b||c!==d)&&this.vea(c)},
PU:function(a,b){-1!==Object.keys(this.dm).indexOf(a)&&this.widget().toggleClass(this.dm[a],!!b)},xv:function(b){if(this.px())try{this.bX(this.options.value,this.xt.WL)}catch(c){(b=this.DH(c,b,a.Bc.Mp.vC))&&this.TA("messagesHidden",b)}else a.u.Ew>a.u.Ql&&a.u.info("Deferred validation skipped as component is readonly or disabled.")},Rca:function(a,b,c,d){var e=a;try{b===this.xt.zL&&(e=this.vH(a)),this.bX(e,b===this.xt.WL)}catch(g){throw a=this.DH(g,c),this.TA("messagesShown",a,d),g;}return e},tV:function(a){var b=
!0;this.yz()&&(b=!1);this.py();b?this.gq()&&this.xv(a.ci):this.VA(a)},vea:function(a,b){var c,d;this.lda(a);c=a;try{c=this.uF(a)}catch(e){d=this.DH(e),this.TA("messagesShown",d,b)}this.sj(c);this.NV(this.mg())},VA:function(a){var b;b=this.cO(this.mg(),null,a);void 0===b||!this.isValid()&&this.h$()||this.$W(b,null,a.ci)},bX:function(b,c){var d=this.PM(),e,g,h=[];if(this.gq()){e=this.rR();try{e.validate(a.Ba.trim(b))}catch(f){this.KD(f,h)}}if(!c)for(g=0;g<d.length;g++)if(e=d[g],"object"===typeof e)if(e.validate&&
"function"===typeof e.validate)try{e.validate(b)}catch(k){this.KD(k,h)}else a.u.Ew>a.u.Ql&&a.u.info("validator does not support the validate method.");if(0<h.length)throw d=Error(),d.Yu=h,d;}},!0);a.Components.SB({editableValue:{displayOptions:{messages:["inline"],converterHint:["placeholder","notewindow"],validatorHint:["notewindow"],title:["notewindow"]}}});(function(){a.Da("oj._ojLabel",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3clabel\x3e",widgetEventPrefix:"oj",options:{ariaRequiredUnsupported:!1,
describedById:null,help:{definition:null,source:null},required:!1,rootAttributes:null},lb:{$N:"tooltipHelp",aO:"tooltipRequired"},widget:function(){return this.hk},refresh:function(){this._super();this.KU();this.GU()},ae:function(a,b){this._super(a,b);this.Q4();this.rE()},_ComponentCreate:function(){this._super();this.JA=this.eventNamespace+"TouchEatClick";this.Bz=this.eventNamespace+"HelpDefPopup";this.im=a.C.sf();this.E6()},ut:function(a){this.yv=a.attr("class")},mq:function(){this.yv?this.element.attr("class",
this.yv):this.element.removeAttr("class")},E6:function(){var a=this.options,b=a.required,a=a.ariaRequiredUnsupported,c=this.$T(),d=null;this.hk=this.element.wrap(this.U5()).closest(".oj-component");this.aba();c&&(d=this.HE());this.wP(d);b&&(a?d.append(this.zy()):this.element.before(this.zy()))},wP:function(a){var b=this.options,c=b.help.definition;if(b.help.source||c)this.Q$(a),this.H3(),this.h4()},Q4:function(){var a=this.options.required;if(null!==a&&"boolean"!==typeof a)throw Error("Option 'required' has invalid value set: "+
a);},rE:function(){var a=this.options;if(this.$T()&&null==a.describedById)throw Error("ojLabel's describedById option must be set if help source is set\n\r\n      or (ariaRequiredUnsupported and required is set).");},aba:function(){var a=this.element.attr("class"),b;if(a&&(a=a.split(/\s+/),null!=a)){b=a.length;for(var c=0;c<b;c++){var d=a[c];0<d.indexOf("-label")&&(this.hk.addClass(d),this.element.removeClass(d))}}},HE:function(){var a=this.hk.find(".oj-label-group"),b=f("\x3cspan\x3e\x3c/span\x3e",
this.document[0]);b.attr("id",this.options.describedById);return a.prepend(b).children().first()},U5:function(){var a,b;this.options.rootAttributes&&(a=this.options.rootAttributes["class"]);b=f("\x3cdiv class\x3d'oj-label oj-component'\x3e\x3cdiv class\x3d'oj-label-group'\x3e\x3c/div\x3e\x3c/div\x3e",this.document[0]);null!==a&&b.addClass(a);return b},zy:function(){var a=this.D(this.lb.aO),b=f("\x3cspan class\x3d'oj-label-required-icon oj-component-icon' role\x3d'img'\x3e\x3c/span\x3e",this.document[0]);
b.attr("title",a);return b},y5:function(a,b){var c;this.Zz()&&(c=f("\x3ca tabindex\x3d'0' target\x3d'_blank' class\x3d'oj-label-help-icon-anchor oj-label-help-icon oj-component-icon oj-clickable-icon-nocontext'\x3e\x3c/a\x3e",this.document[0]),b&&c.attr("href",b),a?c.attr("title",a):c.attr("title",this.D(this.lb.$N)));return c},h4:function(){var a;a=this.options.help.definition;var b,c;b=this.widget().find(".oj-label-help-icon-anchor");if(0!=b.length){a=a?a:this.D(this.lb.$N);this.Iu?(c=f("#"+this.Iu))&&
c.text(a):(c=f("\x3cdiv style\x3d'display:none'\x3e\x3c/div\x3e"),c.uniqueId(),this.Iu=c.prop("id"),c.text(a),f("body").append(c));this.im&&(this.Hy&&this.widget().off(this.JA),this.Hy=function(){return!1});var e=this;this.eA||(this.eA=function(a){e.Q9(a,c,b,!1)});if(this.im)b.un({recognizers:[[d.Press,{time:750}]]}).on("press",this.eA);else b.on("focusin"+this.Bz+" mousedown"+this.Bz,this.eA);a={my:"start bottom",at:"end top",collision:"flipcenter",of:b};c.ojPopup({position:a})}},Q9:function(a,b,
c,d){if("mousedown"===a.type)d=!0;else if("focusin"===a.type&&d)d=!1;else{if(this.im)if("press"===a.type){var e=this.widget();e.on("click"+this.JA,this.Hy);var g=this;b.on("ojclose",function(){e.off(g.JA);g.Hy=null})}else b.off("ojclose");b.ojPopup("isOpen")||b.ojPopup("open",c)}},H3:function(){var a=this.element,b=this.options.help.definition,c;b&&(a.addClass("oj-label-help-def"),(c=a.attr("title"))?a.attr("title",c+" "+b):a.attr("title",b))},ZU:function(a){this.im&&(this.widget().off(this.JA),this.Hy=
null,a.un().off(this.Bz));a.off(this.Bz);this.eA=null},$U:function(){var a;if(null!=this.Iu){if(a=f("#"+this.Iu))a.ojPopup("destroy"),a.remove();this.Iu=null}},sca:function(){this.element.removeClass("oj-label-help-def");this.element.attr("title","")},Q$:function(a){var b=this.options.help.source,c=this.options.help.definition;this.Zz()&&a.prepend(this.y5(c,b))},$T:function(){var a=this.options;return this.Zz()||a.ariaRequiredUnsupported&&a.required},Zz:function(){var a=this.options;return a.help.source||
a.help.definition},GU:function(){var a,b;this.rE();this.sca();a=this.hk.find(".oj-label-help-icon");1===a.length&&(this.ZU(a),this.$U(),a.remove());a=this.Zz();b=this.hk.find("#"+this.options.describedById);null!=a&&0===b.length?b=this.HE():null==a&&0<b.length&&0===b.children().size()&&b.remove();this.wP(b)},KU:function(){var a,b;b=this.hk.find(".oj-label-required-icon");a="#"+this.options.describedById;this.options.required?(this.rE(),0===b.length?this.options.ariaRequiredUnsupported?(b=this.hk.find(a),
0===b.length&&(b=this.HE()),b.append(this.zy())):this.element.before(this.zy()):(a=this.D(this.lb.aO),b.attr("title",a))):(b.remove(),b=this.hk.find(a),0<b.length&&0===b.children().size()&&b.remove())},_setOption:function(a,b){this._superApply(arguments);"required"===a&&this.KU();"help"===a&&this.GU()},getNodeBySubId:function(a){var b;b=this._super(a);b||(a=a.subId,"oj-label-help-icon"===a&&(b=this.widget().find(".oj-label-help-icon")[0]),"oj-label-help-icon-anchor"===a&&(b=this.widget().find(".oj-label-help-icon-anchor")[0]),
"oj-label-required-icon"===a&&(b=this.widget().find(".oj-label-required-icon")[0]));return b||null},_destroy:function(){var b=this.hk.find(".oj-label-help-icon");this.ZU(b);this.$U();a.C.unwrap(this.element,this.hk);return this._super()}})})();a.Re=function(a){this.Init(a)};a.Sa.QB(a.Sa.Wc.Ns,a.Re);a.b.ga(a.Re,a.mc,"oj.InlineMessagingStrategy");a.Re.prototype.Cp=function(b){a.Re.q.Cp.call(this,b);this.HU()};a.Re.prototype.ZK=function(a){return a&&void 0!==a.X_?!0:!1};a.Re.prototype.update=function(){a.Re.q.update.call(this);
this.HU()};a.Re.prototype.Tj=function(){this.cV();a.Re.q.Tj.call(this)};a.Re.prototype.HU=function(){var a,b;a=this.hi().widget();this.lQ()||(this.we=f("\x3cdiv class\x3d'oj-messaging-inline-container'\x3e\x3c/div\x3e"),this.ID(this.we),a.append(this.we));(b=this.w4())?(a=this.we[0],a.innerHTML="",a.innerHTML=b):this.cV()};a.Re.prototype.cV=function(){this.lQ()&&this.we&&(this.jca(this.we),this.we.remove(),this.we=null)};a.Re.prototype.ID=function(b){var c=this.yh();a.j.Va(c,jQuery);a.j.Va(b,jQuery);
b=b.uniqueId().attr("id");var d=c.attr("aria-describedby"),d=d?d.split(/\s+/):[];d.push(b);d=f.trim(d.join(" "));c.attr("aria-describedby",d)};a.Re.prototype.jca=function(b){var c=this.yh();a.j.Va(c,jQuery);a.j.Va(b,jQuery);b=b.attr("id");var d=c.attr("aria-describedby"),d=d?d.split(/\s+/):[];b=f.inArray(b,d);-1!==b&&d.splice(b,1);(d=f.trim(d.join(" ")))?c.attr("aria-describedby",d):c.removeAttr("aria-describedby")};a.Re.prototype.w4=function(){var a=this.hi().document[0];return this.cM()?this.ZD(a):
""};a.Re.prototype.ZD=function(b){var c;c="";var d=this.rC();this.zC()&&(c=this.sC(),c=a.Na.sX(b,c,d,!0));return c};a.Re.prototype.lQ=function(){return null!=this.we};a.Be={};o_("EditableValueUtils",a.Be,a);a.Be.Lfa=function(a,b){var c,d,e={};if(a&&b)switch(b){case "disabled":c=void 0!==a.attr("disabled")?!!a.prop("disabled"):void 0;break;case "pattern":c=a.prop("pattern")||void 0;break;case "placeholder":c=a.prop("placeholder")||void 0;break;case "readonly":c=void 0!==a.attr("readonly")?!!a.prop("readonly"):
void 0;break;case "required":c=a.attr("required");d=a.prop("required");c=void 0!==c?void 0!==d?!!d:!!c:void 0;break;case "title":c=void 0!==a.attr("title")?a.prop("title"):void 0;break;case "value":c=a.val()||void 0;break;default:c=a.attr(b)||void 0}void 0!==c?(e.ZX=!0,e.value=c):e.ZX=!1;return e};a.Be.vl=function(b,c,d,e){for(var g={},h=0;h<b.length;h++){var f,k;f=b[h];k=f.W;var l=f.option||k,u=f.je,w=f.rc,z=d.element,D=d.options[l];void 0===c[l]&&(D=d.options[l],k=a.Be.Lfa(z,k),k.ZX?(f=k.value,
u&&("boolean"===typeof u?f=a.Be.gfa(l,f):"function"===typeof u&&(f=u.call(d,f))),g[l]=f):void 0===D&&(g[l]=f.ra));u=l in g?g[l]:D;w&&"boolean"===typeof w&&a.Be.Iha(l,u)}null!=e&&e(g);d.option(g,{_context:{rd:!0,mb:!0}})};a.Be.Iha=function(a,b){var c=!1;switch(a){case "required":null!==b&&"boolean"!==typeof b&&(c=!0);break;case "readOnly":case "disabled":null!==b&&"boolean"!==typeof b&&(c=!0)}if(c)throw"Option '"+a+"' has invalid value set: "+b;};a.Be.gfa=function(a,b){var c=b;switch(a){case "required":c=
b?!0:!1}return c}});