/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(a,f){a.Da("oj.inputBase",f.oj.editableValue,{version:"1.0.0",widgetEventPrefix:"oj",_ATTR_CHECK:[],_CLASS_NAMES:"",_WIDGET_CLASS_NAMES:"",_ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES:"",_GET_INIT_OPTIONS_PROPS:[{W:"disabled",ra:!1,rc:!0},{W:"pattern",ra:""},{W:"placeholder",ra:""},{W:"value",ra:null},{W:"readonly",option:"readOnly",ra:!1,rc:!0},{W:"required",ra:!1,je:!0,rc:!0},{W:"title",ra:""}],_INPUT_HELPER_KEY:"",rM:"blur",eN:"keydown",HM:"drop",
options:{converter:void 0,placeholder:void 0,readOnly:void 0},ut:function(a){var b=this._superApply(arguments);this.Gba();return b},ae:function(d,b){this._super(d,b);a.Be.vl(this._GET_INIT_OPTIONS_PROPS,b,this)},_ComponentCreate:function(){var a=this.element,b=this._superApply(arguments),c=this.QM(a),e=this.options.readOnly;this.Ki="rtl"===this.hc();"boolean"===typeof e&&this.element.prop("readonly",e);this.ft()&&(this.Iea(),this.IM()&&this.Hea());"pattern"in c&&a.removeAttr("pattern");this.RE={};
this.nd=null;return b},Sg:function(){var a=this._superApply(arguments),b=this;this._CLASS_NAMES&&this.element.addClass(this._CLASS_NAMES);this.yO();this.SC();f.each(["disabled","readOnly"],function(a,d){b.options[d]&&b.sU(d,b.options[d])});return a},sU:function(a,b){"disabled"===a&&this.element.prop("disabled",b);"readOnly"===a&&(this.element.prop("readonly",b),this.lA("readOnly",b));"disabled"!==a&&"readOnly"!==a||this.yO()},_setOption:function(d,b){var c=this._superApply(arguments);"disabled"!==
d&&"readOnly"!==d||this.sU(d,b);"pattern"===d&&(this.RE[a.Vc.VALIDATOR_TYPE_REGEXP]=this.qR(),this.Xp());return c},_destroy:function(){var d=this._superApply(arguments);this.element.off("blur drop keydown");this.WG&&this.WG.remove();this.ft()&&(this.IM()?a.C.unwrap(this.element,this.Tr):a.C.unwrap(this.element));return d},yO:function(){if(!this.options.readOnly&&!this.options.disabled){this.nd={};var a=f.proxy(this.rH,this),b=f.proxy(this.bA,this),c=function(){this.focus()};this.element.on("blur",
a);this.element.on("keydown",b);this.element.on("drop",c);this.nd[this.rM]=a;this.nd[this.eN]=b;this.nd[this.HM]=c}else if(this.nd)for(a=[this.rM,this.eN,this.HM],b=0,c=a.length;b<c;b++)this.nd[a[b]]&&(this.element.off(a[b],this.nd[a[b]]),delete this.nd[a[b]])},dm:{readOnly:"oj-read-only"},Gba:function(){for(var a=this._ATTR_CHECK,b=0,c=a.length;b<c;b++){var e=a[b].attr;"setMandatory"in a[b]&&this.element.attr(e,a[b].setMandatory)}},rH:function(a){this.tc(this.mg(),a)},bA:function(a){a.keyCode===
f.ui.keyCode.ENTER&&this.tc(this.mg(),a)},ft:function(){return this._WIDGET_CLASS_NAMES},IM:function(){return this._ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES},Iea:function(){f(this.element).wrap(f("\x3cdiv\x3e").addClass(this._WIDGET_CLASS_NAMES));this.Tr=this.element.parent()},Hea:function(){f(this.element).wrap(f("\x3cdiv\x3e").addClass(this._ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES))},SC:function(){if(this._INPUT_HELPER_KEY&&this.ft()){var a=this.element.attr("aria-describedby")||"",b=this.Wl(this._INPUT_HELPER_KEY);
this.element.attr("aria-describedby",a+(" "+b));this.WG=f("\x3cdiv class\x3d'oj-helper-hidden-accessible' id\x3d'"+b+"'\x3e"+this.pj(this.D(this._INPUT_HELPER_KEY))+"\x3c/div\x3e");this.TC().append(this.WG)}},pj:function(a){return f("\x3cspan\x3e"+a+"\x3c/span\x3e").text()},TC:function(){return this.widget()},ht:function(){var d=this._superApply(arguments);this.options.pattern&&(this.RE[a.Vc.VALIDATOR_TYPE_REGEXP]=this.qR());return f.extend(this.RE,d)},lA:function(a,b){-1!=Object.keys(this.dm).indexOf(a)&&
this.widget().toggleClass(this.dm[a],!!b)},qR:function(){if(!this.options.pattern)return null;var d={pattern:this.options.pattern,label:this.MF()};f.extend(d,this.options.translations.regexp||{});return a.na.Jp(a.Vc.VALIDATOR_TYPE_REGEXP).createValidator(d)},Wl:function(a){return this.uuid+"_"+a},Tha:function(){return this.Ki},refresh:function(){var a=this._superApply(arguments);this.Ki="rtl"===this.hc();return a},getNodeBySubId:function(a){return this._super(a)},widget:function(){return this.ft()?
this.Tr:this.element}},!0);a.Da("oj.ojInputText",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],_CLASS_NAMES:"oj-inputtext-input",_WIDGET_CLASS_NAMES:"oj-inputtext oj-form-control oj-component",options:{pattern:void 0},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-inputtext-input"===c&&(b=this.element?this.element[0]:null));return b||null},_GetDefaultStyleClass:function(){return"oj-inputtext"},
tx:function(){return"oj-inputBase"}});a.Da("oj.ojTextArea",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3ctextarea\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[],_CLASS_NAMES:"oj-textarea-input",_WIDGET_CLASS_NAMES:"oj-textarea oj-form-control oj-component",options:{pattern:void 0},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-textarea-input"===c&&(b=this.element?this.element[0]:null));return b||null},_GetDefaultStyleClass:function(){return"oj-textarea"},tx:function(){return"oj-inputBase"}});
a.Da("oj.ojInputPassword",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[{attr:"type",setMandatory:"password"}],_CLASS_NAMES:"oj-inputpassword-input",_WIDGET_CLASS_NAMES:"oj-inputpassword oj-form-control oj-component",options:{pattern:void 0},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-inputpassword-input"===c&&(b=this.element?this.element[0]:null));return b||null},_GetDefaultStyleClass:function(){return"oj-inputpassword"}})});