/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","knockout","ojs/ojmodel"],function(a,f){a.Ha=function(){};o_("KnockoutUtils",a.Ha,a);a.Ha.cK="oj._internalObj";a.Ha.Kg="oj._underUpdate";a.Ha.$r="oj.collectionUpdating";a.Ha.cL="oj.collectionSubscription";a.Ha.kL="oj.collectionUpdatingFunc";a.Ha.map=function(d,b,c){function e(b){return function(c){g[a.Ha.Kg]||d.set(b,c)}}var g,h,k,l;if(d instanceof a.l){h=Array(d.Kd());g=c?f.observableArray(h):h;a.Ha.uW(g,d);if(c)for(h=0;h<d.Wb.length;h++)k=d.Wb[h],g()[k]=a.Ha.map(d.yk(k,null,
!0,!1),b);else for(h=0;h<d.Wb.length;h++)k=d.Wb[h],g[k]=a.Ha.map(d.yk(k,null,!0,!1),b);h=function(b){var c;try{if(!g[a.Ha.Kg]){g[a.Ha.$r]=!0;for(c=0;c<b.length;c++){var e=b[c].index,f=a.Ha.Hb(b[c].value),h=b[c].status;"added"===h?e>=d.length-1?d.add(f):d.add(f,{at:e}):"deleted"===h&&d.Qm(f,e)}d.comparator&&(g[a.Ha.Kg]=!0,g.sort(function(b,c){return a.Ha.RO(b,c,d.comparator,d,this)}),g[a.Ha.Kg]=!1)}}catch(k){throw k;}finally{g[a.Ha.$r]=!1}};c&&g.subscribe&&(g[a.Ha.kL]=h,g[a.Ha.cL]=g.subscribe(h,null,
"arrayChange"));c=function(b,c,d){var e;try{!g[a.Ha.$r]&&c instanceof a.l&&(g[a.Ha.Kg]=!0,e=d.index,g.splice(e,1))}catch(f){throw f;}finally{g[a.Ha.Kg]=!1}};h=function(c,d,e){var f,h;try{if(!g[a.Ha.$r]&&d instanceof a.l&&(g[a.Ha.Kg]=!0,f=d.Iaa(c),void 0!==f&&-1<f))if(h=a.Ha.map(c,b),e.fillIn){for(var k=Array.isArray(g)?g.length:g().length;k<f;k++)g.splice(k,0,a.Ha.map(d.yk(k,null,!0,!1),b));g.splice(f,1,h)}else g.splice(f,0,h)}catch(l){throw l;}finally{g[a.Ha.Kg]=!1}};k=function(b){try{!g[a.Ha.$r]&&
b instanceof a.l&&(g[a.Ha.Kg]=!0,f.isObservable(g)?(g[a.Ha.cL]&&g[a.Ha.cL].dispose(),g.removeAll(),g[a.Ha.kL]&&g.subscribe(g[a.Ha.kL],null,"arrayChange")):g=[])}catch(c){throw c;}finally{g[a.Ha.Kg]=!1}};l=function(b){try{!g[a.Ha.$r]&&b instanceof a.l&&(g[a.Ha.Kg]=!0,g.sort(function(c,e){return a.Ha.RO(c,e,d.comparator,b,this)}))}catch(c){throw c;}finally{g[a.Ha.Kg]=!1}};d.ok(a.$.J.ADD,h,void 0,void 0,!0);d.ok(a.$.J.REMOVE,c,void 0,void 0,!0);d.ok(a.$.J.RESET,k,void 0,void 0,!0);d.ok(a.$.J.SORT,l,
void 0,void 0,!0)}else{if(void 0===d)return;g={};c=d.attributes;h=null;for(h in c)c.hasOwnProperty(h)&&(k=f.observable(d.get(h)),g[h]=k,l=e(h),l.uia=h,k.subscribe&&k.subscribe(l));c=function(b){var c,d;try{for(d in g[a.Ha.Kg]=!0,c=b.jJ(),c)if(c.hasOwnProperty(d))g[d](b.get(d))}catch(e){throw e;}finally{g[a.Ha.Kg]=!1}};d.ok(a.$.J.CHANGE,c,void 0,void 0,!0);a.Ha.uW(g,d);b&&b(g)}return g};o_("KnockoutUtils.map",a.Ha.map,a);a.Ha.Hb=function(d){return d instanceof a.t?d:d.hasOwnProperty(a.Ha.cK)?d[a.Ha.cK]:
d};a.Ha.RO=function(d,b,c,e,f){return a.l.fM(a.Ha.Hb(d),a.Ha.Hb(b),c,e,f)};a.Ha.uW=function(d,b){Object.defineProperty(d,a.Ha.cK,{value:b,enumerable:!1})}});