/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","knockout"],function(a,f,d){function b(a,b){var c={};c.value=b.value;return c}function c(a,b){var c={},d=b.optionMetadata;d&&"shouldWrite"===d.writeback&&(c[b.option]=b.value);return c}function e(){this.Init()}function g(a,b,c){this.Init(a,b,c)}function h(a,b){return function(c){var e,g;e=c.parentElement;g=a.createChildContext(c.data,null,function(a){a.$key=c.key;a.$metadata=c.metadata;a.$headerContext=c});d.renderTemplate(b,g,null,e);return null}}function k(a,b){return function(c){var e,
g;e=c.parentElement;g=a.createChildContext(c.data,null,function(a){a.$keys=c.keys;a.$metadata=c.metadata;a.$cellContext=c});d.renderTemplate(b,g,null,e);return null}}function l(a,b){return function(c){var e=a.createChildContext(c.data);d.renderTemplate(b,e,null,c.parentElement);return null}}function m(a,b,c){if("areaLayers"===a){for(a=0;a<b.length;a++){var d=b[a].areaDataLayer;if(d){var e=d.template;null!=e&&(d.renderer=l(c,e))}}return{areaLayers:b}}if("pointDataLayers"===a){for(a=0;a<b.length;a++)e=
b[a].template,null!=e&&(b[a].renderer=l(c,e));return{pointDataLayers:b}}return null}function n(a,b,c){var e={};(function(b,c){e=function(e){var g=null,f=null;"header"==c?(g=a.extend({$columnIndex:e.columnIndex,$headerContext:e.headerContext,$data:e.data}),f=e.headerContext.parentElement):"cell"==c&&(g=a.createChildContext(e.row,null,function(a){a.$columnIndex=e.columnIndex;a.$cellContext=e.cellContext}),f=e.cellContext.parentElement);"footer"==c&&(g=a.extend({$columnIndex:e.columnIndex,$footerContext:e.footerContext}),
f=e.footerContext.parentElement);d.renderTemplate(b,g,null,f,"replaceNode")}})(c,b);return e}function q(a,b){return function(c){var e=a.createChildContext(c.row,null,function(a){a.$rowContext=c.rowContext});d.renderTemplate(b,e,null,c.rowContext.parentElement,"replaceNode")}}function p(a,b){return function(c){var e=a.createChildContext(c.data);d.renderTemplate(b,e,null,c.parentElement);return null}}function r(a,b){return function(c){var e,g;e=c.parentElement;g=a.createChildContext(c.data,null,function(a){a.$itemContext=
c});d.renderTemplate(b,g,null,e,"replaceNode");return null}}function t(a,b,c){return"item"==a?(a=b.template,null!=a&&(b.renderer=r(c,a)),{item:b}):null}a.ia=function(a,b){this.Init(a,b)};o_("ComponentBinding",a.ia,a);a.b.ga(a.ia,a.b,"oj.ComponentBinding");a.ia.create=function(b,c){if(null==b)throw"Binding name is required!";var e=new a.ia(b,c),g=d.bindingHandlers,f,h=Array.isArray(b)?b:[b];for(f=0;f<h.length;f++)g[h[f]]=e;return e};o_("ComponentBinding.create",a.ia.create,a);a.ia.Vj=function(){return a.ia.M1};
o_("ComponentBinding.getDefaultInstance",a.ia.Vj,a);a.ia.prototype.dk=function(a){var b=a["for"],b=null==b?"@global":b,c=this.Sz[b]||[];c.push(a);this.Sz[b]=c};a.b.i("ComponentBinding.prototype.setupManagedAttributes",{dk:a.ia.prototype.dk});a.ia.vJ=function(){a.ia.VO.vJ()};o_("ComponentBinding.deliverChanges",a.ia.vJ,a);a.ia.prototype.Init=function(b,c){a.ia.q.Init.call(this);"string"===typeof c&&(c={componentName:c});this.VD=c||{};this.s4=Array.isArray(b)?b:[b];this.init=a.b.iB(this,this._init);
this.update=a.b.iB(this,this.Oj);this.Sz={}};a.ia.jD="_ojNeedsJUIBInit";a.ia.prototype._init=function(b,c,e,g,h){d.applyBindingsToDescendants(h,b);f(b).data(a.ia.jD,!0);return{controlsDescendantBindings:!0}};a.ia.prototype.Oj=function(b,c,d,e,g){e=f(b);e.data(a.ia.jD)&&(e.removeData(a.ia.jD),this.PS(b,e,c,d,g))};a.ia.prototype.PS=function(e,f,h,p,l){var k=h(),n=null,r=!1,m=[],q=null,t=null,C=null,A=a.ia.q7(this.s4,e,l),G={},F={},J=this,N=0,T={},O=this.VD.componentName;if(null==O){n="component";if(!A[n]&&
(n="role",!A[n])){a.u.error("component attribute is required for the ojComponent binding");return}var I=k[n];if(null==I){a.u.error("non-null component attribute is required for the ojComponent binding");return}C=d.computed(function(){a.ia.Jy(A[n],n,T,l,!1);0==N?O=d.utils.unwrapObservable(I):(A=null,t?t("destroy"):(C.dispose(),C=null),this.PS(e,f,h,p,l));return null},this,{disposeWhenNodeIsRemoved:e})}if(null!=O)if(t=f[O],"function"===typeof t){t=t.bind(f);f.on("ojdestroy"+a.ia.bD,function(b){if(b.target&&
b.target==e){(b=J.VD.beforeDestroy)&&b(e,t,h,p,l);a.ia.XP(!1,F,e,t,h,p,l);r=!0;J=A=null;q.bw();F=G=T=q=null;a.ia.pea(f);t=null;for(b=0;b<m.length;b++)m[b].dispose();m=null}null!=C&&(C.dispose(),C=null)});var G=a.ia.pV(this.Sz,A,O),M=a.ia.Vj();this!==M&&(M=M.i8(A,O),a.Ac.Pf(M,G),G=M);for(var R={},q=new g(t,e,a.ia.VO),M={"^slider$":[{event:"slidechange",getter:b}],"^oj*":[{event:"ojoptionchange",getter:c}]},P=function(){var b=this.Nba,c=A[b];if(!c)throw"Binding expression for property "+b+" is not found";
c=a.ia.Jy(c,b,T,l,0!==N&&!r);if(0===N){var c=a.ia.MW(k[b]),d=G[b];null!=d?(F[b]=d,d=d.ul,null!=d&&(b=d(b,c,e,t,h,p,l)||{},a.Ac.Pf(R,b))):R[b]=c}else if(!r)if(c=a.ia.MW(c),null!=G[b]){if(d=G[b].update,null!=d)for(b=d(b,c,e,t,h,p,l)||{},c=Object.keys(b),d=0;d<c.length;d++){var g=c[d];q.fX(g,b[g])}}else q.fX(b,c);return null},K,ca=Object.keys(k),W=0;W<ca.length;W++)K=ca[W],K!==n&&m.push(d.computed(P,{Nba:K},{disposeWhenNodeIsRemoved:e}));a.ia.hca(f,O,M,A,q,l,T);M=a.ia.xQ(R);t(R);for(var U in M)t("option",
U,M[U]);(U=this.VD.afterCreate)&&U(e,t,h,p,l);a.ia.XP(!0,F,e,t,h,p,l);R=null}else a.u.error("Component %s is not found",O);N=1};a.ia.q7=function(a,b,c){function e(a){return null==a?null:a.replace(/^(\s|\u00A0)+|(\s|\u00A0)+$/g,"")}var g={},f=null,f=d.bindingProvider.instance,h;h=null;f=f.Mfa?f.Mfa(b,c):b.getAttribute("data-bind");if(!f)return g;b=d.jsonExpressionRewriting.parseObjectLiteral(f);for(c=0;c<b.length;c++){var f=b[c],p=e(f.key);if(0<=a.indexOf(p)){h=f.value;break}}if(!h)return g;b=d.jsonExpressionRewriting.parseObjectLiteral(h);
for(a=0;a<b.length;a++)h=b[a],c=h.key,null!=c&&(g[e(c)]=e(h.value));return g};a.ia.Jy=function(a,b,c,d,e){var g=c[b],f=void 0===g;if(f||null===g.yJ&&g.s_&&e){"string"!==typeof a&&(a=a());var g=null,h=!1;if(null!==a){if(f){if(f=a.charAt(0),"'"===f||'"'===f||0>=a.indexOf("("))h=!0}else h=!0;if(!h||e)g=new Function("$context","with($context){with($data||{}){return "+a+";}}")}g={yJ:g,s_:h};c[b]=g}return!g.yJ||!e&&g.s_?null:g.yJ(d)};a.ia.prototype.i8=function(b,c){return a.ia.pV(this.Sz,b,c)};a.ia.pV=
function(a,b,c){function d(b,c){var e=a[b];if(null!=e)for(var f=e.length-1;0<=f;f--){var h=e[f];null!=h.attributes&&g.push(h);if(c&&(h=h.use,null!=h))for(var h=Array.isArray(h)?h:[h],p=0;p<h.length;p++)d(h[p],!0)}}var e={},g=[];d(c,!0);c=f.oj[c];if(null!=c)for(c=Object.getPrototypeOf(c.prototype);null!=c&&"oj"===c.namespace;)d(c.widgetName,!0),c=Object.getPrototypeOf(c);d("@global",!1);if(0<g.length)for(b=Object.keys(b),c=0;c<b.length;c++)for(var h=b[c],p=0;p<g.length;p++){var l=g[p];if(0<=l.attributes.indexOf(h)){e[h]=
{ul:l.init,update:l.update,Ur:l.afterCreate,afa:l.beforeDestroy};break}}return e};a.ia.bD=".oj_ko";a.ia.pea=function(b){b&&b.off(a.ia.bD)};a.ia.hca=function(b,c,d,e,g,f,h){var p={},l;for(l in d)if(c.match(l)){c=d[l];for(d=0;d<c.length;d++)l=c[d],b.on(l.event+a.ia.bD,{cga:l.getter},function(b,c){b.stopPropagation();var d=b.data.cga(b,c);g.xha();try{for(var l in d)if(e[l]){var k=a.ia.Jy(e[l],l,h,f,!0);a.ia.Kea(l,k,d[l],e[l],f,p)}}finally{g.fha()}});break}};a.ia.y8=function(a){var b=["true","false",
"null","undefined"];if(null==a||0<=b.indexOf(a))return null;b=a.match(/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i);return null===b?null:"function(v){"+(b[1]?"Object("+b[1]+")"+b[2]:a)+"\x3dv;}"};a.ia.Kea=function(b,c,e,g,f,h){null!=c&&d.isObservable(c)?d.isWriteableObservable(c)&&c(e):(b=a.ia.Jy(function(){return a.ia.y8(g)},b,h,f,!0))&&b(e)};a.ia.MW=function(b){b=d.utils.unwrapObservable(b);(Array.isArray(b)||a.Ac.isPlainObject(b))&&b.ojConvertToJS&&(b=d.toJS(b));return b};a.ia.xQ=function(a){var b=
{},c;for(c in a)0<=c.indexOf(".")&&(b[c]=a[c]);for(var d in b)delete a[d];return b};a.ia.XP=function(a,b,c,d,e,g,f){for(var h=Object.keys(b),p=0;p<h.length;p++){var l=h[p],k=b[l];(k=a?k.Ur:k.afa)&&k(l,c,d,e,g,f)}};a.ia.y3=function(){return a.wq()&&d?d.version:""};a.b.ga(e,a.b,"ComponentBinding.GlobalChangeQueue");e.prototype.Init=function(){e.q.Init.call(this);this.Pr=[];this.zr=[]};e.prototype.aha=function(b){-1===this.Pr.indexOf(b)&&(this.Pr.push(b),this.By||(this.By=setTimeout(a.b.iB(this,this.WP),
1)))};e.prototype.bha=function(a){a=this.Pr.indexOf(a);0<=a&&this.Pr.splice(a,1)};e.prototype.vJ=function(){this.By&&clearTimeout(this.By);this.WP()};e.prototype.WP=function(){var a;this.By=null;var b=this.Pr;this.Pr=[];for(a=0;a<b.length;a++){var c=b[a];this.zr.push({hL:c,$m:c.Ifa()})}for(;0<this.zr.length;)a=this.zr.shift(),a.hL.Rea(a.$m)};a.b.ga(g,a.b,"ComponentBinding.ComponentChangeTracker");g.prototype.Init=function(a,b,c){g.q.Init.call(this);this.qa=a;this.au=b;this.zr=c;this.qE={};this.Jr=
0};g.prototype.fX=function(a,b){this.haa()||this.r6||(this.qE[a]=b,this.zr.aha(this))};g.prototype.bw=function(){this.zr.bha(this);this.r6=!0};g.prototype.fha=function(){a.j.assert(0<this.Jr,"ComponentChangeTracker._suspendCount underflow");this.Jr-=1};g.prototype.xha=function(){this.Jr+=1};g.prototype.Rea=function(b){if(null!=a.Components.Eg(this.au)){var c=a.ia.xQ(b),d={changed:!0};this.qa("option",b,d);for(var e in c)this.qa("option",e,c[e],d)}};g.prototype.Ifa=function(){var a=this.qE;this.qE=
{};return a};g.prototype.haa=function(){return 1<=this.Jr};a.ia.VO=new e;a.ia.M1=a.ia.create(["ojComponent","jqueryUI"]);(function(){var b=d.removeNode;d.removeNode=function(c){var d=a.Components;d&&a.C.n_(c);try{b(c)}finally{d&&a.C.n_(null)}}})();a.mK={};o_("koStringTemplateEngine",a.mK,a);a.mK.vga=function(){if(!d.templates){var a={},b={},c=new d.nativeTemplateEngine,e=function(c){this.Mr=c;this.text=function(b){if(!b)return a[this.Mr];a[this.Mr]=b};this.data=function(a,c){b[this.Mr]||(b[this.Mr]=
{});if(1===arguments.length)return b[this.Mr][a];b[this.Mr][a]=c}};c.makeTemplateSource=function(a,b){if("string"==typeof a){b=b||document;var c=b.getElementById(a);return c?new d.templateSources.domElement(c):new e(a)}if(a&&1==a.nodeType||8==a.nodeType)return new d.templateSources.anonymousTemplate(a)};d.templates=a;d.setTemplateEngine(c)}};o_("koStringTemplateEngine.install",a.mK.vga,a);a.ia.Vj().dk({attributes:["header","cell"],init:function(a,b,c,d,e,g,f){if("header"===a)return a=b.row,null!=
a&&(c=a.template,null!=c&&(a.renderer=h(f,c))),a=b.column,null!=a&&(c=a.template,null!=c&&(a.renderer=h(f,c))),{header:b};if("cell"===a)return a=b.template,null!=a&&(b.renderer=k(f,a)),{cell:b}},update:function(a,b,c,d,e,g,f){return"header"===a?(a=b.row,null!=a&&(c=a.template,null!=c&&(a.renderer=h(f,c))),a=b.column,null!=a&&(c=a.template,null!=c&&(a.renderer=h(f,c))),{header:b}):"cell"===a?(a=b.template,null!=a&&(b.renderer=k(f,a)),{cell:b}):null},"for":"ojDataGrid"});d.bindingHandlers.ojContextMenu=
{update:function(a,b){function c(a,b,d){m=d;var f=h();if(m)l.one("touchend.ojContextMenu",function(){f.uq(!0);setTimeout(function(){f.uq(!1)},50)});"touchstart"===F&&"contextmenu"===a.type||"contextmenu"===F&&"touchstart"===a.type?(F=null,clearTimeout(t)):!a.isDefaultPrevented()&&(b={launcher:l,initialFocus:"menu",position:{mouse:{my:"start top",at:"start bottom",of:a},touch:{my:"start\x3e40 center",at:"start bottom",of:a,collision:"flipfit"},keyboard:{my:"start top",at:"start bottom",of:"launcher"}}[b]},
f.Vx=!0,f.open(a,b),f.Vx=!1,g().is(":visible")&&(a.preventDefault(),document.addEventListener("keyup",e),"touchstart"===a.type||"contextmenu"===a.type))&&(F=a.type,t=setTimeout(function(){F=null},300))}function e(a){121==a.which&&a.shiftKey&&g().is(":visible")&&a.preventDefault()}function g(){k||p();return k}function h(){n||p();return n}function p(){k=f(N).first();n=k.data("oj-ojMenu");if(!n)throw Error('"contextMenu" set to "'+N+'", which does not reference a valid JET Menu.');k.on("oj__dismiss.ojContextMenu",
function(){document.removeEventListener("keyup",e)})}var l=f(a),k,n,r,m=!1,q=!1,t,F=null,J;l.off(".ojContextMenu").removeClass("oj-menu-context-menu-launcher")[0].removeEventListener("click",J,!0);k&&k.off(".ojContextMenu");clearTimeout(r);k=n=void 0;var N=d.utils.unwrapObservable(b());"string"!==f.type(N)&&(N=a.getAttribute("contextmenu"))&&(N="#"+N);J=function(a){if(m)return a.preventDefault(),a.stopPropagation(),m=!1};a.addEventListener("click",J,!0);l.on("touchstart.ojContextMenu mousedown.ojContextMenu keydown.ojContextMenu ",
function(a){if("mousedown"!==a.type||!h().uq())return m=!1,"touchstart"===a.type&&(q=!0,r=setTimeout(c.bind(void 0,a,"touch",!0),750)),!0}).on("touchend.ojContextMenu touchcancel.ojContextMenu",function(){q=!1;clearTimeout(r);return!0}).on("keydown.ojContextMenu contextmenu.ojContextMenu",function(a){("contextmenu"===a.type||121==a.which&&a.shiftKey)&&c(a,q?"touch":"keydown"===a.type?"keyboard":"mouse",!1);return!0}).addClass("oj-menu-context-menu-launcher")}};a.ia.Vj().dk({attributes:["areaLayers",
"pointDataLayers"],init:function(a,b,c,d,e,g,f){return m(a,b,f)},update:function(a,b,c,d,e,g,f){return m(a,b,f)},"for":"ojThematicMap"});a.ia.Vj().dk({attributes:["columns","columnsDefault","rowTemplate"],init:function(a,b,c,d,e,g,f){if("columns"==a||"columnsDefault"==a){for(c=0;c<b.length;c++){var h=b[c];d=h.template;e=h.footerTemplate;g=h.headerTemplate;null!=d&&(h.renderer=n(f,"cell",d));null!=e&&(h.footerRenderer=n(f,"footer",e));null!=g&&(h.headerRenderer=n(f,"header",g))}return"columns"==a?
{columns:b}:{columnsDefault:b}}if("rowTemplate"==a)return{rowRenderer:q(f,b)}},update:function(a,b,c,d,e,g,f){if("columns"==a||"columnsDefault"==a){var h;for(c=0;c<b.length;c++){var p=b[c];e=p.template;g=p.footerTemplate;h=p.headerTemplate;null!=e&&(p.renderer=n(f,"cell",e));null!=g&&(p.footerRenderer=n(f,"footer",g));null!=h&&(p.headerRenderer=n(f,"header",h))}"columns"==a?d({columns:b}):d({columnsDefault:b})}else if("rowTemplate"==a)return{rowRenderer:q(f,b)};return null},"for":"ojTable"});a.ResponsiveKnockoutUtils=
{};a.ResponsiveKnockoutUtils.createMediaQueryObservable=function(a){if(null==a)throw Error("oj.ResponsiveKnockoutUtils.createMediaQueryObservable: aborting, queryString is null");a=window.matchMedia(a);var b=d.observable(a.matches);a.addListener(function(a){b(a.matches)});-1!=navigator.userAgent.indexOf("WebKit")&&-1==navigator.userAgent.indexOf("Chrome")&&f(window).resize(function(){0===f("body").has(".oj-webkit-bug-123293").length&&f("body").append('\x3cdiv aria-hidden\x3d"true" class\x3d"oj-helper-hidden-accessible oj-webkit-bug-123293"\x3e');
f(".oj-webkit-bug-123293").text((new Date).getMilliseconds().toString())});return b};a.ResponsiveKnockoutUtils.createScreenRangeObservable=function(){var b=a.ResponsiveUtils.getFrameworkQuery(a.ResponsiveUtils.FRAMEWORK_QUERY_KEY.XXL_UP),c=a.ResponsiveUtils.getFrameworkQuery(a.ResponsiveUtils.FRAMEWORK_QUERY_KEY.XL_UP),e=a.ResponsiveUtils.getFrameworkQuery(a.ResponsiveUtils.FRAMEWORK_QUERY_KEY.LG_UP),g=a.ResponsiveUtils.getFrameworkQuery(a.ResponsiveUtils.FRAMEWORK_QUERY_KEY.MD_UP),f=a.ResponsiveUtils.getFrameworkQuery(a.ResponsiveUtils.FRAMEWORK_QUERY_KEY.SM_UP),
h=null==b?null:a.ResponsiveKnockoutUtils.createMediaQueryObservable(b),p=null==c?null:a.ResponsiveKnockoutUtils.createMediaQueryObservable(c),l=null==e?null:a.ResponsiveKnockoutUtils.createMediaQueryObservable(e),k=null==g?null:a.ResponsiveKnockoutUtils.createMediaQueryObservable(g),n=null==f?null:a.ResponsiveKnockoutUtils.createMediaQueryObservable(f);return d.computed(function(){if(h&&h())return a.ResponsiveUtils.SCREEN_RANGE.XXL;if(p&&p())return a.ResponsiveUtils.SCREEN_RANGE.XL;if(l&&l())return a.ResponsiveUtils.SCREEN_RANGE.LG;
if(k&&k())return a.ResponsiveUtils.SCREEN_RANGE.MD;if(n&&n())return a.ResponsiveUtils.SCREEN_RANGE.SM;throw Error(" NO MATCH in oj.ResponsiveKnockoutUtils.createScreenRangeObservable");})};a.ia.Vj().dk({attributes:["template"],init:function(a,b,c,d,e,g,f){return"template"===a?{_templateFunction:p(f,b)}:null},update:function(a,b,c,d,e,g,f){return"template"===a?{_templateFunction:p(f,b)}:null},"for":"ojDiagram"});a.ia.Vj().dk({attributes:["item"],init:function(a,b,c,d,e,g,f){a=t(a,b,f);if(null!=a)return a},
update:function(a,b,c,d,e,g,f){return t(a,b,f)},"for":"ojListViewRenderer"});a.ia.Vj().dk({"for":"ojListView",use:"ojListViewRenderer"});a.ia.Vj().dk({"for":"ojNavigationList",use:"ojListViewRenderer"})});