/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojradiocheckbox"],function(a,f){(function(){a.Da("oj.ojRadioset",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{disabled:!1,value:void 0},refresh:function(){this._super();this.za()},widget:function(){return this.Eha},ae:function(b,c){var d;this._super(b,c);a.Be.vl([{W:"disabled",ra:!1,rc:!0},{W:"placeholder",ra:""},{W:"required",ra:!1,je:!0,rc:!0},{W:"title",ra:""}],c,this);this.dg=this.oF();
void 0===c.value&&(d=this.dg.filter(":checked"),d=0===d.length?void 0:d.val(),void 0!==d&&this.option("value",d,{_context:{rd:!0,mb:!0}}),void 0===this.options.value&&(this.options.value=null))},_ComponentCreate:function(){var a=this.element;this._super();if(a.is("fieldset"))throw Error("ojRadioset cannot be bound to a fieldset. Use a div instead.");this.dg._ojRadioCheckbox();this.Eha=a.addClass("oj-radioset oj-component").attr("role","radiogroup");this._on(this.Hk)},Sg:function(){this._super();this.za()},
qD:function(){this.dg=this.oF();this.dg.filter(".oj-radio").each(function(){var a=void 0!==f(this).attr("disabled")?!!f(this).prop("disabled"):!1;f(this)._ojRadioCheckbox("option","disabled",a)});this.dg.not(".oj-radio")._ojRadioCheckbox()},Focus:function(){this.lg().first().focus();return!0},tD:function(){},oF:function(){var b=this.element,c=b.find("input[type\x3dradio]:first");0===c.length&&a.u.warn("Could not find any input type\x3dradio within this element");c=c.attr("name");return void 0===c?
(b=b.find("input[type\x3dradio]"),b.not("[name]")):b.find("input[type\x3dradio][name\x3d"+c+"]")},Xe:function(a,c,d){a=this.element.find("input[type\x3dradio]");var f=a.filter(":checked");a=f.length?f:a.filter(":enabled").first();this.Ye(c,d,{launcher:a})},za:function(){this.Nm(this.options.disabled)},Hk:{change:function(a){this.ux(a)}},ux:function(a){var c=this.mg();this.tc(c,a,d)},mg:function(){return this.dq()},sj:function(a){a="[value\x3d'"+a+"']";void 0!==a&&void 0!==this.dg&&(a=this.dg.filter(a),
void 0!==a&&0<a.length?a.prop("checked")||a._ojRadioCheckbox("option","checked",!0):this.dg._ojRadioCheckbox("option","checked",!1))},dq:function(){var a=this.dg.filter(":checked");return 0===a.length?null:a.val()},_GetDefaultStyleClass:function(){return"oj-radioset"},lg:function(){return this.oF()},pD:function(){},kx:function(){return!0},Nm:function(a){a=!!a;this.dg.each(function(){f(this).data("oj-_ojRadioCheckbox").zt(a)});this.dg._ojRadioCheckbox("refreshDisabled")},_setOption:function(a,c){this._superApply(arguments);
"disabled"===a&&this.Nm(c)},getNodeBySubId:function(a){var c=this._super(a);c||(a=a.subId,"oj-radioset-inputs"===a&&(c=this.dg.get()));return c||null},_destroy:function(){var a=this._super();this.dg&&this.dg._ojRadioCheckbox("destroy");return a}});var d={mp:!1}})()});