/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojmodel","ojs/ojdatacollection-common"],function(a,f){a.Ce=function(a,b){this.Iga=a;this.ec=b};o_("EmptyNodeSet",a.Ce,a);a.Ce.prototype.getParent=function(){return this.Iga};a.b.i("EmptyNodeSet.prototype.getParent",{getParent:a.Ce.prototype.getParent});a.Ce.prototype.ua=function(){return this.ec};a.b.i("EmptyNodeSet.prototype.getStart",{ua:a.Ce.prototype.ua});a.Ce.prototype.Q=function(){return 0};a.b.i("EmptyNodeSet.prototype.getCount",{Q:a.Ce.prototype.Q});
a.Ce.prototype.getData=function(){return null};a.b.i("EmptyNodeSet.prototype.getData",{getData:a.Ce.prototype.getData});a.Ce.prototype.getMetadata=function(){return null};a.b.i("EmptyNodeSet.prototype.getMetadata",{getMetadata:a.Ce.prototype.getMetadata});a.De=function(a,b){this.zb=a;this.ec=b};o_("FlattenedNodeSet",a.De,a);a.De.prototype.getParent=function(){return this.zb.getParent()};a.b.i("FlattenedNodeSet.prototype.getParent",{getParent:a.De.prototype.getParent});a.De.prototype.ua=function(){return void 0!=
this.ec?this.ec:this.zb.ua()};a.b.i("FlattenedNodeSet.prototype.getStart",{ua:a.De.prototype.ua});a.De.prototype.Q=function(){void 0===this.DB&&(this.DB=this.cR(this.zb,0),void 0!=this.ec&&(this.DB-=this.ec));return this.DB};a.b.i("FlattenedNodeSet.prototype.getCount",{Q:a.De.prototype.Q});a.De.prototype.cR=function(a,b){var c,e,g,f;c=a.ua();e=a.Q();b+=e;if(a.pf)for(g=0;g<e;g++)f=a.pf(g+c),null!=f&&(b=this.cR(f,b));return b};a.De.prototype.getData=function(a){return this.CF(this.zb,a,{index:this.zb.ua()},
this.jb)};a.b.i("FlattenedNodeSet.prototype.getData",{getData:a.De.prototype.getData});a.De.prototype.getMetadata=function(a){return this.CF(this.zb,a,{index:this.zb.ua()},this.QF)};a.b.i("FlattenedNodeSet.prototype.getMetadata",{getMetadata:a.De.prototype.getMetadata});a.De.prototype.QF=function(a,b){return a.getMetadata(b)};a.De.prototype.jb=function(a,b){return a.getData(b)};a.De.prototype.CF=function(a,b,c,e){var g,f,k,l;g=a.ua();f=a.Q();for(k=0;k<f;k++){l=c.index;if(l===b)return e.call(this,
a,k+g);c.index=l+1;if(a.pf&&(l=a.pf(k+g),null!=l&&(l=this.CF(l,b,c,e),null!=l)))return l}return null};a.ig=function(a,b,c){this.nn=a;this.BK=b;this.AK=this.d7(c)};o_("MergedNodeSet",a.ig,a);a.ig.prototype.d7=function(a){var b,c,e;b=this.nn.ua();for(c=b+this.nn.Q();b<c;b++)if(e=this.nn.getMetadata(b).key,a===e)return b;return c-1};a.ig.prototype.getParent=function(){return this.nn.getParent()};a.b.i("MergedNodeSet.prototype.getParent",{getParent:a.ig.prototype.getParent});a.ig.prototype.ua=function(){return this.nn.ua()};
a.b.i("MergedNodeSet.prototype.getStart",{ua:a.ig.prototype.ua});a.ig.prototype.Q=function(){return this.nn.Q()+this.BK.Q()};a.b.i("MergedNodeSet.prototype.getCount",{Q:a.ig.prototype.Q});a.ig.prototype.getData=function(a){a=this.PR(a);return a.set.getData(a.index)};a.b.i("MergedNodeSet.prototype.getData",{getData:a.ig.prototype.getData});a.ig.prototype.getMetadata=function(a){a=this.PR(a);return a.set.getMetadata(a.index)};a.b.i("MergedNodeSet.prototype.getMetadata",{getMetadata:a.ig.prototype.getMetadata});
a.ig.prototype.PR=function(a){if(a<=this.AK)return{set:this.nn,index:a};var b=this.BK.Q();return a>this.AK+b?{set:this.nn,index:a-b}:{set:this.BK,index:a-(this.AK+1)}};a.Ge=function(a,b,c,e){this.zb=a;this.Xi=b;this.ys=c;this.Zh=e};o_("NodeSetWrapper",a.Ge,a);a.Ge.prototype.getParent=function(){return this.zb.getParent()};a.b.i("NodeSetWrapper.prototype.getParent",{getParent:a.Ge.prototype.getParent});a.Ge.prototype.ua=function(){return null!=this.ys?this.ys.start:this.zb.ua()};a.b.i("NodeSetWrapper.prototype.getStart",
{ua:a.Ge.prototype.ua});a.Ge.prototype.Q=function(){var a,b;a=this.zb.ua();b=this.zb.Q();null!=this.ys&&(this.ys.start>a?b=Math.min(0,b-(this.ys.start-a)):this.ys.start<a&&(b=0));return b};a.b.i("NodeSetWrapper.prototype.getCount",{Q:a.Ge.prototype.Q});a.Ge.prototype.getData=function(a){return this.zb.getData(a)};a.b.i("NodeSetWrapper.prototype.getData",{getData:a.Ge.prototype.getData});a.Ge.prototype.getMetadata=function(a){var b;b=this.zb.getMetadata(a);b.index=a;b.parentKey=this.getParent();this.Xi.call(null,
b.key,b);return b};a.b.i("NodeSetWrapper.prototype.getMetadata",{getMetadata:a.Ge.prototype.getMetadata});a.Ge.prototype.pf=function(d){return null!=this.Zh&&-1!=this.Zh.indexOf(this.zb.getMetadata(d).key)||!this.zb.pf||(d=this.zb.pf(d),null==d)?null:new a.Ge(d,this.Xi,null,this.Zh)};a.b.i("NodeSetWrapper.prototype.getChildNodeSet",{pf:a.Ge.prototype.pf});a.ma=function(d,b){this.uf=d;this.Hw=b||{};a.ma.q.constructor.call(this)};o_("FlattenedTreeDataSource",a.ma,a);a.b.ga(a.ma,a.Mg,"oj.FlattenedTreeDataSource");
a.ma.prototype.Init=function(){var d;a.ma.q.Init.call(this);this.uf.on("change",this.J9.bind(this));this.wK=parseInt(this.Hw.fetchSize,10);isNaN(this.wK)&&(this.wK=25);this.yp=parseInt(this.Hw.maxCount,10);isNaN(this.yp)&&(this.yp=500);d=this.Hw.expanded;Array.isArray(d)?this.xl=d:("all"===d&&(this.Zh=[]),this.xl=[]);this.wl=[]};a.b.i("FlattenedTreeDataSource.prototype.Init",{Init:a.ma.prototype.Init});a.ma.prototype.handleEvent=function(d,b){return a.ma.q.handleEvent.call(this,d,b)};a.b.i("FlattenedTreeDataSource.prototype.handleEvent",
{handleEvent:a.ma.prototype.handleEvent});a.ma.prototype.Ae=function(){delete this.wl;delete this.xl;delete this.Zh;this.uf.off("change");this.uf.Ae&&this.uf.Ae()};a.b.i("FlattenedTreeDataSource.prototype.Destroy",{Ae:a.ma.prototype.Ae});a.ma.prototype.JJ=function(){return this.wK};a.ma.prototype.oY=function(){return this.xl};a.b.i("FlattenedTreeDataSource.prototype.getExpandedKeys",{oY:a.ma.prototype.oY});a.ma.prototype.jw=function(a){return null!=this.Hw?this.Hw[a]:null};a.b.i("FlattenedTreeDataSource.prototype.getOption",
{jw:a.ma.prototype.jw});a.ma.prototype.getWrappedDataSource=function(){return this.uf};a.b.i("FlattenedTreeDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:a.ma.prototype.getWrappedDataSource});a.ma.prototype.GF=function(a){var b,c;b=this.JJ();c=this.yp;return-1===b?-1===a?c:a:-1===a?Math.min(b,a):b};a.ma.prototype.np=function(a,b){this.kr()?this.Y6(a,b):this.X6(a,b)};a.ma.prototype.X6=function(d,b){var c,e,g,f,k,l;if(d.start>this.fe()){c=this.PF();if(0>this.fe()){d.count=Math.min(c,
d.count);this.uf.Rd(null,d,{success:function(a){this.ym(a,null,0,d,0,b)}.bind(this),error:function(a){this.Qk(a,b)}.bind(this)});return}if(0<c){e=this.xR();g=e.parent;f=this.uf.nf(g);k=e.index;l=e.depth;-1===f||k<f-1?(e=this.GF(f),d.start=k+1,d.count=-1===f?e:Math.min(c,Math.min(e,f-d.start)),this.uf.Rd(g,d,{success:function(a){this.ym(a,g,l,d,f,b)}.bind(this),error:function(a){this.Qk(a,b)}.bind(this)})):k===f-1?(c=new a.Ce(null,d.start),null!=b&&null!=b.success&&b.success.call(null,c)):(c=this.CQ(g,
l,b,c),c||(c=new a.Ce(null,d.start),null!=b&&null!=b.success&&b.success.call(null,c)));return}}this.WJ(d,b)};a.ma.prototype.PF=function(){return this.yp-(this.fe()+1)};a.ma.prototype.Qk=function(a,b){null!=b&&null!=b.error&&b.error.call(null,a)};a.ma.prototype.ym=function(d,b,c,e,g,f){var k;k=[];d=new a.Ge(d,this.rw.bind(this),e);this.Iba(d,b,c,k);-1===g&&0===d.Q()&&null!=b&&0<c?(k=this.CQ(b,c,f))||null!=f&&null!=f.success&&f.success.call(null,d):0===k.length?null!=f&&null!=f.success&&f.success.call(null,
d):(b=[],b.push(k),k={},k.callbacks=f,k.nodeSet=d,k.keys=[],this.AW(b,k))};a.ma.prototype.CQ=function(a,b,c,e){var g,f,k,l,m,n,q,p,r;void 0===e&&(e=this.PF());this.Y$()&&(g={queueOnly:!0});f=r=this.GF(-1);for(k=this.fe()-1;0<=k;k--)if(l=this.ug(k),m=l.depth,m<b&&(a=l.parent,n=this.uf.nf(a),l=l.index,(q=-1===n)||l<n-1)){p={};p.start=l+1;q?(p.count=Math.min(e,Math.max(0,f)),g=void 0):p.count=Math.min(e,Math.min(f,n-p.start));if(0==p.count)break;this.uf.Rd(a,p,{success:function(b){this.ym(b,a,m,p,n,
c)}.bind(this),error:function(a){this.Qk(a,c)}.bind(this)},g);b=m;f=Math.max(0,f-p.count);if(q||0===m||0===f)break}void 0!=g&&this.uf.Rd(a,{start:p.count,count:0},{success:function(b){this.ym(b,a,m,p,n,c)}.bind(this),error:function(a){this.Qk(a,c)}.bind(this)});return f!=r};a.ma.prototype.Iba=function(a,b,c,e){var g,f,k,l;g=a.ua();f=a.Q();for(k=0;k<f;k++)l=a.getMetadata(g+k),l=l.key,this.Yx(l,c,g+k,b),this.Ou(l)&&e.push(l)};a.ma.prototype.rw=function(a,b){this.Ou(a)&&!b.leaf?b.state="expanded":b.state=
b.leaf?"leaf":"collapsed"};a.ma.prototype.Y6=function(a,b){var c={maxCount:this.yp};0<=this.fe()&&(c.start=this.ug(this.fe()).key);this.uf.ll(null,{success:function(c){this.s9(c,a,b)}.bind(this),error:function(a){this.Qk(a,b)}.bind(this)},c)};a.ma.prototype.s9=function(d,b,c){var e,g,f;b.start>this.fe()?(e=this.PF(),g=Math.min(e,b.count),d=new a.Ge(d,this.rw.bind(this),null,this.Zh),0<=this.fe()?(f=this.xR(),e={index:0,found:!1,count:0},this.CH(d,null,0,f,g,e),g=e.index+1):(e={count:0},this.CH(d,
null,0,null,g,e),g=0),null!=c&&null!=c.success&&(d=null!=e?0===e.count?new a.Ce(null,b.start):new a.De(d,g):new a.De(d),c.success.call(null,d))):this.WJ(b,c)};a.ma.prototype.CH=function(a,b,c,e,g,f){var k,l,m,n,q;k=a.ua();l=a.Q();for(m=0;m<l&&f.count!=g;m++){n=a.getMetadata(k+m);q=n.key;f.checkDepth&&e.depth===c&&(f.found=!0,f.checkDepth=!1);if(null==e||f.found)this.Yx(q,c,k+m,b),f.count+=1,n.state=n.leaf?"leaf":"expanded";null==e||f.found||(q===e.key?n.leaf||this.Ou(q)?f.found=!0:f.checkDepth=!0:
f.index+=1);a.pf&&this.Ou(q)&&(n=a.pf(m),null!=n&&this.CH(n,q,c+1,e,g,f))}};a.ma.prototype.expand=function(a){this.ce(a)};a.b.i("FlattenedTreeDataSource.prototype.expand",{expand:a.ma.prototype.expand});a.ma.prototype.ce=function(d,b){var c,e,f,h;c=this.uf.nf(d);e=this.GF(c);f=this.yp;if(this.fe()+1===f&&(h=this.Vh(d),h==f-1)){this.VJ(d,new a.Ce(d,0),0,b);return}0==e?this.VJ(d,new a.Ce(d,0),0,b):this.uf.Rd(d,{start:0,count:e},{success:function(a){this.VJ(d,a,c,b)}.bind(this),error:function(){this.dga(d)}.bind(this)})};
a.ma.prototype.collapse=function(a){var b,c,e,f,h;b=this.Vh(a)+1;c=this.ug(b-1);e=0;c=c.depth;f=this.fe();for(h=b;h<f+1;h++){var k=this.ug(h).depth;if(k>c)e+=1;else if(k==c)break}if(0!=e){this.kr()?this.Zh.push(a):this.pca(a);f=[];for(c=0;c<e;c++)f.push({key:this.ug(b+c).key,index:b+c});this.WU(b,e);this.RB(f)}this.handleEvent("collapse",{rowKey:a})};a.b.i("FlattenedTreeDataSource.prototype.collapse",{collapse:a.ma.prototype.collapse});a.ma.prototype.Ou=function(a){return this.kr()?this.Zh&&0<this.Zh.length?
-1===this.TQ(a):!0:this.xl&&0<this.xl.length?-1<this.iR(a):!1};a.ma.prototype.TQ=function(a){return this.vR(this.Zh,a)};a.ma.prototype.iR=function(a){return this.vR(this.xl,a)};a.ma.prototype.vR=function(a,b){var c,e;e=-1;for(c=0;c<a.length;c++)a[c]===b&&(e=c);return e};a.ma.prototype.pca=function(a){a=this.iR(a);-1<a&&this.xl.splice(a,1)};a.ma.prototype.kca=function(a){a=this.TQ(a);-1<a&&this.Zh.splice(a,1)};a.ma.prototype.dga=function(a){this.handleEvent("expand",{rowKey:a})};a.ma.prototype.VJ=
function(d,b,c,e){var f,h,k,l,m,n,q,p,r,t,s;b=new a.Ge(b,this.rw.bind(this));h=f=this.Vh(d)+1;k=b.ua();l=b.Q();m=this.ug(f-1);n=m.depth+1;p=[];for(r=k;r<l;r++)k=b.getMetadata(r),q=k.key,this.Ou(q)&&p.push(q),this.fT(f,k,m.key,r,n),f++;this.kr()?this.kca(d):-1===this.xl.indexOf(d)&&this.xl.push(d);void 0!=e&&(t=e.queue,s=e.prevNodeSetInfo);void 0!=s&&(b=new a.ig(s.nodeSet,b,d));if(0!=p.length||void 0!==t&&0!=t.length)void 0===t&&(t=[]),0<p.length&&t.push(p),void 0===s&&(s={},s.firstIndex=h,s.firstKey=
d,s.keys=[]),s.nodeSet=b,s.keys.push(d),this.AW(t,s);else{if(void 0!=s){e=s.callbacks;if(null!=e){e.success.call(null,b);return}this.yB(s.firstIndex,s.firstKey,b)}else this.yB(h,d,b);b=this.yp;-1===c&&l===this.JJ()||c>l||f==b?this.TE(f):this.fe()>=b&&this.TE(b);if(void 0!=s)for(c=0;c<s.keys.length;c++)this.handleEvent("expand",{rowKey:s.keys[c]});this.handleEvent("expand",{rowKey:d})}};a.ma.prototype.AW=function(a,b){var c,e;c=a[a.length-1];e=c.shift();0===c.length&&a.pop();this.ce(e,{prevNodeSetInfo:b,
queue:a})};a.ma.prototype.fT=function(a,b,c,e,f){b=b.key;a<=this.fe()?this.Yx(b,f,e,c,a):this.Yx(b,f,e,c)};a.ma.prototype.TE=function(a,b){var c;void 0==b&&(b=this.fe()+1-a);c=[];for(var e=0;e<b;e++)c.push({row:this.ug(a+e).key,index:a+e});this.WU(a,b);this.RB(c)};a.ma.prototype.J9=function(a){var b,c,e;b=a.operation;c=a.parent;c=Array.isArray(c)?c[c.length-1]:c;e=a.index;"insert"===b?this.w9(c,e,a.data):"delete"===b?this.g9(c,e):"refresh"===b&&this.S9(c)};a.ma.prototype.w9=function(a,b,c){var e,
f;e=this.Vh(a);f=this.ug(e).depth+1;e=e+b+1;c=c.getMetadata(c.ua());this.fT(e,c,a,b,f)};a.ma.prototype.g9=function(d,b){var c,e,f,h,k;c=this.Vh(d);e=this.ug(c);c+=b;f=this.ug(c);a.j.assert(f.parent===e&&f.depth===e.depth+1);e=c+1;for(h=this.fe();e<=h;){k=this.ug(e);if(k.depth!=f.depth)break;e++}this.TE(c,1)};a.ma.prototype.S9=function(a){null==a&&this.refresh()};a.ma.prototype.kr=function(){var a=this.uf.getCapability("fetchDescendants");return void 0!=this.Zh&&null!=a&&"disable"!=a};a.ma.prototype.Y$=
function(){return"enable"===this.uf.getCapability("batchFetch")};a.ma.prototype.refresh=function(){this.S4()};a.ma.prototype.Vh=function(a){var b,c,e;b=this.fe();for(c=0;c<=b;c++)if(e=this.ug(c),e.key==a)return c;return-1};a.ma.prototype.getKey=function(a){return 0>a||a>this.fe()?null:this.ug(a).key};a.ma.prototype.Rfa=function(){return{start:0,end:this.fe()+1}};a.ma.prototype.Kfa=function(a){var b;b=[];a=this.Vh(a);for(a=this.Di(a);null!=a;)b.push(a),a=this.Vh(a),a=this.Di(a);return b.reverse()};
a.ma.prototype.WJ=function(a,b){null!=b&&null!=b.error&&b.error.call(null)};a.ma.prototype.yB=function(){a.j.Xa()};a.ma.prototype.RB=function(){a.j.Xa()};a.ma.prototype.fe=function(){return this.wl.length-1};a.ma.prototype.xR=function(){return this.wl[this.fe()]};a.ma.prototype.ug=function(a){return this.wl[a]};a.ma.prototype.Di=function(a){a=this.wl[a];return null!=a?a.parent:null};a.ma.prototype.Yx=function(a,b,c,e,f){var h={};h.key=a;h.depth=b;h.index=c;h.parent=e;void 0===f?this.wl.push(h):this.wl.splice(f,
0,h)};a.ma.prototype.WU=function(a,b){this.wl.splice(a,b)};a.ma.prototype.S4=function(){this.wl.length=0};a.Da("oj.ojRowExpander",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{context:null,expand:null,collapse:null},Rj:{root:"oj-rowexpander",icon:"oj-component-icon",clickable:"oj-clickable-icon-nocontext",expand:"oj-rowexpander-expand-icon",collapse:"oj-rowexpander-collapse-icon",leaf:"oj-rowexpander-leaf-icon",lazyload:"oj-rowexpander-lazyload-icon",toucharea:"oj-rowexpander-touch-area",
indent:"oj-rowexpander-indent",iconspacer:"oj-rowexpander-icon-spacer",depth0:"oj-rowexpander-depth-0",depth1:"oj-rowexpander-depth-1",depth2:"oj-rowexpander-depth-2",depth3:"oj-rowexpander-depth-3",depth4:"oj-rowexpander-depth-4",depth5:"oj-rowexpander-depth-5",depth6:"oj-rowexpander-depth-6",depth7:"oj-rowexpander-depth-7"},as:{Qs:7,J0:53},_ComponentCreate:function(){this._super();this.element.addClass(this.Rj.root);this.RS()},RS:function(){var a=this,b;b=this.options.context;this.Aa=b.component;
this.kc=b.datasource;this.depth=b.depth;this.mh=b.state;this.Fl=b.key;this.index=b.index;this.MB=b.parentKey;this.J3();this.I3();this.xA();"expanded"===this.mh||"collapsed"===this.mh?(f(this.gL).on("touchend",function(b){b.preventDefault();a.rF()}),f(this.gL).on("click",function(b){b.preventDefault();a.rF()}),f(this.element).on("keypress",function(b){var e=b.keyCode||b.which;if(e===f.ui.keyCode.ENTER||e===f.ui.keyCode.SPACE)a.rF(),b.preventDefault(),b.target.focus()}),this.vB=this.rS.bind(this),f(this.Aa.element).on("ojkeydown",
this.vB),this.TY=this.q9.bind(this),this.SY=this.Y8.bind(this),this.kc.on("expand",this.TY,this),this.kc.on("collapse",this.SY,this)):"leaf"===this.mh&&(this.vB=this.rS.bind(this),f(this.Aa.element).on("ojkeydown",this.vB),f(this.icon).attr("tabindex",-1));this.RY=this.R8.bind(this);f(this.Aa.element).on("ojactive",this.RY)},refresh:function(){this.element.empty();this.RS()},_destroy:function(){f(this.Aa.element).off("ojkeydown",this.vB);f(this.Aa.element).off("ojactive",this.RY);this.kc.off("expand",
this.TY,this);this.kc.off("collapse",this.SY,this);this.element.removeClass(this.Rj.root);this.element.empty()},_setOption:function(a,b,c){this._super(a,b,c);"context"==a&&this.refresh()},J3:function(){var a,b;b=this.depth-1;if(b<this.as.Qs)this.PD(b);else{for(a=1;a<=b/this.as.Qs;a++)this.PD(this.as.Qs);a=b%this.as.Qs;a<this.as.Qs&&this.PD(a)}},PD:function(a){a=f(document.createElement("span")).addClass(this.Rj.indent).addClass(this.Rj["depth"+a]);this.element.append(a)},I3:function(){var a=f(document.createElement("div")).addClass(this.Rj.iconspacer);
this.gL=f(document.createElement("div")).addClass(this.Rj.toucharea);this.icon=f(document.createElement("a")).attr("href","#").attr("aria-labelledby",this.wR()).addClass(this.Rj.icon).addClass(this.Rj.clickable);this.element.append(a.append(this.gL.append(this.icon)))},eo:function(a){this.icon.addClass(this.Rj[a])},Xo:function(a){this.icon.removeClass(this.Rj[a])},xA:function(){switch(this.mh){case "leaf":this.Xo("icon");this.Xo("clickable");this.eo("leaf");break;case "collapsed":this.eo("expand");
this.cy(!1);break;case "expanded":this.eo("collapse");this.cy(!0);break;case "loading":this.Xo("clickable"),this.eo("lazyload")}},RH:function(){switch(this.mh){case "leaf":this.Xo("leaf");this.eo("icon");this.eo("clickable");break;case "collapsed":this.Xo("expand");break;case "expanded":this.Xo("collapse");break;case "loading":this.Xo("lazyload"),this.eo("clickable")}},R8:function(a,b){var c,e;null!=b.activeKey&&(c=b.activeKey.rowKey,this.Fl!==c||null!=b.previousActiveKey&&b.previousActiveKey.row==
b.activeKey.row||!this.Aa.sA||(c=this.D("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.kc.getWrappedDataSource().nf(this.MB)}),e="collapsed"===this.mh?this.D("accessibleStateCollapsed"):"expanded"===this.mh?this.D("accessibleStateExpanded"):"",this.Aa.sA({context:c,state:e})))},rS:function(d,b){var c,e,g;if(this.Fl===b.rowKey&&(d=d.originalEvent,c=d.keyCode||d.which,a.C.vs(d)))if(c==f.ui.keyCode.RIGHT&&"collapsed"===this.mh)this.fH(),this.kc.expand(this.Fl),d.preventDefault();
else if(c==f.ui.keyCode.LEFT&&"expanded"===this.mh)this.fH(),this.kc.collapse(this.Fl),d.preventDefault();else if(d.altKey&&c==this.as.J0&&this.Aa.sA){c=this.kc.Kfa(this.Fl);if(null!=c&&0<c.length)for(e=[],g=0;g<c.length;g++)e.push({key:c[g],label:this.D("accessibleLevelDescription",{level:g+1})});c=this.D("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.kc.getWrappedDataSource().nf(this.MB)});this.Aa.sA({context:c,state:"",ancestors:e});d.preventDefault()}},fH:function(){this.RH();
this.mh="loading";this.xA()},q9:function(a){a=a.rowKey;a===this.Fl&&(this.RH(),this.mh="expanded",this.xA(),this.cy(!0),this._trigger("expand",null,{rowKey:a}))},Y8:function(a){a=a.rowKey;a===this.Fl&&(this.RH(),this.mh="collapsed",this.xA(),this.cy(!1),this._trigger("collapse",null,{rowKey:a}))},rF:function(){var a=this.mh;this.fH();"collapsed"===a?this.kc.expand(this.Fl):"expanded"===a&&this.kc.collapse(this.Fl)},cy:function(a){this.icon.attr("aria-expanded",a)},getNodeBySubId:function(a){return null==
a?this.element?this.element[0]:null:"oj-rowexpander-icon"===a.subId&&null!=this.icon?this.icon.get(0):null},getSubIdByNode:function(a){return a===this.icon.get(0)?{fja:"oj-rowexpander-icon"}:null},Zl:function(){this._super();this.icon.attr("aria-labelledby",this.wR())},wR:function(){return this.element.parent().closest("[id]").attr("id")}})});