/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(["ojs/ojcore","knockout","signals","promise"],function(a,f,d){(function(){function b(b){a.u.info("Entering _updateAll.");for(var c=!1,d=0;d<b.length&&(c=b[d],c=c.Rc.Oj(c.value),c);d++);a.u.info("_updateAll returns "+(c?"true":"false"));return{hasChanged:c}}function c(b){a.u.info("Start _canEnter.");for(var c=!0,d=Promise.resolve(!0),e=[],g=0;g<b.length;g++){var f=b[g],h=f.Rc.uh(f.value);if(h&&(f=h.canEnter,"function"===typeof f)){var p;try{p=f()}catch(k){return a.u.error("Error when executing canEnter callback: "+
k.message),Promise.resolve([])}if(p&&p.then)d=p;else if(c=p,!c){a.u.info("canEnter is false for state: "+h.id);break}}e.push(d)}return c?Promise.all(e).then(function(c){for(var d=0;d<c.length;d++)if(!c[d])return a.u.info("CanEnter promise at position "+d+" returned false."),[];return b}):Promise.resolve([])}function e(a){return a.substring(0,a.lastIndexOf("/"))}function g(a){var b={};if(a){var c=[],c=a.split("\x26"),d;for(d in c){var e=c[d].split(/=(.+)?/);a=e[0];a.length&&("undefined"===typeof b[a]&&
(b[a]=[]),e=e[1]&&decodeURIComponent(e[1].replace(/\+/g," ")),b[a].push(e))}}return b}function h(){var a;window.location.hash&&0<window.location.hash.length?(a=window.location.hash.replace(/[^#]*#/,""),a=a.replace(x+"/","")):a=window.location.href.replace(v+"/","");return a}function k(a){return a.parent?k(a.parent)+"."+a.name:a.name}function l(a,b){for(var c,d=0;d<a.qg.length;d++){var e=a.qg[d].Rc;if(!e.To||e.To===b){c=e;break}}return c}function m(a,b){if(b&&0<Object.getOwnPropertyNames(b).length){var c;
c=-1==a.indexOf("?")?"?":"\x26";var d=a,e=JSON.stringify(b),g=encodeURIComponent(e),e=z.hfa(e),f=!1,h="oj_Router\x3d";e.length<=g.length&&(f=!0);h=f?h+("1"+e):h+("0"+g);if(1024<h.length)throw Error("Size of bookmarkable data is too big.");a=d+(c+h)}return a}function n(){a.u.info("Handling popState event with URL: "+window.location.href);for(var b=null,c=0;c<D.qg.length;c++){var d=D.qg[c].Rc;if(D.hf()&&D.hf()===d.To){b=d;break}}t(b).then(function(a){if(a)return s(h()).then(function(a){q(a.hasChanged)});
q(!1);return Promise.resolve({hasChanged:!1})}).then(null,function(b){a.u.error("Error while changing state in handlePopState: "+b.message)})}function q(b){a.qb.transitionedToState.dispatch({hasChanged:b})}function p(a,b,c){var d=[];a.parent&&(d=p(a.parent,b+1));var e;"undefined"===typeof c?(c=a.MP())&&(e=c.id):e=c.id;e===a.Ek&&0===b&&(e=null);d.push({Rc:a,XB:e});return d}function r(b,c){var d=!0,e=Promise.resolve(!0),g=b.uh(b.hf());if(g){for(var f=0;f<b.qg.length;f++)if(d=r(b.qg[f].Rc,c),!d)return!1;
f=g.bC&&g.bC.canExit?g.bC.canExit:g.canExit;if("function"===typeof f){var h;try{h=f()}catch(p){return a.u.error("Error when executing canExit callback: "+p.message),!1}h&&h.then?e=h:(h||a.u.info("canExit is false for state "+g.id),d=h)}}c.push(e);return d}function t(b){if(!b)return Promise.resolve(!0);var c=[];return(b=r(b,c))?Promise.all(c).then(function(b){for(var c=0;c<b.length;c++)if(!b[c])return a.u.info("CanExit promise at position "+c+" returned false."),!1;return!0}):Promise.resolve(b)}function s(d){var e;
try{var g=d;d={};var f=g.split("?")[1]||"";a.u.info("Parsing: "+g);var g=w.aw(g),h=f.split("oj_Router\x3d")[1];if(h){var f=h=h.split("\x26")[0],p=f.charAt(0),f=f.slice(1);"0"===p&&(f=decodeURIComponent(f));if("1"===p)f=z.xfa(f);else throw Error("Error retrieving bookmarkable data. Format is invalid");d=JSON.parse(f)}if(a.u.option("level")===a.u.bx){a.u.info("Bookmarkable data: ");for(var l in d)a.u.info("   { router: "+l+", value: "+d[l])}l=[];p=[];l=w.parse(g);for(g=0;g<l.length;g++){var r=l[g],
m=d[r.Rc.name];m&&(r.Rc.Bi=m);r.value!==r.Rc.hf()&&p.push(r)}if(a.u.option("level")===a.u.bx)for(a.u.info("Potential changes are: "),r=0;r<p.length;r++)a.u.info("   { router: "+k(p[r].Rc)+", value: "+p[r].value+"}");e=p}catch(t){return Promise.reject(t)}return c(e).then(b)}var v,x,u=function(){var a="",b=window.location.pathname;-1!==b.indexOf(".html",b.length-5)&&(a=b.split("/").pop());return a}(),w,z={S6:String.fromCharCode,CT:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-$",
p7:function(a,b){z.Lt||(z.Lt={});if(!z.Lt[a]){z.Lt[a]={};for(var c=0;c<a.length;c++)z.Lt[a][a[c]]=c}return z.Lt[a][b]},hfa:function(a){return null==a?"":z.i5(a,6,function(a){return z.CT.charAt(a)})},xfa:function(a){return null==a?"":""==a?null:z.k6(a.length,32,function(b){return z.p7(z.CT,a.charAt(b))})},i5:function(a,b,c){if(null==a)return"";var d,e,g={},f={},h="",p="",k="",l=2,r=3,m=2,t="",n=0,s=0,q;for(q=0;q<a.length;q+=1)if(h=a[q],Object.prototype.hasOwnProperty.call(g,h)||(g[h]=r++,f[h]=!0),
p=k+h,Object.prototype.hasOwnProperty.call(g,p))k=p;else{if(Object.prototype.hasOwnProperty.call(f,k)){if(256>k.charCodeAt(0)){for(d=0;d<m;d++)n<<=1,s==b-1?(s=0,t+=c(n),n=0):s++;e=k.charCodeAt(0);for(d=0;8>d;d++)n=n<<1|e&1,s==b-1?(s=0,t+=c(n),n=0):s++,e>>=1}else{e=1;for(d=0;d<m;d++)n=n<<1|e,s==b-1?(s=0,t+=c(n),n=0):s++,e=0;e=k.charCodeAt(0);for(d=0;16>d;d++)n=n<<1|e&1,s==b-1?(s=0,t+=c(n),n=0):s++,e>>=1}l--;0==l&&(l=Math.pow(2,m),m++);delete f[k]}else for(e=g[k],d=0;d<m;d++)n=n<<1|e&1,s==b-1?(s=0,
t+=c(n),n=0):s++,e>>=1;l--;0==l&&(l=Math.pow(2,m),m++);g[p]=r++;k=String(h)}if(""!==k){if(Object.prototype.hasOwnProperty.call(f,k)){if(256>k.charCodeAt(0)){for(d=0;d<m;d++)n<<=1,s==b-1?(s=0,t+=c(n),n=0):s++;e=k.charCodeAt(0);for(d=0;8>d;d++)n=n<<1|e&1,s==b-1?(s=0,t+=c(n),n=0):s++,e>>=1}else{e=1;for(d=0;d<m;d++)n=n<<1|e,s==b-1?(s=0,t+=c(n),n=0):s++,e=0;e=k.charCodeAt(0);for(d=0;16>d;d++)n=n<<1|e&1,s==b-1?(s=0,t+=c(n),n=0):s++,e>>=1}l--;0==l&&(l=Math.pow(2,m),m++);delete f[k]}else for(e=g[k],d=0;d<
m;d++)n=n<<1|e&1,s==b-1?(s=0,t+=c(n),n=0):s++,e>>=1;l--;0==l&&m++}e=2;for(d=0;d<m;d++)n=n<<1|e&1,s==b-1?(s=0,t+=c(n),n=0):s++,e>>=1;for(;;)if(n<<=1,s==b-1){t+=c(n);break}else s++;return t},k6:function(a,b,c){for(var d=[],e=4,g=4,f=3,h="",p="",k,l,r,m,t,n=z.S6,s={val:c(0),position:b,index:1},p=0;3>p;p+=1)d[p]=p;h=0;r=Math.pow(2,2);for(m=1;m!=r;)l=s.val&s.position,s.position>>=1,0==s.position&&(s.position=b,s.val=c(s.index++)),h|=(0<l?1:0)*m,m<<=1;switch(h){case 0:h=0;r=Math.pow(2,8);for(m=1;m!=r;)l=
s.val&s.position,s.position>>=1,0==s.position&&(s.position=b,s.val=c(s.index++)),h|=(0<l?1:0)*m,m<<=1;t=n(h);break;case 1:h=0;r=Math.pow(2,16);for(m=1;m!=r;)l=s.val&s.position,s.position>>=1,0==s.position&&(s.position=b,s.val=c(s.index++)),h|=(0<l?1:0)*m,m<<=1;t=n(h);break;case 2:return""}for(k=p=d[3]=t;;){if(s.index>a)return"";h=0;r=Math.pow(2,f);for(m=1;m!=r;)l=s.val&s.position,s.position>>=1,0==s.position&&(s.position=b,s.val=c(s.index++)),h|=(0<l?1:0)*m,m<<=1;switch(t=h){case 0:h=0;r=Math.pow(2,
8);for(m=1;m!=r;)l=s.val&s.position,s.position>>=1,0==s.position&&(s.position=b,s.val=c(s.index++)),h|=(0<l?1:0)*m,m<<=1;d[g++]=n(h);t=g-1;e--;break;case 1:h=0;r=Math.pow(2,16);for(m=1;m!=r;)l=s.val&s.position,s.position>>=1,0==s.position&&(s.position=b,s.val=c(s.index++)),h|=(0<l?1:0)*m,m<<=1;d[g++]=n(h);t=g-1;e--;break;case 2:return p}0==e&&(e=Math.pow(2,f),f++);if(d[t])h=d[t];else if(t===g)h=k+k[0];else return null;p+=h;d[g++]=k+h[0];e--;k=h;0==e&&(e=Math.pow(2,f),f++)}}};a.qb=function(b,c){var d=
this;a.Vp=function(b,c){c=c||{};a.j.il(b);b=encodeURIComponent(b.replace(a.Ba.ED,""));c.canEnter&&a.j.Xr(c.canEnter);c.enter&&a.j.Xr(c.enter);c.canExit&&a.j.Xr(c.canExit);c.exit&&a.j.Xr(c.exit);"boolean"===typeof c.isDefault&&c.isDefault&&(d.Ek=b);this.bC=void 0;Object.defineProperties(this,{id:{value:b,enumerable:!0},value:{value:c.value,writable:!0,enumerable:!0},label:{value:c.label,writable:!0,enumerable:!0},canEnter:{value:c.canEnter,writable:!0,enumerable:!0},enter:{value:c.enter,writable:!0,
enumerable:!0},canExit:{value:c.canExit,writable:!0,enumerable:!0},exit:{value:c.exit,writable:!0,enumerable:!0}})};o_("RouterState",a.Vp,a);a.Vp.prototype.go=function(){return d.go(this.id)};a.b.i("RouterState.prototype.go",{go:a.Vp.prototype.go});a.Vp.prototype.fZ=function(){return d.hf()===this.id};a.b.i("RouterState.prototype.isCurrent",{fZ:a.Vp.prototype.fZ});this.To=c?c.hf():void 0;this.qg=[];this.Bi=void 0;this.hf=f.observable();this.Nj=null;this.Ek=void 0;this.MP=f.pureComputed(function(){return f.ignoreDependencies(d.uh,
d,[d.hf()])});this.i6=f.pureComputed(function(){var a,b=f.ignoreDependencies(d.uh,d,[d.hf()]);b&&(a=b.value);return a});this.Vaa=Object.create(null,{name:{value:f.pureComputed(function(){var a,b=this.uh(this.hf());b&&((a=b.value)&&"string"===typeof a||(a=b.id));return a},d)},params:{value:d},lifecycleListener:{value:Object.create(null,{attached:{value:function(a){var b=a.valueAccessor().params.currentState();b&&(b.bC=a.viewModel)}}})}});Object.defineProperties(this,{parent:{value:c,enumerable:!0},
name:{value:b,enumerable:!0}})};o_("Router",a.qb,a);Object.defineProperties(a.qb.prototype,{states:{get:function(){return this.Nj},enumerable:!0},stateId:{get:function(){return this.hf},enumerable:!0},currentState:{get:function(){return this.MP},enumerable:!0},currentValue:{get:function(){return this.i6},enumerable:!0},defaultStateId:{get:function(){return this.Ek},enumerable:!0},moduleConfig:{get:function(){return this.Vaa},enumerable:!0}});a.qb.prototype.DX=function(b){a.j.il(b);b=b.replace(a.Ba.ED,
"");for(var c=0;c<this.qg.length;c++){var d=this.qg[c].Rc;if(d.name===b)throw Error('Invalid router name "'+b+'", it already exists.');if(d.To===this.hf())throw Error('Cannot create more than one child router for parent state id "'+d.To+'".');}c=new a.qb(b,this);this.qg.push({name:b,Rc:c});return c};a.b.i("Router.prototype.createChildRouter",{DX:a.qb.prototype.DX});a.qb.prototype.uh=function(b){var c;if(b&&this.Nj){a.j.il(b);for(var d=0;d<this.Nj.length;d++){var e=this.Nj[d];if(e.id===b){c=e;break}}}return c};
a.qb.prototype.Oj=function(b){var c=!1;b&&!this.uh(b)?a.u.error('State id: "'+b+'" is not a valid state for '+k(this)):(a.u.info("Updating state of "+k(this)+" to "+b),(c=this.uh(this.hf()))&&(c=c.exit)&&c.call(this),this.hf(b),c=!0,b&&(b=this.uh(b))&&(b=b.enter)&&b.call(this));return c};a.qb.prototype.zX=function(b){this.hf(void 0);delete this.Ek;delete this.Nj;this.Nj=null;"function"===typeof b?this.uh=b:(this.Nj=[],delete this.uh,Object.keys(b).forEach(function(c){this.Nj.push(new a.Vp(c,b[c]))},
this));return this};a.b.i("Router.prototype.configure",{zX:a.qb.prototype.zX});a.qb.prototype.GY=function(a){return this.uh(a)};a.b.i("Router.prototype.getState",{GY:a.qb.prototype.GY});a.qb.prototype.go=function(b){function c(b){if(b)return s(e.replace(/^\//,"")).then(function(b){if(b.hasChanged){var c=v+e;a.u.info("Changing URL to "+c);history.pushState(null,"",c)}q(b.hasChanged);return b});q(!1);return Promise.resolve({hasChanged:!1})}a.j.Yv(b);a.u.info("Going to state "+b+" on router "+k(this));
var d;if(b){if(d=this.uh(b),!d)return q(!1),Promise.reject(Error('State id "'+b+'" does not exist.'))}else this.Ek&&(d=this.uh(this.Ek));b=p(this,0,d);var e=w.tX(b);b="/"+w.aw(h()).replace(u,"");if(w.aw(e)!==b)return a.u.info("New URL is different."),t(this).then(c);q(!1);return Promise.resolve({hasChanged:!1})};a.b.i("Router.prototype.go",{go:a.qb.prototype.go});a.qb.prototype.z_=function(a){this.Bi=a;a={};for(var b=this;b;)b.Bi&&(a[b.name]=b.Bi),b=b.parent;for(var b=this,c;b;){for(var d=0;d<b.qg.length;d++){var e=
b.qg[d].Rc;if(b.hf()&&b.hf()===e.To){e.Bi&&(a[e.name]=e.Bi);c=e;break}}b=c;c=void 0}c=v+"/"+w.aw(h());c=m(c,a);history.replaceState(null,"",c)};a.b.i("Router.prototype.store",{z_:a.qb.prototype.z_});a.qb.prototype.g_=function(){return this.Bi};a.b.i("Router.prototype.retrieve",{g_:a.qb.prototype.g_});a.qb.prototype.bw=function(){for(;0<this.qg.length;)this.qg[0].Rc.bw();if(this.parent)for(var b=this.parent.qg,c=0;c<b.length;c++){if(b[c].Rc.name===this.name){b.splice(c,1);break}}else x=v="",w={},window.removeEventListener("popstate",
n),a.qb.transitionedToState.removeAll(),a.qb.xB=!1;delete this.To;delete this.Nj;this.Nj=null;delete this.Ek;delete this.Bi};a.b.i("Router.prototype.dispose",{bw:a.qb.prototype.bw});var D=new a.qb("root",void 0);Object.defineProperties(a.qb,{rootInstance:{value:D,enumerable:!0},transitionedToState:{value:new d.Signal,enumerable:!0}});a.qb.ac={};o_("Router.defaults",a.qb.ac,a);Object.defineProperties(a.qb.ac,{urlAdapter:{get:function(){w||(w=new a.qb.lL);return w},set:function(b){if(a.qb.xB)throw Error("Incorrect operation. Cannot change URL adapter after calling sync().");
w=b},enumerable:!0,Wga:!1},baseUrl:{get:function(){v||(v=e(window.location.href.split("#")[0]),x=e(window.location.pathname));return v},set:function(b){if(a.qb.xB)throw Error("Incorrect operation. Cannot change base URL after calling sync().");v=b.replace(/\/$/,"");x=v.replace(window.location.protocol+"//"+window.location.host,"")},enumerable:!0,Wga:!1}});a.qb.eL=function(){a.qb.xB||(w||(w=new a.qb.lL),v||(v=e(window.location.href.split("#")[0]),x=e(window.location.pathname)),window.addEventListener("popstate",
n,!1),a.u.info("Initializing rootInstance."),a.u.info("Base URL is "+v),a.u.info("This page is "+u),a.u.info("Current URL is "+window.location.href),a.qb.xB=!0);return s(h()).then(function(a){q(a.hasChanged);return a})};o_("Router.sync",a.qb.eL,a);a.qb.lL=function(){this.parse=function(a){var b=0,c=D;a=a.split("/");var d=[];do{var e=a[b++];e&&(0===e.length||/\.html$/i.test(e))&&(e=void 0);e=e||c.Ek;d.push({value:e,Rc:c});c=l(c,e)}while(c);return d};this.tX=function(b){var c="",d={};b.forEach(function(a){a.XB&&
(c+="/"+a.XB);a.Rc.Iia&&(d[a.Rc.name]=a.Rc.Bi)});""===c&&(c="/"+u);try{c=m(c,d)}catch(e){a.u.error("Error while building URL: "+e)}return c};this.aw=function(a){return a.split("?")[0]};this.zY=function(a){var b=a.indexOf("?"),c=null;-1!=b&&(c=a.substr(b+1));return g(c)}};o_("Router.urlPathAdapter",a.qb.lL,a);a.qb.Hha=function(){this.parse=function(a){a=this.zY(a);var b=D,c=[];do{var d=a[b.name];d&&(d=d[0],delete a[b.name]);d=d||b.Ek;c.push({value:d,Rc:b});b=l(b,d)}while(b);return c};this.tX=function(b){var c=
"/"+u,d={},e="?";b.forEach(function(a){a.XB&&(c+=e+a.Rc.name+"\x3d"+a.XB,e="\x26");a.Rc.Bi&&(d[a.Rc.name]=a.Rc.Bi)});try{c=m(c,d)}catch(g){a.u.error("Error while building URL: "+g)}return c};this.aw=function(a){var b=a.indexOf("oj_Router\x3d");return-1!=b?a.substr(0,b-1):a};this.zY=function(a){var b=a.indexOf("?"),c=null,c={};-1!=b&&(c=a.substr(b+1),c=g(c));return c}};o_("Router.urlParamAdapter",a.qb.Hha,a);return D})()});