/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojconveyorbelt","jqueryui-amd/sortable","ojs/ojtouchproxy"],function(a,f){(function(){var d={cut:"ojtabscut","paste-before":"ojtabspastebefore","paste-after":"ojtabspasteafter"},b={cut:"labelCut","paste-before":"labelPasteBefore","paste-after":"labelPasteAfter"};a.Da("oj.ojTabs",f.oj.baseComponent,{widgetEventPrefix:"oj",delay:300,options:{selected:0,disabledTabs:null,truncation:"auto",selectOn:"click",orientation:"horizontal",edge:"top",removable:!1,
reorderable:!1,beforeSelect:null,select:null,beforeDeselect:null,deselect:null,beforeRemove:null,remove:null,beforeReorder:null,reorder:null,optionChange:null},_ComponentCreate:function(){var a=this.options;this._super();this.SK=!1;this.wg=!0;this.lI(a.edge);this.nT=0==this.element.children("ul").length;this.Y5();this.yU();this.ka={};this.ka.qd=!1;this.ka.ve=!1;this.ka.Kl=!1;this.ka.Fn=!1;this.zm();this.gm();this.Ad();a=this.sR(a.selected);void 0===a&&(a=0);this.Oy(a);this.wg=void 0},Oy:function(a){this.Mz(a)&&
(a=this.DR(a));this.Xx(void 0===a?void 0:f(this.ob[a]))},Xe:function(a,b,d){if(this.daa(b.target)&&(!this.zI||!this.zI.KA)){var h="keyboard"===d;if("contextmenu"==b.type||h||"touch"==d)a={launcher:f(b.target).closest("li")},this.ka.tab=h?this.ta:a.launcher,this.ka.tab?(this.ka.qd&&(this.ka.Kl||this.ka.Fn)&&(h=!this.ka.jB,this.ka.Kl.hasClass("oj-disabled")!=h&&(h?(this.ka.Kl.addClass("oj-disabled"),this.ka.Fn.addClass("oj-disabled")):(this.ka.Kl.removeClass("oj-disabled"),this.ka.Fn.removeClass("oj-disabled")),
this.ka.ve.ojMenu("refresh"))),this.Ye(b,d,a)):b.preventDefault()}},Uda:function(a){if(!this.xS(a)){var b=f(this.document[0].activeElement).closest("li"),d=this.lu(),h=d.index(b),k=d.length;switch(a.keyCode){case f.ui.keyCode.RIGHT:case f.ui.keyCode.DOWN:h=(h+1)%k;break;case f.ui.keyCode.UP:case f.ui.keyCode.LEFT:h=((0==h?k:h)-1)%k;break;case f.ui.keyCode.END:h=k-1;break;case f.ui.keyCode.HOME:h=0;break;case 46:this.options.removable&&(b=this.eu(this.ta))&&(a.preventDefault(),this.eV({target:b,currentTarget:b,
preventDefault:f.noop}));return;default:return}a.preventDefault();clearTimeout(this.Lea);d=f(d[h]);d.focus();if(!a.ctrlKey){b.attr("aria-selected","false");d.attr("aria-selected","true");var l=this.zu(d),m=this;this.Lea=this._delay(function(){m&&m.ob&&m.option("selected",l,{_context:{originalEvent:a}})},this.delay)}}},oba:function(a){f(a.target).closest(".oj-tabs-selected").attr("id")===this.element.children(".oj-tabs-selected").attr("id")&&!this.xS(a)&&a.ctrlKey&&a.keyCode===f.ui.keyCode.UP&&(a.preventDefault(),
this.ta.focus())},xS:function(a){var b=this.aG();if(a.ctrlKey&&a.keyCode===f.ui.keyCode.PAGE_UP)return this.Xx(this.NQ(b,!1)),!0;if(a.ctrlKey&&a.keyCode===f.ui.keyCode.PAGE_DOWN)return this.Xx(this.NQ(b,!0)),!0},Mz:function(a){return 0<=a&&a<this.ob.length?f(this.ob[a]).hasClass("oj-disabled"):!1},NQ:function(a,b){var d=this.lu(),h=d.index(this.ob[a]),k=d.length,d=f(d[b?(h+1)%k:((0==h?k:h)-1)%k]);d.focus();return d},DR:function(a){for(var b=a+1,d=this.ob.length-1;b<=d;){if(!this.Mz(b))return b;b++}for(b=
a-1;0<=b;){if(!this.Mz(b))return b;b--}},Fb:function(){return"top"==this.options.edge||"bottom"==this.options.edge},_setOption:function(a,b,d){"selected"===a?(b=this.$R(b),void 0!==b&&this.Xx(b)):"disabledTabs"===a?Array.isArray(b)&&(this.OV(b),a=this.aG(),this.Mz(a)&&this.Oy(a),this.refresh()):"removable"===a||"truncation"===a?b!=this.options[a]&&(this._super(a,b,d),this.refresh()):"reorderable"===a?b!==this.options.reorderable&&(this._super(a,b,d),this.refresh()):"orientation"===a?this.eF||(a=this.kU(b))&&
this.lI(a)&&this.refresh():"edge"===a?this.lI(b)&&(this.eF=!0,this._super(a,b,d),this.refresh()):"selectOn"===a?(this.Lr(!0),this._super(a,b,d),this.Li()):("contextMenu"===a&&(this.io(),b&&this.zm(b)),this._super(a,b,d),"translations"===a&&d&&"removeCueText"===d.subkey&&this.Kc&&this.eu(this.Kc).attr("aria-label",b?b.removeCueText:""))},refresh:function(){this._super();this.yU();this.Ad()},Ad:function(){var a=this.element.children(".oj-tabs-selected");this.ta=a.length?this.Kc.children(".oj-selected"):
f();this.v5();this.Li();this.ob.not(this.ta).attr({"aria-selected":"false",tabIndex:"-1"});this.rh.not(this.yo(this.ta)).hide().attr({"aria-expanded":"false","aria-hidden":"true"});this.ta.length?(this.ta.addClass("oj-selected").attr({"aria-selected":"true",tabIndex:"0"}),a.show().attr("aria-expanded","true").removeAttr("aria-hidden")):f(this.ob[0]).attr("tabIndex","0");this.Fb()&&(0<this.ob.length?(this.mea(),this.D3()):this.gG(),this.F3());void 0===this.options.selected||0==this.aG()?this.element.addClass("oj-first-child-selected"):
this.element.removeClass("oj-first-child-selected");this.Cda()},D3:function(){var a=this.Kc.uniqueId().attr("id");this.jp=this.gG().parent().ojConveyorBelt({orientation:"horizontal",contentParent:"#"+a});a=this.jp.parent();if(a.hasClass("oj-tabs-conveyorbelt-wrapper")){var b="0 1 "+this.D7()+"px";a.css("flex",b);a.css("-webkit-flex",b);a.css("-ms-flex",b)}},yU:function(){var a=this,b=this.options.edge;this.aQ();this.X5();this.Kc=this.element.children("ul").addClass("oj-tabs-nav oj-helper-clearfix").attr("role",
"tablist");var d=this.Kc.index();this.element.children(".oj-tabs-facet").each(function(){var a=f(this);a.index()<d?a.addClass("oj-start"):a.removeClass("oj-start")});var h=this.element.children(".oj-tabs-panel");"start"==b||"top"==b?f(h[0]).before(this.Kc):f(h[h.length-1]).after(this.Kc);this.ob=f();this.rh=f();this.Kc.children("li").each(function(){var b=f(this).addClass("oj-tabs-tab").attr({role:"tab",tabIndex:"-1"}).removeAttr("aria-hidden"),d=b.children();d.addClass("oj-tabs-tab-content");d=d.children();
d.addClass("oj-tabs-anchor").attr({role:"presentation",tabIndex:"-1"});d.children().addClass("oj-tabs-title").removeAttr("aria-hidden");a.ob=a.ob.add(b);var d=d.uniqueId().attr("id"),e=b.attr("data-content"),g=a.element.find(a.$H("#"+e));b.attr({"aria-controls":e,"aria-labelledby":d});a.rh=a.rh.add(g);g.attr("aria-labelledby",d).attr("role","tabpanel")});"start"!=b&&"end"!=b||a.Kc.addClass("oj-tabs-nav-root");this.wg&&this.OV(this.options.disabledTabs)},Li:function(){var b={keydown:this.Uda},d=this.options.selectOn,
g=!1;if(d){var h=this;f.each(d.split(" "),function(d,e){"click"==e&&(g=!0);a.C.BB(e)&&(b[e]=h.Ky)})}d=this.lu();this._on(d,b);g||this._on(d,{click:function(a){a.preventDefault()}});this.rh.on("keydown"+this.eventNamespace,this.oba.bind(this));if(this.options.removable){var k={click:this.eV};this._on(this.eu(d),k)}this._focusable(d);this._hoverable(d);this.Bt(d)},Lr:function(a){var b=this.lu();a||this.tq(this.eu(b));this.tq(b);this.rh&&this.rh.off("keydown"+this.eventNamespace)},Ky:function(a){var b=
this.ta,d=f(a.currentTarget).closest("li"),h=b&&d[0]===b[0],k=this.yo(d),l=b&&b.length?this.yo(b):f(),b={fromTab:b,fromContent:l,toTab:d,toContent:k};a.preventDefault();d.hasClass("oj-disabled")||this.SK||h||l&&l.length&&!1===this._trigger("beforeDeselect",a,b)||!this.wg&&!1===this._trigger("beforeSelect",a,b)||(this.wg?this.options.selected=this.zu(d):this.option("selected",this.zu(d),{_context:{originalEvent:a,mb:!0}}),this.ta=d,k.addClass("oj-tabs-selected"),l&&l.length&&l.removeClass("oj-tabs-selected"),
this.eea(a,b))},eea:function(b,d){var g=d.toTab.closest("li"),h=d.toContent,k=d.fromContent;this.SK=!0;var l=d.fromTab.closest("li").removeClass("oj-selected");k.hide();0<k.length&&a.Components.Cn(k[0]);g.addClass("oj-selected");this.Fb()&&0<this.ob.length&&(0==g.index()?this.element.addClass("oj-first-child-selected"):this.element.removeClass("oj-first-child-selected"));h.show();0<h.length&&a.Components.Il(h[0]);this.SK=!1;this.wg||(this._trigger("deselect",b,d),this._trigger("select",b,d));k.attr({"aria-expanded":"false",
"aria-hidden":"true"});l.attr("aria-selected","false");h.length&&k.length?l.attr("tabIndex","-1"):h.length&&this.ob.filter(function(){return"0"===f(this).attr("tabIndex")}).attr("tabIndex","-1");h.attr("aria-expanded","true").removeAttr("aria-hidden");g.attr({"aria-selected":"true",tabIndex:"0"})},Xx:function(a){void 0===a||this.ta&&a[0]===this.ta[0]||(a=a.find(".oj-tabs-anchor")[0],this.Ky({target:a,currentTarget:a,preventDefault:f.noop}))},v5:function(){if(this.options.removable&&this.Fb()){var a=
this.D("removeCueText");this.lu().each(function(b){var d=f(this).find("\x3e :first-child");d.addClass("oj-removable");b="ojtabs-id_rm_"+b;f(this).attr("aria-describedby",b);f("\x3ca href\x3d'#'\x3e").addClass("oj-tabs-icon oj-component-icon oj-clickable-icon-nocontext oj-tabs-close-icon").attr({id:b,tabIndex:"-1","aria-label":a,role:"presentation"}).appendTo(d)})}},lu:function(){return f(this.ob.not(".oj-disabled"))},eu:function(a){return a.find(".oj-tabs-close-icon")},aQ:function(){this.ob&&this.Lr();
this.br&&(a.C.cj(this.element[0],this.ah),this.br=!1,this.tH=void 0);this.pI&&(a.C.sf()&&this.IW(),this.Kc.sortable("destroy"),this.pI=void 0);var b=this.element.children(".oj-tabs-nav-root"),d=!b.hasClass("oj-tabs-nav");if(this.ob&&(this.eu(this.ob).remove(),b.length)){var g=b,h=!0,k=this.Kc;b.children().each(function(){var a=f(this);if(a.hasClass("oj-tabs-conveyorbelt-wrapper"))a=k;else if(!a.hasClass("oj-tabs-facet"))return;h=!1;g.after(a);g=a});h&&d&&b.after(k)}this.jp&&(this.jp.ojConveyorBelt("destroy"),
this.jp.remove(),this.ta=this.jp=null);d&&b.remove();this.Kc=this.ob=null},_destroy:function(){this.io();this.Fb()?this.element.removeClass("oj-tabs oj-component oj-tabs-horizontal oj-tabs-top oj-tabs-bottom oj-first-child-selected"):this.element.removeClass("oj-tabs oj-component oj-tabs-vertical oj-tabs-start oj-tabs-end oj-helper-clearfix");var a=this,b,d,h,k;this.ob.each(function(l){b=f(this);b.removeAttr("tabIndex").removeAttr("aria-selected").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("aria-controls").removeAttr("aria-disabled").removeAttr("role").removeAttr("data-content").removeClass("oj-active oj-disabled oj-selected oj-tabs-gen-id oj-tabs-tab").removeUniqueId().css("display",
"");d=b.children("div").removeClass("oj-tabs-tab-content");h=d.children("a").removeClass("oj-tabs-anchor").removeAttr("tabIndex").removeAttr("role");k=h.children();k.removeClass("oj-tabs-title").removeAttr("aria-hidden");a.nT?k.prependTo(a.rh.get(l)):d.hasClass("oj-tabs-gen-div")&&h.hasClass("oj-tabs-gen-a")?(k.prependTo(b),d.remove()):h.hasClass("oj-tabs-gen-a")?(k.prependTo(d),h.remove()):d.hasClass("oj-tabs-gen-div")&&(h.prependTo(b),d.remove())});var l=this.Kc;this.aQ();l.removeAttr("tabIndex").removeAttr("role").removeClass("oj-tabs-nav oj-tabs-nav-root oj-helper-clearfix").removeUniqueId();
this.nT&&l.remove();this.rh.each(function(){f(this).removeAttr("tabIndex").removeAttr("aria-expanded").removeAttr("aria-selected").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("role").removeClass("oj-active oj-tabs-selected oj-tabs-gen-id oj-tabs-panel").removeUniqueId().css("display","")});this.element.children(".oj-tabs-facet").removeClass("oj-start")},eV:function(a){var b=f(a.currentTarget).closest("li"),d=this.yo(b),h={tab:b,content:d};if(b&&!1!==this._trigger("beforeRemove",
a,h)){a.preventDefault();if(b.hasClass("oj-selected")){var k=this.DR(this.ob.index(b));void 0===k?(this.ta=void 0,this.option("selected",void 0,{_context:{originalEvent:a,mb:!0}})):(this.Oy(k),this.option("selected",this.zu(f(this.ob[k])),{_context:{originalEvent:a,mb:!0}}))}this.Lr();this.ob=this.ob.not(b);b.remove();d.remove();this.UI();this.refresh();this._trigger("remove",a,h)}},$A:function(a,b){var d;if("li"==a.prop("tagName").toLowerCase()){d=a;var f=d.children("div");1==f.length&&f.hasClass("oj-tabs-tab-content")?
(f=f.children("a"),1!=f.length&&(d.wrapInner("\x3ca href\x3d'#'\x3e\x3c/a\x3e"),f.addClass("oj-tabs-gen-a"))):(f=d.wrapInner("\x3cdiv\x3e\x3ca href\x3d'#'\x3e\x3c/a\x3e\x3c/div\x3e").children(),f.addClass("oj-tabs-gen-div oj-tabs-tab-content"),f.children().addClass("oj-tabs-gen-a"))}else d=a.wrap("\x3cli\x3e\x3cdiv\x3e\x3ca href\x3d'#'\x3e\x3c/a\x3e\x3c/div\x3e\x3c/li\x3e").parent().parent().parent(),d.addClass("oj-tabs-gen-li"),d.children().addClass("oj-tabs-gen-div oj-tabs-tab-content");b&&d.attr("data-content",
b);return d},addTab:function(a){var b,d,h=-1;a.tab&&a.content?(d=a.content,b=this.$A(a.tab,this.tz(d)),void 0!==a.index&&(h=a.index)):(d=a,b=this.$A(f(a).find("\x3e :first-child"),this.tz(d)));a=this.element.children(".oj-tabs-nav-root");a=a.hasClass("oj-tabs-nav")?a:a.length?a.find(".oj-tabs-nav"):this.element.children(".oj-tabs-nav");var k=!1;a.length||(a=f("\x3cul\x3e"),k=!0);k&&a.prependTo(this.element);0<=h&&h<a.children().length?(h=a.children(":eq("+h+")"),a=this.element.children("#"+h.attr("aria-controls")),
h.before(b),a.before(d)):(b.appendTo(a),d.appendTo(this.element));this.refresh();0==this.ta.length&&this.Oy(0);var l=this;window.setTimeout(function(){l.ob&&b[0].scrollIntoView(!1)},0)},Eda:function(){this.zI=a.be.iX(this.Kc)},IW:function(){a.be.c_(this.Kc)},Cda:function(){if(this.options.reorderable){var b=this;a.C.sf()&&this.Eda();this.Kc.sortable({axis:b.Fb()?"x":"y",stop:function(a,d){var f=d.item;b.kQ(a,f,f.prev())||b.Kc.sortable("cancel")}});this.pI=!0}else this.IW(),this.pI=!1},ae:function(a,
b){var d=b.edge;this.eF="top"==d||"bottom"==d||"start"==d||"end"==d;this._super(a,b)},kU:function(a){return"horizontal"==a?"top":"vertical"==a?"start":null},lI:function(a){if(this.wg&&!this.eF||!a)a=this.kU(this.options.orientation);var b=this.options.edge;this.element.removeClass("oj-tabs-top oj-tabs-bottom oj-tabs-start oj-tabs-end");switch(a){case "top":case "bottom":!this.rh||"start"!=b&&"end"!=b||this.element.removeClass("oj-tabs-vertical oj-helper-clearfix");this.element.addClass("oj-tabs oj-component oj-tabs-horizontal");
"bottom"==a?this.element.addClass("oj-tabs-bottom"):this.element.addClass("oj-tabs-top");this.wg?this.options.orientation="horizontal":"horizontal"!=this.options.orientation&&this.option("orientation","horizontal",{_context:{mb:!0},changed:!0});break;case "start":case "end":!this.rh||"top"!=b&&"bottom"!=b||this.element.removeClass("oj-tabs-horizontal");this.element.addClass("oj-tabs oj-component oj-tabs-vertical oj-helper-clearfix");"end"==a?this.element.addClass("oj-tabs-end"):this.element.addClass("oj-tabs-start");
this.wg?this.options.orientation="vertical":"vertical"!=this.options.orientation&&this.option("orientation","vertical",{_context:{mb:!0},changed:!0});break;default:return!1}this.wg?this.options.edge=a:this.options.edge!=a&&this.option("edge",a,{_context:{mb:!0},changed:!0});return!0},gG:function(){var a=this.Kc.parent();a.hasClass("oj-tabs-conveyor")||(a=this.Kc.wrap("\x3cdiv\x3e").parent().addClass("oj-tabs-conveyor"),(0<this.element.children(".oj-tabs-facet").length?a.wrap("\x3cdiv\x3e").wrap("\x3cdiv\x3e").parent().parent().addClass("oj-tabs-conveyorbelt-wrapper"):
a).wrap("\x3cdiv\x3e").parent().addClass("oj-tabs-nav-root").uniqueId().attr("id"));return a},Xha:function(a){0>a.id.indexOf("ojtabs-id_")&&f(a).attr("id","ojtabs-id_"+a.id)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var b=a.subId;a=a.index;if("oj-conveyorbelt"!=b&&("number"!==typeof a||0>a||a>=this.rh.length))return null;switch(b){case "oj-conveyorbelt":return this.jp?this.jp[0]:null;case "oj-tabs-panel":return this.yo(this.ob[a])[0];case "oj-tabs-tab":return this.ob[a];
case "oj-tabs-title":return f(this.ob[a]).find(".oj-tabs-title")[0];case "oj-tabs-close-icon":return f(this.ob[a]).find("."+b)[0]}return null},D7:function(){return this.tH+10},aS:function(){var a=this.element.find(".oj-tabs-conveyorbelt-wrapper");return a.length?a[0].clientWidth:this.element[0].clientWidth},pT:function(){return this.tH>this.aS()},J8:function(){var a=Math.floor(this.aS()/this.ob.length);this.options.removable&&(a-=28);return a},uO:function(){var a=this.J8();this.Kc.find(".oj-tabs-title").each(function(){f(this).css("max-width",
""+a+"px").addClass("oj-tabs-title-overflow")})},xca:function(){this.Kc.find(".oj-tabs-title").each(function(){f(this).css("max-width","").removeClass("oj-tabs-title-overflow")})},sia:function(){},Mf:function(){this.sT()&&(this.pT()?this.uO():this.xca())},sT:function(){return"auto"==this.options.truncation||"progressive"==this.options.truncation},mea:function(){this.Fb()&&0<this.ob.length&&(null==this.ah&&(this.ah=this.Mf.bind(this)),a.C.fh(this.element[0],this.ah),this.br=!0,this.tH=this.gG()[0].scrollWidth,
this.sT()&&this.pT()&&this.uO())},tk:function(){this._super();this.refresh()},Zl:function(){this._super();this.refresh()},yi:function(a){return f("\x3ca\x3e").text(this.D(b[a])).attr("href","#").wrap("\x3cli\x3e").parent().attr("id",d[a])},Oaa:function(a){if(!a||!a.length)return!1;this.ka.jB=a},VT:function(a,b,d){if(!b||!b.length||!this.ka.jB)return!1;var f=this.ka.jB;this.ka.jB=!1;this.kQ(a,f,b,d)},Ei:function(a,b){var d=b?b.item.attr("id"):void 0;"ojtabscut"===d?this.Oaa(this.ka.tab):"ojtabspastebefore"===
d?this.VT(a,this.ka.tab,!0):"ojtabspasteafter"===d&&this.VT(a,this.ka.tab,!1)},zm:function(a){var b,d;a||this.options.contextMenu||(b=this.element.attr("contextmenu"))&&(this.options.contextMenu="#"+b);if(a||this.options.contextMenu){b=a||this.options.contextMenu;d=f.type(b);if("function"==d){try{b=b()}catch(h){b=null}d=f.type(b)}if("string"===d){if(b=f(b)){b.css("display","none");d=this.ka;if(!d)return;d.ve=b;d.qd=!0}this.ka.qd&&a&&this.gm()}}},gm:function(){if(this.ka&&this.ka.qd&&this.options.reorderable){var a=
this.ka.ve,b=this;a.on("ojselect",f.proxy(this.Ei,this));var d=!1;a.find("[data-oj-command]").each(function(){if(0===f(this).children("a").length){var a=f(this).attr("data-oj-command").slice(8);f(this).replaceWith(b.yi(a));f(this).addClass("oj-menu-item");d=!0}});d&&a.ojMenu("refresh");this.ka.Kl=a.find("#ojtabspastebefore");this.ka.Fn=a.find("#ojtabspasteafter")}},io:function(){var a=this.ka;a&&a.qd&&(a.qd=!1,a.ve.off("ojselect"),a.ve=null)},kQ:function(a,b,d,f){var k=this.yo(b),l={tab:b,content:k};
if(!1===this._trigger("beforeReorder",a,l))return!1;var m=this.ob.index(b);if(d.length){if(this.ob.index(d)==m)return!0;m=this.yo(d);f?(d.before(b),m.before(k)):(d.after(b),m.after(k))}else if(0<this.ob.length){if(0==m)return!0;this.ob.first().before(b);this.rh.first().before(k)}this.UI();this.refresh();b.focus();this._trigger("reorder",a,l);return!0},$H:function(a){return a?a.replace(/[!"$%&'()*+,.\/:;<=>?@\[\]\^`{|}~]/g,"\\$\x26"):""},yo:function(a){return this.element.find(this.$H("#"+f(a).attr("aria-controls")))},
tz:function(a){var b=a.attr("id");b||(b=a.uniqueId().attr("id"),a.addClass("oj-tabs-gen-id"));return b},$R:function(a){a=this.sR(a);if(-1!==a)return f(this.ob[a])},sR:function(b){var d=-1;"number"===typeof b?0<=b&&b<this.ob.length&&(d=b):"string"===typeof b&&(b=this.$H(b),a.C.BB(b)&&(b=this.element.find("#"+b),b.length&&(d=this.ob.index(b),-1==d&&(d=this.rh.index(b)))));return d},aG:function(){var a=this.options.selected;return"number"===typeof a?a:this.ob.index(f("#"+a))},zu:function(a){if(a){var b=
a.attr("id");return b?b:this.ob.index(a)}},OV:function(a){var b=(this.Kc?this.Kc:this.element.children("ul")).children("li");b.removeClass("oj-disabled").removeAttr("aria-disabled");var d=[];if(a&&0<a.length)for(var f,k,l=0;l<a.length;l++)if(k=this.$R(a[l]))k.addClass("oj-disabled"),k.attr("aria-disabled","true"),k.find(".oj-tabs-anchor").removeAttr("href"),f=k.attr("id"),d.push(f?f:b.index(k));this.UI(d)},UI:function(b){if(!b){b=[];var d=this;this.Kc.children().each(function(){var a=f(this);a.hasClass("oj-disabled")&&
b.push(d.zu(a))})}a.b.oP(this.options.disabledTabs,b)||(this.wg?this.options.disabledTabs=b:this.option({disabledTabs:b},{_context:{mb:!0,rd:!0},changed:!0}))},daa:function(a){var b=!1;this.ob.each(function(){if(this===a||f.contains(this,a))return b=!0,!1});return b},X5:function(){var a=this.ZQ(),b=this,d=this.element.children("ul");0<d.length&&d.children("li").each(function(d){b.$A(f(this),a[d])})},Y5:function(){var a=this.element.children("ul");if(0==a.length){var b=this,d=this.ZQ(),a=f("\x3cul\x3e");
this.element.children().each(function(h){b.$A(f(this).find("\x3e :first-child"),d[h]).appendTo(a)});a.prependTo(this.element)}},F3:function(){var a=this.element.children(".oj-tabs-nav-root"),b=this,d=a.children(".oj-tabs-conveyorbelt-wrapper");a.index();this.element.children(".oj-tabs-facet").each(function(){var h=f(this),k=b.tz(h);0==a.find("#"+k).length&&(h.hasClass("oj-start")?d.before(h):h.appendTo(a))})},ZQ:function(){var a=[],b=this;this.element.children(":not(ul):not(.oj-tabs-facet)").each(function(){var d=
f(this);d.addClass("oj-tabs-panel");a.push(b.tz(d))});return a}})})()});