/**
 * Copyright (c) 2014, 2015, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","promise","ojs/ojeditablevalue","ojs/ojmenu","ojs/ojdatacollection-common"],function(a,f){(function(){a.Da("oj.ojTable",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3ctable\x3e",widgetEventPrefix:"oj",options:{accessibility:null,currentRow:null,data:null,emptyText:null,horizontalGridVisible:"enabled",rowRenderer:null,scrollPolicy:"auto",scrollPolicyOptions:{fetchSize:25,maxCount:500},selection:[],selectionMode:null,verticalGridVisible:"enabled",
columns:[{renderer:null,className:null,field:null,footerClassName:null,footerRenderer:null,footerStyle:null,headerClassName:null,headerRenderer:null,headerStyle:null,headerText:null,id:null,sortable:"auto",sortProperty:null,style:null}],columnsDefault:{renderer:null,className:null,field:null,footerClassName:null,footerRenderer:null,footerStyle:null,headerClassName:null,headerRenderer:null,headerStyle:null,headerText:null,sortable:"auto",sortProperty:null,style:null},beforeCurrentRow:null,ready:null,
sort:null,optionChange:null,translations:{}},lb:{l2:"msgFetchingData",n2:"msgNoData",b2:"labelSelectColumn",fN:"labelSelectRow"},nc:{NM:"Did not change current row due to error.",LM:"Error detail: {error}.",p1:"Did not change current row due to unavailable row index.",o1:"Unavailable row index: {rowIdx}.",z1:"Invalid row index value.",y1:"Row index: {rowIdx}.",KM:"Invalid data type.",JM:"Please specify the appropriate data type.",t1:"Invalid element type.",s1:"Only a \x3ctable\x3e element can be specified for ojTable.",
r1:"Exceeded maximum rows for table scrolling.",q1:"Please reload with smaller data set."},Oha:"_headerColumn",Pha:"_headerColumnText",Mha:"_headerColumnAsc",Nha:"_headerColumnDsc",i1:"_hdrCol",q2:"auto",Ff:"enabled",bm:"disabled",oN:"none",vk:{nq:"single",Bx:"multiple"},r2:{Rg:"auto",e2:"loadMoreOnScroll"},Tg:{Rn:"ascending",bq:"descending"},Tb:{dN:32,O1:13,zx:38,yx:40,bN:37,cN:39,aN:36,$M:35,Q1:9,P1:27,Wn:"shiftKey"},getNodeBySubId:function(d){if(null==d)return this.element?this.element[0]:null;
var b=d.subId;if("oj-table-cell"===b)return b=d.rowIndex,d=d.columnIndex,this.v().ow(b,d)[0];if("oj-table-header"===b||"oj-table-sort-ascending"===b||"oj-table-sort-descending"===b){if(d=d.index,d=this.v().Ed(d),null!=d){if("oj-table-header"===b)return d[0];b="oj-table-sort-ascending"===b?d.find("."+a.g.F.Zp):d.find("."+a.g.F.ct);if(0<b.length)return b[0]}}else if("oj-table-footer"===b&&(d=d.index,b=this.v().KY(d),null!=b))return b[0];return null},refresh:function(){this._super();this.Ad()},refreshRow:function(d){var b=
this.jb();if(!b)return!1;var c=this.v().jh();if(isNaN(d)||0>d||null!=c&&d>=c.length)throw b=this.nc.z1,c=a.ha.Jb(this.nc.y1,{rowIdx:d.toString()}),new RangeError(b+"\n"+c);var c=this.zo(d),e=b.get(c);if(null==e)return!1;var g=this;return this.Ph(function(){return e.then(function(a){g.mA(d,a)}).then(function(){return!0})})},widget:function(){var a=this.v().me();return null!=a?a:this.element},_ComponentCreate:function(){this._super();this.$t();this.dca();this._on(this.Hk);this.eca();this.tv();this.KO=
f.extend(!0,{},this.options)},Sg:function(){this._super();this.v().EX(this.Ei.bind(this));this.Hz()},Xe:function(a,b,c){var e={};this.Bk=b.originalEvent;if(!this.YG(f(this.Bk.target))){var g=this.v().jn(f(this.Bk.target),"oj-table-column-header-cell"),g=null==g?this.v().Ed(this.fO):g,h=this.v().jn(f(this.Bk.target),"oj-table-data-cell");null!=h&&(g=this.v().Th(h),g=this.v().Ed(g));"keydown"===this.Bk.type&&(h=this.uI.Yb(),this.Bk.target==h[0]?null!=g&&null!=g[0]?e.position={my:"start top",at:"start bottom",
of:g[0]}:(h=this.Ci(),0<=h?(h=this.v().Dg(h),e.position={my:"start top",at:"start bottom",of:h[0]}):e.position={my:"start top",at:"start bottom",of:this.Bk.target}):e.position={my:"start top",at:"start bottom",of:this.Bk.target});g.attr("data-oj-sortable")==this.Ff?(f(a.element).find("[data-oj-command\x3doj-table-sortAsc]").removeClass("oj-disabled"),f(a.element).find("[data-oj-command\x3doj-table-sortDsc]").removeClass("oj-disabled")):(f(a.element).find("[data-oj-command\x3doj-table-sortAsc]").addClass("oj-disabled"),
f(a.element).find("[data-oj-command\x3doj-table-sortDsc]").addClass("oj-disabled"));this.Ye(b,c,e)}},_destroy:function(){this.jb();this.fp();this.v().qf().removeAttr(a.Components.Cx);this.element.children().remove("."+a.g.F.yD);this.element.children().remove("."+a.g.F.vD);this.element.children().remove("."+a.g.F.xD);this.element.children().remove("."+a.g.F.zD);this.element.children().remove("."+a.g.F.SN);a.C.unwrap(this.element,this.v().me());this.element.removeClass(a.g.F.ON)},$t:function(){this.eda(function(){this.v().PB();
this.Bv(this.options.selection);this.Uk()&&!this.NP&&this.x6.checkViewport().then(this.mQ,null)});if(!this.element.is("table"))throw new RangeError(this.nc.t1+"\n"+this.nc.s1);this.element.addClass(a.g.F.l3);this.v().kfa(this.Nz(),this.wT());this.v().tha();this.OU();this.rv();this.NU();this.v().PB();if(this.Uk()){var d=this;this.mQ=function(a){null!=a&&a.maxCountLimit&&d.CG()};this.x6=new a.ij(this.v().Dd(),this.f,{fetchSize:this.options.scrollPolicyOptions.fetchSize,maxCount:this.options.scrollPolicyOptions.maxCount,
success:this.mQ})}this.options.disabled&&this.disable();this.Pm(this.v().me())},Hk:{blur:function(a){var b=this.v().Yb();0<b.has(a.relatedTarget).length||null!=a.originalEvent&&a.originalEvent.explicitOriginalTarget==b[0]||(this.W4(),this.dP(),this.eP(!1),this.zA(!1))},focus:function(a){this.XO(a)},"focus .oj-table-column-header-acc-asc-link":function(a){this.XO(a)},"click .oj-table-checkbox-acc-select-column":function(a){var b=this.v().Th(f(a.currentTarget)),c=f(a.currentTarget).is(":checked");c&&
this.cl(b,!0,!0,null);this.Kj(b,c,a.currentTarget,a,!0);a.stopPropagation()},"click .oj-table-checkbox-acc-select-row":function(a){var b=this.v().qB(f(a.currentTarget)),c=f(a.currentTarget).is(":checked"),e=!1;c&&(e=this.Qh(b,!0,!0,null,a,!0));e&&this.Mj(b,c,a.currentTarget,a,!0);a.stopPropagation()},keydown:function(a){if(!(this.YG(f(a.target))||null!=this.v().Xj()&&0<this.v().Xj().has(a.target).length)&&(this.M3(a.keyCode),1==this.Jk().length||2==this.Jk().length&&a[this.Tb.Wn])){if(this.ff(this.Tb.zx)||
this.ff(this.Tb.yx)||this.ff(this.Tb.dN)||this.ff(this.Tb.aN)||this.ff(this.Tb.$M))a.preventDefault(),a.stopPropagation();this.ff(this.Tb.zx)||this.ff(this.Tb.yx)?this.z9(a):this.ff(this.Tb.bN)||this.ff(this.Tb.cN)?this.x9(a):this.ff(this.Tb.Q1)&&this.y9(a)}},keyup:function(a){if(!(this.YG(f(a.target))||null!=this.v().Xj()&&0<this.v().Xj().has(a.target).length)){if(1==this.Jk().length){var b=this.Jk()[0];b==this.Tb.dN?this.E9(a):b==this.Tb.O1?this.B9(a):b==this.Tb.aN?this.D9(a):b==this.Tb.$M?this.A9(a):
b==this.Tb.P1&&this.C9(a);this.SH(b)}this.SH(a.keyCode)}},"mouseenter .oj-table-body-row":function(d){f(d.currentTarget).addClass(a.g.sa.rk)},"mouseleave .oj-table-body-row":function(d){f(d.currentTarget).removeClass(a.g.sa.rk)},"mouseenter .oj-table-column-header-cell":function(d){f(d.currentTarget).addClass(a.g.sa.rk);d=this.v().Th(f(d.currentTarget));this.jW(d)},"mouseleave .oj-table-column-header-cell":function(d){f(d.currentTarget).removeClass(a.g.sa.rk);d=this.v().Th(f(d.currentTarget));this.Go(d,
!0);this.Go(d,!1)},"mouseenter .oj-table-data-cell":function(d){f(d.currentTarget).addClass(a.g.sa.rk)},"mouseleave .oj-table-data-cell":function(d){f(d.currentTarget).removeClass(a.g.sa.rk)},"click .oj-table-column-header-asc-link":function(a){var b=this.v().Th(f(a.target)),c=this.v().Ed(b);c&&(c.data("sorted")==this.Tg.Rn?this.Dj(b,!1,a):this.Dj(b,!0,a),a.preventDefault(),a.stopPropagation())},"click .oj-table-column-header-acc-asc-link":function(a){var b=this.v().Th(f(a.target));this.Dj(b,!0,a);
a.preventDefault();a.stopPropagation()},"click .oj-table-column-header-dsc-link":function(a){var b=this.v().Th(f(a.target)),c=this.v().Ed(b);c&&(c.data("sorted")==this.Tg.bq?this.Dj(b,!0,a):this.Dj(b,!1,a),a.preventDefault(),a.stopPropagation())},"click .oj-table-column-header-acc-dsc-link":function(a){var b=this.v().Th(f(a.target));this.Dj(b,!1,a);a.preventDefault();a.stopPropagation()},"click .oj-table-data-cell":function(d){var b=this.v().qB(f(d.currentTarget)),c=!1;if(c=this.Qh(b,!0,!0,d.currentTarget,
d))if(d[this.Tb.Wn]){if(c=this.e8(),null!=c)if(window.getSelection().removeAllRanges(),b<c){var e;for(e=b;e<=c;e++)this.Mj(e,!0,d.currentTarget,d,!0)}else for(e=c;e<=b;e++)this.Mj(e,!0,d.currentTarget,d,!0)}else a.C.vs(d)?this.Mj(b,!this.wu(b),d.currentTarget,d,!0):0==this.Jk().length&&(this.Bq(),this.Mj(b,!this.wu(b),d.currentTarget,d,!0))},"contextmenu .oj-table-data-cell":function(a){var b=this.v().qB(f(a.currentTarget)),b=this.zo(b);this.bl({rowKey:b},a)},"click .oj-table-column-header-cell":function(d){var b=
this.v().Th(f(d.currentTarget));this.cl(b,!0,!0,d);if(d[this.Tb.Wn]){var c=this.d8();if(null!=c)if(b<c){var e;for(e=b;e<=c;e++)this.Kj(e,!0,d.currentTarget,d,!0)}else for(e=c;e<=b;e++)this.Kj(e,!0,d.currentTarget,d,!0)}else a.C.vs(d)?this.Kj(b,!this.mu(b),d.currentTarget,d,!0):0==this.Jk().length&&(this.Pt(),this.Kj(b,!this.mu(b),d.currentTarget,d,!0))}},Ad:function(){var a=null,b=!1;this.f!=this.options.data&&(this.wE(),null==this.f?b=!0:a=0);this.sP!=this.v().iY()&&this.v().EX(this.Ei.bind(this));
this.v().ffa();this.v().Xga();this.Zba();if(b)return this.Hz();var c=this;this.Ph(function(){return c.Nu(a)})},_setOption:function(a,b){this._superApply(arguments);this.jaa(a,b)?this.Ad():"selection"==a?(this.Bq(),this.Pt(),this.Bv(b)):"currentRow"==a&&this.bl(b,null,!0)},M3:function(a){var b=!1,c;for(c in this.Tb)this.Tb.hasOwnProperty(c)&&this.Tb[c]==a&&(b=!0);if(b){b=this.Jk();c=!1;var e;for(e=0;e<b.length;e++)if(b[e]==a){c=!0;break}c||b.push(a)}},jO:function(a,b,c,e){var g=this.v().GX(a,b.key);
this.v().bL(g,!0);this.v().cZ(a,g,b,c);this.mA(a,b,g,c,e,!0)},XO:function(a){var b=this.Ci(),c=this.Ik();null==b&&null==c&&(this.Nz()?this.Qh(0,!0,!0,null,a):this.cl(0,!0,!1,a))},V4:function(){this.Cq=null;this.zA(!1)},wE:function(){null!=this.f&&this.fp();this.f=null},wj:function(){this.k$();this.l$();this.NP=!1},W4:function(){this.cH=[]},dP:function(){var a=this.Ik();null!=a&&this.cl(a,!1,!1,null);this.fO=-1},eP:function(a){null!=this.Ci()&&this.Qh(-1,!0,a,null,null)},Pt:function(){var a=this.TR(),
b;for(b=0;b<a.length;b++)this.Kj(a[b],!1,null,null,!1)},Bq:function(){var a=this.bG(),b;for(b=0;b<a.length;b++)this.Mj(a[b],!1,null,null,!1)},hP:function(d){var b=this.H8();if(null!=b){var c=this.v().Ed(b),e=c.data("sorted");c.data("sorted",null);b!=d?e==this.Tg.Rn?this.Go(b,!0):this.Go(b,!1):(c.find("."+a.g.F.Zp).removeClass(a.g.sa.Xc),c.find("."+a.g.F.ct).removeClass(a.g.sa.Xc))}},N6:function(d){var b=this;this.Ph(function(){var c=!1;if(1<d.length){var e,g=!0;for(e=0;e<d.length;e++)if(0!=e&&d[e-
1].sh!=d[e].sh-1){g=!1;break}if(g){c=b.v().qf();g=f(document.createDocumentFragment());for(e=0;e<d.length;e++)b.jO(d[e].sh,d[e].row,g,d[0].sh);0==d[0].sh?c.prepend(g):(e=b.v().Dg(d[0].sh),null!=e?c[0].insertBefore(g[0],e[0]):c[0].insertBefore(g[0],null));b.v().ip();a.Components.vf(c[0]);c=!0}}if(!c)for(e=0;e<d.length;e++)b.jO(d[e].sh,d[e].row);b.v().ip();b.rv()})},O6:function(a){var b=this;this.Ph(function(){var c;for(c=0;c<a.length;c++)b.mA(a[c].sh,a[c].row);b.rv()})},P6:function(d){var b=this,c=
this.dR(),e=null!=c?c.rowKey:null;this.Ph(function(){var c,f;for(c=0;c<d.length;c++)b.v().b_(d[c].sh),null!=e&&(f=d[c].row.id,a.b.Cg(f,e)&&(b.bl(null,null),e=null));b.rv();c=b.v().jh();null!=c&&0!=c.length||this.fW()})},Vb:function(){this.Cq||(this.Cq=this.WQ());return this.Cq},WQ:function(){var a=this.options.columns,b=this.options.columnsDefault;if((0==a.length||1==a.length&&null==a[0].id&&null==a[0].headerText&&null==a[0].field)&&null==b.headerText&&null==b.field)return[];var c=[],e;for(e=0;e<
a.length;e++)c[e]=f.extend({},b,a[e]);a=[];for(e=0;e<c.length;e++)a.push(c[e]);e=this.jb();b=!1;null!=e&&"full"==e.getCapability("sort")&&(b=!0);for(e=0;e<c.length;e++)null==a[e].id&&(a[e].id=this.i1+e),null!=a[e].sortable&&a[e].sortable!=this.q2||!b||(a[e].sortable=this.Ff);return a},UQ:function(d){var b=this.Vb();if(null!=b){var c,e;for(c=0;c<b.length;c++)if(e=b[c],a.b.Cg(e.id,d))return c}return null},VQ:function(a){a=this.v().Yb().find(a);var b=[];if(a&&0<a.length){var c,e,g,h;for(c=0;c<a.length;c++){h=
this.v().Th(f(a.get(c)));g=!1;for(e=0;e<b.length;e++)b[e]==h&&(g=!0);g||b.push(h)}}return b},Yy:function(a){var b=this.Vb();return null!=b&&a<b.length?b[a].id:null},Zy:function(a,b){var c=this.Vb()[a];return"cell"==b?c.renderer:"footer"==b?c.footerRenderer:"header"==b?c.headerRenderer:null},dR:function(){return this.jb()?this.qo:null},jb:function(){if(!this.f&&null!=this.options.data){var d=this.options.data;if(d instanceof a.R||d instanceof a.pa)this.f=d;else throw Error(this.nc.KM+"\n"+this.nc.JM);
this.tv()}return this.f},Ik:function(){return this.VQ("."+a.g.F.Tn+"."+a.g.sa.qj)[0]},Ci:function(){return this.SR("."+a.g.F.Zn+"."+a.g.sa.qj)[0]},aia:function(a){return this.IF(a).Ti},mu:function(a){return this.IF(a).selected},$y:function(){return null==this.options.selectionMode?null:this.options.selectionMode.column},IF:function(d){d=this.v().Ed(d);return{Ti:d.hasClass(a.g.sa.qj),selected:d.hasClass(a.g.sa.Xc)}},Jk:function(){this.cH||(this.cH=[]);return this.cH.reverse()},d8:function(){return null!=
this.Em&&0<this.Em.length?this.Em[0]:null},e8:function(){return null!=this.Fm&&0<this.Fm.length?this.Fm[0]:null},C8:function(a,b){var c=[];if(null!=a){var e;for(e=0;e<a.indexes.length;e++)c.push({row:{data:a.data[e],key:a.keys[e],index:a.indexes[e]},sh:b+e})}return c},tu:function(d){var b=this.v().jh();if(null!=b&&0<b.length){var c;for(c=0;c<b.length;c++)if(a.b.Cg(f(b[c]).data("rowKey"),d))return c}return null},uo:function(d){var b=this.v().jh();if(null!=b&&0<b.length){var c;for(c=0;c<b.length;c++)if(a.b.Cg(f(b[c]).data("rowKey"),
d))return d=this.jb(),b=0,d instanceof a.pa&&(b=d.getStartItemIndex()),c+b}return null},SR:function(a){a=this.v().Yb().find(a);var b=[];if(a&&0<a.length){var c,e,g,h;for(c=0;c<a.length;c++){g=this.v().qB(f(a.get(c)));h=!1;for(e=0;e<b.length;e++)b[e]==g&&(h=!0);h||b.push(g)}}return b},vu:function(d){var b=this.v().jh();if(null!=b&&0<b.length){var c=this.jb(),e=0;c instanceof a.pa&&(e=c.getStartItemIndex());for(c=0;c<b.length;c++)if(e+c==d)return f(b[c]).data("rowKey")}return null},zo:function(a){a=
this.v().Dg(a);return null!=a?a.data("rowKey"):null},D8:function(){return this.options.rowRenderer},wu:function(d){return this.v().Dg(d).hasClass(a.g.sa.Xc)},ZF:function(){return null==this.options.selectionMode?null:this.options.selectionMode.row},TR:function(){return this.VQ("."+a.g.F.Tn+"."+a.g.sa.Xc)},bG:function(){return this.SR("."+a.g.F.Zn+"."+a.g.sa.Xc)},UR:function(){var a=this.bG(),b=this.TR(),c=null,e=!0;if(null!=a&&0<a.length)c=a;else if(null!=b&&0<b.length)c=b,e=!1;else return null;var a=
[],b=0,g=null,f,k,l,m,n;for(n=0;n<c.length;n++)l=c[n],0==n?(f={startIndex:{},endIndex:{},startKey:{},endKey:{}},e?(m=this.zo(l),k=this.uo(m),f.startKey.row=m,f.endKey.row=m,f.startIndex.row=k,f.endIndex.row=k):(f.startIndex.column=l,f.endIndex.column=l,m=this.Yy(l),f.startKey.column=m,f.endKey.column=m),a[0]=f):(f=a[b],e?(m=this.zo(l),k=this.uo(m),f.endKey.row=m,f.endIndex.row=k):(f.endIndex.column=l,m=this.Yy(l),f.endKey.column=m),l!=g+1&&(e?(m=this.zo(g),k=this.uo(m),f.endKey.row=m,f.endIndex.row=
k,f={startIndex:{},endIndex:{},startKey:{},endKey:{}},m=this.zo(l),k=this.uo(m),f.startKey.row=m,f.endKey.row=m,f.startIndex.row=k,f.endIndex.row=k):(f.endIndex.column=g,m=this.Yy(g),f.endKey.column=m,f={startIndex:{},endIndex:{},startKey:{},endKey:{}},f.startIndex.column=l,f.endIndex.column=l,m=this.Yy(l),f.startKey.column=m,f.endKey.column=m),b++,a[b]=f)),g=l;return a},H8:function(){var a=this.v().TJ(),b,c;for(b=0;b<a.length;b++)if(c=f(a[b]).data("sorted"),null!=c)return b;return null},sz:function(a){a=
a.find(":tabbable");return null!=a&&0<a.length?a:null},v:function(){this.uI||(this.uI=new a.g(this));return this.uI},Ei:function(a,b){var c=b.item.attr("data-oj-command"),e=this.v().jn(f(this.Bk.target),"oj-table-column-header-cell"),g=this.v().jn(f(this.Bk.target),"oj-table-data-cell"),h=null;null!=e&&(h=this.v().Th(e));null!=g&&(h=this.v().Th(g));"oj-table-sortAsc"==c?this.Dj(h,!0,a):"oj-table-sortDsc"==c&&this.Dj(h,!1,a)},c9:function(d){this.wj();a.u.error(d)},d9:function(){this.KV()},sG:function(d){try{var b=
this;this.Ph(function(){var c=0,g=b.jb();g instanceof a.pa&&(c=g.getStartItemIndex());var g=[],f;for(f=0;f<d.data.length;f++)g[f]=f+c+d.startIndex;b.FU({data:d.data,keys:d.keys,indexes:g},d.startIndex)})}catch(c){a.u.error(c)}finally{this.wj()}},vz:function(){try{var d=this.Nu(),b=this;this.Ph(function(){b.bl(null,null);return d})}catch(c){a.u.error(c)}finally{this.wj()}},wz:function(){try{this.Hz();var d=this;this.Ph(function(){d.bl(null,null)})}catch(b){a.u.error(b)}finally{this.wj()}},tG:function(d){try{var b=
this.jb(),c=d.data,e=d.indexes,g=d.keys;c instanceof Array||(c=[c]);d=0;b instanceof a.pa&&(d=b.getStartItemIndex());var b=[],f;for(f=0;f<c.length;f++){var k=e[f]-d;void 0!==k&&b.push({row:{data:c[f],key:g[f],index:e[f]},sh:k})}0<b.length&&this.N6(b)}catch(l){a.u.error(l)}finally{this.wj()}},f9:function(d){try{var b=this.jb(),c=d.data,e=d.indexes,g=d.keys;c instanceof Array||(c=[c]);d=0;b instanceof a.pa&&(d=b.getStartItemIndex());var b=[],f;for(f=0;f<c.length;f++){var k=e[f]-d;void 0!==k&&b.push({row:{data:c[f],
key:g[f],index:e[f]},sh:k})}0<b.length&&this.O6(b)}catch(l){a.u.error(l)}finally{this.wj()}},uG:function(d){try{var b=this.jb(),c=d.data,e=d.indexes,g=d.keys;c instanceof Array||(c=[c]);d=0;b instanceof a.pa&&(d=b.getStartItemIndex());var b=[],f;for(f=c.length-1;0<=f;f--){var k=e[f]-d;void 0!==k&&b.push({row:{data:c[f],key:g[f],index:e[f]},sh:k})}0<b.length&&this.P6(b)}catch(l){a.u.error(l)}finally{this.wj()}},vG:function(d){try{var b;if(null!=d){var c,e,g,f=this.Vb();for(c=0;c<f.length;c++)if(e=
f[c],g=null==e.sortProperty?e.field:e.sortProperty,d.header==g){b=c;break}null!=b&&this.MU(b,d.direction==this.Tg.Rn)}var k=this.options.selection;if(null!=k){d=!1;if(1<k.length)d=!0;else if(null!=k[0]){var l=k[0].endIndex;a.b.Cg(k[0].startIndex,l)||null==l||(d=!0)}d&&(this.Bv(null),this.option("selection",null,{_context:{rd:!0,mb:!0}}))}this.bl(this.options.currentRow,null);var m=this;this.Ph(function(){return m.Nu(null)}).then(function(){null!=b&&setTimeout(function(){m.vV(b)},0)})}catch(n){a.u.error(n)}finally{this.wj()}},
x9:function(a){var b=this.Ik(),c=this.Vb();if(null!=b){var e=b;this.ff(this.Tb.bN)?e=0<b?b-1:b:this.ff(this.Tb.cN)&&(e=b<c.length-1?b+1:b);e!=b&&(this.cl(e,!0,!1,null),a[this.Tb.Wn]&&(c=this.mu(e),this.Kj(e,!c,null,a,!0),c&&this.mu(b)&&this.Kj(b,!1,null,a,!0)))}},y9:function(a){var b=!1,c=this.Ci();if(null!=c&&this.DW){var e=document.activeElement,g=this.v().qf();if(f.contains(g[0],e))return;e=this.sz(g);null!=e&&(b=!0,a[this.Tb.Wn]||(c=this.v().Dg(c),c=this.sz(c),null!=c?f(c[0]).focus():f(e[0]).focus(),
a.preventDefault(),a.stopPropagation()))}if(!b){c=this.v().Yb();b=this.sz(f(document));c=this.sz(c);c=null!=c?c.length:0;e=b.index(this.v().Yb());if(a[this.Tb.Wn])if(0<e)f(b[e-1]).focus();else return;else f(b[e+c+1]).focus();a.preventDefault();a.stopPropagation()}this.SH(a.keyCode)},z9:function(a){var b=this.Ci(),c=this.Ik();if(null!=b){var c=this.v().jh(),e=null!=c?c.length:0,c=b;this.ff(this.Tb.zx)?c=0<b?b-1:b:this.ff(this.Tb.yx)&&(c=b<e-1?b+1:b);c!=b?this.Qh(c,!0,!0,null,a)&&a[this.Tb.Wn]&&(e=
this.wu(c),this.Mj(c,!e,null,a,!0),e&&this.wu(b)&&this.Mj(b,!1,null,a,!0)):c==b&&0==b&&this.ff(this.Tb.zx)&&this.cl(0,!0,!1,null)}else null!=c&&this.ff(this.Tb.yx)&&this.Qh(0,!0,!0,null,a)},A9:function(a){var b=this.Ik();if(null!=b&&b!=this.Vb().length-1)this.cl(this.Vb().length-1,!0,!1,null);else{var b=this.Ci(),c=this.v().jh(),c=null!=c?c.length:0;null!=b&&b!=c-1&&0<c&&this.Qh(c-1,!0,!0,null,a)}},B9:function(a){var b=this.Ik();if(null!=b&&this.Vb()[b].sortable==this.Ff){var c=this.v().Ed(b).data("sorted");
null==c||c==this.Tg.bq?this.Dj(b,!0,a):this.Dj(b,!1,a)}},C9:function(a){a.preventDefault();a.stopPropagation();this.v().Yb().focus();this.zA(!1)},D9:function(a){var b=this.Ik();null!=b&&0!=b?this.cl(0,!0,!1,null):(b=this.Ci(),null!=b&&0!=b&&this.Qh(0,!0,!0,null,a))},E9:function(a){var b=this.Ci();null!=b?this.Mj(b,!this.wu(b),null,a,!0):(b=this.Ik(),null!=b&&(this.Bq(),this.Kj(b,!this.mu(b),null,a,!0)))},CG:function(){this.Hda(this.nc.r1,this.nc.q1,a.X.Ob.WARNING)},Y9:function(d,b){"rtl"===this.hc()&&
(d=Math.abs(d),this.v().Pz()&&(d=b-d));var c=this.v().kn(),e=this.v().Xj();this.v().Zj()?(c&&("rtl"===this.hc()?c.css(a.g.O.Kx,"-"+d+a.g.oa.Ub):c.css(a.g.O.Xn,"-"+d+a.g.oa.Ub)),e&&("rtl"===this.hc()?e.css(a.g.O.Kx,"-"+d+a.g.oa.Ub):e.css(a.g.O.Xn,"-"+d+a.g.oa.Ub))):((c=this.v().rs())&&("rtl"===this.hc()?c.css(a.g.O.Kx,"-"+d+a.g.oa.Ub):c.css(a.g.O.Xn,"-"+d+a.g.oa.Ub)),(c=this.v().qs())&&("rtl"===this.hc()?c.css(a.g.O.Kx,"-"+d+a.g.oa.Ub):c.css(a.g.O.Xn,"-"+d+a.g.oa.Ub)))},Dj:function(a,b,c){this.hP(a);
var e=this.Vb()[a];this.V$(null==e.sortProperty?e.field:e.sortProperty,b,c);this.nW=e;this.MU(a,b)},k$:function(){var d=this.v().UJ();if(d.css(a.g.O.hd)!=a.g.oa.Yl){var b=d.outerHeight(),c=this.v().me(),e=parseInt(c.css(a.g.O.sM),10),g=parseInt(c.css(a.g.O.Ax),10);c.css(a.g.O.Ax,g-e-b+a.g.oa.Ub);c.removeClass(a.g.sa.Ux);d.removeClass(a.g.sa.Ux);d.css(a.g.O.UC,"");d.css(a.g.O.hd,a.g.oa.Yl)}},NG:function(){var a=this.v().$fa();null!=a&&a.remove()},l$:function(){this.v().pw().css(a.g.O.hd,a.g.oa.Yl)},
Go:function(d,b){if(this.Vb()[d].sortable==this.Ff){var c=this.v().Ed(d),e=c.data("sorted");!b||null!=e&&e!=this.Tg.bq?b||null!=e&&e!=this.Tg.Rn||(c=c.find("."+a.g.F.ct),c.addClass(a.g.sa.rb),c.removeClass(a.g.sa.We),c.removeClass(a.g.sa.Xc)):(c=c.find("."+a.g.F.Zp),c.addClass(a.g.sa.rb),c.removeClass(a.g.sa.We),c.removeClass(a.g.sa.Xc))}},Hz:function(){var d=this,b=this.jb();null!=b&&b instanceof a.R&&!(b instanceof a.pa)?(this.v().Dd()[0].scrollTop=0,this.Uk()?this.Ph(function(){return d.Nu(0,{fetchType:"init",
pageSize:d.options.scrollPolicyOptions.fetchSize})}):this.Ph(function(){return d.Nu(0,{fetchType:"init"})})):null==b&&this.Ph(function(){return Promise.resolve()})},Nu:function(d,b){b=b||{};b.startIndex=d;b.silent=!0;var c=this.jb(),e=this;return new Promise(function(d,f){null!=c?(e.KV(),c.fetch(b).then(function(b){if(null!=b&&null!=b.data){var f=0;c instanceof a.pa&&(f=c.getStartItemIndex());var h=[],n;for(n=0;n<b.data.length;n++)h[n]=n+f+b.startIndex;e.FU({data:b.data,keys:b.keys,indexes:h},b.startIndex)}e.wj();
d(null)},function(a){e.wj();f(a)})):d(null)})},V$:function(a,b,c){var e=this.jb();if(!e)return null;this.iW();var g={};g.key=a;g.direction=b?this.Tg.Rn:this.Tg.bq;this._trigger("sort",c,{header:g.key,direction:g.direction});e.sort(g)},Z$:function(){if(null!=this.Cq){var a=this.WQ();if(this.Cq.length!=a.length)return!0;var b,c;for(b=0;b<a.length;b++)for(c in a[b])if(a[b].hasOwnProperty(c)&&a[b][c]!=this.Cq[b][c])return!0;return!1}return!0},ff:function(a){var b=this.Jk(),c;for(c=0;c<b.length;c++)if(b[c]==
a)return!0;return!1},Uk:function(){return this.options.scrollPolicy==this.r2.e2?!0:!1},YG:function(a){for(var b,c=this.v().Yb();null!=a&&a[0]!=c[0]&&"TD"!=(b=a.prop("nodeName"))&&"TH"!=b;)if(3==a[0].nodeType)a=a[0].parentNode;else{var e=a.attr("tabIndex");if(null!=e&&0<=e||b.match(/^INPUT|SELECT|OPTION|BUTTON|^A\b|TEXTAREA/)&&-1!=e)return!0;a=a.parentNode}return!1},wT:function(){var a=this.Vb(),b,c;for(b=0;b<a.length;b++)if(c=this.Zy(b,"footer"),null!=c)return!1;return!0},Nz:function(){var a=this.Vb(),
b;for(b=0;b<a.length;b++)if(null!=a[b].headerText||null!=a[b].headerStyle||null!=a[b].sortable&&a[b].sortable!=this.oN||null!=a[b].sortProperty||null!=a[b].headerRenderer)return!1;return!0},iaa:function(){return!0==this.Dca},qia:function(){return this.DW},jaa:function(d,b){var c=this.KO,e=!1;"contextMenu"==d&&b=="#"+this.v().Yb().attr("id")+"_contextmenu"?e=!1:"selection"==d||"currentRow"==d||a.b.Cg(b,c[d])||(e=!0);this.KO=f.extend(!0,{},this.options);return e},kaa:function(){var a=this.Vb(),b;for(b=
0;b<a.length;b++)if(null!=a[b].sortable&&a[b].sortable!=this.oN)return!0;return!1},FU:function(d,b){if(this.Z$()||!this.iaa()&&!this.Nz())if(this.V4(),this.OU(),null!=this.nW){var c,e,g=!1,f=this.Vb();if(null!=f){for(c=0;c<f.length;c++)if(e=f[c],a.b.Cg(e,this.nW)){g=!0;break}g||this.jb().sort(null)}}this.rv();this.NU(d,b)},MU:function(d,b){this.hP(d);var c=this.v().Ed(d),e=c.data("sorted");b&&e!=this.Tg.Rn?(c.data("sorted",this.Tg.Rn),e=c.find("."+a.g.F.Zp),e.addClass(a.g.sa.We),e.removeClass(a.g.sa.rb),
e=c.find("."+a.g.F.lx),e.removeClass(a.g.sa.rb),e=c.find("."+a.g.F.nx),e.addClass(a.g.sa.rb),this.Go(d,!b)):b||e==this.Tg.bq||(c.data("sorted",this.Tg.bq),e=c.find("."+a.g.F.ct),e.addClass(a.g.sa.We),e.removeClass(a.g.sa.rb),e=c.find("."+a.g.F.nx),e.removeClass(a.g.sa.rb),e=c.find("."+a.g.F.lx),e.addClass(a.g.sa.rb))},NU:function(d,b){var c=this.v().qf();if(null!=c){var e=this.C8(d,b),g;if(0==b)a.Components.ag(c[0]),c.empty();else if(g=c.children(),null!=g&&0<g.length)for(g=g.length-1;g>=b;g--)this.v().b_(g);
this.v().ip();this.NG();g=c.children();if(0!=e.length||null!=g&&0!=g.length){var h=f(document.createDocumentFragment()),k,l,m;for(g=0;g<e.length;g++)k=e[g].row,l=e[g].sh,null!=k&&(m=this.v().GX(l,k.key),this.v().bL(m,!0),this.v().cZ(l,m,k,h),this.mA(l,k,m,h,b,!0));c.append(h);this.v().PB();a.Components.vf(c[0])}else this.fW()}},mA:function(d,b,c,e,g,h){var k=this.D8(),l=this.Vb(),m=this.v().qf();(isNaN(d)||0>d)&&a.u.error("Error: Invalid rowIdx value: "+d);if(null==c)if(c=this.v().Dg(d))c.empty(),
h=!0,this.v().tJ(d,b.key,c);else return;this.NG();if(k)for(h=this.v().tB(b,c[0]),h=k({rowContext:h,row:f.extend({},b.data)}),null!=h?c.append(h):(null==e?c=f(m.children()[d]):(g=null==g?0:g,c=f(e.children()[d-g])),this.v().ip(),this.v().YK(b,c),this.v().bL(c,!1)),this.v().tJ(d,b.key,c),c=c.children("td"),e=1;e<c.length;e++)g=f(c[e]),this.v().XK(d,b.key,e-1,g),this.v().ZB(e-1,g,!1);else for(this.v().YK(b,c),e=0;e<l.length;e++)g=this.Zy(e,"cell"),this.v().lha(d,e,c,b,g,h)},rv:function(){var d=this.Vb(),
b=this.v().Xj();if(!b){if(this.wT())return;b=this.v().HX();this.v().A_(b)}b=this.v().qs();b.empty();if(d&&0<d.length){this.v().IX(b);var c,e,g;for(c=0;c<d.length;c++)e=this.Zy(c,"footer"),g=this.v().pfa(),this.v().B_(c,g),this.v().sga(c,g),e&&(e=e({footerContext:this.v().tB(null,g[0]),columnIndex:c}),null!=e?(g.empty(),g.append(e)):(g=f(b.children(":not(."+a.g.F.Hh+")")[c]),this.v().B_(c,g)))}},OU:function(){var d=this.Vb(),b=this.v().kn();if(!b){if(this.Nz())return;b=this.v().JX();this.v().C_(b)}b=
this.v().rs();b.empty();if(d&&0<d.length){var c=this.v().qfa();b.append(c);for(var e,g,h,k,c=0;c<d.length;c++)e=d[c],g=this.Zy(c,"header"),h=this.v().rfa(c),g&&(k=this.v().tB(null,h[0]),k={headerContext:k,columnIndex:c,data:e.headerText},e.sortable==a.g.Ff?k.columnHeaderSortableIconRenderer=function(b,c){a.Tl.oJ(this,0,c)}:k.columnHeaderDefaultRenderer=function(b,c){a.Tl.nJ(this,0,c)},e=g(k),null!=e?(h.empty(),h.append(e)):(h=f(b.children(":not(."+a.g.F.YC+")")[c]),this.v().q_(c,h),this.v().D_(c,
h,!1))),this.v().sfa(c,this.$y());this.Dca=!0}},Zba:function(){var a=this.v().pw();null!=a&&a.remove();this.v().KX()},dca:function(){var a=f.event.special;a.ojtablebeforecurrentrow={handle:function(a,c){return a.handleObj.handler.apply(this,[a,c])}};a.ojtablesort={handle:function(a,c){return a.handleObj.handler.apply(this,[a,c])}}},tv:function(){var d=this.jb();if(null!=d){this.fp();this.Eb=[];this.Eb.push({eventType:a.R.J.REQUEST,eventHandler:this.d9.bind(this)});this.Eb.push({eventType:a.R.J.SYNC,
eventHandler:this.sG.bind(this)});this.Eb.push({eventType:a.R.J.SORT,eventHandler:this.vG.bind(this)});this.Eb.push({eventType:a.R.J.ADD,eventHandler:this.tG.bind(this)});this.Eb.push({eventType:a.R.J.REMOVE,eventHandler:this.uG.bind(this)});this.Eb.push({eventType:a.R.J.CHANGE,eventHandler:this.f9.bind(this)});this.Eb.push({eventType:a.R.J.REFRESH,eventHandler:this.vz.bind(this)});this.Eb.push({eventType:a.R.J.RESET,eventHandler:this.wz.bind(this)});this.Eb.push({eventType:a.R.J.ERROR,eventHandler:this.c9.bind(this)});
var b,c;for(b=0;b<this.Eb.length;b++)(c=d.on(this.Eb[b].eventType,this.Eb[b].eventHandler))&&(this.Eb[b].eventHandler=c)}},eca:function(){null!=this.v().Dd()&&this.v().Dd().scroll(function(a){var b=f(a.target).scrollLeft();a=f(a.target)[0].scrollWidth-f(a.target)[0].clientWidth;this.Y9(b,a)}.bind(this))},Pm:function(d){if(!this.ZG){var b=this;a.C.fh(d[0],function(){var a=b.v().me().outerHeight(),d=b.v().me().outerWidth();b.v().PB(d,a)},50);this.ZG=!0}},SH:function(a){var b=this.Jk(),c;for(c=0;c<b.length;c++)b[c]==
a&&b.splice(c,1)},vV:function(a){var b="rtl"===this.hc(),c=this.v().qf(),e=this.v().Ed(a);if(e){a=this.v().CY();var e=e.get(0).getBoundingClientRect(),g=c.get(0).getBoundingClientRect(),f=!1;b?(e.left<g.left+a&&(b=g.left-e.left+a,this.v().Kz()||(b*=-1),c.scrollLeft(c.scrollLeft()+b),f=!0),e.right>g.right&&!f&&(b=e.right-g.right,this.v().Kz()||(b*=-1),c.scrollLeft(c.scrollLeft()-b))):(e.left<g.left&&(b=g.left-e.left,c.scrollLeft(c.scrollLeft()-b),f=!0),e.right>g.right-a&&!f&&(b=e.right-g.right+a,c.scrollLeft(c.scrollLeft()+
b)))}},Xca:function(a){var b=this.v().Dg(a);a=this.v().Xfa();var b=b.get(0).getBoundingClientRect(),c=this.v().Dd(),e=c.get(0).getBoundingClientRect(),g=!1;b.bottom>e.bottom-a&&(a=b.bottom-e.bottom+a,c.scrollTop(c.scrollTop()+a),g=!0);b.top<e.top&&!g&&(a=e.top-b.top,c.scrollTop(c.scrollTop()-a))},bl:function(d,b,c){var e=this.qo,g;g=!0;if(null==d){if(null!=e){try{g=this._trigger("beforecurrentrow",b,{currentRow:null,previousCurrentRow:this.qo})}catch(f){d=this.nc.NM;var k=a.ha.Jb(this.nc.LM,{error:f.toString()});
a.u.info(d+"\n"+k);return!1}if(!g)return!1;this.qo=null;this.option("currentRow",null,{_context:{rd:!0,originalEvent:b,mb:!0}});null==b&&this.Qh(-1,!0,!1,null,b);e=e.rowIndex;e=this.vu(e);e=this.tu(e);g=this.v().Dg(e);null!=g&&g.removeClass(a.g.F.wD)}return!0}var l=this.jb(),m=d.rowIndex,n=d.rowKey;null==n&&(n=this.vu(m));null==m&&(m=this.uo(n));k=this.tu(n);d={rowIndex:m,rowKey:n};if(-1!=k&&(!l||0==l.totalSize()||-1>k||null===k||null===n)){d=this.nc.p1;k=a.ha.Jb(this.nc.o1,{rowIdx:k});if(c)throw Error(d+
"\n"+k);a.u.info(d+"\n"+k);return!1}c=this.Ci();if(l=!a.b.Cg(this.qo,d)){try{g=this._trigger("beforecurrentrow",b,{currentRow:{rowIndex:m,rowKey:n},previousCurrentRow:this.qo})}catch(q){return d=this.nc.NM,k=a.ha.Jb(this.nc.LM,{error:q.toString()}),a.u.info(d+"\n"+k),!1}if(!g)return!1;this.qo={rowIndex:m,rowKey:n};this.option("currentRow",this.qo,{_context:{rd:!0,originalEvent:b,mb:!0}});g=this.v().Dg(k);null!=g&&g.addClass(a.g.F.wD);null!=e&&(e=e.rowIndex,e=this.vu(e),e=this.tu(e),g=this.v().Dg(e),
null!=g&&g.removeClass(a.g.F.wD))}(l||c!=d.rowIndex)&&null==b&&this.Qh(k,!0,!1,null,b);return!0},KV:function(){this.iW();this.NG();this.NP=!0},cl:function(a,b,c,e){var g=null;null!=e&&(g=e.currentTarget);if(b){var f=this.Ik();null!=f&&f!=a&&this.cl(f,!1,!1,e);this.eP(!0);c&&this.Bq();this.vV(a);this.fO=a}this.LV(a,{Ti:b},g)},Kj:function(d,b,c,e,g){if(this.$y()==this.vk.nq||this.$y()==this.vk.Bx)(isNaN(d)||0>d)&&a.u.error("Error: Invalid column selection value: "+d),this.$y()==this.vk.nq&&b&&this.Pt(),
this.LV(d,{selected:b},c,e),this.kda(d,b),d=this.v().LY(d),f(d.children("."+a.g.F.uM)[0]).prop("checked",b),g&&(b=this.UR(),this.option("selection",b,{_context:{rd:!0,mb:!0}}))},LV:function(d,b){var c=this.v().Ed(d);if(c){var e=b.Ti,g=b.selected;null!=g&&c.hasClass(a.g.sa.Xc)!=g&&(g?c.addClass(a.g.sa.Xc):c.removeClass(a.g.sa.Xc));null!=e&&(e?(c.addClass(a.g.sa.qj),this.jW(d)):(c.removeClass(a.g.sa.qj),this.Go(d,!0),this.Go(d,!1)));this.wea(d)}},kda:function(a,b){this.Em||(this.Em=[]);var c;for(c=
0;c<this.Em.length;c++)if(this.Em[c]==a){this.Em.splice(c,1);break}b&&this.Em.push(a)},mda:function(a,b){this.Fm||(this.Fm=[]);for(var c=0;c<this.Fm.length;c++)if(this.Fm[c]==a){this.Fm.splice(c,1);break}b&&this.Fm.push(a)},Qh:function(d,b,c,e,g){if(-1==d){var f=this.Ci();null!=f&&this.Qh(f,!1,c,null,null);return c&&(g=this.bl(null,g),!g)?!1:!0}var k=this.v().Dg(d);if(!k)return!1;if(b){f=this.Ci();null!=f&&f!=d&&this.Qh(f,!1,c,e,null);if(c&&(c=this.zo(d),g=this.bl({rowKey:c},g),!g))return!1;k.addClass(a.g.sa.qj);
this.Xca(d);this.UA(d,{Ti:!0,hover:!1});this.dP();this.Pt();this.zA(!0)}else k.removeClass(a.g.sa.qj);this.UA(d,{Ti:b});return!0},Mj:function(d,b,c,e,g){if(this.ZF()==this.vk.nq||this.ZF()==this.vk.Bx)(isNaN(d)||0>d)&&a.u.error("Error: Invalid row selection value: "+d),this.ZF()==this.vk.nq&&b&&this.Bq(),c=this.v().Dg(d),null!=c&&(e=!1,c.hasClass(a.g.sa.Xc)!=b&&(b?c.addClass(a.g.sa.Xc):c.removeClass(a.g.sa.Xc),e=!0),e&&(b?this.UA(d,{hover:!1,Ti:!1,selected:!0}):this.UA(d,{selected:!1})),this.mda(d,
b),d=this.v().HY(c),f(d.children("."+a.g.F.vM)[0]).prop("checked",b),g&&(b=this.UR(),this.option("selection",b,{_context:{rd:!0,mb:!0}})))},Bv:function(d){if(null==d)this.Bq(),this.Pt();else{var b,c,e,g,f,k;for(b=0;b<d.length;b++){e=d[b];if(null==e.startKey&&null==e.startIndex||null==e.endKey&&null==e.endIndex)return a.u.error("Error: Invalid range object in selection. Both start and end objects must be specified"),null;g=k=c=f=null;null!=e.startKey&&null!=e.startKey.row&&(f=this.uo(e.startKey.row));
null!=e.endKey&&null!=e.endKey.row&&(c=this.uo(e.endKey.row));null!=e.startKey&&null!=e.startKey.column&&(k=this.UQ(e.startKey.column));null!=e.endKey&&null!=e.endKey.column&&(g=this.UQ(e.endKey.column));null==f&&null!=e.startIndex&&(f=e.startIndex.row);null==c&&null!=e.endIndex&&(c=e.endIndex.row);null==k&&null!=e.startIndex&&(k=e.startIndex.column);null==g&&null!=e.endIndex&&(g=e.endIndex.column);if(null!=f&&null!=c&&null!=k&&null!=g)return a.u.error("Error: Invalid range object in selection - Can only support row or column selection. Not both"),
null;if(null!=f&&0<=f&&null!=c&&0<=c)for(g=this.vu(f),c=this.vu(c),g=this.tu(g),e=this.tu(c),c=g;c<=e;c++)try{this.Mj(c,!0,null,null,!1)}catch(l){a.u.error("Error: "+l)}else if(null!=k&&null!=g)for(c=k;c<=g;c++)try{this.Kj(c,!0,null,null,!1)}catch(m){a.u.error("Error: "+m)}else return a.u.error("Error: Invalid range object in selection - \n start row: "+f+"\nend row: "+c+"\nstart column: "+k+"\nend column: "+g),null}}},zA:function(a){this.DW=a},Hda:function(d,b,c){this.v().mha(d,b,c);d=this.v().UJ();
if(d.css(a.g.O.hd)==a.g.oa.Yl){d.css(a.g.O.hd,a.g.oa.Yp);var e=parseInt(d.css(a.g.O.Ex),10),g=parseInt(d.css(a.g.O.Fx),10);b=this.v().me();c==a.X.Ob.WARNING&&(b.addClass(a.g.sa.Ux),d.addClass(a.g.sa.Ux));c=b.width();d.css(a.g.O.jd,c-e-g+a.g.oa.Ub);c=d.outerHeight();var e=parseInt(b.css(a.g.O.sM),10),g=parseInt(b.css(a.g.O.b1),10),f=parseInt(b.css(a.g.O.Ax),10),f=f+e+c;b.css(a.g.O.Ax,f+a.g.oa.Ub);d.css(a.g.O.UC,-1*(f+e)+a.g.oa.Ub);d.css(a.g.O.Xn,-1*g+a.g.oa.Ub)}},fW:function(){this.v().wfa(this.Vb().length)},
iW:function(){this.v().pw().css(a.g.O.hd,a.g.oa.XM);this.v().$Z()},jW:function(d){if(this.Vb()[d].sortable==this.Ff&&(d=this.v().Ed(d))&&null==d.data("sorted")){var b=d.find("."+a.g.F.Zp);b.addClass(a.g.sa.We);b.removeClass(a.g.sa.rb);d.find("."+a.g.F.lx).removeClass(a.g.sa.rb);d.find("."+a.g.F.nx).addClass(a.g.sa.rb)}},fp:function(){var a=this.jb();if(null!=this.Eb&&null!=a){var b;for(b=0;b<this.Eb.length;b++)a.off(this.Eb[b].eventType,this.Eb[b].eventHandler)}},wea:function(d){var b=this.IF(d).selected,
c=this.bG(),e=this.v().jh();if(null!=e&&0<e.length){var g,h,k,l;for(g=0;g<e.length;g++)if(k=this.v().ow(g,d),b)f(k).addClass(a.g.sa.Xc);else{l=!1;for(h=0;h<c.length;h++)if(g==c[h]){l=!0;break}l||f(k).removeClass(a.g.sa.Xc)}}},UA:function(d,b){var c=this.v().IY(d),e=b.Ti,g=b.selected,h=b.hover;if(c){if(null!=h){var k;for(k=0;k<c.length;k++)h?f(c[k]).addClass(a.g.sa.rk):f(c[k]).removeClass(a.g.sa.rk)}if(null!=e)for(k=0;k<c.length;k++)e?f(c[k]).addClass(a.g.sa.qj):f(c[k]).removeClass(a.g.sa.qj);if(null!=
g)for(k=0;k<c.length;k++)g?f(c[k]).addClass(a.g.sa.Xc):f(c[k]).removeClass(a.g.sa.Xc)}},eda:function(a){this.EQ=a?a.bind(this):void 0},Ph:function(d){var b=this;this.xr||(this.Gv=0,this.xr=Promise.resolve());this.Gv++;return this.xr=this.xr.then(d.bind(b)).then(function(a){b.Gv--;0==b.Gv&&(b.xr=void 0,b.EQ&&b.EQ(),b._trigger("ready"));return a},function(c){b.Gv--;0==b.Gv&&(b.xr=void 0,a.u.error(c));return Promise.reject(c)})}})})();a.ib=function(d,b){b=b||{};if(!(d instanceof a.ma))throw Error(a.R.nc._ERR_DATA_INVALID_TYPE_SUMMARY+
"\n"+a.R.nc._ERR_DATA_INVALID_TYPE_DETAIL);this.f=d;this.nd=[];this.aa=0;this.Jm=[];null==this.f.jw("fetchSize")&&(this.f.JJ=function(){return-1});var c=this;this.f.yB=function(b,d,f){var k,l,m,n=[],q=[],p=[];for(d=0;d<f.Q();d++)k=f.getData(d),m=f.getMetadata(d).key,l=b+d,c.Jm[l]={},c.Jm[l].nodeSet=f,c.Jm[l].startIndex=b,n.push(k),q.push(m),p.push(l),c.ca.data.splice(l,0,k),c.ca.keys.splice(l,0,m),c.ca.indexes.splice(l,0,l);c.Ra||a.R.q.handleEvent.call(c,a.R.J.ADD,{data:n,keys:q,indexes:p});c.nv();
c.Ra&&setTimeout(function(){c.fetch()},0)};this.f.RB=function(b){var d,f,k=[],l=[],m=[];for(d=0;d<b.length;d++)f=b[d].index-d,k.push(""),l.push(""),m.push(f),c.ca.data.splice(f,1),c.ca.keys.splice(f,1),c.ca.indexes.splice(f,1);c.Ra||a.R.q.handleEvent.call(c,a.R.J.REMOVE,{data:k,keys:l,indexes:m});c.nv();c.Ra&&setTimeout(function(){c.fetch()},0)};this.Init();if(null!=b&&("enabled"==b.startFetch||null==b.startFetch)||null==b)this.Ev=!0};o_("FlattenedTreeTableDataSource",a.ib,a);a.b.ga(a.ib,a.R,"oj.FlattenedTreeTableDataSource");
a.ib.prototype.Init=function(){a.ib.q.Init.call(this)};a.b.i("FlattenedTreeTableDataSource.prototype.Init",{Init:a.ib.prototype.Init});a.ib.prototype.getCapability=function(){return"full"};a.b.i("FlattenedTreeTableDataSource.prototype.getCapability",{getCapability:a.ib.prototype.getCapability});a.ib.prototype.getWrappedDataSource=function(){return this.f};a.b.i("FlattenedTreeTableDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:a.ib.prototype.getWrappedDataSource});a.ib.prototype.fetch=
function(a){a=a||{};return"init"!=a.fetchType||this.Ev?this.ee(a):Promise.resolve()};a.b.i("FlattenedTreeTableDataSource.prototype.fetch",{fetch:a.ib.prototype.fetch});a.ib.prototype.at=function(a){var b;b=0>a||a>=this.ca.length?null:{data:this.ca.data[a],index:a,key:this.ca.keys[a]};return new Promise(function(a){a(b)})};a.b.i("FlattenedTreeTableDataSource.prototype.at",{at:a.ib.prototype.at});a.ib.prototype.collapse=function(a){this.f.collapse(a)};a.b.i("FlattenedTreeTableDataSource.prototype.collapse",
{collapse:a.ib.prototype.collapse});a.ib.prototype.expand=function(a){this.f.expand(a)};a.b.i("FlattenedTreeTableDataSource.prototype.expand",{expand:a.ib.prototype.expand});a.ib.prototype.get=function(){a.j.Xa();return null};a.b.i("FlattenedTreeTableDataSource.prototype.get",{get:a.ib.prototype.get});a.ib.prototype.on=function(d,b){if("expand"==d||"collapse"==d)this.f.on(d,b);else a.ib.q.on.call(this,d,b)};a.b.i("FlattenedTreeTableDataSource.prototype.on",{on:a.ib.prototype.on});a.ib.prototype.off=
function(d,b){"expand"==d||"collapse"==d?this.f.off(d,b):a.ib.q.off.call(this,d,b)};a.b.i("FlattenedTreeTableDataSource.prototype.off",{off:a.ib.prototype.off});a.ib.prototype.sort=function(d){if(null==d)return Promise.resolve();var b=this;d.axis="column";return new Promise(function(c,e){b.f.getWrappedDataSource().sort(d,{success:function(){setTimeout(function(){b.f.refresh();b.ca=null;var e={header:d.key,direction:d.direction};a.R.q.handleEvent.call(b,a.R.J.SORT,e);c(e)},0)}.bind(this),error:function(a){e(a)}.bind(this)})})};
a.b.i("FlattenedTreeTableDataSource.prototype.sort",{sort:a.ib.prototype.sort});a.ib.prototype.totalSize=function(){return-1};a.b.i("FlattenedTreeTableDataSource.prototype.totalSize",{totalSize:a.ib.prototype.totalSize});a.ib.prototype.QF=function(a){return this.Jm[a].nodeSet.getMetadata(a-this.Jm[a].startIndex)};a.ib.prototype.ee=function(d){d=d||{};this.Dv(d);this.aa=null==d.startIndex?this.aa:d.startIndex;var b=Number.MAX_VALUE;this.Ra=null==d.pageSize?this.Ra:d.pageSize;null!=this.Ra&&(b=this.Ra);
var c=this.aa;if(null!=this.ca)if(null!=this.Ra){var e=this.ca.data.length-1;if(this.aa+this.Ra-1<=e){var e=a.ib.ez(this.ca,this.aa,this.Ra),b=[],c=[],g;for(g=this.aa;g<=e;g++)b[g-this.aa]=this.ca.data[g],c[g-this.aa]="";e={data:b,keys:c,startIndex:this.aa};this.sg(d,e,null);return Promise.resolve(e)}this.aa<=e&&(c=e+1)}else this.f.refresh(),this.ca=null;var f={start:c,count:b},k=this;return new Promise(function(b,c){k.f.np(f,{success:function(c){k.wG(c);d.refresh=!0;var e=a.ib.ez(k.ca,k.aa,k.Ra),
g=[],f=[],h;for(h=k.aa;h<=e;h++)g[h-k.aa]=k.ca.data[h],f[h-k.aa]=c.getMetadata(h).key;c={data:g,keys:f,startIndex:k.aa};k.sg(d,c,null);b(c)}.bind(this),error:function(a){k.sg(d,null,a);c(a)}.bind(this)})})};a.ib.prototype.wG=function(d){var b,c;for(b=0;b<d.Q();b++)c=this.aa+b,this.Jm[c]={},this.Jm[c].nodeSet=d,this.Jm[c].startIndex=this.aa;this.ca||(this.ca={},this.ca.data=[],this.ca.keys=[],this.ca.indexes=[]);a.ib.xm(d,this,this.ca)};a.ib.prototype.Dv=function(d){d.silent||a.R.q.handleEvent.call(this,
a.R.J.REQUEST,{startIndex:d.startIndex})};a.ib.prototype.sg=function(d,b,c){null!=c?a.R.q.handleEvent.call(this,a.R.J.ERROR,c):d.silent||a.R.q.handleEvent.call(this,a.R.J.SYNC,b)};a.ib.ez=function(a,b,c){var e=a.data.length-1;0<c&&(e=b+c-1,e=e>a.data.length-1?a.data.length-1:e);return e};a.ib.xm=function(a,b,c){b=a.Q()-1;var e;for(e=a.ua();e<=b;e++){var g=a.getData(e);c.data[e]=g;c.keys[e]="";c.indexes[e]=e}};a.ib.prototype.nv=function(){for(var a=0;a<this.ca.data.length;a++)this.ca.indexes[a]=a};
a.g=function(a){this.Aa=a;this.options=a.options;this.element=a.element;this.Init()};o_("TableDomUtils",a.g,a);a.b.ga(a.g,a.b,"oj.TableDomUtils");a.g.prototype.Init=function(){a.g.q.Init.call(this)};a.b.i("TableDomUtils.prototype.Init",{Init:a.g.prototype.Init});a.g.prototype.ffa=function(){this.ip();this.Rh=null};a.g.prototype.ip=function(){this.hE=null};a.g.prototype.EX=function(d){var b=null,c=this;if(null!=this.options.contextMenu||null!=this.Yb().attr("contextmenu")){var e=this.iY(),b=f(e);if(null!=
b&&0<b.length){var g=b.find("[data-oj-command]");if(null!=g&&0<g.length){var h;g.each(function(){0===f(this).children(a.g.Mb.RC).length&&(h=f(this).attr("data-oj-command").split("-"),f(this).replaceWith(c.FX(h[h.length-1])))});this.QT=b;this.Aa.sP=e;b.ojMenu("refresh");b.on("ojselect",d)}}}else this.Aa.kaa()&&(b=f(document.createElement(a.g.Mb.x3)),b.css(a.g.O.hd,a.g.oa.Yl),b.attr(a.g.bb.Ie,this.Yb().attr(a.g.bb.Ie)+"_contextmenu"),this.me().append(b),e=this.FX("sort"),b.append(e),b.ojMenu(),this.QT=
b,this.Aa.sP="#"+b.attr(a.g.bb.Ie),b.on("ojselect",d),this.Aa._setOption("contextMenu","#"+b.attr(a.g.bb.Ie)))};a.g.prototype.FX=function(a){return"sort"===a?f(this.sJ(a)).append(f("\x3cul\x3e\x3c/ul\x3e").append(f(this.sJ("sortAsc"))).append(f(this.sJ("sortDsc")))):null};a.g.prototype.sJ=function(a){var b=f(document.createElement("li"));b.attr("data-oj-command","oj-table-"+a);b.append(this.jfa(a));return b};a.g.prototype.jfa=function(d){var b=f(document.createElement(a.g.Mb.RC));b.attr(a.g.bb.F1,
"#");var c=null;"sort"==d?c=this.Aa.D("labelSort"):"sortAsc"==d?c=this.Aa.D("labelSortAsc"):"sortDsc"==d&&(c=this.Aa.D("labelSortDsc"));b.text(c);return b};a.g.prototype.kfa=function(a,b){this.Yb();this.nfa();this.Zj()&&this.ofa();a||this.JX();b||this.HX();this.lfa();this.KX();this.tfa()};a.g.prototype.lfa=function(){var d=this.Yb(),b=f(document.createElement(a.g.Mb.WN));d.append(b);this.gE=b};a.g.prototype.mfa=function(){return f(document.createElement(a.g.Mb.rq))};a.g.prototype.tJ=function(d,b,
c){var e=this.HY(c),g=null==this.kn()?!0:!1;null==e&&(d=null!=b?b.toString():d.toString(),e=f(document.createElement(a.g.Mb.rq)),e.addClass(a.g.F.Ox),e.addClass(a.g.F.Hh),g||e.attr(a.g.bb.cD,this.Yb().attr(a.g.bb.Ie)+":"+a.g.xM),g=f(document.createElement(a.g.Mb.wx)),g.attr(a.g.bb.Ie,this.Yb().attr(a.g.bb.Ie)+":acc_sel_row_"+this.wB(d)),g.attr(a.g.bb.Sx,"checkbox"),g.attr(a.g.bb.vt,"-1"),d=this.Aa.D(this.Aa.lb.fN),g.attr(a.g.bb.Px,d),g.addClass(a.g.F.vM),e.append(g),c.prepend(e))};a.g.prototype.GX=
function(d,b){var c=f(document.createElement(a.g.Mb.sq));this.tJ(d,b,c);return c};a.g.prototype.nfa=function(){var d=f(document.createElement(a.g.Mb.cq));this.element.parent()[0].replaceChild(d[0],this.element[0]);d.prepend(this.element);this.ky=d};a.g.prototype.HX=function(){var d=this.Yb(),b=f(document.createElement(a.g.Mb.XN)),c=f(document.createElement(a.g.Mb.sq));this.IX(c);b.append(c);c=this.kn();null!=c?c.after(b):(c=this.qf(),null!=c?c.before(b):d.append(b));return b};a.g.prototype.IX=function(d){var b=
d.children("."+a.g.F.Hh);null!=b&&0<b.length?f(b[0]):(b=f(document.createElement(a.g.Mb.rq)),b.addClass(a.g.F.Hh),b.attr(a.g.bb.vt,"-1"),d.prepend(b))};a.g.prototype.pfa=function(){return f(document.createElement(a.g.Mb.rq))};a.g.prototype.JX=function(){var d=this.Yb(),b=f(document.createElement(a.g.Mb.ZN)),c=f(document.createElement(a.g.Mb.sq));this.kE=c;b.append(c);c=this.Xj();null!=c?c.before(b):(c=this.qf(),null!=c?c.before(b):d.append(b));return this.jE=b};a.g.prototype.qfa=function(){var d=
f(document.createElement(a.g.Mb.YN));d.addClass(a.g.F.YC);d.addClass(a.g.F.Hh);d.attr(a.g.bb.Ie,this.Yb().attr(a.g.bb.Ie)+":"+a.g.xM);var b=this.Aa.D(this.Aa.lb.fN);d.attr(a.g.bb.Px,b);d.text(b);return d};a.g.prototype.rfa=function(d){function b(a){a.text(c.headerText)}var c=this.Aa.Vb()[d],e=f(document.createElement(a.g.Mb.YN));this.D_(d,e,!0);e.attr("abbr",c.headerText);e.attr(a.g.bb.Px,c.headerText);this.tga(d,e);d={columnIndex:d,headerContext:{component:this.Aa,parentElement:e}};c.sortable==a.g.Ff?
(e.attr("data-oj-sortable",a.g.Ff),a.Tl.oJ(d,0,b)):a.Tl.nJ(d,0,b);return e};a.g.prototype.sfa=function(d,b){if(b==a.g.vk.nq||b==a.g.vk.Bx){var c=this.Ed(d),e=this.LY(d);if(null==e){e=f(document.createElement(a.g.Mb.cq));e.addClass(a.g.F.wM);e.addClass(a.g.F.Hh);var g=f(document.createElement(a.g.Mb.wx));g.attr(a.g.bb.Ie,this.Yb().attr(a.g.bb.Ie)+":acc_sel_col"+d);g.attr(a.g.bb.Sx,"checkbox");g.attr(a.g.bb.vt,"-1");var h=this.Aa.D(this.Aa.lb.b2);g.attr(a.g.bb.Px,h);g.addClass(a.g.F.uM);e.append(g);
c.prepend(e)}}};a.g.prototype.ofa=function(){var d=this.Yb(),b=this.me(),c=f(document.createElement(a.g.Mb.cq));c.addClass(a.g.F.UN);b[0].replaceChild(c[0],d[0]);c.append(d);this.iE=c};a.g.prototype.wfa=function(d){var b=this.qf(),c=f(document.createElement(a.g.Mb.sq));c.addClass(a.g.F.TN);this.ufa(c);this.vfa(c,d);b.append(c)};a.g.prototype.ufa=function(d){var b=f(document.createElement(a.g.Mb.rq));b.addClass(a.g.F.Hh);b.attr(a.g.bb.vt,"-1");d.prepend(b)};a.g.prototype.vfa=function(d,b){var c=f(document.createElement(a.g.Mb.rq));
c.attr(a.g.bb.d1,b||1);c.addClass(a.g.F.SN);var e=null,e=null!=this.options.emptyText?this.options.emptyText:this.Aa.D(this.Aa.lb.n2);c.text(e);d.append(c)};a.g.prototype.tfa=function(){var d=this.me(),b=f(document.createElement(a.g.Mb.cq));b.addClass(a.g.F.RN);b.css(a.g.O.hd,a.g.oa.Yl);d.append(b);this.lE=b};a.g.prototype.KX=function(){var d=this.me(),b=f(document.createElement(a.g.Mb.cq));b.addClass(a.g.F.zD);b.css(a.g.O.hd,a.g.oa.Yl);var c=f(document.createElement(a.g.Mb.cq));c.addClass(a.g.F.n3);
c.text(this.Aa.D(this.Aa.lb.l2));b.append(c);d.append(b);this.mE=b};a.g.prototype.iY=function(){return null==this.options.contextMenu?"#"+this.Yb().attr("contextmenu"):this.options.contextMenu};a.g.prototype.Th=function(d){var b=this.jn(d,a.g.F.pq);if(null!=b)return b.parent().children("."+a.g.F.pq).index(b);b=this.jn(d,a.g.F.Tn);if(null!=b)return b.parent().children("."+a.g.F.Tn).index(b);d=this.jn(d,a.g.F.qq);return null!=d?d.parent().children("."+a.g.F.qq).index(d):null};a.g.prototype.qB=function(d){return this.jn(d,
a.g.F.Zn).index()};a.g.prototype.jn=function(a,b){var c;if(null==a)return null;a=f(a);if(a.hasClass(b))return a;c=a.parents("."+b);return 0!=c.length?c.eq(0):null};a.g.prototype.tB=function(d,b){var c={};c.component=this.Aa;var e=this.Aa.jb();e instanceof a.pa&&(e=e.getWrappedDataSource());c.datasource=e;c.parentElement=b;if(null!=d&&(c.status=this.Vfa(d),e instanceof a.ib)){var e=e.QF(d.index),g;for(g in e)e.hasOwnProperty(g)&&(c[g]=e[g])}return c};a.g.prototype.Vfa=function(a){return{rowIndex:a.index,
rowKey:a.key,currentRow:f.extend({},this.Aa.dR())}};a.g.prototype.Xfa=function(){var a=this.Dd();return 0<a.get(0).clientHeight?a.get(0).offsetHeight-a.get(0).clientHeight:0};a.g.prototype.CY=function(){var a=this.Dd();return 0<a.get(0).clientWidth?a.get(0).offsetWidth-a.get(0).clientWidth:0};a.g.prototype.Dd=function(){return this.Zj()?this.JY():this.qf()};a.g.prototype.Yb=function(){return f(this.element)};a.g.prototype.qf=function(){if(!this.gE){var d=this.Yb(),b=null;d&&(b=d.children("."+a.g.F.vD))&&
0<b.length&&(this.gE=f(b.get(0)))}return this.gE};a.g.prototype.ow=function(a,b,c){return(a=this.IY(a,c))?a.length>b?f(a[b]):null:null};a.g.prototype.HY=function(d){return null!=d&&(d=d.children("."+a.g.F.Ox),null!=d&&0<d.length)?f(d[0]):null};a.g.prototype.IY=function(d,b){b||(b=this.Dg(d));if(!b)return null;var c=b.children("."+a.g.F.pq);return null!=c&&0<c.length?c:null};a.g.prototype.Dg=function(a){var b=this.jh();return b&&null!=a?b.length>a?f(b[a]):null:null};a.g.prototype.jh=function(){if(!this.hE){var d=
this.qf().children("."+a.g.F.Zn);null!=d&&0<d.length&&(this.hE=d)}return this.hE};a.g.prototype.me=function(){this.ky||(this.Zj()?this.ky=f(this.element.get(0).parentNode.parentNode):this.ky=f(this.element.get(0).parentNode));return this.ky};a.g.prototype.Xj=function(){var d=this.Yb(),b=null;return d&&(b=d.children("."+a.g.F.xD))&&0<b.length?f(b.get(0)):null};a.g.prototype.KY=function(d){var b=this.qs(),b=f(b).children("."+a.g.F.qq);return b.length>=d?f(b[d]):null};a.g.prototype.qs=function(){if(!this.JO){var d=
this.Xj();if(!d)return null;this.JO=f(d.children("."+a.g.F.PN).get(0))}return this.JO};a.g.prototype.kn=function(){if(!this.jE){var d=this.Yb(),b=null;d&&(b=d.children("."+a.g.F.yD))&&0<b.length&&(this.jE=f(b.get(0)))}return this.jE};a.g.prototype.Ed=function(a){var b=this.TJ();return b?b.length>a?f(b[a]):null:null};a.g.prototype.LY=function(d){d=this.Ed(d);return null!=d&&(d=d.children("."+a.g.F.wM),null!=d&&0<d.length)?f(d[0]):null};a.g.prototype.TJ=function(){var d=this.rs();return null!=d&&(d=
d.children("."+a.g.F.Tn),null!=d&&0<d.length)?d:null};a.g.prototype.rs=function(){if(!this.kE){var d=this.kn();if(!d)return null;this.kE=f(d.children("."+a.g.F.QN).get(0))}return this.kE};a.g.prototype.JY=function(){if(!this.iE){var d=this.me();d&&(d=d.children("."+a.g.F.UN))&&0<d.length&&(this.iE=f(d.get(0)))}return this.iE};a.g.prototype.UJ=function(){if(!this.lE){var d=this.me();d&&(d=d.children("."+a.g.F.RN))&&0<d.length&&(this.lE=f(d.get(0)))}return this.lE};a.g.prototype.$fa=function(){var d=
this.qf();return d&&(d=d.children("."+a.g.F.TN))&&0<d.length?f(d.get(0)):null};a.g.prototype.pw=function(){if(!this.mE){var d=this.me();d&&(d=d.children("."+a.g.F.zD))&&0<d.length&&(this.mE=f(d.get(0)))}return this.mE};a.g.prototype.wB=function(a){var b=0;if(0==a.length)return b;var c,e;for(e=0;e<a.length;e++)c=a.charCodeAt(e),b=(b<<5)-b+c,b&=b;return b};a.g.prototype.rga=function(d,b,c,e,g){this.XK(d,b,c,e);d=f(g).children("."+a.g.F.pq);0==c?(c=g.children("."+a.g.F.Ox),null!=c&&0<c.length?f(c[0]).after(e):
g.prepend(e)):d.length>=c?f(d.get(c-1)).after(e):f(g).append(e)};a.g.prototype.cZ=function(d,b,c,e){this.YK(c,b);null==e?(c=this.qf(),e=c.children("."+a.g.F.Zn),0==d?c.prepend(b):e.length>=d?f(e.get(d-1)).after(b):c.append(b)):e.append(b);this.ip()};a.g.prototype.sga=function(d,b){var c=this.qs(),e=f(c).children("."+a.g.F.qq);0==d?(e=c.children("."+a.g.F.Hh),null!=e&&0<e.length?f(e[0]).after(b):c.prepend(b)):c.length>=d?f(e.get(d-1)).after(b):c.append(b)};a.g.prototype.tga=function(d,b){var c=this.rs(),
e=this.TJ();this.q_(d,b);var g=this.Ed(d);g?g.replaceWith(b):0==d?(e=c.children("."+a.g.F.YC),null!=e&&0<e.length?f(e[0]).after(b):c.prepend(b)):e.length>=d?f(e.get(d-1)).after(b):c.append(b)};a.g.prototype.Zj=function(){return this.Kz()&&10>this.Kz()?!0:!1};a.g.prototype.kZ=function(){var d=this.me(),b=this.Yb(),c=this.pw(),e=c.css(a.g.O.hd).toString();c.css(a.g.O.hd,a.g.oa.Yl);var g=[];g[0]=0<d[0].clientHeight?b[0].clientHeight>d[0].clientHeight?1:1<d[0].clientHeight-b[0].clientHeight?-1:0:0;g[1]=
0<d[0].clientWidth?b[0].clientWidth>d[0].clientWidth?1:1<d[0].clientWidth-b[0].clientWidth?-1:0:0;c.css(a.g.O.hd,e);return g};a.g.prototype.Xga=function(){var d=this,b=this.QT;b&&0<b.length&&b.find("[data-oj-command]").each(function(){var b=f(this).children(a.g.Mb.RC);if(0<b.length){var e=f(this).attr("data-oj-command").split("-"),e=e[e.length-1],g;"sort"==e?g=d.Aa.D("labelSort"):"sortAsc"==e?g=d.Aa.D("labelSortAsc"):"sortDsc"==e&&(g=d.Aa.D("labelSortDsc"));b.contents().filter(function(){return 3===
this.nodeType})[0].nodeValue=g}})};a.g.prototype.PB=function(a,b){this.Yba(a,b);this.Aa.bl(this.options.currentRow,null)};a.g.prototype.b_=function(d){d=this.Dg(d);null!=d&&(a.Components.ag(d[0]),d.remove(),this.ip())};a.g.prototype.lha=function(d,b,c,e,g,h){var k=this.Aa.Vb()[b],l=null;h||(l=this.ow(d,b,c));l?(l.empty(),this.ZB(b,l,!1)):(l=this.mfa(),this.ZB(b,l,!0),this.rga(d,e.key,b,l,c));h=null;null!=k.field&&(h=e.data[k.field]);g?(k=this.tB(e,l[0]),g=g({cellContext:k,columnIndex:b,data:h,row:f.extend({},
e.data)}),null!=g?l.append(g):(l=f(c.children(":not(."+a.g.F.Ox+")")[b]),this.XK(d,e.key,b,l),this.ZB(b,l,!1))):l.text(h)};a.g.prototype.XK=function(d,b,c,e){var g=this.options.accessibility;c=this.Aa.Vb()[c];var f=null,k=null==this.kn()?!0:!1,f=null!=g&&null!=g.rowHeader?g.rowHeader:this.Aa.Vb()[0].id;d=null!=b?b.toString():d.toString();d=this.Yb().attr(a.g.bb.Ie)+":"+f+"_"+this.wB(d);b=this.Yb().attr(a.g.bb.Ie)+":"+c.id;f==c.id?(e.attr(a.g.bb.Ie,d),k&&(b="")):b=k?d:b+" "+d;e.attr(a.g.bb.cD)||e.attr(a.g.bb.cD,
b)};a.g.prototype.YK=function(a,b){b.data("rowKey",a.key)};a.g.prototype.q_=function(d,b){var c=this.Aa.Vb()[d];b.attr(a.g.bb.Ie)||b.attr(a.g.bb.Ie,this.Yb().attr(a.g.bb.Ie)+":"+c.id)};a.g.prototype.mha=function(d,b,c){var e=this.UJ();e.empty();e.append(a.Na.rX(document,d,b,c,null))};a.g.prototype.tha=function(){var d=this.Yb(),b=this.me(),c=d.children(a.g.Mb.ZN),c=0<c.length?f(c[0]):null,e=d.children(a.g.Mb.XN),e=0<e.length?f(e[0]):null,g=d.children(a.g.Mb.WN),g=0<g.length?f(g[0]):null;d.attr(a.g.bb.vt,
"0");this.Aa._focusable(d);this.Aa._focusable(b);this.C_(c);this.A_(e);this.uha(g)};a.g.prototype.uha=function(d){d.addClass(a.g.F.vD);d.attr(a.Components.Cx,this.Aa.widgetName)};a.g.prototype.ZB=function(d,b,c){var e=this.options;d=this.Aa.Vb()[d];if(c||!b.hasClass(a.g.F.pq))b.addClass(a.g.F.pq),null==d.style||!c&&b.attr(a.g.bb.rj)==d.style||b.attr(a.g.bb.rj,d.style),null==d.className||!c&&b.hasClass(d.className)||b.addClass(d.className);e.verticalGridVisible==a.g.Ff&&(!c&&b.hasClass(a.g.F.VN)||
b.addClass(a.g.F.VN))};a.g.prototype.bL=function(d,b){!b&&d.hasClass(a.g.F.Zn)||d.addClass(a.g.F.Zn);this.options.horizontalGridVisible==a.g.Ff&&(!b&&d.hasClass(a.g.F.wt)||d.addClass(a.g.F.wt))};a.g.prototype.vha=function(d){d.addClass(a.g.F.ON);d.addClass(a.g.F.k3);d.addClass(a.g.sa.GD)};a.g.prototype.A_=function(d){d&&(d.addClass(a.g.F.xD),f(d.children(a.g.Mb.sq)[0]).addClass(a.g.F.PN))};a.g.prototype.B_=function(d,b){var c=this.options,e=d==this.Aa.Vb().length-1?!0:!1,g=this.Aa.Vb()[d];b.attr(a.g.bb.rj,
g.footerStyle);b.hasClass(a.g.F.qq)||b.addClass(a.g.F.qq);c.verticalGridVisible!=a.g.Ff||e||b.addClass(a.g.F.m3);g.footerClassName&&b.addClass(g.footerClassName)};a.g.prototype.C_=function(d){d&&(d.addClass(a.g.F.yD),d.css(a.g.O.hd,"table-header-group"),d=f(d.children(a.g.Mb.sq)[0]),d.addClass(a.g.F.QN),d.css(a.g.O.em,a.g.oa.lq))};a.g.prototype.D_=function(d,b,c){d=this.Aa.Vb()[d];if(c||!b.hasClass(a.g.F.Tn))b.addClass(a.g.F.Tn),null==d.headerStyle||!c&&b.attr(a.g.bb.rj)==d.headerStyle||b.attr(a.g.bb.rj,
d.headerStyle),null==d.headerClassName||!c&&b.hasClass(d.headerClassName)||b.addClass(d.headerClassName)};a.g.prototype.Kz=function(){if("undefined"==typeof this.hy){var a=navigator.userAgent;"Microsoft Internet Explorer"==navigator.appName?(a=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(a),null!=a&&(this.hy=parseFloat(a[1]))):0<=a.indexOf("Trident")?this.hy=11:this.hy=null}return this.hy};a.g.prototype.Pz=function(){"undefined"==typeof this.GO&&(this.GO=/webkit/.test(navigator.userAgent.toLowerCase()));return this.GO};
a.g.prototype.Yba=function(d,b){var c=this.Yb(),e=this.kn(),g=this.Xj(),h=this.qs(),k=this.rs(),l=this.me(),m=this.qf();if(this.KS)this.KS=!1;else{var n=null,q=null;if(null!=this.Dd()){var p=this.Dd()[0].scrollHeight-this.Dd()[0].clientHeight,r=this.Dd()[0].scrollWidth-this.Dd()[0].clientWidth;0<p&&(n=this.Dd()[0].scrollTop);0<r&&(q=this.Dd()[0].scrollLeft)}this.zca();this.vha(l);p=this.kZ();this.Kr=1===p[0]?!0:!1;this.dp=1===p[1]?!0:!1;if(null!=m){if(this.Kr||this.dp){this.Rh||(this.Rh={});0<d||
0<b?(0<d&&this.dp&&(this.Rh[a.g.O.jd]=d),0<b&&this.Kr&&(this.Rh[a.g.O.Vn]=b)):(this.Rh[a.g.O.Vn]=this.Kr?l[0].offsetHeight:0,this.Rh[a.g.O.jd]=this.dp?l[0].offsetWidth:0);this.FA||(this.FA=l.outerWidth()-l.innerWidth());this.BW||(this.BW=l.outerHeight()-l.innerHeight());r=0;this.Kr&&!this.dp&&(l.css(a.g.O.Dx,a.g.oa.Rg),r=l.get(0).offsetWidth-l.get(0).clientWidth,0<this.Rh[a.g.O.jd]?c.css(a.g.O.jd,l.get(0).clientWidth+a.g.oa.Ub):(c.css(a.g.O.jd,l.get(0).scrollWidth+r+a.g.oa.Ub),p=this.kZ(),1===p[1]&&
c.css(a.g.O.jd,l.get(0).clientWidth+a.g.oa.Ub)),l.css(a.g.O.Dx,""),this.KS=!0);var t=c.width();this.$ca();var s=0,c=c.children("caption");null!=c&&0<c.length&&(s=f(c[0]).outerHeight(),c.css(a.g.O.hd,a.g.oa.XM),null!=e&&e.css(a.g.O.tM,l.css(a.g.O.tM).toString()));c=0;null!=e&&(e.css(a.g.O.hd,a.g.oa.Yp),this.Zj()?(e.css(a.g.O.em,a.g.oa.mM),e.css(a.g.O.AD,"0px")):e.css(a.g.O.em,a.g.oa.lq),k.css(a.g.O.hd,a.g.oa.Yp),k.css(a.g.O.em,a.g.oa.lq),c=e.outerHeight());this.Zj()&&l.css(a.g.O.s2,c+s+a.g.oa.Ub);
k=0;null!=g&&(this.Zj()?(g.css(a.g.O.em,a.g.oa.mM),e.css(a.g.O.UC,"0px")):g.css(a.g.O.em,a.g.oa.lq),g.css(a.g.O.hd,a.g.oa.Yp),h.css(a.g.O.hd,a.g.oa.Yp),h.css(a.g.O.em,a.g.oa.lq));m.css(a.g.O.hd,a.g.oa.Yp);h=0;this.Zj()||(m.css(a.g.O.pN,a.g.oa.Rg),m.css(a.g.O.em,a.g.oa.lq),this.dp?m.css(a.g.O.jd,this.Rh[a.g.O.jd]-this.FA):0<r&&m.css(a.g.O.jd,t-this.FA+r),m.width(),null!=g&&(k=g.outerHeight(),m.css(a.g.O.AD,-1*k+a.g.oa.Ub)),this.Kr?(h=this.Rh[a.g.O.Vn]-c-k-s-this.BW,0<h&&(m.css(a.g.O.Vn,h+a.g.oa.Ub),
m.css(a.g.O.hN,h+a.g.oa.Ub))):h=m.outerHeight(),r=this.CY(),this.dp?(t=this.jh(),null!=t&&0<t.length?(m.css(a.g.O.lt,a.g.oa.Rg),l.css(a.g.O.lt,a.g.oa.jt),null!=e&&(t=this.Rh[a.g.O.jd]-this.FA,0<t&&(0<r?e.css(a.g.O.jd,t-r+a.g.oa.Ub):e.css(a.g.O.jd,t+a.g.oa.Ub)))):(m.css(a.g.O.lt,a.g.oa.jt),l.css(a.g.O.lt,a.g.oa.Rg),l.css(a.g.O.pN,a.g.oa.jt))):m.css(a.g.O.lt,a.g.oa.jt));this.Zj()&&(e=this.JY(),e.css(a.g.O.Dx,a.g.oa.Rg),this.dp&&e.css(a.g.O.jd,this.Rh[a.g.O.jd]),this.Kr&&e.css(a.g.O.Vn,this.Rh[a.g.O.Vn]-
c-k),m.css(a.g.O.A1,a.g.oa.Xn),l.css(a.g.O.Dx,a.g.oa.jt));null!=g&&(this.Zj()||g.css(a.g.O.AD,h+a.g.oa.Ub))}this.fda();this.yca(0>p[0]);this.$Z();null!=n&&(p=this.Dd()[0].scrollHeight-this.Dd()[0].clientHeight,n=n>p?p:n,this.Aa.Uk()&&p==n&&n--,this.Dd()[0].scrollTop=n);null!=q&&(r=this.Dd()[0].scrollWidth-this.Dd()[0].clientWidth,q=q>r?r:q,this.Dd()[0].scrollLeft=q)}}};a.g.prototype.$Z=function(){var d=this.me(),b=this.qf(),c=this.pw(),e=d;0<b.height()&&(e=b);c&&c[0].offsetParent&&(c.css(a.g.O.Vn,
b.height()+a.g.oa.Ub),c.css(a.g.O.jd,b.width()+a.g.oa.Ub),b=f(c[0].children[0]),d="rtl"===this.Aa.hc(),e={my:"center",at:"center",collision:"none",of:e},e=a.fd.Ig(e,d),c.position(e),c={my:"center",at:"center",collision:"none",of:c},c=a.fd.Ig(c,d),b.position(c))};a.g.prototype.rca=function(){var d=this.Aa.Vb(),b,c;for(b=0;b<d.length;b++)c=this.Ed(b),null!=c&&c.css(a.g.O.kq,"");b=this.jh();if(null!=b&&0<b.length)for(b=0;b<d.length;b++)c=this.ow(0,b,null),null!=c&&c.css(a.g.O.kq,"")};a.g.prototype.yca=
function(d){if(this.options.horizontalGridVisible==a.g.Ff){var b=this.jh();if(null!=b&&0<b.length){var c;for(c=0;c<b.length;c++)f(b[c]).hasClass(a.g.F.wt)||f(b[c]).addClass(a.g.F.wt);b=f(b[b.length-1]);d||b.removeClass(a.g.F.wt)}}};a.g.prototype.zca=function(){var d=this.Yb(),b=this.kn(),c=this.rs(),e=this.Xj(),g=this.qs(),h=this.qf();if(null!=b&&(b.attr(a.g.bb.rj,""),c.attr(a.g.bb.rj,""),(b=c.find("."+a.g.F.dt))&&0<b.length))for(c=0;c<b.length;c++)f(b[c]).css(a.g.O.jd,"");null!=e&&(e.attr(a.g.bb.rj,
""),g.attr(a.g.bb.rj,""));d.css(a.g.O.hd,"");d.css(a.g.O.jd,"");null!=h&&h.attr(a.g.bb.rj,"");this.rca()};a.g.prototype.$ca=function(){var d=this.Aa.Vb(),b=[],c=[],e,g,f,k;for(e=0;e<d.length;e++)g=this.Ed(e),null!=g&&(g.width(),this.Pz()?(b[e]=parseInt(window.getComputedStyle(g[0])[a.g.O.jd],10),0==e&&(b[e]+=1)):b[e]=g.width(),c[e]=parseInt(g.css(a.g.O.Fx),10)+parseInt(g.css(a.g.O.Ex),10),f=null,(k=g.find("."+a.g.F.dt))&&0<k.length&&(f=k.get(0).clientHeight),null!=f&&(g=g.find("."+a.g.F.mx),g.css(a.g.O.hN,
f+a.g.oa.Ub)));for(e=0;e<d.length;e++)g=this.Ed(e),null!=g&&g.css(a.g.O.kq,b[e]+a.g.oa.Ub),f=this.KY(e),null!=f&&(this.Pz()&&0==e?f.css(a.g.O.kq,b[e]-1+a.g.oa.Ub):f.css(a.g.O.kq,b[e]+a.g.oa.Ub));e=this.jh();if(null!=e&&0<e.length)for(e=0;e<d.length;e++)f=this.ow(0,e,null),null!=f&&(f.width(),g=parseInt(f.css(a.g.O.Fx),10)+parseInt(f.css(a.g.O.Ex),10),this.Pz()&&0==e&&(b[e]-=1),g=g>c[e]?b[e]-g+c[e]:b[e]+c[e]-g,f.css(a.g.O.kq,g+a.g.oa.Ub))};a.g.prototype.fda=function(){var d=this.Aa.Vb(),b,c,e,g,h,
k;for(b=0;b<d.length;b++)c=d[b],e=this.Ed(b),null!=e&&(g=e.children("."+a.g.F.mx),0<g.length&&(g=f(g[0]),(h=e.find("."+a.g.F.dt))&&0<h.length&&(k=0,c.sortable==a.g.Ff&&(k=f(e.find("."+a.g.F.yM).get(0)).width()),0<g[0].clientWidth&&h.width()+k>g[0].clientWidth&&(h.css(a.g.O.jd,""),c=h.width(),e=e.width()-k,c>e+1&&h.css(a.g.O.jd,e+a.g.oa.Ub)))))};a.g.F={uM:"oj-table-checkbox-acc-select-column",vM:"oj-table-checkbox-acc-select-row",k3:"oj-table-container",UN:"oj-table-scroller",ON:"oj-table",l3:"oj-table-element",
xD:"oj-table-footer",PN:"oj-table-footer-row",yD:"oj-table-header",QN:"oj-table-header-row",Tn:"oj-table-column-header-cell",wM:"oj-table-column-header-acc-select-column",YC:"oj-table-column-header-acc-select-row",mx:"oj-table-column-header",dt:"oj-table-column-header-text",lx:"oj-table-column-header-asc",nx:"oj-table-column-header-dsc",yM:"oj-table-column-header-sort-placeholder",e1:"oj-table-column-header-acc-asc-link",f1:"oj-table-column-header-acc-dsc-link",Zp:"oj-table-column-header-asc-link",
ct:"oj-table-column-header-dsc-link",g1:"oj-table-column-header-asc-icon",h1:"oj-table-column-header-dsc-icon",vD:"oj-table-body",Zn:"oj-table-body-row",wD:"oj-table-body-current-row",pq:"oj-table-data-cell",Ox:"oj-table-data-cell-acc-select",VN:"oj-table-vgrid-lines",wt:"oj-table-hgrid-lines",qq:"oj-table-footer-cell",m3:"oj-table-footer-cell-vgrid-lines",RN:"oj-table-inline-message",zD:"oj-table-status-message",n3:"oj-table-status-message-text",SN:"oj-table-no-data-message",TN:"oj-table-no-data-row",
$n:"oj-component-icon",Hh:"oj-helper-hidden-accessible"};a.g.O={hd:"display",em:"position",Vn:"height",jd:"width",AD:"top",UC:"bottom",Xn:"left",Kx:"right",s2:"padding-top",Ex:"padding-left",Fx:"padding-right",Dx:"overflow",lt:"overflow-x",pN:"overflow-y",kq:"min-width",hN:"min-height",A1:"float",tM:"border-top",sM:"border-bottom-width",b1:"border-left-width",Ax:"margin-bottom"};a.g.oa={Yl:"none",Yp:"block",lq:"relative",mM:"absolute",XM:"inline",Rg:"auto",jt:"hidden",Xn:"left",Ub:"px"};a.g.bb={rj:"style",
vt:"tabindex",Sx:"type",Ie:"id",Px:"title",F1:"href",cD:"headers",d1:"colspan"};a.g.Mb={cq:"div",RC:"a",sq:"tr",rq:"td",YN:"th",WN:"tbody",ZN:"thead",XN:"tfoot",wx:"input",x3:"ul"};a.g.sa={GD:"oj-component",Ve:"oj-active",Sn:"oj-clickable-icon-nocontext",rb:"oj-disabled",We:"oj-enabled",qj:"oj-focus",rk:"oj-hover",Xc:"oj-selected",Ux:"oj-warning"};a.g.xM="_hdrColRowSel";a.g.Ff="enabled";a.g.bm="disabled";a.g.vk={nq:"single",Bx:"multiple"};a.Tl={};a.Tl.nJ=function(d,b,c){b=f(d.headerContext.parentElement);
d=f(document.createElement("div"));d.addClass(a.g.F.mx);b.empty();b.append(d);b=f(document.createElement("div"));b.addClass(a.g.F.dt);d.prepend(b);c(b)};o_("TableRendererUtils.columnHeaderDefaultRenderer",a.Tl.nJ,a);a.Tl.oJ=function(d,b,c){b=d.headerContext.component;var e=f(d.headerContext.parentElement);d=f(document.createElement("div"));d.addClass(a.g.F.mx);e.empty();e.append(d);"rtl"===b.hc()?d.css(a.g.O.Ex,"0px"):d.css(a.g.O.Fx,"0px");e=f(document.createElement("div"));e.addClass(a.g.F.lx);d.append(e);
var g=f(document.createElement("a"));g.addClass(a.g.F.Zp);g.addClass(a.g.F.$n);g.addClass(a.g.F.g1);g.addClass(a.g.sa.rb);g.addClass(a.g.sa.Sn);b._hoverable(g);e.append(g);var g=e.width(),h=e.height(),k=f(document.createElement("a"));k.attr("tabindex","0");k.attr("href","#");k.addClass(a.g.F.e1);k.addClass(a.g.F.Hh);k.text(b.D("labelSortAsc"));e.append(k);e=f(document.createElement("div"));e.addClass(a.g.F.yM);e.css(a.g.O.hd,"inline-block");e.css("width",g+"px");e.css("height",h+"px");d.append(e);
e=f(document.createElement("div"));e.addClass(a.g.F.nx);e.addClass(a.g.sa.rb);d.append(e);g=f(document.createElement("a"));g.addClass(a.g.F.ct);g.addClass(a.g.F.$n);g.addClass(a.g.F.h1);g.addClass(a.g.sa.rb);g.addClass(a.g.sa.Sn);b._hoverable(g);e.append(g);g=f(document.createElement("a"));g.attr("tabindex","0");g.attr("href","#");g.addClass(a.g.F.f1);g.addClass(a.g.F.Hh);g.text(b.D("labelSortDsc"));e.append(g);b=f(document.createElement("div"));b.addClass(a.g.F.dt);d.prepend(b);c(b)};o_("TableRendererUtils.columnHeaderSortableIconRenderer",
a.Tl.oJ,a)});